<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Bdd Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="../../classes.php"><span>Data&#160;Structure&#160;Index</span></a></li>
      <li><a href="../../functions.php"><span>Data&#160;Fields</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d7c/a00003.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Data Fields</a>  </div>
  <div class="headertitle">
<div class="title">Bdd Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A class to connect to a database.  
 <a href="../../d1/d7c/a00003.php#details">More...</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:af86a0c684918a64668175a1abe8e053e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#af86a0c684918a64668175a1abe8e053e">__construct</a> ($type, $host, $name=&quot;&quot;, $user=&quot;&quot;, $pass=&quot;&quot;)</td></tr>
<tr class="memdesc:af86a0c684918a64668175a1abe8e053e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Class constructor.  <a href="#af86a0c684918a64668175a1abe8e053e">More...</a><br /></td></tr>
<tr class="separator:af86a0c684918a64668175a1abe8e053e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a49ea7222535c5339106a865860248333"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a49ea7222535c5339106a865860248333">query</a> ($command)</td></tr>
<tr class="memdesc:a49ea7222535c5339106a865860248333"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use the QUERY.  <a href="#a49ea7222535c5339106a865860248333">More...</a><br /></td></tr>
<tr class="separator:a49ea7222535c5339106a865860248333"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61b9097ace78236a1a7f9cfd9e9ab01c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a61b9097ace78236a1a7f9cfd9e9ab01c">getTables</a> ()</td></tr>
<tr class="memdesc:a61b9097ace78236a1a7f9cfd9e9ab01c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the tables of the database.  <a href="#a61b9097ace78236a1a7f9cfd9e9ab01c">More...</a><br /></td></tr>
<tr class="separator:a61b9097ace78236a1a7f9cfd9e9ab01c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a339d28e140f0d54394c2d3a8287eff6c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a339d28e140f0d54394c2d3a8287eff6c">getTableColumns</a> ($table)</td></tr>
<tr class="memdesc:a339d28e140f0d54394c2d3a8287eff6c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the columns of a table of the database.  <a href="#a339d28e140f0d54394c2d3a8287eff6c">More...</a><br /></td></tr>
<tr class="separator:a339d28e140f0d54394c2d3a8287eff6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12251d0c022e9e21c137a105ff683f13"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a12251d0c022e9e21c137a105ff683f13">getId</a> ()</td></tr>
<tr class="memdesc:a12251d0c022e9e21c137a105ff683f13"><td class="mdescLeft">&#160;</td><td class="mdescRight">Recovery of the last autogenerated index.  <a href="#a12251d0c022e9e21c137a105ff683f13">More...</a><br /></td></tr>
<tr class="separator:a12251d0c022e9e21c137a105ff683f13"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5ce0c72a61b23c61a97f20838fe87aa0"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a5ce0c72a61b23c61a97f20838fe87aa0">select</a> ($name, $selection, $opt=&quot;&quot;)</td></tr>
<tr class="memdesc:a5ce0c72a61b23c61a97f20838fe87aa0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use the SELECT.  <a href="#a5ce0c72a61b23c61a97f20838fe87aa0">More...</a><br /></td></tr>
<tr class="separator:a5ce0c72a61b23c61a97f20838fe87aa0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a42cf896ff4b5b71e541d9ba5be622c1f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a42cf896ff4b5b71e541d9ba5be622c1f">selectJson</a> ($name, $selection, $opt=&quot;&quot;)</td></tr>
<tr class="memdesc:a42cf896ff4b5b71e541d9ba5be622c1f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use the SELECT and convert the answer in JSON format.  <a href="#a42cf896ff4b5b71e541d9ba5be622c1f">More...</a><br /></td></tr>
<tr class="separator:a42cf896ff4b5b71e541d9ba5be622c1f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7482084ce484f8618147627a406a26ce"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a7482084ce484f8618147627a406a26ce">insert</a> ($name, $val)</td></tr>
<tr class="memdesc:a7482084ce484f8618147627a406a26ce"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use the INSERT.  <a href="#a7482084ce484f8618147627a406a26ce">More...</a><br /></td></tr>
<tr class="separator:a7482084ce484f8618147627a406a26ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acdbc7d53f773fc1aa4f87d3091977e88"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#acdbc7d53f773fc1aa4f87d3091977e88">update</a> ($name, $val, $opts=&quot;&quot;)</td></tr>
<tr class="memdesc:acdbc7d53f773fc1aa4f87d3091977e88"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use the UPDATE.  <a href="#acdbc7d53f773fc1aa4f87d3091977e88">More...</a><br /></td></tr>
<tr class="separator:acdbc7d53f773fc1aa4f87d3091977e88"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac8cdf7b55d4b86aa9007ccfb43360100"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#ac8cdf7b55d4b86aa9007ccfb43360100">delete</a> ($name, $where)</td></tr>
<tr class="memdesc:ac8cdf7b55d4b86aa9007ccfb43360100"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use the DELETE.  <a href="#ac8cdf7b55d4b86aa9007ccfb43360100">More...</a><br /></td></tr>
<tr class="separator:ac8cdf7b55d4b86aa9007ccfb43360100"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Data Fields</h2></td></tr>
<tr class="memitem:a1fa3127fc82f96b1436d871ef02be319"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d7c/a00003.php#a1fa3127fc82f96b1436d871ef02be319">$db</a></td></tr>
<tr class="separator:a1fa3127fc82f96b1436d871ef02be319"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A class to connect to a database. </p>
<p>Set only for MySQL or SQLite To show what is send, define $DEBUG and set it to true </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00017">17</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="af86a0c684918a64668175a1abe8e053e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">__construct </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$type</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$host</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$name</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$user</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$pass</em> = <code>&quot;&quot;</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Class constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$type</td><td>The type of the database </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$host</td><td>The host for the database </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$name</td><td>The database name </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$user</td><td>The username for a connection </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$pass</td><td>The password for a connection </td></tr>
  </table>
  </dd>
</dl>
<p>Database types array</p>
<p>Create a PDO Object according to the choosen type</p>
<p>On error, say the different possible types in the error_log file </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00030">30</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_af86a0c684918a64668175a1abe8e053e_cgraph.png" border="0" usemap="#d1/d7c/a00003_af86a0c684918a64668175a1abe8e053e_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_af86a0c684918a64668175a1abe8e053e_cgraph" id="d1/d7c/a00003_af86a0c684918a64668175a1abe8e053e_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="144,5,195,32"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ac8cdf7b55d4b86aa9007ccfb43360100"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">delete </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$name</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$where</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Use the DELETE. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$name</td><td>The table name </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$where</td><td>The WHERE condition for the remove </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00314">314</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_ac8cdf7b55d4b86aa9007ccfb43360100_cgraph.png" border="0" usemap="#d1/d7c/a00003_ac8cdf7b55d4b86aa9007ccfb43360100_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_ac8cdf7b55d4b86aa9007ccfb43360100_cgraph" id="d1/d7c/a00003_ac8cdf7b55d4b86aa9007ccfb43360100_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="111,5,161,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a12251d0c022e9e21c137a105ff683f13"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">getId </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Recovery of the last autogenerated index. </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00179">179</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

</div>
</div>
<a class="anchor" id="a339d28e140f0d54394c2d3a8287eff6c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">getTableColumns </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$table</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the columns of a table of the database. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$table</td><td>The table where to get the columns </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00154">154</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_a339d28e140f0d54394c2d3a8287eff6c_cgraph.png" border="0" usemap="#d1/d7c/a00003_a339d28e140f0d54394c2d3a8287eff6c_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_a339d28e140f0d54394c2d3a8287eff6c_cgraph" id="d1/d7c/a00003_a339d28e140f0d54394c2d3a8287eff6c_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="177,5,228,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a61b9097ace78236a1a7f9cfd9e9ab01c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">getTables </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the tables of the database. </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00126">126</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_a61b9097ace78236a1a7f9cfd9e9ab01c_cgraph.png" border="0" usemap="#d1/d7c/a00003_a61b9097ace78236a1a7f9cfd9e9ab01c_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_a61b9097ace78236a1a7f9cfd9e9ab01c_cgraph" id="d1/d7c/a00003_a61b9097ace78236a1a7f9cfd9e9ab01c_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="132,5,183,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a7482084ce484f8618147627a406a26ce"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">insert </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$name</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$val</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Use the INSERT. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$name</td><td>The table name </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$val</td><td>The values to add </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00244">244</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_a7482084ce484f8618147627a406a26ce_cgraph.png" border="0" usemap="#d1/d7c/a00003_a7482084ce484f8618147627a406a26ce_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_a7482084ce484f8618147627a406a26ce_cgraph" id="d1/d7c/a00003_a7482084ce484f8618147627a406a26ce_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="108,5,159,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a49ea7222535c5339106a865860248333"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">query </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$command</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Use the QUERY. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$command</td><td>The command to query </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00101">101</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_a49ea7222535c5339106a865860248333_cgraph.png" border="0" usemap="#d1/d7c/a00003_a49ea7222535c5339106a865860248333_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_a49ea7222535c5339106a865860248333_cgraph" id="d1/d7c/a00003_a49ea7222535c5339106a865860248333_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="108,5,159,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a5ce0c72a61b23c61a97f20838fe87aa0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">select </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$name</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$selection</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$opt</em> = <code>&quot;&quot;</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Use the SELECT. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$name</td><td>The table name </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$selection</td><td>The selection part of the command </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$opt</td><td>Other options for the command </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00194">194</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_a5ce0c72a61b23c61a97f20838fe87aa0_cgraph.png" border="0" usemap="#d1/d7c/a00003_a5ce0c72a61b23c61a97f20838fe87aa0_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_a5ce0c72a61b23c61a97f20838fe87aa0_cgraph" id="d1/d7c/a00003_a5ce0c72a61b23c61a97f20838fe87aa0_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="111,5,161,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a42cf896ff4b5b71e541d9ba5be622c1f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">selectJson </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$name</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$selection</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$opt</em> = <code>&quot;&quot;</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Use the SELECT and convert the answer in JSON format. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$name</td><td>The table name </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$selection</td><td>The selection part of the command </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$opt</td><td>Other options for the command </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00224">224</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_a42cf896ff4b5b71e541d9ba5be622c1f_cgraph.png" border="0" usemap="#d1/d7c/a00003_a42cf896ff4b5b71e541d9ba5be622c1f_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_a42cf896ff4b5b71e541d9ba5be622c1f_cgraph" id="d1/d7c/a00003_a42cf896ff4b5b71e541d9ba5be622c1f_cgraph">
<area shape="rect" id="node2" href="../../d1/d7c/a00003.php#a5ce0c72a61b23c61a97f20838fe87aa0" title="Use the SELECT. " alt="" coords="139,5,196,32"/>
<area shape="rect" id="node3" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="244,5,295,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="acdbc7d53f773fc1aa4f87d3091977e88"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">update </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$name</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$val</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$opts</em> = <code>&quot;&quot;</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Use the UPDATE. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$name</td><td>The table name </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$val</td><td>The values to update </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$opts</td><td>Other options for the command </td></tr>
  </table>
  </dd>
</dl>
<p>Put the datas in $val in the right shape </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00264">264</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d7c/a00003_acdbc7d53f773fc1aa4f87d3091977e88_cgraph.png" border="0" usemap="#d1/d7c/a00003_acdbc7d53f773fc1aa4f87d3091977e88_cgraph" alt=""/></div>
<map name="d1/d7c/a00003_acdbc7d53f773fc1aa4f87d3091977e88_cgraph" id="d1/d7c/a00003_acdbc7d53f773fc1aa4f87d3091977e88_cgraph">
<area shape="rect" id="node2" href="../../d1/d7c/a00003.php#a339d28e140f0d54394c2d3a8287eff6c" title="Get the columns of a table of the database. " alt="" coords="115,5,239,32"/>
<area shape="rect" id="node3" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="287,31,337,57"/>
<area shape="rect" id="node4" href="../../dc/d87/a00032.php#a064414d8c8aa8cc8f2d5d023c7c9b485" title="Convert a date DD/MM/YYYY to YYYY&#45;MM&#45;DD. " alt="" coords="143,107,210,133"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Field Documentation</h2>
<a class="anchor" id="a1fa3127fc82f96b1436d871ef02be319"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">$db</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00018">18</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d7/d7a/a00016_source.php">bdd.php</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d1/d7c/a00003.php">Bdd</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
