<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: bootstrap.bundle.js File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d51/a00017.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">bootstrap.bundle.js File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../d4/d51/a00017_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d4/d31/a00069"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php">modifiers</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ad5264b1ac651bfff3aa367a0eb3dd3c5"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ad5264b1ac651bfff3aa367a0eb3dd3c5">_defineProperties</a> (target, props)</td></tr>
<tr class="separator:ad5264b1ac651bfff3aa367a0eb3dd3c5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39e10dc3069b4a23aa52bea0bec60e36"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a39e10dc3069b4a23aa52bea0bec60e36">_createClass</a> (<a class="el" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>, protoProps, staticProps)</td></tr>
<tr class="separator:a39e10dc3069b4a23aa52bea0bec60e36"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9ab4e1b2ef047b1bbe1f49ee0819fb79"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a9ab4e1b2ef047b1bbe1f49ee0819fb79">_extends</a> ()</td></tr>
<tr class="separator:a9ab4e1b2ef047b1bbe1f49ee0819fb79"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a27737cea0ea011c8416e8a57922ded98"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a27737cea0ea011c8416e8a57922ded98">_inheritsLoose</a> (subClass, superClass)</td></tr>
<tr class="separator:a27737cea0ea011c8416e8a57922ded98"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2ce86410bf57cf30a6e57ffccc82e0fb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a2ce86410bf57cf30a6e57ffccc82e0fb">for</a> (var <a class="el" href="../../de/d11/a00021.php#a73aff07b65d7c0b09ccf6b4c4f1b7a9d">i</a>=0;<a class="el" href="../../de/d11/a00021.php#a73aff07b65d7c0b09ccf6b4c4f1b7a9d">i</a>&lt; longerTimeoutBrowsers.length;<a class="el" href="../../de/d11/a00021.php#a73aff07b65d7c0b09ccf6b4c4f1b7a9d">i</a>+=1)</td></tr>
<tr class="separator:a2ce86410bf57cf30a6e57ffccc82e0fb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2e40d59c35a8f8b89e1caa872d0a0f56"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a2e40d59c35a8f8b89e1caa872d0a0f56">microtaskDebounce</a> (<a class="el" href="../../d3/dea/a00046.php#a8a938b10dab9fa9d43908785f7e2c002">fn</a>)</td></tr>
<tr class="separator:a2e40d59c35a8f8b89e1caa872d0a0f56"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0183381b0aa13f5c36d406bb7071d2cc"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a0183381b0aa13f5c36d406bb7071d2cc">taskDebounce</a> (<a class="el" href="../../d3/dea/a00046.php#a8a938b10dab9fa9d43908785f7e2c002">fn</a>)</td></tr>
<tr class="separator:a0183381b0aa13f5c36d406bb7071d2cc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1fe412e3e396aa0250776634a65b544c"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a1fe412e3e396aa0250776634a65b544c">isOffsetContainer</a> (element)</td></tr>
<tr class="separator:a1fe412e3e396aa0250776634a65b544c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08e668616aad32cf43ed2ca4d2af7182"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a08e668616aad32cf43ed2ca4d2af7182">includeScroll</a> (rect, element)</td></tr>
<tr class="separator:a08e668616aad32cf43ed2ca4d2af7182"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6f99b2261196d1f2c9d5d035bb47bf40"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a6f99b2261196d1f2c9d5d035bb47bf40">getBordersSize</a> (styles, axis)</td></tr>
<tr class="separator:a6f99b2261196d1f2c9d5d035bb47bf40"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8214a24c6c0e45b5479c63b473cc6ce6"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a8214a24c6c0e45b5479c63b473cc6ce6">getSize</a> (axis, body, html, computedStyle)</td></tr>
<tr class="separator:a8214a24c6c0e45b5479c63b473cc6ce6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa26c4a814e420d16eaf5c7ac49b667d9"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aa26c4a814e420d16eaf5c7ac49b667d9">getWindowSizes</a> ()</td></tr>
<tr class="separator:aa26c4a814e420d16eaf5c7ac49b667d9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab1a56442bacbc27c3a4e72aee080e209"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ab1a56442bacbc27c3a4e72aee080e209">getOffsetRectRelativeToArbitraryNode</a> (children, parent)</td></tr>
<tr class="separator:ab1a56442bacbc27c3a4e72aee080e209"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6cf88445ea7151cc8e81dc4b0cb8de77"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a6cf88445ea7151cc8e81dc4b0cb8de77">getViewportOffsetRectRelativeToArtbitraryNode</a> (element)</td></tr>
<tr class="separator:a6cf88445ea7151cc8e81dc4b0cb8de77"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fa3042e5a4ee75afbc234ea2261f2dc"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a9fa3042e5a4ee75afbc234ea2261f2dc">getArea</a> (_ref)</td></tr>
<tr class="separator:a9fa3042e5a4ee75afbc234ea2261f2dc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf179fee398e6c6ca0aa3bfe412c95fc"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#acf179fee398e6c6ca0aa3bfe412c95fc">getWindow</a> (element)</td></tr>
<tr class="separator:acf179fee398e6c6ca0aa3bfe412c95fc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5d33c8c99f4895dc1c7032a3d8550511"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a5d33c8c99f4895dc1c7032a3d8550511">attachToScrollParents</a> (scrollParent, event, callback, scrollParents)</td></tr>
<tr class="separator:a5d33c8c99f4895dc1c7032a3d8550511"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a57efe929cc6b44042891d05e15cec785"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a57efe929cc6b44042891d05e15cec785">global</a></td></tr>
<tr class="separator:a57efe929cc6b44042891d05e15cec785"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abf075bdbe59fd2c3336ed052c9c72b31"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#abf075bdbe59fd2c3336ed052c9c72b31">factory</a></td></tr>
<tr class="separator:abf075bdbe59fd2c3336ed052c9c72b31"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05c09a5e9d53fa7adf0a7936038c2fa3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a05c09a5e9d53fa7adf0a7936038c2fa3">this</a></td></tr>
<tr class="separator:a05c09a5e9d53fa7adf0a7936038c2fa3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5eafccb5437ef09b552101a016d8c32"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#af5eafccb5437ef09b552101a016d8c32">exports</a></td></tr>
<tr class="separator:af5eafccb5437ef09b552101a016d8c32"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:addc9193a1db02e0d80e6dfe0eb7321c6"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#addc9193a1db02e0d80e6dfe0eb7321c6">isBrowser</a> = typeof window !== '<a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a>' &amp;&amp; typeof document !== '<a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a>'</td></tr>
<tr class="separator:addc9193a1db02e0d80e6dfe0eb7321c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeb61d371b221f357127ed7331e93f95b"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aeb61d371b221f357127ed7331e93f95b">longerTimeoutBrowsers</a> = ['Edge', 'Trident', 'Firefox']</td></tr>
<tr class="separator:aeb61d371b221f357127ed7331e93f95b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afc40ee311a39fef1f778824d2059d426"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#afc40ee311a39fef1f778824d2059d426">timeoutDuration</a> = 0</td></tr>
<tr class="separator:afc40ee311a39fef1f778824d2059d426"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abf8f67cf88551441a1896c50ffd6c8e4"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#abf8f67cf88551441a1896c50ffd6c8e4">supportsMicroTasks</a> = <a class="el" href="../../d4/d51/a00017.php#addc9193a1db02e0d80e6dfe0eb7321c6">isBrowser</a> &amp;&amp; window.Promise</td></tr>
<tr class="separator:abf8f67cf88551441a1896c50ffd6c8e4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1086dd4e23ce39ca6cf57fb61ac759c7"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a1086dd4e23ce39ca6cf57fb61ac759c7">debounce</a> = <a class="el" href="../../d4/d51/a00017.php#abf8f67cf88551441a1896c50ffd6c8e4">supportsMicroTasks</a> ? <a class="el" href="../../d4/d51/a00017.php#a2e40d59c35a8f8b89e1caa872d0a0f56">microtaskDebounce</a> : <a class="el" href="../../d4/d51/a00017.php#a0183381b0aa13f5c36d406bb7071d2cc">taskDebounce</a></td></tr>
<tr class="separator:a1086dd4e23ce39ca6cf57fb61ac759c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afdf7dbd507451f3148f2fe067eb7fc30"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#afdf7dbd507451f3148f2fe067eb7fc30">isIE10</a> = <a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a></td></tr>
<tr class="separator:afdf7dbd507451f3148f2fe067eb7fc30"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa5a2e5bf0a535a30a11262d9df06151b"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aa5a2e5bf0a535a30a11262d9df06151b">classCallCheck</a></td></tr>
<tr class="separator:aa5a2e5bf0a535a30a11262d9df06151b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaf3dfd019b0e65fefde9702c4b377344"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aaf3dfd019b0e65fefde9702c4b377344">createClass</a></td></tr>
<tr class="separator:aaf3dfd019b0e65fefde9702c4b377344"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a817fcb70b363027b28fec000da90139a"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a817fcb70b363027b28fec000da90139a">defineProperty</a></td></tr>
<tr class="separator:a817fcb70b363027b28fec000da90139a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2eea16a19b83a9509e2f9188c0fdc0f"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ac2eea16a19b83a9509e2f9188c0fdc0f">_extends</a></td></tr>
<tr class="separator:ac2eea16a19b83a9509e2f9188c0fdc0f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ccf3b6984f59af0bfb81b608fd51477"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a4ccf3b6984f59af0bfb81b608fd51477">validPlacements</a> = placements.slice(3)</td></tr>
<tr class="separator:a4ccf3b6984f59af0bfb81b608fd51477"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec6c1ccd0838ded5f3b5e2ce3196d4db"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aec6c1ccd0838ded5f3b5e2ce3196d4db">BEHAVIORS</a></td></tr>
<tr class="separator:aec6c1ccd0838ded5f3b5e2ce3196d4db"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae26895307b59dc67206da971565ba0d9"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ae26895307b59dc67206da971565ba0d9">modifiers</a></td></tr>
<tr class="separator:ae26895307b59dc67206da971565ba0d9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr><td colspan="2"><div class="groupHeader">dataObject</div></td></tr>
<tr><td colspan="2"><div class="groupText"><p>The <code>dataObject</code> is an object containing all the informations used by Popper.js this object get passed to modifiers and to the <code>onCreate</code> and <code>onUpdate</code> callbacks. </p>
</div></td></tr>
<tr class="memitem:a82ae6814d07287d0c9be02efec53e216"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a82ae6814d07287d0c9be02efec53e216">Defaults</a></td></tr>
<tr class="separator:a82ae6814d07287d0c9be02efec53e216"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab34a4e248b9bfbf76de92f866779e0e6"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ab34a4e248b9bfbf76de92f866779e0e6">Popper</a></td></tr>
<tr class="separator:ab34a4e248b9bfbf76de92f866779e0e6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="member-group"></a>
referenceObject</h2></td></tr>
<tr><td class="ititle" colspan="2"><p><a class="anchor" id="amgrp1f3dc82a770d337ec2bf4bbc48d5481b"></a>The <code>referenceObject</code> is an object that provides an interface compatible with Popper.js and lets you use it as replacement of a real DOM node.<br />
 You can use this method to position a popper relatively to a set of coordinates in case you don't have a DOM node to use as reference.</p>
<div class="fragment"><div class="line"><span class="keyword">new</span> <a class="code" href="../../d4/d51/a00017.php#ab34a4e248b9bfbf76de92f866779e0e6">Popper</a>(referenceObject, popperNode);</div></div><!-- fragment --><p>NB: This feature isn't supported in Internet Explorer 10 </p>
</td></tr>
<tr class="memitem:a70b71395559d3d60a9b61ccf566f30ea"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a70b71395559d3d60a9b61ccf566f30ea">Util</a></td></tr>
<tr class="separator:a70b71395559d3d60a9b61ccf566f30ea"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7d2656468b57cd8302b39f91252cb544"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a7d2656468b57cd8302b39f91252cb544">Alert</a></td></tr>
<tr class="separator:a7d2656468b57cd8302b39f91252cb544"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a433ddab0735db5a5563d580ba50f0972"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a433ddab0735db5a5563d580ba50f0972">Button</a></td></tr>
<tr class="separator:a433ddab0735db5a5563d580ba50f0972"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a973fed123161d28ea502af96c99576a6"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a973fed123161d28ea502af96c99576a6">Carousel</a></td></tr>
<tr class="separator:a973fed123161d28ea502af96c99576a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4df4f2a75d24a2e6a7e8a33a097c355a"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a4df4f2a75d24a2e6a7e8a33a097c355a">Collapse</a></td></tr>
<tr class="separator:a4df4f2a75d24a2e6a7e8a33a097c355a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e37ae01d446a8be7bf004a86805ffa6"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a0e37ae01d446a8be7bf004a86805ffa6">placements</a> = ['auto-start', 'auto', 'auto-end', 'top-start', 'top', 'top-end', 'right-start', 'right', 'right-end', 'bottom-end', 'bottom', 'bottom-start', 'left-end', 'left', 'left-start']</td></tr>
<tr class="separator:a0e37ae01d446a8be7bf004a86805ffa6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6c4547b977e8248fe4d4d24817f7245c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dd/da2/a00019.php#adee3eefdf0550a70ab4d8ee0ca3b341e">Popper</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a6c4547b977e8248fe4d4d24817f7245c">Utils</a> = (typeof window !== '<a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a>' ? window : <a class="el" href="../../dd/da2/a00019.php#a57efe929cc6b44042891d05e15cec785">global</a>).PopperUtils</td></tr>
<tr class="separator:a6c4547b977e8248fe4d4d24817f7245c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1ad233b38aa8a375e2ba938ca959bd15"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a1ad233b38aa8a375e2ba938ca959bd15">Dropdown</a></td></tr>
<tr class="separator:a1ad233b38aa8a375e2ba938ca959bd15"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac31034cff9cb6db90f2650ab2367c22f"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ac31034cff9cb6db90f2650ab2367c22f">Modal</a></td></tr>
<tr class="separator:ac31034cff9cb6db90f2650ab2367c22f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8bc91fbc10ac1566135a747b9c84dd3d"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a8bc91fbc10ac1566135a747b9c84dd3d">Tooltip</a></td></tr>
<tr class="separator:a8bc91fbc10ac1566135a747b9c84dd3d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2bf106dab0efd524a9e3f21400c0005e"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a2bf106dab0efd524a9e3f21400c0005e">Popover</a></td></tr>
<tr class="separator:a2bf106dab0efd524a9e3f21400c0005e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7da938810984f5d9d2a251c9d9bdb46d"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a7da938810984f5d9d2a251c9d9bdb46d">ScrollSpy</a></td></tr>
<tr class="separator:a7da938810984f5d9d2a251c9d9bdb46d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1796b6dc9a42d7d6f1993786e3c5ec60"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a1796b6dc9a42d7d6f1993786e3c5ec60">Tab</a></td></tr>
<tr class="separator:a1796b6dc9a42d7d6f1993786e3c5ec60"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab45c8e85029d540beda13b791383683b"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ab45c8e85029d540beda13b791383683b">minMajor</a> = 1</td></tr>
<tr class="separator:ab45c8e85029d540beda13b791383683b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa257d76c0438aa54d422b9ff7c93182e"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aa257d76c0438aa54d422b9ff7c93182e">ltMajor</a> = 2</td></tr>
<tr class="separator:aa257d76c0438aa54d422b9ff7c93182e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab65218829b3656b7fbd23c5dae199cd1"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ab65218829b3656b7fbd23c5dae199cd1">minMinor</a> = 9</td></tr>
<tr class="separator:ab65218829b3656b7fbd23c5dae199cd1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e159562ce969efc5a491a39bec7b2d0"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a7e159562ce969efc5a491a39bec7b2d0">minPatch</a> = 1</td></tr>
<tr class="separator:a7e159562ce969efc5a491a39bec7b2d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a581df085d40865cd480fe18169714875"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a581df085d40865cd480fe18169714875">maxMajor</a> = 4</td></tr>
<tr class="separator:a581df085d40865cd480fe18169714875"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1d78b68187f1cdff0641757c89a23e94"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a1d78b68187f1cdff0641757c89a23e94">Scrollspy</a> = <a class="el" href="../../dd/da2/a00019.php#a7da938810984f5d9d2a251c9d9bdb46d">ScrollSpy</a></td></tr>
<tr class="separator:a1d78b68187f1cdff0641757c89a23e94"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a464b6f75f6d1ac2d8136c5f2be3996ec"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a464b6f75f6d1ac2d8136c5f2be3996ec">if</a> (<a class="el" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a>[0]&lt; <a class="el" href="../../dd/da2/a00019.php#aa257d76c0438aa54d422b9ff7c93182e">ltMajor</a> &amp;&amp;<a class="el" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a>[1]&lt; <a class="el" href="../../dd/da2/a00019.php#ab65218829b3656b7fbd23c5dae199cd1">minMinor</a>||<a class="el" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a>[0]===<a class="el" href="../../dd/da2/a00019.php#ab45c8e85029d540beda13b791383683b">minMajor</a> &amp;&amp;<a class="el" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a>[1]===<a class="el" href="../../dd/da2/a00019.php#ab65218829b3656b7fbd23c5dae199cd1">minMinor</a> &amp;&amp;<a class="el" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a>[2]&lt; <a class="el" href="../../dd/da2/a00019.php#a7e159562ce969efc5a491a39bec7b2d0">minPatch</a>||<a class="el" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a>[0] &gt;=<a class="el" href="../../dd/da2/a00019.php#a581df085d40865cd480fe18169714875">maxMajor</a>)</td></tr>
<tr class="separator:a464b6f75f6d1ac2d8136c5f2be3996ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2981dc68da79c6db76965e22a748c4ef"><td class="memItemLeft" align="right" valign="top">Object&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a2981dc68da79c6db76965e22a748c4ef">defineProperty</a> (<a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a>, '__esModule',{value:true})</td></tr>
<tr class="separator:a2981dc68da79c6db76965e22a748c4ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a39e10dc3069b4a23aa52bea0bec60e36"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function _createClass </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Constructor</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>protoProps</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>staticProps</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00024">24</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a39e10dc3069b4a23aa52bea0bec60e36_cgraph.png" border="0" usemap="#d4/d51/a00017_a39e10dc3069b4a23aa52bea0bec60e36_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a39e10dc3069b4a23aa52bea0bec60e36_cgraph" id="d4/d51/a00017_a39e10dc3069b4a23aa52bea0bec60e36_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#ad5264b1ac651bfff3aa367a0eb3dd3c5" title="_defineProperties" alt="" coords="152,5,275,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ad5264b1ac651bfff3aa367a0eb3dd3c5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function _defineProperties </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>target</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>props</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00014">14</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a9ab4e1b2ef047b1bbe1f49ee0819fb79"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function _extends </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00030">30</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a27737cea0ea011c8416e8a57922ded98"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function _inheritsLoose </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>subClass</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>superClass</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00048">48</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a5d33c8c99f4895dc1c7032a3d8550511"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function attachToScrollParents </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>scrollParent</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>event</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>callback</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>scrollParents</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l02356">2356</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a5d33c8c99f4895dc1c7032a3d8550511_cgraph.png" border="0" usemap="#d4/d51/a00017_a5d33c8c99f4895dc1c7032a3d8550511_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a5d33c8c99f4895dc1c7032a3d8550511_cgraph" id="d4/d51/a00017_a5d33c8c99f4895dc1c7032a3d8550511_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#acf179fee398e6c6ca0aa3bfe412c95fc" title="getWindow" alt="" coords="204,5,291,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a2981dc68da79c6db76965e22a748c4ef"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Object defineProperty </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a>&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">'__esModule'&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">{value:true}&#160;</td>
          <td class="paramname">&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a2ce86410bf57cf30a6e57ffccc82e0fb"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">for </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01424">1424</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a9fa3042e5a4ee75afbc234ea2261f2dc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getArea </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>_ref</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l02006">2006</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a9fa3042e5a4ee75afbc234ea2261f2dc_cgraph.png" border="0" usemap="#d4/d51/a00017_a9fa3042e5a4ee75afbc234ea2261f2dc_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a9fa3042e5a4ee75afbc234ea2261f2dc_cgraph" id="d4/d51/a00017_a9fa3042e5a4ee75afbc234ea2261f2dc_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#ab1a56442bacbc27c3a4e72aee080e209" title="getOffsetRectRelativeToArbitraryNode" alt="" coords="120,5,367,32"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php#a08e668616aad32cf43ed2ca4d2af7182" title="includeScroll" alt="" coords="415,5,511,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a6f99b2261196d1f2c9d5d035bb47bf40"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getBordersSize </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>styles</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>axis</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01700">1700</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="ab1a56442bacbc27c3a4e72aee080e209"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getOffsetRectRelativeToArbitraryNode </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>children</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>parent</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01864">1864</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_ab1a56442bacbc27c3a4e72aee080e209_cgraph.png" border="0" usemap="#d4/d51/a00017_ab1a56442bacbc27c3a4e72aee080e209_cgraph" alt=""/></div>
<map name="d4/d51/a00017_ab1a56442bacbc27c3a4e72aee080e209_cgraph" id="d4/d51/a00017_ab1a56442bacbc27c3a4e72aee080e209_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a08e668616aad32cf43ed2ca4d2af7182" title="includeScroll" alt="" coords="300,5,396,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a8214a24c6c0e45b5479c63b473cc6ce6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getSize </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>axis</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>body</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>html</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>computedStyle</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01722">1722</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a6cf88445ea7151cc8e81dc4b0cb8de77"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getViewportOffsetRectRelativeToArtbitraryNode </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>element</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01909">1909</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a6cf88445ea7151cc8e81dc4b0cb8de77_cgraph.png" border="0" usemap="#d4/d51/a00017_a6cf88445ea7151cc8e81dc4b0cb8de77_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a6cf88445ea7151cc8e81dc4b0cb8de77_cgraph" id="d4/d51/a00017_a6cf88445ea7151cc8e81dc4b0cb8de77_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#ab1a56442bacbc27c3a4e72aee080e209" title="getOffsetRectRelativeToArbitraryNode" alt="" coords="256,5,503,32"/>
<area shape="rect" id="node4" href="../../d4/d51/a00017.php#aa26c4a814e420d16eaf5c7ac49b667d9" title="getWindowSizes" alt="" coords="319,56,439,83"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php#a08e668616aad32cf43ed2ca4d2af7182" title="includeScroll" alt="" coords="551,5,647,32"/>
<area shape="rect" id="node5" href="../../d4/d51/a00017.php#a8214a24c6c0e45b5479c63b473cc6ce6" title="getSize" alt="" coords="565,56,632,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="acf179fee398e6c6ca0aa3bfe412c95fc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getWindow </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>element</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Get the window associated with the element  {Element} element </p><dl class="section return"><dt>Returns</dt><dd>{Window} </dd></dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l02351">2351</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="aa26c4a814e420d16eaf5c7ac49b667d9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function getWindowSizes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01726">1726</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_aa26c4a814e420d16eaf5c7ac49b667d9_cgraph.png" border="0" usemap="#d4/d51/a00017_aa26c4a814e420d16eaf5c7ac49b667d9_cgraph" alt=""/></div>
<map name="d4/d51/a00017_aa26c4a814e420d16eaf5c7ac49b667d9_cgraph" id="d4/d51/a00017_aa26c4a814e420d16eaf5c7ac49b667d9_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a8214a24c6c0e45b5479c63b473cc6ce6" title="getSize" alt="" coords="173,5,240,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a464b6f75f6d1ac2d8136c5f2be3996ec"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">if </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06308">6308</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a08e668616aad32cf43ed2ca4d2af7182"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function includeScroll </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rect</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>element</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01677">1677</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a1fe412e3e396aa0250776634a65b544c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function isOffsetContainer </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>element</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01577">1577</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a2e40d59c35a8f8b89e1caa872d0a0f56"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function microtaskDebounce </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>fn</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01431">1431</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a0183381b0aa13f5c36d406bb7071d2cc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function taskDebounce </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>fn</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01445">1445</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="ac2eea16a19b83a9509e2f9188c0fdc0f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var _extends</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">= Object.assign || <span class="keyword">function</span> (target) {</div><div class="line">  <span class="keywordflow">for</span> (var <a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a> = 1; <a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a> &lt; arguments.length; <a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a>++) {</div><div class="line">    var source = arguments[<a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a>];</div><div class="line"></div><div class="line">    <span class="keywordflow">for</span> (var key in source) {</div><div class="line">      <span class="keywordflow">if</span> (Object.prototype.hasOwnProperty.call(source, key)) {</div><div class="line">        target[key] = source[key];</div><div class="line">      }</div><div class="line">    }</div><div class="line">  }</div><div class="line"></div><div class="line">  <span class="keywordflow">return</span> target;</div><div class="line">}</div><div class="ttc" id="a00046_php_a5e25b1d1bed9ab5f3174b76d6a722180"><div class="ttname"><a href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a></div><div class="ttdeci">var i</div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dea/a00046_source.php#l00002">jquery.min.js:2</a></div></div>
</div><!-- fragment -->
<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01780">1780</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a7d2656468b57cd8302b39f91252cb544"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Alert</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): alert.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00201">201</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="aec6c1ccd0838ded5f3b5e2ce3196d4db"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var BEHAVIORS</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">= {</div><div class="line">  FLIP: <span class="stringliteral">&#39;flip&#39;</span>,</div><div class="line">  CLOCKWISE: <span class="stringliteral">&#39;clockwise&#39;</span>,</div><div class="line">  COUNTERCLOCKWISE: <span class="stringliteral">&#39;counterclockwise&#39;</span></div><div class="line">}</div></div><!-- fragment -->
<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l02815">2815</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a433ddab0735db5a5563d580ba50f0972"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Button</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): button.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00373">373</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a973fed123161d28ea502af96c99576a6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Carousel</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): carousel.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00536">536</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="aa5a2e5bf0a535a30a11262d9df06151b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var classCallCheck</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">= <span class="keyword">function</span> (instance, <a class="code" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>) {</div><div class="line">  <span class="keywordflow">if</span> (!(instance instanceof <a class="code" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>)) {</div><div class="line">    <span class="keywordflow">throw</span> <span class="keyword">new</span> TypeError(<span class="stringliteral">&quot;Cannot call a class as a function&quot;</span>);</div><div class="line">  }</div><div class="line">}</div><div class="ttc" id="a00020_php_a0545907c609a48549a0cf5d4c692f851"><div class="ttname"><a href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a></div><div class="ttdeci">a fn a fn alert Constructor</div><div class="ttdef"><b>Definition:</b> <a href="../../db/db2/a00020_source.php#l00006">autres/bootstrap.min.js:6</a></div></div>
</div><!-- fragment -->
<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01737">1737</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a4df4f2a75d24a2e6a7e8a33a097c355a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Collapse</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): collapse.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01035">1035</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="aaf3dfd019b0e65fefde9702c4b377344"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var createClass</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">= <span class="keyword">function</span> () {</div><div class="line">  <span class="keyword">function</span> defineProperties(target, props) {</div><div class="line">    <span class="keywordflow">for</span> (var <a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a> = 0; <a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a> &lt; props.length; <a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a>++) {</div><div class="line">      var descriptor = props[<a class="code" href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a>];</div><div class="line">      descriptor.enumerable = descriptor.enumerable || <span class="keyword">false</span>;</div><div class="line">      descriptor.configurable = <span class="keyword">true</span>;</div><div class="line">      <span class="keywordflow">if</span> (<span class="stringliteral">&quot;value&quot;</span> in descriptor) descriptor.writable = <span class="keyword">true</span>;</div><div class="line">      Object.defineProperty(target, descriptor.key, descriptor);</div><div class="line">    }</div><div class="line">  }</div><div class="line"></div><div class="line">  <span class="keywordflow">return</span> <span class="keyword">function</span> (<a class="code" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>, protoProps, staticProps) {</div><div class="line">    <span class="keywordflow">if</span> (protoProps) defineProperties(<a class="code" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>.prototype, protoProps);</div><div class="line">    <span class="keywordflow">if</span> (staticProps) defineProperties(<a class="code" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>, staticProps);</div><div class="line">    <span class="keywordflow">return</span> <a class="code" href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a>;</div><div class="line">  };</div><div class="line">}()</div><div class="ttc" id="a00020_php_a0545907c609a48549a0cf5d4c692f851"><div class="ttname"><a href="../../db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">Constructor</a></div><div class="ttdeci">a fn a fn alert Constructor</div><div class="ttdef"><b>Definition:</b> <a href="../../db/db2/a00020_source.php#l00006">autres/bootstrap.min.js:6</a></div></div>
<div class="ttc" id="a00046_php_a5e25b1d1bed9ab5f3174b76d6a722180"><div class="ttname"><a href="../../d3/dea/a00046.php#a5e25b1d1bed9ab5f3174b76d6a722180">i</a></div><div class="ttdeci">var i</div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dea/a00046_source.php#l00002">jquery.min.js:2</a></div></div>
</div><!-- fragment -->
<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01743">1743</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a1086dd4e23ce39ca6cf57fb61ac759c7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var debounce = <a class="el" href="../../d4/d51/a00017.php#abf8f67cf88551441a1896c50ffd6c8e4">supportsMicroTasks</a> ? <a class="el" href="../../d4/d51/a00017.php#a2e40d59c35a8f8b89e1caa872d0a0f56">microtaskDebounce</a> : <a class="el" href="../../d4/d51/a00017.php#a0183381b0aa13f5c36d406bb7071d2cc">taskDebounce</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a debounced version of a method, that's asynchronously deferred but called in the minimum time possible.</p>
<p>{Function} fn </p><dl class="section return"><dt>Returns</dt><dd>{Function} </dd></dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01469">1469</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a82ae6814d07287d0c9be02efec53e216"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#adee3eefdf0550a70ab4d8ee0ca3b341e">Popper</a> Defaults</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">= {</div><div class="line">  </div><div class="line">  placement: <span class="stringliteral">&#39;bottom&#39;</span>,</div><div class="line"></div><div class="line">  </div><div class="line">  eventsEnabled: <span class="keyword">true</span>,</div><div class="line"></div><div class="line">  </div><div class="line">  removeOnDestroy: <span class="keyword">false</span>,</div><div class="line"></div><div class="line">  </div><div class="line">  onCreate: <span class="keyword">function</span> onCreate() {},</div><div class="line"></div><div class="line">  </div><div class="line">  onUpdate: <span class="keyword">function</span> onUpdate() {},</div><div class="line"></div><div class="line">  </div><div class="line">  <a class="code" href="../../d4/d31/a00069.php">modifiers</a>: <a class="code" href="../../d4/d31/a00069.php">modifiers</a></div><div class="line">}</div><div class="ttc" id="a00069_php"><div class="ttname"><a href="../../d4/d31/a00069.php">modifiers</a></div></div>
</div><!-- fragment --><p>Default options provided to Popper.js constructor.<br />
 These can be overriden using the <code>options</code> argument of Popper.js.<br />
 To override an option, simply pass as 3rd argument an object with the same structure of this object, example: </p><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;new Popper(ref, pop, {</div><div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;  modifiers: {</div><div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;    preventOverflow: { enabled: false }</div><div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;  }</div><div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;})</div></div><!-- fragment --><p>  {Object} </p>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l03621">3621</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a817fcb70b363027b28fec000da90139a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var defineProperty</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">= <span class="keyword">function</span> (obj, key, value) {</div><div class="line">  <span class="keywordflow">if</span> (key in obj) {</div><div class="line">    Object.defineProperty(obj, key, {</div><div class="line">      value: value,</div><div class="line">      enumerable: <span class="keyword">true</span>,</div><div class="line">      configurable: <span class="keyword">true</span>,</div><div class="line">      writable: <span class="keyword">true</span></div><div class="line">    });</div><div class="line">  } <span class="keywordflow">else</span> {</div><div class="line">    obj[key] = value;</div><div class="line">  }</div><div class="line"></div><div class="line">  <span class="keywordflow">return</span> obj;</div><div class="line">}</div></div><!-- fragment -->
<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01765">1765</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a1ad233b38aa8a375e2ba938ca959bd15"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Dropdown</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): dropdown.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l03839">3839</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="af5eafccb5437ef09b552101a016d8c32"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function exports</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00010">10</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="abf075bdbe59fd2c3336ed052c9c72b31"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function factory</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">{</div><div class="line">    typeof <a class="code" href="../../d4/d51/a00017.php#af5eafccb5437ef09b552101a016d8c32">exports</a> === <span class="stringliteral">&#39;object&#39;</span> &amp;&amp; typeof module !== <span class="stringliteral">&#39;undefined&#39;</span> ? <a class="code" href="../../d4/d51/a00017.php#abf075bdbe59fd2c3336ed052c9c72b31">factory</a>(exports, require(<span class="stringliteral">&#39;jquery&#39;</span>)) :</div><div class="line">    typeof define === <span class="stringliteral">&#39;function&#39;</span> &amp;&amp; define.amd ? define([<span class="stringliteral">&#39;exports&#39;</span>, <span class="stringliteral">&#39;jquery&#39;</span>], <a class="code" href="../../d4/d51/a00017.php#abf075bdbe59fd2c3336ed052c9c72b31">factory</a>) :</div><div class="line">    (<a class="code" href="../../d4/d51/a00017.php#abf075bdbe59fd2c3336ed052c9c72b31">factory</a>((<a class="code" href="../../d4/d51/a00017.php#a57efe929cc6b44042891d05e15cec785">global</a>.bootstrap = {}),<a class="code" href="../../d4/d51/a00017.php#a57efe929cc6b44042891d05e15cec785">global</a>.jQuery))</div><div class="ttc" id="a00017_php_abf075bdbe59fd2c3336ed052c9c72b31"><div class="ttname"><a href="../../d4/d51/a00017.php#abf075bdbe59fd2c3336ed052c9c72b31">factory</a></div><div class="ttdeci">function factory</div><div class="ttdef"><b>Definition:</b> <a href="../../d4/d51/a00017_source.php#l00006">bootstrap.bundle.js:6</a></div></div>
<div class="ttc" id="a00017_php_af5eafccb5437ef09b552101a016d8c32"><div class="ttname"><a href="../../d4/d51/a00017.php#af5eafccb5437ef09b552101a016d8c32">exports</a></div><div class="ttdeci">function exports</div><div class="ttdef"><b>Definition:</b> <a href="../../d4/d51/a00017_source.php#l00010">bootstrap.bundle.js:10</a></div></div>
<div class="ttc" id="a00017_php_a57efe929cc6b44042891d05e15cec785"><div class="ttname"><a href="../../d4/d51/a00017.php#a57efe929cc6b44042891d05e15cec785">global</a></div><div class="ttdeci">function global</div><div class="ttdef"><b>Definition:</b> <a href="../../d4/d51/a00017_source.php#l00006">bootstrap.bundle.js:6</a></div></div>
</div><!-- fragment -->
<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00006">6</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a57efe929cc6b44042891d05e15cec785"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function global</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Bootstrap v4.0.0 (<a href="https://getbootstrap.com">https://getbootstrap.com</a>) Copyright 2011-2018 The Bootstrap Authors (<a href="https://github.com/twbs/bootstrap/graphs/contributors">https://github.com/twbs/bootstrap/graphs/contributors</a>) Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </p>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00006">6</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="addc9193a1db02e0d80e6dfe0eb7321c6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var isBrowser = typeof window !== '<a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a>' &amp;&amp; typeof document !== '<a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a>'</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>!  Kickass library to create and place poppers near their reference elements. </p><dl class="section version"><dt>Version</dt><dd>1.12.9  Copyright (c) 2016 Federico Zivolo and contributors</dd></dl>
<p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:</p>
<p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</p>
<p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. </p>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01421">1421</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="afdf7dbd507451f3148f2fe067eb7fc30"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var isIE10 = <a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Tells if you are running Internet Explorer 10 </p>
<dl class="section return"><dt>Returns</dt><dd>{Boolean} isIE10 </dd></dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01713">1713</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="aeb61d371b221f357127ed7331e93f95b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var longerTimeoutBrowsers = ['Edge', 'Trident', 'Firefox']</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01422">1422</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="aa257d76c0438aa54d422b9ff7c93182e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var ltMajor = 2</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06303">6303</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a581df085d40865cd480fe18169714875"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var maxMajor = 4</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06306">6306</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="ab45c8e85029d540beda13b791383683b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var minMajor = 1</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0-alpha.6): index.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06302">6302</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="ab65218829b3656b7fbd23c5dae199cd1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var minMinor = 9</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06304">6304</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a7e159562ce969efc5a491a39bec7b2d0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var minPatch = 1</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06305">6305</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="ac31034cff9cb6db90f2650ab2367c22f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Modal</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): modal.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l04304">4304</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="ae26895307b59dc67206da971565ba0d9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var modifiers</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l03283">3283</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a0e37ae01d446a8be7bf004a86805ffa6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#adee3eefdf0550a70ab4d8ee0ca3b341e">Popper</a> placements = ['auto-start', 'auto', 'auto-end', 'top-start', 'top', 'top-end', 'right-start', 'right', 'right-end', 'bottom-end', 'bottom', 'bottom-start', 'left-end', 'left', 'left-start']</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l02792">2792</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a2bf106dab0efd524a9e3f21400c0005e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Popover</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): popover.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l05545">5545</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="ab34a4e248b9bfbf76de92f866779e0e6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var Popper</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>onCreate </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">{dataObject}</td><td>data  onUpdate </td></tr>
    <tr><td class="paramname">{dataObject}</td><td>data </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l03679">3679</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a7da938810984f5d9d2a251c9d9bdb46d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var ScrollSpy</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): scrollspy.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l05738">5738</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a1d78b68187f1cdff0641757c89a23e94"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Scrollspy = <a class="el" href="../../dd/da2/a00019.php#a7da938810984f5d9d2a251c9d9bdb46d">ScrollSpy</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06321">6321</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="abf8f67cf88551441a1896c50ffd6c8e4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var supportsMicroTasks = <a class="el" href="../../d4/d51/a00017.php#addc9193a1db02e0d80e6dfe0eb7321c6">isBrowser</a> &amp;&amp; window.Promise</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01458">1458</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a1796b6dc9a42d7d6f1993786e3c5ec60"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Tab</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): tab.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l06049">6049</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a05c09a5e9d53fa7adf0a7936038c2fa3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">this</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00010">10</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="afc40ee311a39fef1f778824d2059d426"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var timeoutDuration = 0</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l01423">1423</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a8bc91fbc10ac1566135a747b9c84dd3d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Tooltip</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): tooltip.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l04880">4880</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a70b71395559d3d60a9b61ccf566f30ea"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#af5eafccb5437ef09b552101a016d8c32">exports</a> Util</td>
        </tr>
      </table>
</div><div class="memdoc">
<hr/>
<p> Bootstrap (v4.0.0): util.js </p><h2>Licensed under MIT (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">https://github.com/twbs/bootstrap/blob/master/LICENSE</a>) </h2>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00061">61</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a6c4547b977e8248fe4d4d24817f7245c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dd/da2/a00019.php#adee3eefdf0550a70ab4d8ee0ca3b341e">Popper</a> Utils = (typeof window !== '<a class="el" href="../../d3/dea/a00046.php#ae21cc36bf0d65014c717a481a3f8a468">undefined</a>' ? window : <a class="el" href="../../dd/da2/a00019.php#a57efe929cc6b44042891d05e15cec785">global</a>).PopperUtils</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l03828">3828</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
<a class="anchor" id="a4ccf3b6984f59af0bfb81b608fd51477"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var validPlacements = placements.slice(3)</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l02795">2795</a> of file <a class="el" href="../../d4/d51/a00017_source.php">bootstrap.bundle.js</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../dir_50bae84d6b514f2657cf039fb05a19d6.php">bases</a></li><li class="navelem"><a class="el" href="../../dir_c4b901946932eaa63527c32fb86946a7.php">bootstrap</a></li><li class="navelem"><a class="el" href="../../d4/d51/a00017.php">bootstrap.bundle.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
