<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: jeu.js File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d51/a00017.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">jeu.js File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../d4/d51/a00017_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a0228b8c787f8da646bec8fdca3eb908b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a0228b8c787f8da646bec8fdca3eb908b">ajaxRequest</a> ('GET','php/request.php/nomDifficulte', <a class="el" href="../../d4/d51/a00017.php#a34b3788c0664245d1de030f262f040ef">affichageDifficulte</a>,'id_partie='+id_partie)</td></tr>
<tr class="separator:a0228b8c787f8da646bec8fdca3eb908b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a939d4356eec3d36168c300490d57eaff"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a939d4356eec3d36168c300490d57eaff">compteur</a> (event)</td></tr>
<tr class="memdesc:a939d4356eec3d36168c300490d57eaff"><td class="mdescLeft">&#160;</td><td class="mdescRight">Advance the counter by 1 of proposition or question and go to the game function for change display.  <a href="#a939d4356eec3d36168c300490d57eaff">More...</a><br /></td></tr>
<tr class="separator:a939d4356eec3d36168c300490d57eaff"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a34b3788c0664245d1de030f262f040ef"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a34b3788c0664245d1de030f262f040ef">affichageDifficulte</a> (ajaxResponse)</td></tr>
<tr class="memdesc:a34b3788c0664245d1de030f262f040ef"><td class="mdescLeft">&#160;</td><td class="mdescRight">display difficulty.  <a href="#a34b3788c0664245d1de030f262f040ef">More...</a><br /></td></tr>
<tr class="separator:a34b3788c0664245d1de030f262f040ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8c9d97109099b8ce02792d0c4abd3ae3"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a8c9d97109099b8ce02792d0c4abd3ae3">jeu</a> ()</td></tr>
<tr class="memdesc:a8c9d97109099b8ce02792d0c4abd3ae3"><td class="mdescLeft">&#160;</td><td class="mdescRight">check if the game is over.  <a href="#a8c9d97109099b8ce02792d0c4abd3ae3">More...</a><br /></td></tr>
<tr class="separator:a8c9d97109099b8ce02792d0c4abd3ae3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5cab69f44f6222a1ebdef86c7812ab6f"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a5cab69f44f6222a1ebdef86c7812ab6f">affichageJeu</a> ()</td></tr>
<tr class="memdesc:a5cab69f44f6222a1ebdef86c7812ab6f"><td class="mdescLeft">&#160;</td><td class="mdescRight">display the questions and propositions with the value of counter question and proposition.  <a href="#a5cab69f44f6222a1ebdef86c7812ab6f">More...</a><br /></td></tr>
<tr class="separator:a5cab69f44f6222a1ebdef86c7812ab6f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a386cd203962abda96c636c5e90a9ba36"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a386cd203962abda96c636c5e90a9ba36">recuperationReponseTemp</a> (reponse)</td></tr>
<tr class="memdesc:a386cd203962abda96c636c5e90a9ba36"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the time and value of the answer with an ajax request for the value.  <a href="#a386cd203962abda96c636c5e90a9ba36">More...</a><br /></td></tr>
<tr class="separator:a386cd203962abda96c636c5e90a9ba36"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fe0edff04aec322abcdf9789acffee7"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a9fe0edff04aec322abcdf9789acffee7">recupererQuestions</a> (ajaxResponse)</td></tr>
<tr class="memdesc:a9fe0edff04aec322abcdf9789acffee7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Recover the Questions and send an ajax request who send data in the function "recupererPropositions".  <a href="#a9fe0edff04aec322abcdf9789acffee7">More...</a><br /></td></tr>
<tr class="separator:a9fe0edff04aec322abcdf9789acffee7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeb580a625cac6fdcbd0386c6a35db66f"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#aeb580a625cac6fdcbd0386c6a35db66f">recupererPropositions</a> (ajaxResponse)</td></tr>
<tr class="memdesc:aeb580a625cac6fdcbd0386c6a35db66f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Recover the propositions of the array json and create array to recover time and answer then he call the function jeu.  <a href="#aeb580a625cac6fdcbd0386c6a35db66f">More...</a><br /></td></tr>
<tr class="separator:aeb580a625cac6fdcbd0386c6a35db66f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab6f570fb5c26a4deb0c8f0fe5d0187b2"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ab6f570fb5c26a4deb0c8f0fe5d0187b2">affichageScore</a> (ajaxResponse)</td></tr>
<tr class="memdesc:ab6f570fb5c26a4deb0c8f0fe5d0187b2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Display the time and the score of the game.  <a href="#ab6f570fb5c26a4deb0c8f0fe5d0187b2">More...</a><br /></td></tr>
<tr class="separator:ab6f570fb5c26a4deb0c8f0fe5d0187b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a22a3db21d6be0a4210b9693e40966afa"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a22a3db21d6be0a4210b9693e40966afa">questions</a> =new Array()</td></tr>
<tr class="separator:a22a3db21d6be0a4210b9693e40966afa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab516b26a4218f0f59b789a0d446bf79f"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#ab516b26a4218f0f59b789a0d446bf79f">proposition</a> =new Array()</td></tr>
<tr class="separator:ab516b26a4218f0f59b789a0d446bf79f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20b6cd228a69593c03af5dc445393936"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a20b6cd228a69593c03af5dc445393936">data</a> =new Array()</td></tr>
<tr class="separator:a20b6cd228a69593c03af5dc445393936"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8acc3305bb0c57accb21b6c3dfb9a6fd"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a8acc3305bb0c57accb21b6c3dfb9a6fd">compteurProposition</a> =0</td></tr>
<tr class="separator:a8acc3305bb0c57accb21b6c3dfb9a6fd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a991c67d3335f20552b86efe85cc5d875"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a991c67d3335f20552b86efe85cc5d875">compteurQuestion</a> =0</td></tr>
<tr class="separator:a991c67d3335f20552b86efe85cc5d875"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a34b3788c0664245d1de030f262f040ef"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function affichageDifficulte </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>display difficulty. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The Array of "nom_difficulte" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00048">48</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="a5cab69f44f6222a1ebdef86c7812ab6f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function affichageJeu </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>display the questions and propositions with the value of counter question and proposition. </p>
<ul>
<li></li>
</ul>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00071">71</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="ab6f570fb5c26a4deb0c8f0fe5d0187b2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function affichageScore </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Display the time and the score of the game. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The arrays of "score" and "time" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00134">134</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="a0228b8c787f8da646bec8fdca3eb908b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">ajaxRequest </td>
          <td>(</td>
          <td class="paramtype">'GET'&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">'php/request.php/nomDifficulte'&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../d4/d51/a00017.php#a34b3788c0664245d1de030f262f040ef">affichageDifficulte</a>&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">'&#160;</td>
          <td class="paramname"><em>id_partie</em> = <code>'+id_partie</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a939d4356eec3d36168c300490d57eaff"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function compteur </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Advance the counter by 1 of proposition or question and go to the game function for change display. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event of the button </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00032">32</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a939d4356eec3d36168c300490d57eaff_cgraph.png" border="0" usemap="#d4/d51/a00017_a939d4356eec3d36168c300490d57eaff_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a939d4356eec3d36168c300490d57eaff_cgraph" id="d4/d51/a00017_a939d4356eec3d36168c300490d57eaff_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a386cd203962abda96c636c5e90a9ba36" title="Get the time and value of the answer with an ajax request for the value. " alt="" coords="129,5,308,32"/>
<area shape="rect" id="node4" href="../../d4/d51/a00017.php#a8c9d97109099b8ce02792d0c4abd3ae3" title="check if the game is over. " alt="" coords="199,56,238,83"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php#a0228b8c787f8da646bec8fdca3eb908b" title="ajaxRequest" alt="" coords="363,5,458,32"/>
<area shape="rect" id="node5" href="../../d4/d51/a00017.php#a5cab69f44f6222a1ebdef86c7812ab6f" title="display the questions and propositions with the value of counter question and proposition. " alt="" coords="363,56,459,83"/>
<area shape="rect" id="node6" href="../../d4/d51/a00017.php#ab6f570fb5c26a4deb0c8f0fe5d0187b2" title="Display the time and the score of the game. " alt="" coords="356,107,465,133"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a8c9d97109099b8ce02792d0c4abd3ae3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function jeu </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>check if the game is over. </p>
<p>If the game is not finished he call the function "affichageJeu".Otherwise he send data to calculate score with an ajax request </p>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00059">59</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a8c9d97109099b8ce02792d0c4abd3ae3_cgraph.png" border="0" usemap="#d4/d51/a00017_a8c9d97109099b8ce02792d0c4abd3ae3_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a8c9d97109099b8ce02792d0c4abd3ae3_cgraph" id="d4/d51/a00017_a8c9d97109099b8ce02792d0c4abd3ae3_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a5cab69f44f6222a1ebdef86c7812ab6f" title="display the questions and propositions with the value of counter question and proposition. " alt="" coords="99,5,195,32"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php#a0228b8c787f8da646bec8fdca3eb908b" title="ajaxRequest" alt="" coords="99,56,194,83"/>
<area shape="rect" id="node4" href="../../d4/d51/a00017.php#ab6f570fb5c26a4deb0c8f0fe5d0187b2" title="Display the time and the score of the game. " alt="" coords="92,107,201,133"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a386cd203962abda96c636c5e90a9ba36"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function recuperationReponseTemp </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>reponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the time and value of the answer with an ajax request for the value. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">reponse</td><td>The reponse of the player </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00087">87</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a386cd203962abda96c636c5e90a9ba36_cgraph.png" border="0" usemap="#d4/d51/a00017_a386cd203962abda96c636c5e90a9ba36_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a386cd203962abda96c636c5e90a9ba36_cgraph" id="d4/d51/a00017_a386cd203962abda96c636c5e90a9ba36_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a0228b8c787f8da646bec8fdca3eb908b" title="ajaxRequest" alt="" coords="232,5,327,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aeb580a625cac6fdcbd0386c6a35db66f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function recupererPropositions </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Recover the propositions of the array json and create array to recover time and answer then he call the function jeu. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The arrays of "solution_un","solution_deux","id_questions" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00118">118</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_aeb580a625cac6fdcbd0386c6a35db66f_cgraph.png" border="0" usemap="#d4/d51/a00017_aeb580a625cac6fdcbd0386c6a35db66f_cgraph" alt=""/></div>
<map name="d4/d51/a00017_aeb580a625cac6fdcbd0386c6a35db66f_cgraph" id="d4/d51/a00017_aeb580a625cac6fdcbd0386c6a35db66f_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a8c9d97109099b8ce02792d0c4abd3ae3" title="check if the game is over. " alt="" coords="201,56,240,83"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php#a5cab69f44f6222a1ebdef86c7812ab6f" title="display the questions and propositions with the value of counter question and proposition. " alt="" coords="295,5,391,32"/>
<area shape="rect" id="node4" href="../../d4/d51/a00017.php#a0228b8c787f8da646bec8fdca3eb908b" title="ajaxRequest" alt="" coords="295,56,390,83"/>
<area shape="rect" id="node5" href="../../d4/d51/a00017.php#ab6f570fb5c26a4deb0c8f0fe5d0187b2" title="Display the time and the score of the game. " alt="" coords="288,107,397,133"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a9fe0edff04aec322abcdf9789acffee7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function recupererQuestions </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Recover the Questions and send an ajax request who send data in the function "recupererPropositions". </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The arrays of "solution_un","solution_deux","id_questions" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00104">104</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d51/a00017_a9fe0edff04aec322abcdf9789acffee7_cgraph.png" border="0" usemap="#d4/d51/a00017_a9fe0edff04aec322abcdf9789acffee7_cgraph" alt=""/></div>
<map name="d4/d51/a00017_a9fe0edff04aec322abcdf9789acffee7_cgraph" id="d4/d51/a00017_a9fe0edff04aec322abcdf9789acffee7_cgraph">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php#a0228b8c787f8da646bec8fdca3eb908b" title="ajaxRequest" alt="" coords="478,5,573,32"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php#aeb580a625cac6fdcbd0386c6a35db66f" title="Recover the propositions of the array json and create array to recover time and answer then he call t..." alt="" coords="188,56,336,83"/>
<area shape="rect" id="node4" href="../../d4/d51/a00017.php#a8c9d97109099b8ce02792d0c4abd3ae3" title="check if the game is over. " alt="" coords="384,56,423,83"/>
<area shape="rect" id="node5" href="../../d4/d51/a00017.php#a5cab69f44f6222a1ebdef86c7812ab6f" title="display the questions and propositions with the value of counter question and proposition. " alt="" coords="477,56,573,83"/>
<area shape="rect" id="node6" href="../../d4/d51/a00017.php#ab6f570fb5c26a4deb0c8f0fe5d0187b2" title="Display the time and the score of the game. " alt="" coords="471,107,580,133"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="a8acc3305bb0c57accb21b6c3dfb9a6fd"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var compteurProposition =0</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00018">18</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="a991c67d3335f20552b86efe85cc5d875"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var compteurQuestion =0</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00019">19</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="a20b6cd228a69593c03af5dc445393936"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">data['reponses'] =new Array()</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00013">13</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="ab516b26a4218f0f59b789a0d446bf79f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var proposition =new Array()</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00012">12</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
<a class="anchor" id="a22a3db21d6be0a4210b9693e40966afa"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">questions['id_question'] =new Array()</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d4/d51/a00017_source.php#l00008">8</a> of file <a class="el" href="../../d4/d51/a00017_source.php">jeu.js</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../d4/d51/a00017.php">jeu.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
