<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Dialog.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d5f/a00064.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a>  </div>
  <div class="headertitle">
<div class="title">Dialog.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;QtWidgets&gt;</code><br />
<code>#include &quot;<a class="el" href="../../d2/d1f/a00083_source.php">PushButton.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../dc/d54/a00094_source.php">TitleLabel.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Dialog.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/db3/a00130.png" border="0" usemap="#Dialog_8hpp" alt=""/></div>
<map name="Dialog_8hpp" id="Dialog_8hpp">
<area shape="rect" id="node3" href="../../d2/d1f/a00083.php" title="PushButton.hpp" alt="" coords="5,155,120,181"/>
<area shape="rect" id="node4" href="../../dc/d54/a00094.php" title="TitleLabel.hpp" alt="" coords="239,80,342,107"/>
<area shape="rect" id="node5" href="../../df/d5d/a00084.php" title="Widgets/Qt.hpp" alt="" coords="279,155,393,181"/>
<area shape="rect" id="node6" href="../../df/d13/a00085.php" title="QtDefines.hpp" alt="" coords="577,453,684,480"/>
<area shape="rect" id="node47" href="../../da/d74/a00099.php" title="Window.hpp" alt="" coords="595,229,690,256"/>
<area shape="rect" id="node50" href="../../d1/dc1/a00092.php" title="TableWidget.hpp" alt="" coords="276,229,396,256"/>
<area shape="rect" id="node7" href="../../d1/d44/a00098.php" title="Widget.hpp" alt="" coords="547,528,635,555"/>
<area shape="rect" id="node8" href="../../de/de1/a00065.php" title="DrawScene.hpp" alt="" coords="709,528,824,555"/>
<area shape="rect" id="node9" href="../../db/ddf/a00088.php" title="Scene.hpp" alt="" coords="630,603,714,629"/>
<area shape="rect" id="node11" href="../../d6/d2c/a00072.php" title="GraphScene.hpp" alt="" coords="950,528,1069,555"/>
<area shape="rect" id="node16" href="../../d9/dec/a00090.php" title="Spacers.hpp" alt="" coords="401,603,495,629"/>
<area shape="rect" id="node17" href="../../da/d2a/a00086.php" title="QtFunctions.hpp" alt="" coords="738,603,857,629"/>
<area shape="rect" id="node38" href="../../d2/db1/a00070.php" title="Font.hpp" alt="" coords="398,528,471,555"/>
<area shape="rect" id="node39" href="../../d9/d2e/a00056.php" title="C++/C++.hpp" alt="" coords="1497,528,1599,555"/>
<area shape="rect" id="node18" href="../../d1/d6f/a00063.php" title="C++/defines.hpp" alt="" coords="1821,677,1939,704"/>
<area shape="rect" id="node24" href="../../d4/d6d/a00055.php" title="bdd.hpp" alt="" coords="1627,752,1695,779"/>
<area shape="rect" id="node28" href="../../d4/de8/a00061.php" title="convert.hpp" alt="" coords="2363,976,2453,1003"/>
<area shape="rect" id="node29" href="../../d4/d31/a00069.php" title="files.hpp" alt="" coords="1285,901,1355,928"/>
<area shape="rect" id="node30" href="../../d4/d7d/a00093.php" title="time.hpp" alt="" coords="2025,901,2097,928"/>
<area shape="rect" id="node31" href="../../d4/d63/a00082.php" title="pointers.hpp" alt="" coords="1816,827,1909,853"/>
<area shape="rect" id="node32" href="../../da/d82/a00091.php" title="string.hpp" alt="" coords="2369,827,2447,853"/>
<area shape="rect" id="node35" href="../../d1/d1e/a00087.php" title="RNG.hpp" alt="" coords="2241,901,2319,928"/>
<area shape="rect" id="node36" href="../../dc/dee/a00053.php" title="Args.hpp" alt="" coords="1528,752,1603,779"/>
<area shape="rect" id="node37" href="../../d1/d09/a00077.php" title="maths.hpp" alt="" coords="2472,752,2555,779"/>
<area shape="rect" id="node25" href="../../d9/df8/a00096.php" title="types.hpp" alt="" coords="1402,976,1481,1003"/>
<area shape="rect" id="node26" href="../../da/d24/a00068.php" title="errors.hpp" alt="" coords="1459,827,1539,853"/>
<area shape="rect" id="node34" href="../../d1/dea/a00054.php" title="array.hpp" alt="" coords="1563,901,1639,928"/>
<area shape="rect" id="node27" href="../../d3/d8b/a00059.php" title="console.hpp" alt="" coords="1395,901,1487,928"/>
<area shape="rect" id="node33" href="../../db/db6/a00074.php" title="macro.hpp" alt="" coords="2601,901,2684,928"/>
<area shape="rect" id="node40" href="../../d9/db3/a00066.php" title="Entities.hpp" alt="" coords="2703,677,2793,704"/>
<area shape="rect" id="node41" href="../../d8/d53/a00081.php" title="Player.hpp" alt="" coords="2731,603,2815,629"/>
<area shape="rect" id="node42" href="../../df/d03/a00062.php" title="cryptage.hpp" alt="" coords="1706,603,1803,629"/>
<area shape="rect" id="node43" href="../../d7/df7/a00058.php" title="collides.hpp" alt="" coords="2320,677,2411,704"/>
<area shape="rect" id="node44" href="../../db/dab/a00089.php" title="sorting.hpp" alt="" coords="1219,752,1306,779"/>
<area shape="rect" id="node45" href="../../d9/d77/a00095.php" title="tree.hpp" alt="" coords="2435,677,2504,704"/>
<area shape="rect" id="node46" href="../../db/df8/a00076.php" title="Map.hpp" alt="" coords="1331,752,1403,779"/>
<area shape="rect" id="node48" href="../../d4/d3a/a00101.php" title="WindowTitleBar.hpp" alt="" coords="615,304,753,331"/>
<area shape="rect" id="node49" href="../../d0/d61/a00100.php" title="WindowButton.hpp" alt="" coords="679,379,811,405"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/d06/a00131.png" border="0" usemap="#Dialog_8hppdep" alt=""/></div>
<map name="Dialog_8hppdep" id="Dialog_8hppdep">
<area shape="rect" id="node2" href="../../d9/da5/a00075.php" title="MainWindow.h" alt="" coords="5,80,113,107"/>
</map>
</div>
</div>
<p><a href="../../df/d5f/a00064_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d7a/a00016.php">Dialog</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An implementation of QDialog for the software.  <a href="../../d7/d7a/a00016.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>08 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../df/d5f/a00064_source.php">Dialog.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../df/d5f/a00064.php">Dialog.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
