<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Qt: TableWidget Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/df3/a00034.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../d2/dc8/a00242.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">TableWidget Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Create a personnalized <a class="el" href="../../db/df3/a00034.php" title="Create a personnalized TableWidget. ">TableWidget</a>.  
 <a href="../../db/df3/a00034.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d9/da4/a00078_source.php">TableWidget.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TableWidget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/d82/a00243.png" border="0" usemap="#TableWidget_inherit__map" alt="Inheritance graph"/></div>
<map name="TableWidget_inherit__map" id="TableWidget_inherit__map">
<area shape="rect" id="node2" href="../../d1/dc6/a00037.php" title="Create a personnalized Widget. " alt="" coords="21,80,84,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for TableWidget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/d08/a00244.png" border="0" usemap="#TableWidget_coll__map" alt="Collaboration graph"/></div>
<map name="TableWidget_coll__map" id="TableWidget_coll__map">
<area shape="rect" id="node2" href="../../d1/dc6/a00037.php" title="Create a personnalized Widget. " alt="" coords="21,80,84,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa29e2c37c0e310779790537890c529f2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#aa29e2c37c0e310779790537890c529f2">TableWidget</a> (QWidget *parent=nullptr, size_t w=0, size_t h=0)</td></tr>
<tr class="memdesc:aa29e2c37c0e310779790537890c529f2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a QGridLayout.  <a href="#aa29e2c37c0e310779790537890c529f2">More...</a><br /></td></tr>
<tr class="separator:aa29e2c37c0e310779790537890c529f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5fb6edc429e21280d8f47faf6fe012fa"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a5fb6edc429e21280d8f47faf6fe012fa">~TableWidget</a> ()</td></tr>
<tr class="separator:a5fb6edc429e21280d8f47faf6fe012fa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9965d8f6b70b52fc8e25906a20d4a771"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a9965d8f6b70b52fc8e25906a20d4a771">addHeader</a> (QWidget *widget)</td></tr>
<tr class="separator:a9965d8f6b70b52fc8e25906a20d4a771"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a59d73338e3d97bafc754ed798fd487f6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a59d73338e3d97bafc754ed798fd487f6">addHeader</a> (QWidget *widget, size_t x)</td></tr>
<tr class="separator:a59d73338e3d97bafc754ed798fd487f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a25bba3124cdbe518985157ff23b0b1d0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a25bba3124cdbe518985157ff23b0b1d0">setHeader</a> (QWidget *widget, size_t x)</td></tr>
<tr class="separator:a25bba3124cdbe518985157ff23b0b1d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abe173d2bf4af78a34eea42f6015dfc24"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#abe173d2bf4af78a34eea42f6015dfc24">add</a> (QWidget *widget)</td></tr>
<tr class="memdesc:abe173d2bf4af78a34eea42f6015dfc24"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a widget to the table.  <a href="#abe173d2bf4af78a34eea42f6015dfc24">More...</a><br /></td></tr>
<tr class="separator:abe173d2bf4af78a34eea42f6015dfc24"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acce74e5071c06cb79eb9120e7ca321f2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#acce74e5071c06cb79eb9120e7ca321f2">add</a> (QCheckBox *widget)</td></tr>
<tr class="memdesc:acce74e5071c06cb79eb9120e7ca321f2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a checkbox to the table.  <a href="#acce74e5071c06cb79eb9120e7ca321f2">More...</a><br /></td></tr>
<tr class="separator:acce74e5071c06cb79eb9120e7ca321f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a89b038bcb974698aa762291d72cb52e3"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a89b038bcb974698aa762291d72cb52e3">add</a> (QWidget *widget, size_t x, size_t y)</td></tr>
<tr class="memdesc:a89b038bcb974698aa762291d72cb52e3"><td class="mdescLeft">&#160;</td><td class="mdescRight">Put a widget at the position <em>x/<em>y</em>.</em>  <a href="#a89b038bcb974698aa762291d72cb52e3">More...</a><br /></td></tr>
<tr class="separator:a89b038bcb974698aa762291d72cb52e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38b92f2d6e93627e3034f07a73138b1e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a38b92f2d6e93627e3034f07a73138b1e">set</a> (QWidget *widget, size_t x, size_t y)</td></tr>
<tr class="memdesc:a38b92f2d6e93627e3034f07a73138b1e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Replace a widget at the position <em>x/<em>y</em>.</em>  <a href="#a38b92f2d6e93627e3034f07a73138b1e">More...</a><br /></td></tr>
<tr class="separator:a38b92f2d6e93627e3034f07a73138b1e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ec3251ece680a9da68c7e4adb1f6531"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../db/df3/a00034.php">TableWidget</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a6ec3251ece680a9da68c7e4adb1f6531">get</a> (size_t w=0, size_t h=0)</td></tr>
<tr class="memdesc:a6ec3251ece680a9da68c7e4adb1f6531"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the grid layout address.  <a href="#a6ec3251ece680a9da68c7e4adb1f6531">More...</a><br /></td></tr>
<tr class="separator:a6ec3251ece680a9da68c7e4adb1f6531"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00037"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00037')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d1/dc6/a00037.php">Widget</a></td></tr>
<tr class="memitem:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00037"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/dc6/a00037.php#ace1aa23652eb4425355a81760b39fd37">Widget</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00037"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a QWidget.  <a href="#ace1aa23652eb4425355a81760b39fd37">More...</a><br /></td></tr>
<tr class="separator:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00037"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a714cf798aadb4d615f6f60a355382c02 inherit pub_methods_a00037"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/dc6/a00037.php#a714cf798aadb4d615f6f60a355382c02">~Widget</a> ()</td></tr>
<tr class="separator:a714cf798aadb4d615f6f60a355382c02 inherit pub_methods_a00037"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a8ee97e18b4afb72672b36ef2002537ae"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df3/a00034.php#a8ee97e18b4afb72672b36ef2002537ae">update</a> ()</td></tr>
<tr class="memdesc:a8ee97e18b4afb72672b36ef2002537ae"><td class="mdescLeft">&#160;</td><td class="mdescRight">Update the grid layout.  <a href="#a8ee97e18b4afb72672b36ef2002537ae">More...</a><br /></td></tr>
<tr class="separator:a8ee97e18b4afb72672b36ef2002537ae"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_a00037"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_a00037')"><img src="../../closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="../../d1/dc6/a00037.php">Widget</a></td></tr>
<tr class="memitem:af755e8891f462562c88c37735345a798 inherit pro_methods_a00037"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/dc6/a00037.php#af755e8891f462562c88c37735345a798">paintEvent</a> (QPaintEvent *event)</td></tr>
<tr class="separator:af755e8891f462562c88c37735345a798 inherit pro_methods_a00037"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Create a personnalized <a class="el" href="../../db/df3/a00034.php" title="Create a personnalized TableWidget. ">TableWidget</a>. </p>

<p>Definition at line <a class="el" href="../../d9/da4/a00078_source.php#l00018">18</a> of file <a class="el" href="../../d9/da4/a00078_source.php">TableWidget.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aa29e2c37c0e310779790537890c529f2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TableWidget::TableWidget </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>w</em> = <code>0</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>h</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Create a QGridLayout. </p>

</div>
</div>
<a class="anchor" id="a5fb6edc429e21280d8f47faf6fe012fa"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TableWidget::~TableWidget </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="abe173d2bf4af78a34eea42f6015dfc24"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::add </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add a widget to the table. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The widget to add </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="acce74e5071c06cb79eb9120e7ca321f2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::add </td>
          <td>(</td>
          <td class="paramtype">QCheckBox *&#160;</td>
          <td class="paramname"><em>widget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add a checkbox to the table. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The checkbox to add </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="a89b038bcb974698aa762291d72cb52e3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::add </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>y</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Put a widget at the position <em>x/<em>y</em>.</em> </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The widget to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The x position in the grid </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">y</td><td>The y position in the grid </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>
<dl class="todo"><dt><b><a class="el" href="../../d8/d84/a00001.php#_todo000007">Todo:</a></b></dt><dd></dd></dl>

</div>
</div>
<a class="anchor" id="a9965d8f6b70b52fc8e25906a20d4a771"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::addHeader </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The widget to add </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="a59d73338e3d97bafc754ed798fd487f6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::addHeader </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>x</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The widget to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The x position on the top of the grid </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>
<dl class="todo"><dt><b><a class="el" href="../../d8/d84/a00001.php#_todo000005">Todo:</a></b></dt><dd></dd></dl>

</div>
</div>
<a class="anchor" id="a6ec3251ece680a9da68c7e4adb1f6531"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../db/df3/a00034.php">TableWidget</a>* TableWidget::get </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>w</em> = <code>0</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>h</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the grid layout address. </p>

</div>
</div>
<a class="anchor" id="a38b92f2d6e93627e3034f07a73138b1e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::set </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>y</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Replace a widget at the position <em>x/<em>y</em>.</em> </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The widget to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The x position in the grid </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">y</td><td>The y position in the grid </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>
<dl class="todo"><dt><b><a class="el" href="../../d8/d84/a00001.php#_todo000008">Todo:</a></b></dt><dd></dd></dl>

</div>
</div>
<a class="anchor" id="a25bba3124cdbe518985157ff23b0b1d0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::setHeader </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>x</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The widget to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The x position on the top of the grid </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>
<dl class="todo"><dt><b><a class="el" href="../../d8/d84/a00001.php#_todo000006">Todo:</a></b></dt><dd></dd></dl>

</div>
</div>
<a class="anchor" id="a8ee97e18b4afb72672b36ef2002537ae"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void TableWidget::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Update the grid layout. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d9/da4/a00078_source.php">TableWidget.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../db/df3/a00034.php">TableWidget</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
