<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: stars.js File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d5f/a00064.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">stars.js File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../df/d5f/a00064_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a8d8ff71978dcadc4b21e080d661d45dd"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a8d8ff71978dcadc4b21e080d661d45dd">initStars</a> ()</td></tr>
<tr class="memdesc:a8d8ff71978dcadc4b21e080d661d45dd"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initialize the differents stars in the page.  <a href="#a8d8ff71978dcadc4b21e080d661d45dd">More...</a><br /></td></tr>
<tr class="separator:a8d8ff71978dcadc4b21e080d661d45dd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c1449df7daaf21306568d1c11699946"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a0c1449df7daaf21306568d1c11699946">createStars</a> ()</td></tr>
<tr class="memdesc:a0c1449df7daaf21306568d1c11699946"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create all the stars that will be shown in the page.  <a href="#a0c1449df7daaf21306568d1c11699946">More...</a><br /></td></tr>
<tr class="separator:a0c1449df7daaf21306568d1c11699946"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab033da43f4d9abb9484023adb3cbe8da"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#ab033da43f4d9abb9484023adb3cbe8da">listImgs</a> ()</td></tr>
<tr class="memdesc:ab033da43f4d9abb9484023adb3cbe8da"><td class="mdescLeft">&#160;</td><td class="mdescRight">List the images for the stars.  <a href="#ab033da43f4d9abb9484023adb3cbe8da">More...</a><br /></td></tr>
<tr class="separator:ab033da43f4d9abb9484023adb3cbe8da"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9ff16f762d4b2a92426066a7753ac288"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a9ff16f762d4b2a92426066a7753ac288">enlight</a> (val)</td></tr>
<tr class="memdesc:a9ff16f762d4b2a92426066a7753ac288"><td class="mdescLeft">&#160;</td><td class="mdescRight">Enlight the stars to match with the value.  <a href="#a9ff16f762d4b2a92426066a7753ac288">More...</a><br /></td></tr>
<tr class="separator:a9ff16f762d4b2a92426066a7753ac288"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1dfb32225dcbd4dd553ee4204d6f1d5f"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a1dfb32225dcbd4dd553ee4204d6f1d5f">envoid</a> ()</td></tr>
<tr class="memdesc:a1dfb32225dcbd4dd553ee4204d6f1d5f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Envoid all the stars.  <a href="#a1dfb32225dcbd4dd553ee4204d6f1d5f">More...</a><br /></td></tr>
<tr class="separator:a1dfb32225dcbd4dd553ee4204d6f1d5f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a06b93344f587b996f3b18b0a0df6e151"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a06b93344f587b996f3b18b0a0df6e151">choose</a> (val)</td></tr>
<tr class="memdesc:a06b93344f587b996f3b18b0a0df6e151"><td class="mdescLeft">&#160;</td><td class="mdescRight">Enlight the stars and put the choosen value in the right input.  <a href="#a06b93344f587b996f3b18b0a0df6e151">More...</a><br /></td></tr>
<tr class="separator:a06b93344f587b996f3b18b0a0df6e151"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a34b8ff6d001a03489d89d2104f8d1e66"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a34b8ff6d001a03489d89d2104f8d1e66">addOnload</a> (<a class="el" href="../../df/d5f/a00064.php#a8d8ff71978dcadc4b21e080d661d45dd">initStars</a>)</td></tr>
<tr class="memdesc:a34b8ff6d001a03489d89d2104f8d1e66"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a function to the onloadFunction array and save the arguments.  <a href="#a34b8ff6d001a03489d89d2104f8d1e66">More...</a><br /></td></tr>
<tr class="separator:a34b8ff6d001a03489d89d2104f8d1e66"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ae2475e10618961c050dcba04e8c42331"><td class="memItemLeft" align="right" valign="top">use&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#ae2475e10618961c050dcba04e8c42331">strict</a></td></tr>
<tr class="separator:ae2475e10618961c050dcba04e8c42331"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a743f72d241d1185709756428de13d3af"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a743f72d241d1185709756428de13d3af">starParent</a></td></tr>
<tr class="separator:a743f72d241d1185709756428de13d3af"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0b952db6fba6e7a88c006f17bf0d01d5"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a0b952db6fba6e7a88c006f17bf0d01d5">stars</a></td></tr>
<tr class="separator:a0b952db6fba6e7a88c006f17bf0d01d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a07a2aabd64594dc36dd810cad2669deb"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a07a2aabd64594dc36dd810cad2669deb">input</a></td></tr>
<tr class="separator:a07a2aabd64594dc36dd810cad2669deb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa72e0c8a20e6bcc571d3a1c51846e627"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#aa72e0c8a20e6bcc571d3a1c51846e627">path</a></td></tr>
<tr class="separator:aa72e0c8a20e6bcc571d3a1c51846e627"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a386c3ec694dd3e8e178623e2d1cb302a"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php#a386c3ec694dd3e8e178623e2d1cb302a">change</a> = 1</td></tr>
<tr class="separator:a386c3ec694dd3e8e178623e2d1cb302a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>09 juin 2018</dd></dl>
<ul>
<li>Add <b>stars</b> to the page at <b>onload</b> <br />
<ul>
<li>The value of the choosen note is in an hidden input<br />
<ul>
<li><b>id</b> = starInput</li>
<li><b>name</b> = stars </li>
</ul>
</li>
</ul>
</li>
</ul>

<p>Definition in file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>
</div><h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a34b8ff6d001a03489d89d2104f8d1e66"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">addOnload </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../df/d5f/a00064.php#a8d8ff71978dcadc4b21e080d661d45dd">initStars</a>&#160;</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add a function to the onloadFunction array and save the arguments. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">funct</td><td>The function to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">args</td><td>The arguments of the function </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/dec/a00010_source.php#l00520">520</a> of file <a class="el" href="../../d7/dec/a00010_source.php">_script.js</a>.</p>

</div>
</div>
<a class="anchor" id="a06b93344f587b996f3b18b0a0df6e151"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function choose </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>val</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Enlight the stars and put the choosen value in the right input. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">val</td><td>The value of the choosen star </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00111">111</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d5f/a00064_a06b93344f587b996f3b18b0a0df6e151_cgraph.png" border="0" usemap="#df/d5f/a00064_a06b93344f587b996f3b18b0a0df6e151_cgraph" alt=""/></div>
<map name="df/d5f/a00064_a06b93344f587b996f3b18b0a0df6e151_cgraph" id="df/d5f/a00064_a06b93344f587b996f3b18b0a0df6e151_cgraph">
<area shape="rect" id="node2" href="../../df/d5f/a00064.php#a34b8ff6d001a03489d89d2104f8d1e66" title="Add a function to the onloadFunction array and save the arguments. " alt="" coords="117,5,201,32"/>
<area shape="rect" id="node3" href="../../df/d5f/a00064.php#a8d8ff71978dcadc4b21e080d661d45dd" title="Initialize the differents stars in the page. " alt="" coords="124,56,195,83"/>
<area shape="rect" id="node4" href="../../df/d5f/a00064.php#a0c1449df7daaf21306568d1c11699946" title="Create all the stars that will be shown in the page. " alt="" coords="249,56,339,83"/>
<area shape="rect" id="node5" href="../../df/d5f/a00064.php#ab033da43f4d9abb9484023adb3cbe8da" title="List the images for the stars. " alt="" coords="387,56,455,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a0c1449df7daaf21306568d1c11699946"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function createStars </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Create all the stars that will be shown in the page. </p>

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00044">44</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d5f/a00064_a0c1449df7daaf21306568d1c11699946_cgraph.png" border="0" usemap="#df/d5f/a00064_a0c1449df7daaf21306568d1c11699946_cgraph" alt=""/></div>
<map name="df/d5f/a00064_a0c1449df7daaf21306568d1c11699946_cgraph" id="df/d5f/a00064_a0c1449df7daaf21306568d1c11699946_cgraph">
<area shape="rect" id="node2" href="../../df/d5f/a00064.php#ab033da43f4d9abb9484023adb3cbe8da" title="List the images for the stars. " alt="" coords="143,5,211,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a9ff16f762d4b2a92426066a7753ac288"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function enlight </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>val</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Enlight the stars to match with the value. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">val</td><td>The value to know how to enlight the stars </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00088">88</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="a1dfb32225dcbd4dd553ee4204d6f1d5f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function envoid </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Envoid all the stars. </p>

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00099">99</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="a8d8ff71978dcadc4b21e080d661d45dd"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function initStars </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Initialize the differents stars in the page. </p>

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00021">21</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d5f/a00064_a8d8ff71978dcadc4b21e080d661d45dd_cgraph.png" border="0" usemap="#df/d5f/a00064_a8d8ff71978dcadc4b21e080d661d45dd_cgraph" alt=""/></div>
<map name="df/d5f/a00064_a8d8ff71978dcadc4b21e080d661d45dd_cgraph" id="df/d5f/a00064_a8d8ff71978dcadc4b21e080d661d45dd_cgraph">
<area shape="rect" id="node2" href="../../df/d5f/a00064.php#a0c1449df7daaf21306568d1c11699946" title="Create all the stars that will be shown in the page. " alt="" coords="124,5,213,32"/>
<area shape="rect" id="node3" href="../../df/d5f/a00064.php#ab033da43f4d9abb9484023adb3cbe8da" title="List the images for the stars. " alt="" coords="261,5,329,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ab033da43f4d9abb9484023adb3cbe8da"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function listImgs </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>List the images for the stars. </p>

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00073">73</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="a386c3ec694dd3e8e178623e2d1cb302a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var change = 1</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00070">70</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="a07a2aabd64594dc36dd810cad2669deb"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var input</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00017">17</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="aa72e0c8a20e6bcc571d3a1c51846e627"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var path</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00018">18</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="a743f72d241d1185709756428de13d3af"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var starParent</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00015">15</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="a0b952db6fba6e7a88c006f17bf0d01d5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var stars</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00016">16</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
<a class="anchor" id="ae2475e10618961c050dcba04e8c42331"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">use strict</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d5f/a00064_source.php#l00013">13</a> of file <a class="el" href="../../df/d5f/a00064_source.php">stars.js</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../dir_50bae84d6b514f2657cf039fb05a19d6.php">bases</a></li><li class="navelem"><a class="el" href="../../dir_ec12e7499930959167fb559b06c96237.php">stars</a></li><li class="navelem"><a class="el" href="../../df/d5f/a00064.php">stars.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
