<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: map.js File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dd/d32/a00041.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">map.js File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../dd/d32/a00041_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a5fdd1fc67d338661568dbc6e4fe7e719"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a5fdd1fc67d338661568dbc6e4fe7e719">initMap</a> ()</td></tr>
<tr class="memdesc:a5fdd1fc67d338661568dbc6e4fe7e719"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initialize the map.  <a href="#a5fdd1fc67d338661568dbc6e4fe7e719">More...</a><br /></td></tr>
<tr class="separator:a5fdd1fc67d338661568dbc6e4fe7e719"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a17dbb98377912b404462ccec2e3c8e72"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a17dbb98377912b404462ccec2e3c8e72">createMap</a> ()</td></tr>
<tr class="memdesc:a17dbb98377912b404462ccec2e3c8e72"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create the map.  <a href="#a17dbb98377912b404462ccec2e3c8e72">More...</a><br /></td></tr>
<tr class="separator:a17dbb98377912b404462ccec2e3c8e72"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a43394d09245390ebc26bdb06b4604940"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a43394d09245390ebc26bdb06b4604940">changeIn</a> (el)</td></tr>
<tr class="memdesc:a43394d09245390ebc26bdb06b4604940"><td class="mdescLeft">&#160;</td><td class="mdescRight">Change the color on hover(in)  <a href="#a43394d09245390ebc26bdb06b4604940">More...</a><br /></td></tr>
<tr class="separator:a43394d09245390ebc26bdb06b4604940"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a01d3cfe94d4243a467f31642bb71b733"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a01d3cfe94d4243a467f31642bb71b733">changeOut</a> (el)</td></tr>
<tr class="memdesc:a01d3cfe94d4243a467f31642bb71b733"><td class="mdescLeft">&#160;</td><td class="mdescRight">Change the color on hover(out)  <a href="#a01d3cfe94d4243a467f31642bb71b733">More...</a><br /></td></tr>
<tr class="separator:a01d3cfe94d4243a467f31642bb71b733"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa72428ec28ea58db7cbf03b3614ea4f2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#aa72428ec28ea58db7cbf03b3614ea4f2">addOnload</a> (<a class="el" href="../../dd/d32/a00041.php#a5fdd1fc67d338661568dbc6e4fe7e719">initMap</a>)</td></tr>
<tr class="memdesc:aa72428ec28ea58db7cbf03b3614ea4f2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a function to the onloadFunction array and save the arguments.  <a href="#aa72428ec28ea58db7cbf03b3614ea4f2">More...</a><br /></td></tr>
<tr class="separator:aa72428ec28ea58db7cbf03b3614ea4f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ae2475e10618961c050dcba04e8c42331"><td class="memItemLeft" align="right" valign="top">use&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#ae2475e10618961c050dcba04e8c42331">strict</a></td></tr>
<tr class="separator:ae2475e10618961c050dcba04e8c42331"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a763e2208cbf426758308114c1a1e47c8"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a763e2208cbf426758308114c1a1e47c8">mapParent</a></td></tr>
<tr class="separator:a763e2208cbf426758308114c1a1e47c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa72e0c8a20e6bcc571d3a1c51846e627"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#aa72e0c8a20e6bcc571d3a1c51846e627">path</a></td></tr>
<tr class="separator:aa72e0c8a20e6bcc571d3a1c51846e627"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a57e1ea504f03daee917d0e04d295e5f6"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a57e1ea504f03daee917d0e04d295e5f6">lc</a></td></tr>
<tr class="separator:a57e1ea504f03daee917d0e04d295e5f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad84057e5e00175fe176b18d3fe8eff11"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#ad84057e5e00175fe176b18d3fe8eff11">pc</a></td></tr>
<tr class="separator:ad84057e5e00175fe176b18d3fe8eff11"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2eff8c8ce9e90e8935a675a162e65740"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a2eff8c8ce9e90e8935a675a162e65740">hlc</a></td></tr>
<tr class="separator:a2eff8c8ce9e90e8935a675a162e65740"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace94b0bf8ea7451bbb85d83324c0b1fe"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#ace94b0bf8ea7451bbb85d83324c0b1fe">hpc</a></td></tr>
<tr class="separator:ace94b0bf8ea7451bbb85d83324c0b1fe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af873e7c3edea50d105e73b055c6bdacf"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#af873e7c3edea50d105e73b055c6bdacf">width</a></td></tr>
<tr class="separator:af873e7c3edea50d105e73b055c6bdacf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a14523cb74edc3f6175c54e598a379c27"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a14523cb74edc3f6175c54e598a379c27">file</a></td></tr>
<tr class="separator:a14523cb74edc3f6175c54e598a379c27"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a531d8057e65534a794e87650c4a67c6c"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a531d8057e65534a794e87650c4a67c6c">scale</a></td></tr>
<tr class="separator:a531d8057e65534a794e87650c4a67c6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a48e18769649a3ca5bab0fafdec44cb15"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d32/a00041.php#a48e18769649a3ca5bab0fafdec44cb15">map</a></td></tr>
<tr class="memdesc:a48e18769649a3ca5bab0fafdec44cb15"><td class="mdescLeft">&#160;</td><td class="mdescRight">Map of the regions.  <a href="#a48e18769649a3ca5bab0fafdec44cb15">More...</a><br /></td></tr>
<tr class="separator:a48e18769649a3ca5bab0fafdec44cb15"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>09 juin 2018</dd></dl>
<ul>
<li>At page onload, add a map of France where you can choose a region<br />
<ul>
<li>The choosen region is in the url of the path<br />
</li>
<li>Attributes ;<br />
<ul>
<li><b>id</b> = map <br />
</li>
<li><b>path</b> <br />
</li>
<li><b>plain-color</b> <br />
</li>
<li><b>line-color</b> <br />
</li>
<li><b>hover-plain-color</b> <br />
</li>
<li><b>hover-line-color</b> <br />
</li>
<li><b>scale</b> <br />
</li>
</ul>
</li>
</ul>
</li>
</ul>

<p>Definition in file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>
</div><h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="aa72428ec28ea58db7cbf03b3614ea4f2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">addOnload </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../dd/d32/a00041.php#a5fdd1fc67d338661568dbc6e4fe7e719">initMap</a>&#160;</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add a function to the onloadFunction array and save the arguments. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">funct</td><td>The function to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">args</td><td>The arguments of the function </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/dec/a00010_source.php#l00520">520</a> of file <a class="el" href="../../d7/dec/a00010_source.php">_script.js</a>.</p>

</div>
</div>
<a class="anchor" id="a43394d09245390ebc26bdb06b4604940"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function changeIn </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>el</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Change the color on hover(in) </p>

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00223">223</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a01d3cfe94d4243a467f31642bb71b733"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function changeOut </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>el</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Change the color on hover(out) </p>

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00229">229</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d32/a00041_a01d3cfe94d4243a467f31642bb71b733_cgraph.png" border="0" usemap="#dd/d32/a00041_a01d3cfe94d4243a467f31642bb71b733_cgraph" alt=""/></div>
<map name="dd/d32/a00041_a01d3cfe94d4243a467f31642bb71b733_cgraph" id="dd/d32/a00041_a01d3cfe94d4243a467f31642bb71b733_cgraph">
<area shape="rect" id="node2" href="../../dd/d32/a00041.php#aa72428ec28ea58db7cbf03b3614ea4f2" title="Add a function to the onloadFunction array and save the arguments. " alt="" coords="139,5,223,32"/>
<area shape="rect" id="node3" href="../../dd/d32/a00041.php#a5fdd1fc67d338661568dbc6e4fe7e719" title="Initialize the map. " alt="" coords="149,56,213,83"/>
<area shape="rect" id="node4" href="../../dd/d32/a00041.php#a17dbb98377912b404462ccec2e3c8e72" title="Create the map. " alt="" coords="271,56,353,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a17dbb98377912b404462ccec2e3c8e72"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function createMap </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Create the map. </p>

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00179">179</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a5fdd1fc67d338661568dbc6e4fe7e719"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function initMap </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Initialize the map. </p>

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00123">123</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d32/a00041_a5fdd1fc67d338661568dbc6e4fe7e719_cgraph.png" border="0" usemap="#dd/d32/a00041_a5fdd1fc67d338661568dbc6e4fe7e719_cgraph" alt=""/></div>
<map name="dd/d32/a00041_a5fdd1fc67d338661568dbc6e4fe7e719_cgraph" id="dd/d32/a00041_a5fdd1fc67d338661568dbc6e4fe7e719_cgraph">
<area shape="rect" id="node2" href="../../dd/d32/a00041.php#a17dbb98377912b404462ccec2e3c8e72" title="Create the map. " alt="" coords="117,5,200,32"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="a14523cb74edc3f6175c54e598a379c27"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var file</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00030">30</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a2eff8c8ce9e90e8935a675a162e65740"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var hlc</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00026">26</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="ace94b0bf8ea7451bbb85d83324c0b1fe"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var hpc</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00027">27</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a57e1ea504f03daee917d0e04d295e5f6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var lc</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00024">24</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a48e18769649a3ca5bab0fafdec44cb15"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var map</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Map of the regions. </p>

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00035">35</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a763e2208cbf426758308114c1a1e47c8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var mapParent</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00021">21</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="aa72e0c8a20e6bcc571d3a1c51846e627"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var path</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00022">22</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="ad84057e5e00175fe176b18d3fe8eff11"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var pc</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00025">25</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="a531d8057e65534a794e87650c4a67c6c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var scale</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00032">32</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="ae2475e10618961c050dcba04e8c42331"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">use strict</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00019">19</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
<a class="anchor" id="af873e7c3edea50d105e73b055c6bdacf"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var width</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00029">29</a> of file <a class="el" href="../../dd/d32/a00041_source.php">map.js</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../dir_50bae84d6b514f2657cf039fb05a19d6.php">bases</a></li><li class="navelem"><a class="el" href="../../dir_b5a3024adcc2bc773725d39b304ac1f2.php">map</a></li><li class="navelem"><a class="el" href="../../dd/d32/a00041.php">map.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
