<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: palmares.js Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d3/d52/a00023_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">palmares.js</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d3/d52/a00023.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;$(<span class="stringliteral">&#39;#bouton1&#39;</span>).addEventListener(<span class="stringliteral">&#39;click&#39;</span>,<a class="code" href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">affichage</a>);</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;$(<span class="stringliteral">&#39;#bouton2&#39;</span>).addEventListener(<span class="stringliteral">&#39;click&#39;</span>,<a class="code" href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">affichage</a>);</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;$(<span class="stringliteral">&#39;#bouton3&#39;</span>).addEventListener(<span class="stringliteral">&#39;click&#39;</span>,<a class="code" href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">affichage</a>);</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;$(<span class="stringliteral">&#39;#bouton4&#39;</span>).addEventListener(<span class="stringliteral">&#39;click&#39;</span>,<a class="code" href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">affichage</a>);</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<a class="code" href="../../d3/d52/a00023.php#aefe809d5ec4fc79376f1ca1c67b71524">ajaxRequest</a>(<span class="stringliteral">&#39;GET&#39;</span>, <span class="stringliteral">&#39;php/request.php/tableauPalmares&#39;</span>, <a class="code" href="../../d3/d52/a00023.php#aa1ccf3e9b222affe42cc578b6d898694">loadTabPalmares</a>,<span class="stringliteral">&#39;difficulte=&quot;1&quot;&#39;</span>);</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<a class="code" href="../../d3/d52/a00023.php#aefe809d5ec4fc79376f1ca1c67b71524">ajaxRequest</a>(<span class="stringliteral">&#39;GET&#39;</span>, <span class="stringliteral">&#39;php/request.php/tableauDifficulte&#39;</span>, <a class="code" href="../../d3/d52/a00023.php#aae5ee08540b9075228e330d9f9db693c">affichageBouton</a>);</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno"><a class="line" href="../../d3/d52/a00023.php#aae5ee08540b9075228e330d9f9db693c">   19</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../d3/d52/a00023.php#aae5ee08540b9075228e330d9f9db693c">affichageBouton</a>(ajaxResponse){</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;var json= JSON.parse(ajaxResponse);</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="keywordflow">for</span> (var i = 0; i &lt; json.length; i++) {</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;  $(<span class="stringliteral">&#39;#bouton&#39;</span>+(i+1)).innerHTML=json[i][<span class="stringliteral">&#39;nom_difficulte&#39;</span>];</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;}</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;$(<span class="stringliteral">&#39;#bouton1&#39;</span>).style.backgroundColor=<span class="stringliteral">&quot;rgba(0,0,0,0.3)&quot;</span>;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;}</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">   31</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">affichage</a>(event) {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;  var <a class="code" href="../../d1/d7c/a00003.php#ad71ab45724394ceb19d97c8180ab0e89">difficulte</a>=<span class="keyword">event</span>.currentTarget.value;</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;  $(<span class="stringliteral">&#39;#bouton1&#39;</span>).style.backgroundColor=<span class="stringliteral">&quot;#707070&quot;</span>;</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;  $(<span class="stringliteral">&#39;#bouton2&#39;</span>).style.backgroundColor=<span class="stringliteral">&quot;#707070&quot;</span>;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;  $(<span class="stringliteral">&#39;#bouton3&#39;</span>).style.backgroundColor=<span class="stringliteral">&quot;#707070&quot;</span>;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;  $(<span class="stringliteral">&#39;#bouton4&#39;</span>).style.backgroundColor=<span class="stringliteral">&quot;#707070&quot;</span>;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;  <span class="keyword">event</span>.currentTarget.style.backgroundColor=<span class="stringliteral">&quot;rgba(0,0,0,0.3)&quot;</span>;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;  <a class="code" href="../../d3/d52/a00023.php#aefe809d5ec4fc79376f1ca1c67b71524">ajaxRequest</a>(<span class="stringliteral">&#39;GET&#39;</span>, <span class="stringliteral">&#39;php/request.php/tableauPalmares&#39;</span>,<a class="code" href="../../d3/d52/a00023.php#aa1ccf3e9b222affe42cc578b6d898694">loadTabPalmares</a>,<span class="stringliteral">&#39;difficulte=&#39;</span>+difficulte);</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;}</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno"><a class="line" href="../../d3/d52/a00023.php#aa1ccf3e9b222affe42cc578b6d898694">   45</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../d3/d52/a00023.php#aa1ccf3e9b222affe42cc578b6d898694">loadTabPalmares</a>(ajaxResponse){</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;var json,text;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;json= JSON.parse(ajaxResponse);</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;text=<span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;<span class="keywordflow">for</span> (var i = 0; i &lt; json.length; i++) {</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;  text+=<span class="stringliteral">&#39;&lt;tr&gt;&lt;td&gt;&#39;</span>+</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;  (i+1)+<span class="stringliteral">&#39; Kg&lt;/td&gt;&lt;td&gt;&#39;</span>+</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;  json[i][<span class="stringliteral">&quot;pseudo&quot;</span>]+<span class="stringliteral">&#39;&lt;/td&gt;&lt;td&gt;&#39;</span>+</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;  json[i][<span class="stringliteral">&quot;score&quot;</span>]+<span class="stringliteral">&#39; Dog / &#39;</span>+json[i][<span class="stringliteral">&quot;temps&quot;</span>]+<span class="stringliteral">&#39;&lt;/td&gt;&lt;td&gt;&#39;</span>+</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;  json[i][<span class="stringliteral">&quot;id_partie&quot;</span>]+<span class="stringliteral">&#39;&lt;/td&gt;&lt;td&gt;&#39;</span>+</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;  json[i][<span class="stringliteral">&quot;date_score&quot;</span>]+</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;  <span class="stringliteral">&#39;&lt;/td&gt;&lt;/tr&gt;&#39;</span>;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;}</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;$(<span class="stringliteral">&#39;#tableauPalmares&#39;</span>).innerHTML= text;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;resizeOnloadFunctions();</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;}</div><div class="ttc" id="a00023_php_aefe809d5ec4fc79376f1ca1c67b71524"><div class="ttname"><a href="../../d3/d52/a00023.php#aefe809d5ec4fc79376f1ca1c67b71524">ajaxRequest</a></div><div class="ttdeci">ajaxRequest('GET', 'php/request.php/tableauPalmares', loadTabPalmares,'difficulte=&quot;1&quot;')</div></div>
<div class="ttc" id="a00023_php_af74f80f2d76592fc7d873aeabb9aecf5"><div class="ttname"><a href="../../d3/d52/a00023.php#af74f80f2d76592fc7d873aeabb9aecf5">affichage</a></div><div class="ttdeci">function affichage(event)</div><div class="ttdoc">Displays the array in relation to the chosen difficulty by the user. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d52/a00023_source.php#l00031">palmares.js:31</a></div></div>
<div class="ttc" id="a00003_php_ad71ab45724394ceb19d97c8180ab0e89"><div class="ttname"><a href="../../d1/d7c/a00003.php#ad71ab45724394ceb19d97c8180ab0e89">difficulte</a></div><div class="ttdeci">var difficulte</div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d7c/a00003_source.php#l00021">accueilPerso.js:21</a></div></div>
<div class="ttc" id="a00023_php_aa1ccf3e9b222affe42cc578b6d898694"><div class="ttname"><a href="../../d3/d52/a00023.php#aa1ccf3e9b222affe42cc578b6d898694">loadTabPalmares</a></div><div class="ttdeci">function loadTabPalmares(ajaxResponse)</div><div class="ttdoc">Displays the scoreboards recover in ajax response. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d52/a00023_source.php#l00045">palmares.js:45</a></div></div>
<div class="ttc" id="a00023_php_aae5ee08540b9075228e330d9f9db693c"><div class="ttname"><a href="../../d3/d52/a00023.php#aae5ee08540b9075228e330d9f9db693c">affichageBouton</a></div><div class="ttdeci">function affichageBouton(ajaxResponse)</div><div class="ttdoc">Displays button with the name difficulty of the database. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/d52/a00023_source.php#l00019">palmares.js:19</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../d3/d52/a00023.php">palmares.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
