<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: class-Paypal.php Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d3/dfe/a00025_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">class-Paypal.php</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d3/dfe/a00025.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;&lt;?php</div><div class="line"><a name="l00014"></a><span class="lineno"><a class="line" href="../../de/d5e/a00007.php">   14</a></span>&#160;    <span class="keyword">class </span><a class="code" href="../../de/d5e/a00007.php">Paypal</a> {</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;        <span class="keyword">private</span> $version;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;        <span class="keyword">private</span> $user;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;        <span class="keyword">private</span> $pass;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;        <span class="keyword">private</span> $signature;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;        <span class="keyword">private</span> $debug;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <span class="comment">/* \brief Class constructor */</span></div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="../../de/d5e/a00007.php#a0ed77dab5f67e7f02f86e720999536a4">   22</a></span>&#160;        <span class="keyword">public</span> <span class="keyword">function</span> <a class="code" href="../../de/d5e/a00007.php#a0ed77dab5f67e7f02f86e720999536a4">__construct</a>($debug = <span class="keyword">false</span>){</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;            $this-&gt;<a class="code" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a> = 78.0;</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;            $this-&gt;debug = $debug;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        }</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00028"></a><span class="lineno"><a class="line" href="../../de/d5e/a00007.php#aef0e8bcafd146bad2546d7672fcc0787">   28</a></span>&#160;        <span class="keyword">public</span> <span class="keyword">function</span> <a class="code" href="../../de/d5e/a00007.php#aef0e8bcafd146bad2546d7672fcc0787">setInformations</a>($user, $pass, $signature){</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            <span class="keywordflow">if</span>(!<a class="code" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a>($user) || !<a class="code" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a>($pass) || !<a class="code" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a>($signature)){</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                error_log(<span class="stringliteral">&quot;Please complete correctly the paypal informations&quot;</span>);</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                die;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;            }</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;            $this-&gt;user = $user;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;            $this-&gt;pass = $pass;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;            $this-&gt;signature = $signature;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;        }</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="../../de/d5e/a00007.php#accd14bda49a1044b4d8dd93f020f11ee">   40</a></span>&#160;        <span class="keyword">public</span> <span class="keyword">function</span> <a class="code" href="../../de/d5e/a00007.php#accd14bda49a1044b4d8dd93f020f11ee">getUrl</a>(){</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;            <span class="keywordflow">if</span>($this-&gt;debug === <span class="keyword">true</span>){</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                $api_paypal = <span class="stringliteral">&#39;https://api-3t.sandbox.paypal.com/nvp?&#39;</span>;</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;            } <span class="keywordflow">else</span> {</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                $api_paypal = <span class="stringliteral">&#39;https://api-3t.paypal.com/nvp?&#39;</span>;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;            }</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;            <span class="keywordflow">return</span> $api_paypal . <span class="stringliteral">&#39;VERSION=&#39;</span> . $this-&gt;<a class="code" href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a> . <span class="stringliteral">&#39;&amp;USER=&#39;</span> . $this-&gt;user . <span class="stringliteral">&#39;&amp;PWD=&#39;</span> . $this-&gt;pass . <span class="stringliteral">&#39;&amp;SIGNATURE=&#39;</span> . $this-&gt;signature;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        }</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno"><a class="line" href="../../de/d5e/a00007.php#a3380e4f27e13c6c10cee88aefff37309">   58</a></span>&#160;        <span class="keyword">public</span> <span class="keyword">function</span> <a class="code" href="../../de/d5e/a00007.php#a3380e4f27e13c6c10cee88aefff37309">getRequest</a>($cancelUrl, $returnUrl, $amount, $desc = <span class="stringliteral">&quot;&quot;</span>){</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;            $api = $this-&gt;<a class="code" href="../../de/d5e/a00007.php#accd14bda49a1044b4d8dd93f020f11ee">getUrl</a>();</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;            $request = $api .</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                       <span class="stringliteral">&quot;&amp;METHOD=SetExpressCheckout&quot;</span> .</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                       <span class="stringliteral">&quot;&amp;CANCELURL=&quot;</span>.urlencode($cancelUrl).</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                       <span class="stringliteral">&quot;&amp;RETURNURL=&quot;</span>.urlencode($returnUrl).</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                       <span class="stringliteral">&quot;&amp;AMT=&quot;</span>.$amount.</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                       <span class="stringliteral">&quot;&amp;CURRENCYCODE=EUR&quot;</span>;</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;            <span class="keywordflow">if</span>(<a class="code" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a>($desc) &amp;&amp; $desc !== <span class="stringliteral">&quot;&quot;</span>){</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                $request .= <span class="stringliteral">&quot;&amp;DESC=&quot;</span>.urlencode($desc);</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;            }</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;            $request .= <span class="stringliteral">&quot;&amp;LOCALECODE=FR&quot;</span>;</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;            <span class="keywordflow">return</span> $request;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;        }</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;    }</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;?&gt;</div><div class="ttc" id="a00007_php"><div class="ttname"><a href="../../de/d5e/a00007.php">Paypal</a></div><div class="ttdoc">A class to talk with the Paypal API. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dfe/a00025_source.php#l00014">class-Paypal.php:14</a></div></div>
<div class="ttc" id="a00007_php_a3380e4f27e13c6c10cee88aefff37309"><div class="ttname"><a href="../../de/d5e/a00007.php#a3380e4f27e13c6c10cee88aefff37309">Paypal\getRequest</a></div><div class="ttdeci">getRequest($cancelUrl, $returnUrl, $amount, $desc=&quot;&quot;)</div><div class="ttdoc">Return the request asked. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dfe/a00025_source.php#l00058">class-Paypal.php:58</a></div></div>
<div class="ttc" id="a00010_php_a9e0d51979af70f1e0d06bb7bb7047898"><div class="ttname"><a href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a></div><div class="ttdeci">function isset()</div><div class="ttdoc">Function to know if a variable exist. </div><div class="ttdef"><b>Definition:</b> <a href="../../d7/dec/a00010_source.php#l00406">_script.js:406</a></div></div>
<div class="ttc" id="a00007_php_a0ed77dab5f67e7f02f86e720999536a4"><div class="ttname"><a href="../../de/d5e/a00007.php#a0ed77dab5f67e7f02f86e720999536a4">Paypal\__construct</a></div><div class="ttdeci">__construct($debug=false)</div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dfe/a00025_source.php#l00022">class-Paypal.php:22</a></div></div>
<div class="ttc" id="a00007_php_accd14bda49a1044b4d8dd93f020f11ee"><div class="ttname"><a href="../../de/d5e/a00007.php#accd14bda49a1044b4d8dd93f020f11ee">Paypal\getUrl</a></div><div class="ttdeci">getUrl()</div><div class="ttdoc">Return the url of ask. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dfe/a00025_source.php#l00040">class-Paypal.php:40</a></div></div>
<div class="ttc" id="a00020_php_af15ce22371f8af3b38c7d40a4987b366"><div class="ttname"><a href="../../db/db2/a00020.php#af15ce22371f8af3b38c7d40a4987b366">version</a></div><div class="ttdeci">but lower than version(jQuery)</div></div>
<div class="ttc" id="a00007_php_aef0e8bcafd146bad2546d7672fcc0787"><div class="ttname"><a href="../../de/d5e/a00007.php#aef0e8bcafd146bad2546d7672fcc0787">Paypal\setInformations</a></div><div class="ttdeci">setInformations($user, $pass, $signature)</div><div class="ttdoc">Set the $user, $pass, signature for the API. </div><div class="ttdef"><b>Definition:</b> <a href="../../d3/dfe/a00025_source.php#l00028">class-Paypal.php:28</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_05194b7bb14e4bdbd759acf3e4294839.php">php</a></li><li class="navelem"><a class="el" href="../../dir_272b8c85f84b9c47a49e8b7a9d6744ed.php">bases</a></li><li class="navelem"><a class="el" href="../../d3/dfe/a00025.php">class-Paypal.php</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
