<ul class="navbar">
	<li class="navbar-item <?php echo is_this_active("index.php"); ?>"><a class="major-navbar-item" href="./" target="_self"></a></li>
	<li class="navbar-item <?php echo is_this_active("index.php"); ?>"><a href="./" target="_self"></a></li>
</ul>
	
<div class="social_networks">
	<a href="https://twitter.com/" target="_blank"><img class="icon" src="design/css/home_made/img/twitter.png" alt="Twitter" title="Twitter" /></a>
	<a href="https://www.facebook.com/" target="_blank"><img class="icon" src="design/css/home_made/img/facebook.png" alt="Facebook" title="Facebook" /></a>
	<a href="https://www.instagram.com/" target="_blank"><img class="icon" src="design/css/home_made/img/instagram.png" alt="Instagram" title="Instagram" /></a>
	<a href="https://plus.google.com/" target="_blank"><img class="icon" src="design/css/home_made/img/google_plus.png" alt="Google+" title="Google+" /></a>
	<a href="https://www.pinterest.fr/" target="_blank"><img class="icon" src="design/css/home_made/img/pinterest.png" alt="Pinterest" title="Pinterest" /></a>
</div>
