<ul class="navbar">
	<li class=" <?php echo is_this_active("index.php"); ?>"><a href="./index.php" target="_self"><img src="design/img/logo.png" alt="logo du site">HOT DOG QUIZ</a></li>
	<li class=" <?php echo is_this_active("palmares.php"); ?>"><a href="./palmares.php" target="_self">PALMARÈS</a></li>
	<!--<li class="menu"><img class="logo" src="ressources/logo.png" alt="logo du site"></li> -->
	<!-- a faire en php :
	<div>
	<li class=" <?php //echo is_this_active("palmares.php"); ?>"><a href="" target="_self">CONNEXION</a></li>
	<li class=" <?php //echo is_this_active("palmares.php"); ?>"><a href="" target="_self">INSCRIPTION</a></li>
</div> -->
</ul>
