<ul class="navbar">
	<li class="navbar-item <?php echo is_this_active("index.php"); ?>"><a class="major-navbar-item" href="./" target="_self">HOT DOG QUIZ</a></li>
	<li class="navbar-item <?php echo is_this_active("palmares.php"); ?>"><a href="./palmares.php" target="_self">PALMARÈS</a></li>
	<!--<li class="menu"><img class="logo" src="ressources/logo.png" alt="logo du site"></li> -->
	<div>
	<li class="navbar-item <?php echo is_this_active("palmares.php"); ?>"><a href="" target="_self">CONNEXION</a></li>
	<li class="navbar-item <?php echo is_this_active("palmares.php"); ?>"><a href="" target="_self">INSCRIPTION</a></li>
	</div>
</ul>
