<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: RSA Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d0/d33/a00027.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="../../da/d1e/a00149.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">RSA Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A class to use the <a class="el" href="../../d0/d33/a00027.php" title="A class to use the RSA algorithm for encryption. ">RSA</a> algorithm for encryption.  
 <a href="../../d0/d33/a00027.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d5/df9/a00044_source.php">cryptage.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for RSA:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d7d/a00150.png" border="0" usemap="#RSA_inherit__map" alt="Inheritance graph"/></div>
<map name="RSA_inherit__map" id="RSA_inherit__map">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. " alt="" coords="5,5,67,32"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for RSA:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/db2/a00151.png" border="0" usemap="#RSA_coll__map" alt="Collaboration graph"/></div>
<map name="RSA_coll__map" id="RSA_coll__map">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. " alt="" coords="5,5,67,32"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a8b8df3c7a74905f3e35a8e01bfd7da59"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#a8b8df3c7a74905f3e35a8e01bfd7da59">RSA</a> ()</td></tr>
<tr class="separator:a8b8df3c7a74905f3e35a8e01bfd7da59"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a552895f20169b13fd412bc83738b5db5"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#a552895f20169b13fd412bc83738b5db5">getPublic</a> ()</td></tr>
<tr class="memdesc:a552895f20169b13fd412bc83738b5db5"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the public key.  <a href="#a552895f20169b13fd412bc83738b5db5">More...</a><br /></td></tr>
<tr class="separator:a552895f20169b13fd412bc83738b5db5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa900df17edf76fe7158630ec63db1fa4"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#aa900df17edf76fe7158630ec63db1fa4">getPrivate</a> ()</td></tr>
<tr class="memdesc:aa900df17edf76fe7158630ec63db1fa4"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the private key.  <a href="#aa900df17edf76fe7158630ec63db1fa4">More...</a><br /></td></tr>
<tr class="separator:aa900df17edf76fe7158630ec63db1fa4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab0019252770d8ace87c447472d5d8b1e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#ab0019252770d8ace87c447472d5d8b1e">setPublic</a> (std::string key=&quot;&quot;)</td></tr>
<tr class="memdesc:ab0019252770d8ace87c447472d5d8b1e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the public key.  <a href="#ab0019252770d8ace87c447472d5d8b1e">More...</a><br /></td></tr>
<tr class="separator:ab0019252770d8ace87c447472d5d8b1e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa502d81bc7559e4db119b81ce898b2ce"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#aa502d81bc7559e4db119b81ce898b2ce">setPrivate</a> (std::string key=&quot;&quot;)</td></tr>
<tr class="memdesc:aa502d81bc7559e4db119b81ce898b2ce"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the private key.  <a href="#aa502d81bc7559e4db119b81ce898b2ce">More...</a><br /></td></tr>
<tr class="separator:aa502d81bc7559e4db119b81ce898b2ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d51d182786f83236c013c7cb10c2095"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#a3d51d182786f83236c013c7cb10c2095">crypt</a> (std::string message)</td></tr>
<tr class="memdesc:a3d51d182786f83236c013c7cb10c2095"><td class="mdescLeft">&#160;</td><td class="mdescRight">Overload of the crypt <a class="el" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. ">Crypto</a>'s method.  <a href="#a3d51d182786f83236c013c7cb10c2095">More...</a><br /></td></tr>
<tr class="separator:a3d51d182786f83236c013c7cb10c2095"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a77fb6e6d0ce8b989bfa013c324c310d7"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#a77fb6e6d0ce8b989bfa013c324c310d7">decrypt</a> (std::string message)</td></tr>
<tr class="memdesc:a77fb6e6d0ce8b989bfa013c324c310d7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Overload of the decrypt <a class="el" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. ">Crypto</a>'s method.  <a href="#a77fb6e6d0ce8b989bfa013c324c310d7">More...</a><br /></td></tr>
<tr class="separator:a77fb6e6d0ce8b989bfa013c324c310d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab84588271f2e5417d47251be249951b4"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#ab84588271f2e5417d47251be249951b4">crypt</a> ()</td></tr>
<tr class="separator:ab84588271f2e5417d47251be249951b4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00014"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00014')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d2/de7/a00014.php">Crypto</a></td></tr>
<tr class="memitem:abc5714d83e17c9961258646a94e75079 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#abc5714d83e17c9961258646a94e75079">Crypto</a> ()</td></tr>
<tr class="separator:abc5714d83e17c9961258646a94e75079 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:a7d293f0a39aacf8eb05abc7355d436e2"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#a7d293f0a39aacf8eb05abc7355d436e2">publicK</a></td></tr>
<tr class="separator:a7d293f0a39aacf8eb05abc7355d436e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a933f86ffad0a7a2d5d5e6099bdb5f1be"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php#a933f86ffad0a7a2d5d5e6099bdb5f1be">privateK</a></td></tr>
<tr class="separator:a933f86ffad0a7a2d5d5e6099bdb5f1be"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A class to use the <a class="el" href="../../d0/d33/a00027.php" title="A class to use the RSA algorithm for encryption. ">RSA</a> algorithm for encryption. </p>
<dl class="todo"><dt><b><a class="el" href="../../d8/d84/a00001.php#_todo000002">Todo:</a></b></dt><dd>Create the class </dd></dl>

<p>Definition at line <a class="el" href="../../d5/df9/a00044_source.php#l00085">85</a> of file <a class="el" href="../../d5/df9/a00044_source.php">cryptage.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a8b8df3c7a74905f3e35a8e01bfd7da59"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">RSA::RSA </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a3d51d182786f83236c013c7cb10c2095"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string RSA::crypt </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>message</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Overload of the crypt <a class="el" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. ">Crypto</a>'s method. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">message</td><td>The message to encrypt</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the encrypted message </dd></dl>

</div>
</div>
<a class="anchor" id="ab84588271f2e5417d47251be249951b4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void RSA::crypt </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Rewrite the pur virtual method crypt of the parent <a class="el" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. ">Crypto</a></p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Implements <a class="el" href="../../d2/de7/a00014.php#a76d99d39d43cf53d9b18a00bec7a8132">Crypto</a>.</p>

<p>Definition at line <a class="el" href="../../d5/df9/a00044_source.php#l00139">139</a> of file <a class="el" href="../../d5/df9/a00044_source.php">cryptage.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a77fb6e6d0ce8b989bfa013c324c310d7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string RSA::decrypt </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>message</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Overload of the decrypt <a class="el" href="../../d2/de7/a00014.php" title="A class to be the parent for every crypt class. ">Crypto</a>'s method. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">message</td><td>The message to decrypt</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the decrypted message </dd></dl>

</div>
</div>
<a class="anchor" id="aa900df17edf76fe7158630ec63db1fa4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string RSA::getPrivate </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the private key. </p>
<dl class="section return"><dt>Returns</dt><dd>Return the private key of the object </dd></dl>

</div>
</div>
<a class="anchor" id="a552895f20169b13fd412bc83738b5db5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string RSA::getPublic </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the public key. </p>
<dl class="section return"><dt>Returns</dt><dd>Return the public key of the object </dd></dl>

</div>
</div>
<a class="anchor" id="aa502d81bc7559e4db119b81ce898b2ce"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void RSA::setPrivate </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>key</em> = <code>&quot;&quot;</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the private key. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">key</td><td>The key</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="ab0019252770d8ace87c447472d5d8b1e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void RSA::setPublic </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>key</em> = <code>&quot;&quot;</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the public key. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">key</td><td>The key</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a933f86ffad0a7a2d5d5e6099bdb5f1be"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::string RSA::privateK</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d5/df9/a00044_source.php#l00142">142</a> of file <a class="el" href="../../d5/df9/a00044_source.php">cryptage.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a7d293f0a39aacf8eb05abc7355d436e2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::string RSA::publicK</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d5/df9/a00044_source.php#l00141">141</a> of file <a class="el" href="../../d5/df9/a00044_source.php">cryptage.hpp</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d5/df9/a00044_source.php">cryptage.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d0/d33/a00027.php">RSA</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
