<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: Tree.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/db3/a00066.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#enum-members">Enumerations</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">Tree.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;vector&gt;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d6d/a00055_source.php">maths.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Tree.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d3a/a00101.png" border="0" usemap="#Tree_8hpp" alt=""/></div>
<map name="Tree_8hpp" id="Tree_8hpp">
<area shape="rect" id="node3" href="../../d4/d6d/a00055.php" title="maths.hpp" alt="" coords="88,80,171,107"/>
</map>
</div>
</div>
<p><a href="../../d9/db3/a00066_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d11/a00021.php">Node&lt; T &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A struct to define a node for the tree.  <a href="../../de/d11/a00021.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d61/a00031.php">Tree&lt; T &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A class to manage a binary tree.  <a href="../../df/d61/a00031.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:a0a1e73288e0ceb794c65bd86a4b7f231"><td class="memItemLeft" align="right" valign="top">typedef long double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a></td></tr>
<tr class="separator:a0a1e73288e0ceb794c65bd86a4b7f231"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="enum-members"></a>
Enumerations</h2></td></tr>
<tr class="memitem:afaf56d0935db4c37008c7c186bdde7c0"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/db3/a00066.php#afaf56d0935db4c37008c7c186bdde7c0">TREE_SORT</a> { <a class="el" href="../../d9/db3/a00066.php#afaf56d0935db4c37008c7c186bdde7c0a6ec9ae46a1e5c631ae04fc9c4c2d63bc">ASC</a>, 
<a class="el" href="../../d9/db3/a00066.php#afaf56d0935db4c37008c7c186bdde7c0ac09f77dd64a2d5dedf24b5835d9eaa5a">DESC</a>
 }<tr class="memdesc:afaf56d0935db4c37008c7c186bdde7c0"><td class="mdescLeft">&#160;</td><td class="mdescRight">The sorting order of the tree.  <a href="../../d9/db3/a00066.php#afaf56d0935db4c37008c7c186bdde7c0">More...</a><br /></td></tr>
</td></tr>
<tr class="separator:afaf56d0935db4c37008c7c186bdde7c0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac65cb214851db32b3bf2b7072e229e06"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06">TREE_DIRECTION</a> { <a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06aec8379af7490bb9eaaf579cf17876f38">RIGHT</a>, 
<a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06adb45120aafd37a973140edee24708065">LEFT</a>, 
<a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06ac157bdf0b85a40d2619cbc8bc1ae5fe2">NONE</a>
 }</td></tr>
<tr class="separator:ac65cb214851db32b3bf2b7072e229e06"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a05b65486fa381f9881b8ea58c13382ad"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a05b65486fa381f9881b8ea58c13382ad"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06">TREE_DIRECTION</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d9/db3/a00066.php#a05b65486fa381f9881b8ea58c13382ad">treeAscSorter</a> (std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt; datas, std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt; nodeDatas)</td></tr>
<tr class="memdesc:a05b65486fa381f9881b8ea58c13382ad"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function to sort a tree ascendently depending on weights.  <a href="#a05b65486fa381f9881b8ea58c13382ad">More...</a><br /></td></tr>
<tr class="separator:a05b65486fa381f9881b8ea58c13382ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adcf4acfe617e3974a5ba668de737b80c"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:adcf4acfe617e3974a5ba668de737b80c"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06">TREE_DIRECTION</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d9/db3/a00066.php#adcf4acfe617e3974a5ba668de737b80c">treeDescSorter</a> (std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt; datas, std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt; nodeDatas)</td></tr>
<tr class="memdesc:adcf4acfe617e3974a5ba668de737b80c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function to sort a tree descendently depending on weights.  <a href="#adcf4acfe617e3974a5ba668de737b80c">More...</a><br /></td></tr>
<tr class="separator:adcf4acfe617e3974a5ba668de737b80c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>11 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d9/db3/a00066_source.php">Tree.hpp</a>.</p>
</div><h2 class="groupheader">Typedef Documentation</h2>
<a class="anchor" id="a0a1e73288e0ceb794c65bd86a4b7f231"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef long double <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d9/db3/a00066_source.php#l00015">15</a> of file <a class="el" href="../../d9/db3/a00066_source.php">Tree.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Enumeration Type Documentation</h2>
<a class="anchor" id="ac65cb214851db32b3bf2b7072e229e06"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06">TREE_DIRECTION</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a class="anchor" id="ac65cb214851db32b3bf2b7072e229e06aec8379af7490bb9eaaf579cf17876f38"></a>RIGHT&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="ac65cb214851db32b3bf2b7072e229e06adb45120aafd37a973140edee24708065"></a>LEFT&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="ac65cb214851db32b3bf2b7072e229e06ac157bdf0b85a40d2619cbc8bc1ae5fe2"></a>NONE&#160;</td><td class="fielddoc">
</td></tr>
</table>

<p>Definition at line <a class="el" href="../../d9/db3/a00066_source.php#l00023">23</a> of file <a class="el" href="../../d9/db3/a00066_source.php">Tree.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="afaf56d0935db4c37008c7c186bdde7c0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="../../d9/db3/a00066.php#afaf56d0935db4c37008c7c186bdde7c0">TREE_SORT</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The sorting order of the tree. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a class="anchor" id="afaf56d0935db4c37008c7c186bdde7c0a6ec9ae46a1e5c631ae04fc9c4c2d63bc"></a>ASC&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="afaf56d0935db4c37008c7c186bdde7c0ac09f77dd64a2d5dedf24b5835d9eaa5a"></a>DESC&#160;</td><td class="fielddoc">
</td></tr>
</table>

<p>Definition at line <a class="el" href="../../d9/db3/a00066_source.php#l00018">18</a> of file <a class="el" href="../../d9/db3/a00066_source.php">Tree.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a05b65486fa381f9881b8ea58c13382ad"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06">TREE_DIRECTION</a> treeAscSorter </td>
          <td>(</td>
          <td class="paramtype">std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt;&#160;</td>
          <td class="paramname"><em>datas</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt;&#160;</td>
          <td class="paramname"><em>nodeDatas</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function to sort a tree ascendently depending on weights. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">datas</td><td>The datas to compare to </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">nodeDatas</td><td>The datas of the node to compare to <em>datas</em> </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return -1/0/1 to say which node to go </dd></dl>

<p>Definition at line <a class="el" href="../../d9/db3/a00066_source.php#l00051">51</a> of file <a class="el" href="../../d9/db3/a00066_source.php">Tree.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="adcf4acfe617e3974a5ba668de737b80c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d9/db3/a00066.php#ac65cb214851db32b3bf2b7072e229e06">TREE_DIRECTION</a> treeDescSorter </td>
          <td>(</td>
          <td class="paramtype">std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt;&#160;</td>
          <td class="paramname"><em>datas</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::pair&lt; T, <a class="el" href="../../d9/db3/a00066.php#a0a1e73288e0ceb794c65bd86a4b7f231">NodeWeight</a> &gt;&#160;</td>
          <td class="paramname"><em>nodeDatas</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function to sort a tree descendently depending on weights. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">datas</td><td>The datas to compare to </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">nodeDatas</td><td>The datas of the node to compare to <em>datas</em> </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return -1/0/1 to say which node to go </dd></dl>

<p>Definition at line <a class="el" href="../../d9/db3/a00066_source.php#l00072">72</a> of file <a class="el" href="../../d9/db3/a00066_source.php">Tree.hpp</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d9/db3/a00066.php">Tree.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
