<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: Object.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d6d/a00055.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a>  </div>
  <div class="headertitle">
<div class="title">Object.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Object.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/dec/a00090.png" border="0" usemap="#Object_8hpp" alt=""/></div>
<map name="Object_8hpp" id="Object_8hpp">
<area shape="rect" id="node2" href="../../d5/db6/a00042.php" title="Contraption.hpp" alt="" coords="421,80,536,107"/>
<area shape="rect" id="node3" href="../../d6/d97/a00045.php" title="defines.hpp" alt="" coords="434,155,523,181"/>
<area shape="rect" id="node46" href="../../db/d3a/a00040.php" title="collides.hpp" alt="" coords="793,155,884,181"/>
<area shape="rect" id="node49" href="../../d1/d84/a00052.php" title="Map.hpp" alt="" coords="264,155,336,181"/>
<area shape="rect" id="node10" href="../../d1/dc6/a00037.php" title="bdd.hpp" alt="" coords="749,229,817,256"/>
<area shape="rect" id="node44" href="../../d4/d8c/a00035.php" title="Args.hpp" alt="" coords="75,304,149,331"/>
<area shape="rect" id="node15" href="../../d4/dca/a00048.php" title="errors.hpp" alt="" coords="365,379,445,405"/>
<area shape="rect" id="node37" href="../../d4/de8/a00061.php" title="string.hpp" alt="" coords="913,304,991,331"/>
<area shape="rect" id="node16" href="../../dd/d32/a00041.php" title="console.hpp" alt="" coords="653,453,745,480"/>
<area shape="rect" id="node26" href="../../d2/dee/a00049.php" title="files.hpp" alt="" coords="487,453,558,480"/>
<area shape="rect" id="node29" href="../../d1/d6f/a00063.php" title="time.hpp" alt="" coords="204,453,276,480"/>
<area shape="rect" id="node17" href="../../d6/d42/a00043.php" title="convert.hpp" alt="" coords="792,528,883,555"/>
<area shape="rect" id="node23" href="../../de/de1/a00065.php" title="types.hpp" alt="" coords="659,528,738,555"/>
<area shape="rect" id="node32" href="../../df/d03/a00062.php" title="Threadable.hpp" alt="" coords="33,528,143,555"/>
<area shape="rect" id="node36" href="../../d7/df7/a00058.php" title="pointers.hpp" alt="" coords="29,603,123,629"/>
<area shape="rect" id="node40" href="../../d2/d79/a00051.php" title="macro.hpp" alt="" coords="745,379,828,405"/>
<area shape="rect" id="node41" href="../../de/d8c/a00036.php" title="array.hpp" alt="" coords="359,453,435,480"/>
<area shape="rect" id="node42" href="../../d3/d8b/a00059.php" title="RNG.hpp" alt="" coords="852,379,929,405"/>
<area shape="rect" id="node47" href="../../dc/dee/a00053.php" title="maths.hpp" alt="" coords="1004,229,1087,256"/>
</map>
</div>
</div>
<p><a href="../../d4/d6d/a00055_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d11/a00021.php">Object</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An object.  <a href="../../de/d11/a00021.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>07 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d4/d6d/a00055_source.php">Object.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d4/d6d/a00055.php">Object.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
