<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>ProjetFinalCPP: Class Members - Functions</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">ProjetFinalCPP
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_func.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;<ul>
<li>adminWidgets()
: <a class="el" href="d7/d46/a00002.php#aceb5bf98f0d68be0d164584da0605624">MainWindow</a>
</li>
<li>connections()
: <a class="el" href="d7/d46/a00002.php#a430b81b3bb84b8561b4e63fe76e28c39">MainWindow</a>
</li>
<li>createAdminWidgets()
: <a class="el" href="d7/d46/a00002.php#a2364ae069aba1f220ac4cd2fecaf4d6c">MainWindow</a>
</li>
<li>createConnectDialog()
: <a class="el" href="d7/d46/a00002.php#a63c8b347f526518517340a5f912c5575">MainWindow</a>
</li>
<li>createConnectWidgets()
: <a class="el" href="d7/d46/a00002.php#a78ab18fed76eb54bda4508dc9be4b64b">MainWindow</a>
</li>
<li>initAdminWidgets()
: <a class="el" href="d7/d46/a00002.php#a601d88aa6fbda83575e07d7dc9e19a15">MainWindow</a>
</li>
<li>initConnectDialog()
: <a class="el" href="d7/d46/a00002.php#a79d1533b5cbbc9040c5d78c9dfb29d38">MainWindow</a>
</li>
<li>initConnectWidgets()
: <a class="el" href="d7/d46/a00002.php#a5cfeb89a38b9225a3b3964e6d688ba60">MainWindow</a>
</li>
<li>MainWindow()
: <a class="el" href="d7/d46/a00002.php#a08a133d21fea8948f84acc105ab5fc33">MainWindow</a>
</li>
<li>setContentAdminWidgets()
: <a class="el" href="d7/d46/a00002.php#af0aca5335b2f075de2cdbf0fe9c33645">MainWindow</a>
</li>
<li>setContentConnectDialog()
: <a class="el" href="d7/d46/a00002.php#a3338456a91f9f32f2f30b9e702df5ea4">MainWindow</a>
</li>
<li>setContentConnectWidgets()
: <a class="el" href="d7/d46/a00002.php#a9da75111decb2a68a08c06dec6796d8a">MainWindow</a>
</li>
<li>useAdminWidgets()
: <a class="el" href="d7/d46/a00002.php#ac5cd67fa4d5e5aace91a9c98cc8feec7">MainWindow</a>
</li>
<li>useConnectDialog()
: <a class="el" href="d7/d46/a00002.php#a79a619ed1dd1d17b8b3624d919fefe4e">MainWindow</a>
</li>
<li>useConnectWidgets()
: <a class="el" href="d7/d46/a00002.php#aad6ca3020e583fffe727258905c15629">MainWindow</a>
</li>
<li>verifyConnection()
: <a class="el" href="d7/d46/a00002.php#a70aa06cbac136bf2ce8bee98b9bebd27">MainWindow</a>
</li>
<li>~MainWindow()
: <a class="el" href="d7/d46/a00002.php#ae98d00a93bc118200eeef9f9bba1dba7">MainWindow</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
