<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Class Members - Functions</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_enum.php"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.php"><span>Enumerator</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_a"><span>a</span></a></li>
      <li><a href="functions_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_j.php#index_j"><span>j</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li class="current"><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_func_s.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>save()
: <a class="el" href="df/d86/a00012.php#a3b03a811157d84449f3cf467c1f4758e">ConsoleCursor</a>
, <a class="el" href="d0/d33/a00027.php#a28dc3cce3cd6eb596209d10174d0b37b">Map</a>
</li>
<li>Scene()
: <a class="el" href="dd/d32/a00041.php#abaaf58cde185094df3ab47c5eedef55e">Scene</a>
</li>
<li>set()
: <a class="el" href="d5/db6/a00042.php#a38b92f2d6e93627e3034f07a73138b1e">TableWidget</a>
</li>
<li>setA()
: <a class="el" href="d7/dd4/a00013.php#ad1482208cab08d738341ab2265b37deb">Contraption</a>
</li>
<li>setAge()
: <a class="el" href="d1/d2b/a00018.php#a1dd5e5689f86ac1ddc9a539c498d82ec">Entity</a>
</li>
<li>setAttributes()
: <a class="el" href="d7/dd4/a00013.php#a96a40d8c6b09bc86be65042fad49592f">Contraption</a>
</li>
<li>setBackground()
: <a class="el" href="d6/d2d/a00047.php#a3f710c0adafe15f27766f70a1c5b4dee">Window</a>
, <a class="el" href="d4/dca/a00048.php#ac7b9d8d3e328e0285ef4664e20acb8d3">WindowButton</a>
</li>
<li>setCaste()
: <a class="el" href="d0/d0b/a00004.php#a1817b0ca58a288635443ec70eef39435">Ant</a>
</li>
<li>setCentralWidget()
: <a class="el" href="d6/d2d/a00047.php#a8c65cb42e811de87be8743af6b9d21ed">Window</a>
</li>
<li>setClickedColor()
: <a class="el" href="d4/dca/a00048.php#a7a087338372f7592853b050d168df152">WindowButton</a>
</li>
<li>setContentAdminWidgets()
: <a class="el" href="d6/d5b/a00026.php#af0aca5335b2f075de2cdbf0fe9c33645">MainWindow</a>
</li>
<li>setContentConnectWidgets()
: <a class="el" href="d6/d5b/a00026.php#a9da75111decb2a68a08c06dec6796d8a">MainWindow</a>
</li>
<li>setDamages()
: <a class="el" href="d1/d2b/a00018.php#abcead1c3d42baabdcfb06b695b163a04">Entity</a>
</li>
<li>setDatabase()
: <a class="el" href="de/d21/a00006.php#a14ed61f03ce957690801dcc27e59930a">BDD</a>
</li>
<li>setExperience()
: <a class="el" href="dc/d87/a00032.php#af93214bdf82686e3c24401d6fb50ee4d">Player&lt; PlayerParent &gt;</a>
</li>
<li>setExperienceMax()
: <a class="el" href="dc/d87/a00032.php#a835918495707d8b37e0ebeed0d6cf439">Player&lt; PlayerParent &gt;</a>
</li>
<li>setFatal()
: <a class="el" href="de/d21/a00006.php#a1c3535db0b4aa44778421c5f35c379ff">BDD</a>
</li>
<li>setFood()
: <a class="el" href="d1/d7c/a00003.php#ac1860f30915418b618296f857be9151d">Animal</a>
</li>
<li>setFoodMax()
: <a class="el" href="d1/d7c/a00003.php#ae77854b90674fa4d0de31766b04efc36">Animal</a>
</li>
<li>setGradient()
: <a class="el" href="d4/dca/a00048.php#a434a8192bfe4dea8c7b4e1b052a1a943">WindowButton</a>
</li>
<li>setH()
: <a class="el" href="d7/dd4/a00013.php#afb8030a7a7df2bef59356c293f845487">Contraption</a>
, <a class="el" href="d0/d33/a00027.php#a713ccdad293fb792e0a8cf29d9b048e0">Map</a>
</li>
<li>setHeader()
: <a class="el" href="d5/db6/a00042.php#a25bba3124cdbe518985157ff23b0b1d0">TableWidget</a>
</li>
<li>setHoveredColor()
: <a class="el" href="d4/dca/a00048.php#a6947ea55943b909c1d492ad2f79ae1f8">WindowButton</a>
</li>
<li>setId()
: <a class="el" href="dc/d87/a00032.php#aaf3aba878522716fba266caa573df8f9">Player&lt; PlayerParent &gt;</a>
</li>
<li>setIndex()
: <a class="el" href="d4/dee/a00008.php#af473fc46af7d680963e7aca100aae1f3">CheckBox</a>
, <a class="el" href="db/df3/a00034.php#a9deef0b896e8f06dcf727f52441df445">PushButton</a>
</li>
<li>setLevel()
: <a class="el" href="d7/dd4/a00013.php#ae9131d3133c67c22f8692d4bd806187e">Contraption</a>
</li>
<li>setLife()
: <a class="el" href="d1/d2b/a00018.php#afd211ba2273c0fafef236763c80df4e9">Entity</a>
</li>
<li>setMail()
: <a class="el" href="dc/d87/a00032.php#ab0075a5ffb42bfe0d6e84e36cad3e0ab">Player&lt; PlayerParent &gt;</a>
</li>
<li>setMap()
: <a class="el" href="d7/dd4/a00013.php#a0d88e87317d6f003471fcf52808a4a25">Contraption</a>
</li>
<li>setMargin()
: <a class="el" href="d6/d2d/a00047.php#a4cec8e761a776437c9886d6982c22a54">Window</a>
</li>
<li>setNormalColor()
: <a class="el" href="d4/dca/a00048.php#a4babac31336534efca737c5f73710c1d">WindowButton</a>
</li>
<li>setPassword()
: <a class="el" href="dc/d87/a00032.php#a809fc643a612879ac35690383dfd31e8">Player&lt; PlayerParent &gt;</a>
</li>
<li>setPointsDist()
: <a class="el" href="db/db2/a00020.php#a8039208138c6c15d89f3460b552f6b37">GraphScene</a>
</li>
<li>setPosition()
: <a class="el" href="d7/dd4/a00013.php#a05facc668dcb27c1bab72118aa5bafe7">Contraption</a>
</li>
<li>setPrivate()
: <a class="el" href="db/d3a/a00040.php#aa502d81bc7559e4db119b81ce898b2ce">RSA</a>
</li>
<li>setPublic()
: <a class="el" href="db/d3a/a00040.php#ab0019252770d8ace87c447472d5d8b1e">RSA</a>
</li>
<li>setReborn()
: <a class="el" href="d1/d2b/a00018.php#a192bdf0dc40a986f8aed9be2d8607cb5">Entity</a>
</li>
<li>setRegen()
: <a class="el" href="d1/d2b/a00018.php#a5741125f8abd83cf979bc9a590712057">Entity</a>
</li>
<li>setResistance()
: <a class="el" href="d1/d2b/a00018.php#a91d83b59b1f3bcae287c7185cc06f561">Entity</a>
</li>
<li>setSize()
: <a class="el" href="d0/d33/a00027.php#a9813f83a659948693862d888b259a322">Map</a>
, <a class="el" href="d6/d2d/a00047.php#a2983759dc6be4f8da44eff6069b2d3c8">Window</a>
</li>
<li>setSpecialAttack()
: <a class="el" href="d1/d7c/a00003.php#acd3a1a440f7f4f0553235f0ed106b7f8">Animal</a>
</li>
<li>setSpecies()
: <a class="el" href="d1/d7c/a00003.php#aacbfd4edeec5da6823f8f64d615aa23e">Animal</a>
</li>
<li>setSpeed()
: <a class="el" href="d1/d7c/a00003.php#aebcd5a392cc2f21a3a84c64bdb6da8d8">Animal</a>
</li>
<li>setStone()
: <a class="el" href="d0/d0b/a00004.php#a98381326b3d00b7ae08aae01a9b84ab7">Ant</a>
</li>
<li>setStoneMax()
: <a class="el" href="d0/d0b/a00004.php#a81a08f12660a3591d2eaa89d4d8ade22">Ant</a>
</li>
<li>setStrength()
: <a class="el" href="dc/de2/a00024.php#a49702b5127cacf36d0e401dee60bc341">Hostile</a>
</li>
<li>setTable()
: <a class="el" href="de/d21/a00006.php#aa6720203c42f48b71f4d9a97f64b687f">BDD</a>
, <a class="el" href="d4/dee/a00008.php#ad24f0483b08b440dad2d4569be54a1ff">CheckBox</a>
, <a class="el" href="db/df3/a00034.php#a9b4855b32fc3e96e6d0ca35a212aba5f">PushButton</a>
</li>
<li>setTarget()
: <a class="el" href="dc/de2/a00024.php#ab2f44509aba02128b145f53b45ae3d6e">Hostile</a>
</li>
<li>setText()
: <a class="el" href="d7/d7a/a00016.php#a71fa68c918f499cf0882f10e163653b7">Dialog</a>
</li>
<li>setTilesize()
: <a class="el" href="d4/d51/a00017.php#aa9cd414cc46f3396f58e4a7af88d6b4c">DrawScene</a>
</li>
<li>setTimeActReborn()
: <a class="el" href="d1/d2b/a00018.php#ad52da0415cd4ba8b93f34ceb0c229569">Entity</a>
</li>
<li>setTimeActRegen()
: <a class="el" href="d1/d2b/a00018.php#ac4980b5bbf4fcba13d28be159c7c8739">Entity</a>
</li>
<li>setTimePrecReborn()
: <a class="el" href="d1/d2b/a00018.php#a9150f012d86d1ef0f9c070d41da8e5ba">Entity</a>
</li>
<li>setTimePrecRegen()
: <a class="el" href="d1/d2b/a00018.php#a67c69bfc713e0275c704bd2ad40bf997">Entity</a>
</li>
<li>setUsername()
: <a class="el" href="dc/d87/a00032.php#a5b02ead36931c416ed8000b9a0a2d8aa">Player&lt; PlayerParent &gt;</a>
</li>
<li>setW()
: <a class="el" href="d7/dd4/a00013.php#a83d954f1cb764a7410de01d33cb9e396">Contraption</a>
, <a class="el" href="d0/d33/a00027.php#a60a9e42b7c5a623a9ff3b5754519c0df">Map</a>
</li>
<li>setWindowTitle()
: <a class="el" href="d6/d2d/a00047.php#a008e887882941bcd08b6439dc001ea51">Window</a>
</li>
<li>setX()
: <a class="el" href="d7/dd4/a00013.php#ab14db8239bfc09ba3c5c6e07a23033b7">Contraption</a>
</li>
<li>setXMax()
: <a class="el" href="db/db2/a00020.php#a294013125013fbd6218eeb892c53d6b4">GraphScene</a>
</li>
<li>setXMin()
: <a class="el" href="db/db2/a00020.php#a53a17a634417fcde5b9cac44699ed7a6">GraphScene</a>
</li>
<li>setXRange()
: <a class="el" href="db/db2/a00020.php#a7b4d85fc0786904021c33902cec3dbdb">GraphScene</a>
</li>
<li>setXStep()
: <a class="el" href="db/db2/a00020.php#a7bcd5ff38039ca92991a9b72b6f0e8ea">GraphScene</a>
</li>
<li>setY()
: <a class="el" href="d7/dd4/a00013.php#a9a260fe681d3f4be9cb08546dff4d3d4">Contraption</a>
</li>
<li>setYMax()
: <a class="el" href="db/db2/a00020.php#a4345f99a23e4cc5fa07c55cf3511537e">GraphScene</a>
</li>
<li>setYMin()
: <a class="el" href="db/db2/a00020.php#a4a87303127505bce46d4dcc30ce1f122">GraphScene</a>
</li>
<li>setYRange()
: <a class="el" href="db/db2/a00020.php#a4f75f2238bcc5df131f3e4198bc1c186">GraphScene</a>
</li>
<li>setYStep()
: <a class="el" href="db/db2/a00020.php#a0691b268ad07ea33bf254b0f489df59d">GraphScene</a>
</li>
<li>setZ()
: <a class="el" href="d7/dd4/a00013.php#a61b34301ffd55f3f9b6bc319020e691d">Contraption</a>
</li>
<li>showEvent()
: <a class="el" href="d6/d2d/a00047.php#a677a2c1046a84743e709515f5618b1e8">Window</a>
</li>
<li>showTitlebar()
: <a class="el" href="d6/d2d/a00047.php#a8ad2a767e19299b153f9bc0457f13114">Window</a>
</li>
<li>start()
: <a class="el" href="da/da0/a00009.php#a8a050959dcff11c85d695989e9099a8c">Clock</a>
, <a class="el" href="d6/d42/a00043.php#a18a29af58bc18e1644230c747afb35ec">Timer</a>
</li>
<li>stateChanged()
: <a class="el" href="d4/dee/a00008.php#a2a8d7c87f758badc4fcb643519e7d78a">CheckBox</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
