<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Class Members - Variables</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li class="current"><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_enum.php"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.php"><span>Enumerator</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_d"><span>d</span></a></li>
      <li><a href="#index_h"><span>h</span></a></li>
      <li><a href="#index_i"><span>i</span></a></li>
      <li><a href="#index_l"><span>l</span></a></li>
      <li><a href="#index_m"><span>m</span></a></li>
      <li><a href="#index_p"><span>p</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li><a href="#index_t"><span>t</span></a></li>
      <li><a href="#index_v"><span>v</span></a></li>
      <li><a href="#index_w"><span>w</span></a></li>
      <li><a href="#index_x"><span>x</span></a></li>
      <li><a href="#index_y"><span>y</span></a></li>
      <li class="current"><a href="#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_vars.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>angle
: <a class="el" href="d2/de7/a00014.php#a062e1a4fe2f7d6f8d771f13f10844a19">ContraptionAttr</a>
</li>
</ul>


<h3><a class="anchor" id="index_d"></a>- d -</h3><ul>
<li>direction
: <a class="el" href="d1/d7c/a00003.php#a3f306d4e967d165b8ef55f6cdf9bde23">Animal</a>
</li>
</ul>


<h3><a class="anchor" id="index_h"></a>- h -</h3><ul>
<li>h
: <a class="el" href="d2/de7/a00014.php#a480fb32edc0218d9d1cead0a8e6f9d15">ContraptionAttr</a>
, <a class="el" href="d5/de0/a00050.php#aab0b2a75b9747cdc33e2982b2df3c322">WorldDimensions</a>
</li>
</ul>


<h3><a class="anchor" id="index_i"></a>- i -</h3><ul>
<li>init
: <a class="el" href="dc/d87/a00032.php#a024d37d9bdf83c1cc6618df8cc574aa2">Player&lt; PlayerParent &gt;</a>
</li>
<li>initialized
: <a class="el" href="d5/d16/a00029.php#a6faa1b5c8a9e19348d0bfef6232c90cb">Node&lt; T &gt;</a>
, <a class="el" href="dd/d32/a00041.php#a5b9c0375ba50d6f3f7e83d983088ac08">Scene</a>
</li>
</ul>


<h3><a class="anchor" id="index_l"></a>- l -</h3><ul>
<li>left
: <a class="el" href="d5/d16/a00029.php#a2841886a16c27e72b21885025c00b44b">Node&lt; T &gt;</a>
</li>
<li>losted
: <a class="el" href="dc/d87/a00032.php#ac3b3f61fa669c386bb9b2c912363d0b5">Player&lt; PlayerParent &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_m"></a>- m -</h3><ul>
<li>m_Cache
: <a class="el" href="d6/d2d/a00047.php#a065e43061d8abb3717302dc1acf139c3">Window</a>
</li>
<li>m_start
: <a class="el" href="da/da0/a00009.php#ad482076b35f14f806f688e956245483a">Clock</a>
, <a class="el" href="d6/d42/a00043.php#a8fb741bf0ac74d067fcfcfafb2c8ab61">Timer</a>
</li>
</ul>


<h3><a class="anchor" id="index_p"></a>- p -</h3><ul>
<li>paused
: <a class="el" href="dc/d87/a00032.php#aefb2fbad6ea8b979f46de232a4ff9eaa">Player&lt; PlayerParent &gt;</a>
</li>
<li>pixmaps
: <a class="el" href="d4/d51/a00017.php#a99f3c0b81bbecfbf850e920ffc2f6f0a">DrawScene</a>
</li>
<li>printed_background
: <a class="el" href="d4/d51/a00017.php#aecb82ecbd590818d52d58227101a490d">DrawScene</a>
</li>
<li>privateK
: <a class="el" href="db/d3a/a00040.php#a933f86ffad0a7a2d5d5e6099bdb5f1be">RSA</a>
</li>
<li>publicK
: <a class="el" href="db/d3a/a00040.php#a7d293f0a39aacf8eb05abc7355d436e2">RSA</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>right
: <a class="el" href="d5/d16/a00029.php#ad7092450d89448320103cde1f72da320">Node&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>scaled_pixmaps
: <a class="el" href="d4/d51/a00017.php#af1a71ac1ae84ae88e00810307b2f146d">DrawScene</a>
</li>
<li>started
: <a class="el" href="da/da0/a00009.php#aed945651f59f21f56df523af2719597e">Clock</a>
, <a class="el" href="d6/d42/a00043.php#ab3cd20a0909df03a384a09b1b8151d3e">Timer</a>
</li>
</ul>


<h3><a class="anchor" id="index_t"></a>- t -</h3><ul>
<li>target
: <a class="el" href="dc/de2/a00024.php#a54cd84496707554686bc5fc43b57a4f8">Hostile</a>
</li>
<li>tileSize
: <a class="el" href="d4/d51/a00017.php#a124d4bd03677251c2159bd0dd4254306">DrawScene</a>
</li>
</ul>


<h3><a class="anchor" id="index_v"></a>- v -</h3><ul>
<li>values
: <a class="el" href="d5/d16/a00029.php#a440411e958356c1d3912dce01ae74edc">Node&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_w"></a>- w -</h3><ul>
<li>w
: <a class="el" href="d2/de7/a00014.php#a949dbd15efa71ddbb294abf15517d8b0">ContraptionAttr</a>
, <a class="el" href="d5/de0/a00050.php#a56d14d07cb773a1a4bf12f16e7b57d07">WorldDimensions</a>
</li>
<li>weight
: <a class="el" href="d5/d16/a00029.php#aa2cb07a6e63a4dc1f1a05d3e634a8fdd">Node&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_x"></a>- x -</h3><ul>
<li>x
: <a class="el" href="d0/dc0/a00033.php#ab99c56589bc8ad5fa5071387110a5bc7">Point</a>
</li>
</ul>


<h3><a class="anchor" id="index_y"></a>- y -</h3><ul>
<li>y
: <a class="el" href="d0/dc0/a00033.php#afa38be143ae800e6ad69ce8ed4df62d8">Point</a>
</li>
</ul>


<h3><a class="anchor" id="index_z"></a>- z -</h3><ul>
<li>z
: <a class="el" href="d0/dc0/a00033.php#a05ba3b1dfcb19430582ae953cbbfbded">Point</a>
, <a class="el" href="d5/de0/a00050.php#aa07c34b536e895dc3ab45bb353aa54a6">WorldDimensions</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
