<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>ProjetFinalCPP: File Members</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">ProjetFinalCPP
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li class="current"><a href="globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="globals.php"><span>All</span></a></li>
      <li class="current"><a href="globals_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('globals_func.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;<ul>
<li>addAsk()
: <a class="el" href="d1/d7c/a00003.php#a2003fa6138007746e85c2b697d147b58">functions.hpp</a>
</li>
<li>addCategory()
: <a class="el" href="d1/d7c/a00003.php#afeb2d8632fb1dad24def5d95d27f43f0">functions.hpp</a>
</li>
<li>addGame()
: <a class="el" href="d1/d7c/a00003.php#a35ee2c6a333148aed442bb741b2bf82d">functions.hpp</a>
</li>
<li>addQuestion()
: <a class="el" href="d1/d7c/a00003.php#ad86a004962b3149094f4cc660ecb05d4">functions.hpp</a>
</li>
<li>addUsers()
: <a class="el" href="d1/d7c/a00003.php#aff4b34ff516467549fc9daa6a8f3d4ac">functions.hpp</a>
</li>
<li>deleteAsk()
: <a class="el" href="d1/d7c/a00003.php#af57e491c251eeaf366674ea6df624cd1">functions.hpp</a>
</li>
<li>deleteCategory()
: <a class="el" href="d1/d7c/a00003.php#a14880f51cece87ca27691c7acfa01d8a">functions.hpp</a>
</li>
<li>deleteGame()
: <a class="el" href="d1/d7c/a00003.php#a8205b4d8f60ec0146b15eace1d79d95a">functions.hpp</a>
</li>
<li>deletePoints()
: <a class="el" href="d1/d7c/a00003.php#a46e754bfd8e03764969330bc39a1fa66">functions.hpp</a>
</li>
<li>deleteQuestion()
: <a class="el" href="d1/d7c/a00003.php#a0c5a4808a05a3628f1b8e88ac398c70a">functions.hpp</a>
</li>
<li>deleteUsers()
: <a class="el" href="d1/d7c/a00003.php#a4df7c0879644507b94167bd565cd88bc">functions.hpp</a>
</li>
<li>list()
: <a class="el" href="d1/d7c/a00003.php#a487aa0a5ee1a53eddfa78ea676d3ff2b">functions.hpp</a>
</li>
<li>listAsk()
: <a class="el" href="d1/d7c/a00003.php#a0820a14dbb5072c112cf32466c8fc6c3">functions.hpp</a>
</li>
<li>listCategory()
: <a class="el" href="d1/d7c/a00003.php#af3143ec2b5319c969adf991c009373f0">functions.hpp</a>
</li>
<li>listDifficulty()
: <a class="el" href="d1/d7c/a00003.php#ad63ee67279e62ee5eaf73bb188ba0b4a">functions.hpp</a>
</li>
<li>listGame()
: <a class="el" href="d1/d7c/a00003.php#a1caf2a7a9b33c712063314f6bac74470">functions.hpp</a>
</li>
<li>listPoints()
: <a class="el" href="d1/d7c/a00003.php#af34790c4f5c0c4ad30d069fa2766559c">functions.hpp</a>
</li>
<li>listQuestion()
: <a class="el" href="d1/d7c/a00003.php#a887113739bafac257bbd35996edfeb81">functions.hpp</a>
</li>
<li>listUsers()
: <a class="el" href="d1/d7c/a00003.php#aa43b53615192bcce310fc51944bf217b">functions.hpp</a>
</li>
<li>updateAsk()
: <a class="el" href="d1/d7c/a00003.php#aaee44428f5b0401f7b9ad5b073254fd3">functions.hpp</a>
</li>
<li>updateCategory()
: <a class="el" href="d1/d7c/a00003.php#a2227326c53ffa5963bcc96c7983c6383">functions.hpp</a>
</li>
<li>updateDifficulty()
: <a class="el" href="d1/d7c/a00003.php#a4f84d201465ec63094f6407c0cdb6a8d">functions.hpp</a>
</li>
<li>updateGame()
: <a class="el" href="d1/d7c/a00003.php#a870df29ea630e53aa77c960373e0825f">functions.hpp</a>
</li>
<li>updateQuestion()
: <a class="el" href="d1/d7c/a00003.php#ae13343b52f992bcba9e6fcb79bddf71e">functions.hpp</a>
</li>
<li>updateUsers()
: <a class="el" href="d1/d7c/a00003.php#ac6acc509b5aa3caa3f76450ed835759e">functions.hpp</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
