<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: maths.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/de0/a00050.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">maths.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;iostream&gt;</code><br />
<code>#include &lt;cmath&gt;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for maths.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/d1f/a00083.png" border="0" usemap="#maths_8hpp" alt=""/></div>
</div>
</div>
<p><a href="../../d5/de0/a00050_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ab5254a19797bf686467bc0f475bf6fdd"><td class="memTemplParams" colspan="2">template&lt;typename V &gt; </td></tr>
<tr class="memitem:ab5254a19797bf686467bc0f475bf6fdd"><td class="memTemplItemLeft" align="right" valign="top">V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#ab5254a19797bf686467bc0f475bf6fdd">wholePart</a> (V a)</td></tr>
<tr class="memdesc:ab5254a19797bf686467bc0f475bf6fdd"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the whole part of the given number.  <a href="#ab5254a19797bf686467bc0f475bf6fdd">More...</a><br /></td></tr>
<tr class="separator:ab5254a19797bf686467bc0f475bf6fdd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6a8af65111300da455bef67651f83c73"><td class="memTemplParams" colspan="2">template&lt;typename V &gt; </td></tr>
<tr class="memitem:a6a8af65111300da455bef67651f83c73"><td class="memTemplItemLeft" align="right" valign="top">V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a6a8af65111300da455bef67651f83c73">decimalPart</a> (V a)</td></tr>
<tr class="memdesc:a6a8af65111300da455bef67651f83c73"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the decimal part of the given number.  <a href="#a6a8af65111300da455bef67651f83c73">More...</a><br /></td></tr>
<tr class="separator:a6a8af65111300da455bef67651f83c73"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9f362f22a77587bb719f13bc7fb185a2"><td class="memTemplParams" colspan="2">template&lt;typename V , typename U &gt; </td></tr>
<tr class="memitem:a9f362f22a77587bb719f13bc7fb185a2"><td class="memTemplItemLeft" align="right" valign="top">V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a9f362f22a77587bb719f13bc7fb185a2">mod</a> (V a, U b)</td></tr>
<tr class="memdesc:a9f362f22a77587bb719f13bc7fb185a2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the modulo of two numbers.  <a href="#a9f362f22a77587bb719f13bc7fb185a2">More...</a><br /></td></tr>
<tr class="separator:a9f362f22a77587bb719f13bc7fb185a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6e9b223b45f9c0ef8d93fa65db1a8f98"><td class="memTemplParams" colspan="2">template&lt;typename V &gt; </td></tr>
<tr class="memitem:a6e9b223b45f9c0ef8d93fa65db1a8f98"><td class="memTemplItemLeft" align="right" valign="top">V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a6e9b223b45f9c0ef8d93fa65db1a8f98">pgcd</a> (V a, V b)</td></tr>
<tr class="memdesc:a6e9b223b45f9c0ef8d93fa65db1a8f98"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the result of the pgcd.  <a href="#a6e9b223b45f9c0ef8d93fa65db1a8f98">More...</a><br /></td></tr>
<tr class="separator:a6e9b223b45f9c0ef8d93fa65db1a8f98"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab60083feca94427f7b2c4dfaeb249f07"><td class="memTemplParams" colspan="2">template&lt;typename V &gt; </td></tr>
<tr class="memitem:ab60083feca94427f7b2c4dfaeb249f07"><td class="memTemplItemLeft" align="right" valign="top">V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#ab60083feca94427f7b2c4dfaeb249f07">eucl</a> (V a, V b)</td></tr>
<tr class="memdesc:ab60083feca94427f7b2c4dfaeb249f07"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the result of the euclidian function.  <a href="#ab60083feca94427f7b2c4dfaeb249f07">More...</a><br /></td></tr>
<tr class="separator:ab60083feca94427f7b2c4dfaeb249f07"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa7446c664998ff110eeaf6c2bab19772"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:aa7446c664998ff110eeaf6c2bab19772"><td class="memTemplItemLeft" align="right" valign="top">T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#aa7446c664998ff110eeaf6c2bab19772">dist</a> (T x1, T x2, T y1, T y2, T z1=0, T z2=0)</td></tr>
<tr class="memdesc:aa7446c664998ff110eeaf6c2bab19772"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the distance of the given coordinates.  <a href="#aa7446c664998ff110eeaf6c2bab19772">More...</a><br /></td></tr>
<tr class="separator:aa7446c664998ff110eeaf6c2bab19772"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a54a702d8a0a5aa317cc65f5b01ed4ee6"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a54a702d8a0a5aa317cc65f5b01ed4ee6"><td class="memTemplItemLeft" align="right" valign="top">T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a54a702d8a0a5aa317cc65f5b01ed4ee6">sq</a> (T in)</td></tr>
<tr class="memdesc:a54a702d8a0a5aa317cc65f5b01ed4ee6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the square of the given number.  <a href="#a54a702d8a0a5aa317cc65f5b01ed4ee6">More...</a><br /></td></tr>
<tr class="separator:a54a702d8a0a5aa317cc65f5b01ed4ee6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad44dc8b9cd6eaa619880db19cf171751"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:ad44dc8b9cd6eaa619880db19cf171751"><td class="memTemplItemLeft" align="right" valign="top">T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#ad44dc8b9cd6eaa619880db19cf171751">abs</a> (T in)</td></tr>
<tr class="memdesc:ad44dc8b9cd6eaa619880db19cf171751"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the absolute value of the given number.  <a href="#ad44dc8b9cd6eaa619880db19cf171751">More...</a><br /></td></tr>
<tr class="separator:ad44dc8b9cd6eaa619880db19cf171751"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a193486f414e3b93b2284a85977a4a02c"><td class="memTemplParams" colspan="2">template&lt;typename T , typename V , typename U  = typename std::conditional&lt;		std::is_integral&lt;T&gt;::value &amp;&amp; std::is_integral&lt;V&gt;::value || std::is_floating_point&lt;T&gt;::value &amp;&amp; std::is_floating_point&lt;V&gt;::value,		typename std::conditional&lt;			sizeof(T) &gt;= sizeof(V),			T,			V		&gt;::type, typename std::conditional&lt; std::is_floating_point&lt; T &gt;::value &amp;&amp;std::is_integral&lt; V &gt;::value, T, typename std::conditional&lt; std::is_floating_point&lt; V &gt;::value &amp;&amp;std::is_integral&lt; T &gt;::value, V, V &gt;::type &gt;::type &gt; </td></tr>
<tr class="memitem:a193486f414e3b93b2284a85977a4a02c"><td class="memTemplItemLeft" align="right" valign="top">::type U&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a193486f414e3b93b2284a85977a4a02c">min</a> (T a, V b)</td></tr>
<tr class="memdesc:a193486f414e3b93b2284a85977a4a02c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the minimum of the arguments.  <a href="#a193486f414e3b93b2284a85977a4a02c">More...</a><br /></td></tr>
<tr class="separator:a193486f414e3b93b2284a85977a4a02c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5673d3f9fc79ba39127c4a339dea626"><td class="memTemplParams" colspan="2">template&lt;typename T , typename V , typename U  = typename std::conditional&lt;		std::is_integral&lt;T&gt;::value &amp;&amp; std::is_integral&lt;V&gt;::value || std::is_floating_point&lt;T&gt;::value &amp;&amp; std::is_floating_point&lt;V&gt;::value,		typename std::conditional&lt;			sizeof(T) &gt;= sizeof(V),			T,			V		&gt;::type, typename std::conditional&lt; std::is_floating_point&lt; T &gt;::value &amp;&amp;std::is_integral&lt; V &gt;::value, T, typename std::conditional&lt; std::is_floating_point&lt; V &gt;::value &amp;&amp;std::is_integral&lt; T &gt;::value, V, V &gt;::type &gt;::type &gt; </td></tr>
<tr class="memitem:ac5673d3f9fc79ba39127c4a339dea626"><td class="memTemplItemLeft" align="right" valign="top">::type U&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#ac5673d3f9fc79ba39127c4a339dea626">max</a> (T a, V b)</td></tr>
<tr class="memdesc:ac5673d3f9fc79ba39127c4a339dea626"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the maximum of the arguments.  <a href="#ac5673d3f9fc79ba39127c4a339dea626">More...</a><br /></td></tr>
<tr class="separator:ac5673d3f9fc79ba39127c4a339dea626"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a709c7dabaae9dea50d277980278081e0"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a709c7dabaae9dea50d277980278081e0"><td class="memTemplItemLeft" align="right" valign="top">T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a709c7dabaae9dea50d277980278081e0">round</a> (T a, int zeros=0)</td></tr>
<tr class="memdesc:a709c7dabaae9dea50d277980278081e0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the round of the given number.  <a href="#a709c7dabaae9dea50d277980278081e0">More...</a><br /></td></tr>
<tr class="separator:a709c7dabaae9dea50d277980278081e0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a94305b67cb0435c3395b548ec8283154"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a94305b67cb0435c3395b548ec8283154">isPrime</a> (float nb)</td></tr>
<tr class="memdesc:a94305b67cb0435c3395b548ec8283154"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return true if the given number is prime, false either.  <a href="#a94305b67cb0435c3395b548ec8283154">More...</a><br /></td></tr>
<tr class="separator:a94305b67cb0435c3395b548ec8283154"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a65b1640156c68ea7687a41428022c1d8"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a65b1640156c68ea7687a41428022c1d8">isNumber</a> (char c)</td></tr>
<tr class="memdesc:a65b1640156c68ea7687a41428022c1d8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return true if the caracter is a number.  <a href="#a65b1640156c68ea7687a41428022c1d8">More...</a><br /></td></tr>
<tr class="separator:a65b1640156c68ea7687a41428022c1d8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af667d8a0d7e420b313a26791c49359fb"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#af667d8a0d7e420b313a26791c49359fb">sigmoide</a> (double in)</td></tr>
<tr class="memdesc:af667d8a0d7e420b313a26791c49359fb"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the result of the sigmoide function.  <a href="#af667d8a0d7e420b313a26791c49359fb">More...</a><br /></td></tr>
<tr class="separator:af667d8a0d7e420b313a26791c49359fb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa55b9d8528b25fa5167908db82dff21"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#aaa55b9d8528b25fa5167908db82dff21">dsigmoide</a> (double in)</td></tr>
<tr class="memdesc:aaa55b9d8528b25fa5167908db82dff21"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute with the derivated sigmoide.  <a href="#aaa55b9d8528b25fa5167908db82dff21">More...</a><br /></td></tr>
<tr class="separator:aaa55b9d8528b25fa5167908db82dff21"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75105ac3cb9ee25de080d973f0bfe112"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php#a75105ac3cb9ee25de080d973f0bfe112">log2p</a> (int x)</td></tr>
<tr class="memdesc:a75105ac3cb9ee25de080d973f0bfe112"><td class="mdescLeft">&#160;</td><td class="mdescRight">Do the log of x in base 2.  <a href="#a75105ac3cb9ee25de080d973f0bfe112">More...</a><br /></td></tr>
<tr class="separator:a75105ac3cb9ee25de080d973f0bfe112"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>10 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>
</div><h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="ad44dc8b9cd6eaa619880db19cf171751"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">T abs </td>
          <td>(</td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Return the absolute value of the given number. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">in</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the absolute value of <em>in</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00149">149</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a6a8af65111300da455bef67651f83c73"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename V &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">V decimalPart </td>
          <td>(</td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>a</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the decimal part of the given number. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the decimal part of <em>a</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00030">30</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de0/a00050_a6a8af65111300da455bef67651f83c73_cgraph.png" border="0" usemap="#d5/de0/a00050_a6a8af65111300da455bef67651f83c73_cgraph" alt=""/></div>
<map name="d5/de0/a00050_a6a8af65111300da455bef67651f83c73_cgraph" id="d5/de0/a00050_a6a8af65111300da455bef67651f83c73_cgraph">
<area shape="rect" id="node2" href="../../d5/de0/a00050.php#ab5254a19797bf686467bc0f475bf6fdd" title="Return the whole part of the given number. " alt="" coords="144,5,224,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aa7446c664998ff110eeaf6c2bab19772"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">T dist </td>
          <td>(</td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>x1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>x2</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>y1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>y2</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>z1</em> = <code>0</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>z2</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Return the distance of the given coordinates. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">x1</td><td>X position of the first point </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">x2</td><td>X position of the second point </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">y1</td><td>Y position of the first point </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">y2</td><td>Y position of the second point </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">z1</td><td>Z position of the first point </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">z2</td><td>Z position of the second point</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the distance between the given coordinates </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00129">129</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="aaa55b9d8528b25fa5167908db82dff21"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double dsigmoide </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Compute with the derivated sigmoide. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">in</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the result </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00271">271</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de0/a00050_aaa55b9d8528b25fa5167908db82dff21_cgraph.png" border="0" usemap="#d5/de0/a00050_aaa55b9d8528b25fa5167908db82dff21_cgraph" alt=""/></div>
<map name="d5/de0/a00050_aaa55b9d8528b25fa5167908db82dff21_cgraph" id="d5/de0/a00050_aaa55b9d8528b25fa5167908db82dff21_cgraph">
<area shape="rect" id="node2" href="../../d5/de0/a00050.php#a54a702d8a0a5aa317cc65f5b01ed4ee6" title="Return the square of the given number. " alt="" coords="135,5,173,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ab60083feca94427f7b2c4dfaeb249f07"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename V &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">V eucl </td>
          <td>(</td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the result of the euclidian function. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">b</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the result of the euclidian divide </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00082">82</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a65b1640156c68ea7687a41428022c1d8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool isNumber </td>
          <td>(</td>
          <td class="paramtype">char&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return true if the caracter is a number. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">c</td><td>The caracter to verify</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd><b>true</b> or <b>false</b> </dd></dl>

</div>
</div>
<a class="anchor" id="a94305b67cb0435c3395b548ec8283154"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool isPrime </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>nb</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return true if the given number is prime, false either. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">nb</td><td>The value to verify</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd><b>true</b> or <b>false</b> </dd></dl>

</div>
</div>
<a class="anchor" id="a75105ac3cb9ee25de080d973f0bfe112"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int log2p </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>x</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Do the log of x in base 2. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return log2(<em>x</em>) </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00281">281</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="ac5673d3f9fc79ba39127c4a339dea626"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T , typename V , typename U  = typename std::conditional&lt;		std::is_integral&lt;T&gt;::value &amp;&amp; std::is_integral&lt;V&gt;::value || std::is_floating_point&lt;T&gt;::value &amp;&amp; std::is_floating_point&lt;V&gt;::value,		typename std::conditional&lt;			sizeof(T) &gt;= sizeof(V),			T,			V		&gt;::type, typename std::conditional&lt; std::is_floating_point&lt; T &gt;::value &amp;&amp;std::is_integral&lt; V &gt;::value, T, typename std::conditional&lt; std::is_floating_point&lt; V &gt;::value &amp;&amp;std::is_integral&lt; T &gt;::value, V, V &gt;::type &gt;::type &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">::type U max </td>
          <td>(</td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the maximum of the arguments. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">b</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the maximum of <em>a</em> and <em>b</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00215">215</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a193486f414e3b93b2284a85977a4a02c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T , typename V , typename U  = typename std::conditional&lt;		std::is_integral&lt;T&gt;::value &amp;&amp; std::is_integral&lt;V&gt;::value || std::is_floating_point&lt;T&gt;::value &amp;&amp; std::is_floating_point&lt;V&gt;::value,		typename std::conditional&lt;			sizeof(T) &gt;= sizeof(V),			T,			V		&gt;::type, typename std::conditional&lt; std::is_floating_point&lt; T &gt;::value &amp;&amp;std::is_integral&lt; V &gt;::value, T, typename std::conditional&lt; std::is_floating_point&lt; V &gt;::value &amp;&amp;std::is_integral&lt; T &gt;::value, V, V &gt;::type &gt;::type &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">::type U min </td>
          <td>(</td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the minimum of the arguments. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">b</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the minimum of <em>a</em> and <em>b</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00181">181</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a9f362f22a77587bb719f13bc7fb185a2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename V , typename U &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">V mod </td>
          <td>(</td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">U&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the modulo of two numbers. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">b</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the result of the modulo </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00041">41</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de0/a00050_a9f362f22a77587bb719f13bc7fb185a2_cgraph.png" border="0" usemap="#d5/de0/a00050_a9f362f22a77587bb719f13bc7fb185a2_cgraph" alt=""/></div>
<map name="d5/de0/a00050_a9f362f22a77587bb719f13bc7fb185a2_cgraph" id="d5/de0/a00050_a9f362f22a77587bb719f13bc7fb185a2_cgraph">
<area shape="rect" id="node2" href="../../d5/de0/a00050.php#a6a8af65111300da455bef67651f83c73" title="Return the decimal part of the given number. " alt="" coords="100,5,191,32"/>
<area shape="rect" id="node3" href="../../d5/de0/a00050.php#ab5254a19797bf686467bc0f475bf6fdd" title="Return the whole part of the given number. " alt="" coords="239,5,319,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a6e9b223b45f9c0ef8d93fa65db1a8f98"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename V &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">V pgcd </td>
          <td>(</td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the result of the pgcd. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">b</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the result of pgcd </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00061">61</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de0/a00050_a6e9b223b45f9c0ef8d93fa65db1a8f98_cgraph.png" border="0" usemap="#d5/de0/a00050_a6e9b223b45f9c0ef8d93fa65db1a8f98_cgraph" alt=""/></div>
<map name="d5/de0/a00050_a6e9b223b45f9c0ef8d93fa65db1a8f98_cgraph" id="d5/de0/a00050_a6e9b223b45f9c0ef8d93fa65db1a8f98_cgraph">
<area shape="rect" id="node2" href="../../d5/de0/a00050.php#a9f362f22a77587bb719f13bc7fb185a2" title="Return the modulo of two numbers. " alt="" coords="104,5,151,32"/>
<area shape="rect" id="node3" href="../../d5/de0/a00050.php#a6a8af65111300da455bef67651f83c73" title="Return the decimal part of the given number. " alt="" coords="199,5,289,32"/>
<area shape="rect" id="node4" href="../../d5/de0/a00050.php#ab5254a19797bf686467bc0f475bf6fdd" title="Return the whole part of the given number. " alt="" coords="337,5,417,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a709c7dabaae9dea50d277980278081e0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T round </td>
          <td>(</td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>zeros</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the round of the given number. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to round </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">zeros</td><td>The number of nums after the coma</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the rounded value of <em>a</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00229">229</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de0/a00050_a709c7dabaae9dea50d277980278081e0_cgraph.png" border="0" usemap="#d5/de0/a00050_a709c7dabaae9dea50d277980278081e0_cgraph" alt=""/></div>
<map name="d5/de0/a00050_a709c7dabaae9dea50d277980278081e0_cgraph" id="d5/de0/a00050_a709c7dabaae9dea50d277980278081e0_cgraph">
<area shape="rect" id="node2" href="../../d5/de0/a00050.php#a94305b67cb0435c3395b548ec8283154" title="Return true if the given number is prime, false either. " alt="" coords="114,5,181,32"/>
<area shape="rect" id="node3" href="../../d5/de0/a00050.php#a65b1640156c68ea7687a41428022c1d8" title="Return true if the caracter is a number. " alt="" coords="108,56,187,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="af667d8a0d7e420b313a26791c49359fb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double sigmoide </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Return the result of the sigmoide function. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">in</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the result </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00261">261</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a54a702d8a0a5aa317cc65f5b01ed4ee6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">T sq </td>
          <td>(</td>
          <td class="paramtype">T&#160;</td>
          <td class="paramname"><em>in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Return the square of the given number. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">in</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the square of <em>in</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00139">139</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="ab5254a19797bf686467bc0f475bf6fdd"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename V &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">V wholePart </td>
          <td>(</td>
          <td class="paramtype">V&#160;</td>
          <td class="paramname"><em>a</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the whole part of the given number. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">a</td><td>The value to compute</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the whole part of <em>a</em> </dd></dl>

<p>Definition at line <a class="el" href="../../d5/de0/a00050_source.php#l00020">20</a> of file <a class="el" href="../../d5/de0/a00050_source.php">maths.hpp</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d5/de0/a00050.php">maths.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
