<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: inscription.js Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dd/d1b/a00015_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">inscription.js</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../dd/d1b/a00015.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment">/* addEventListener */</span></div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;$(<span class="stringliteral">&quot;#formulaireInscription&quot;</span>).addEventListener(<span class="stringliteral">&#39;submit&#39;</span>,<a class="code" href="../../dd/d1b/a00015.php#ae14c93c8599895dff3c04db5d1d8504c">valideInscription</a>);</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;$(<span class="stringliteral">&quot;#pseudo&quot;</span>).addEventListener(<span class="stringliteral">&#39;change&#39;</span>,<a class="code" href="../../da/da0/a00009.php#a0db9c30b86d2f4aa120daa6247990007">verifPseudo</a>);</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;$(<span class="stringliteral">&quot;#email&quot;</span>).addEventListener(<span class="stringliteral">&#39;change&#39;</span>,<a class="code" href="../../da/da0/a00009.php#a4a822815e57b31479eb6d364e3003fa2">verifMail</a>);</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;$(<span class="stringliteral">&quot;#boutonAvatar&quot;</span>).addEventListener(<span class="stringliteral">&#39;change&#39;</span>,<a class="code" href="../../da/da0/a00009.php#a1426a760631d33602005a8bb59e49c7a">recupérationAvatar</a>);</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;$(<span class="stringliteral">&quot;#boutonAvatar2&quot;</span>).addEventListener( <span class="stringliteral">&quot;click&quot;</span>, <span class="keyword">function</span>( event ) {</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;  <span class="keyword">event</span>.preventDefault();</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;  $(<span class="stringliteral">&quot;#boutonAvatar&quot;</span>).click();</div><div class="line"><a name="l00016"></a><span class="lineno"><a class="line" href="../../dd/d1b/a00015.php#a5df37b7f02e5cdc7d9412b7f872b8e01">   16</a></span>&#160;  <span class="keywordflow">return</span> <span class="keyword">false</span>;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;});</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;$(<span class="stringliteral">&quot;#pseudo&quot;</span>).addEventListener(<span class="stringliteral">&#39;blur&#39;</span>,<span class="keyword">function</span>(event){</div><div class="line"><a name="l00020"></a><span class="lineno"><a class="line" href="../../dd/d1b/a00015.php#a1f0d86ab32405786812d806542ca3280">   20</a></span>&#160;var <a class="code" href="../../dd/d1b/a00015.php#a1f0d86ab32405786812d806542ca3280">pseudo</a>=<span class="keyword">event</span>.currentTarget.value;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;console.log($(<span class="stringliteral">&#39;#boutonAvatar&#39;</span>).files[0].type);</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;<a class="code" href="../../dd/d1b/a00015.php#af2952b3a0807f32876447a30f44b4a4c">ajaxRequest</a>(<span class="stringliteral">&quot;GET&quot;</span>,<span class="stringliteral">&#39;php/request.php/pseudo&#39;</span>,<a class="code" href="../../da/da0/a00009.php#ac5538f7db327e4d05dd85cbfb8db94d7">verifPseudoBDD</a>,<span class="stringliteral">&#39;pseudo=&#39;</span>+pseudo);</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;});</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;$(<span class="stringliteral">&quot;#email&quot;</span>).addEventListener(<span class="stringliteral">&#39;blur&#39;</span>,<span class="keyword">function</span>(event){</div><div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="../../dd/d1b/a00015.php#afabde1db53e2a42b1568728e0fc155f7">   26</a></span>&#160;var <a class="code" href="../../dd/d1b/a00015.php#afabde1db53e2a42b1568728e0fc155f7">email</a>=<span class="keyword">event</span>.currentTarget.value;</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;<a class="code" href="../../dd/d1b/a00015.php#af2952b3a0807f32876447a30f44b4a4c">ajaxRequest</a>(<span class="stringliteral">&quot;GET&quot;</span>,<span class="stringliteral">&#39;php/request.php/email&#39;</span>,<a class="code" href="../../da/da0/a00009.php#a24e23b6a325155daad0f098a989d6d41">verifEmailBDD</a>,<span class="stringliteral">&#39;email=&#39;</span>+email);</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;});</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="comment">/***************************/</span></div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="../../dd/d1b/a00015.php#a558403c3a40c010539026c0e7e8a7b49">   30</a></span>&#160;var <a class="code" href="../../dd/d1b/a00015.php#a558403c3a40c010539026c0e7e8a7b49">verifBDDPseudo</a>=<span class="keyword">false</span>;</div><div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="../../dd/d1b/a00015.php#adda857c7fc0ffa8117463c95f5ba277e">   31</a></span>&#160;var <a class="code" href="../../dd/d1b/a00015.php#adda857c7fc0ffa8117463c95f5ba277e">verifBDDEmail</a>=<span class="keyword">false</span>;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;</div><div class="line"><a name="l00037"></a><span class="lineno"><a class="line" href="../../dd/d1b/a00015.php#ae14c93c8599895dff3c04db5d1d8504c">   37</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../dd/d1b/a00015.php#ae14c93c8599895dff3c04db5d1d8504c">valideInscription</a>(event){</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;  var text;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;  <span class="keywordflow">if</span>(verifBDDPseudo==<span class="keyword">true</span> || verifBDDEmail==<span class="keyword">true</span> || <a class="code" href="../../da/da0/a00009.php#a5e7778e2c5dd64ac673d79add217c6cf">verifMotDePasse</a>()==<span class="keyword">true</span> || <a class="code" href="../../da/da0/a00009.php#a4a822815e57b31479eb6d364e3003fa2">verifMail</a>()==<span class="keyword">true</span> || <a class="code" href="../../da/da0/a00009.php#a0db9c30b86d2f4aa120daa6247990007">verifPseudo</a>()==<span class="keyword">true</span> || <a class="code" href="../../da/da0/a00009.php#a9d0e9578c0fb0424b8b09301ecffffd5">verifImage</a>()==<span class="keyword">true</span>){</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    <span class="keyword">event</span>.preventDefault();</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="keywordflow">if</span>(verifBDDPseudo){</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;        <a class="code" href="../../da/da0/a00009.php#a76081b25499ce0257c512f37f1ad9988">surligne</a>(pseudo, <span class="keyword">true</span>);</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;        text = <span class="stringliteral">&#39;Votre pseudo est déja pris&#39;</span>;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    }<span class="keywordflow">else</span> <span class="keywordflow">if</span>(verifBDDEmail){</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;        <a class="code" href="../../da/da0/a00009.php#a76081b25499ce0257c512f37f1ad9988">surligne</a>(<a class="code" href="../../dd/d1b/a00015.php#afabde1db53e2a42b1568728e0fc155f7">email</a>, <span class="keyword">true</span>);</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        text = <span class="stringliteral">&#39;Un compte est déja relié à cette adresse email&#39;</span>;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;    }<span class="keywordflow">else</span> <span class="keywordflow">if</span>(<a class="code" href="../../da/da0/a00009.php#a5e7778e2c5dd64ac673d79add217c6cf">verifMotDePasse</a>()){</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        text = <span class="stringliteral">&#39;Veuillez mettre 2 fois le même mot de passe&#39;</span>;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;    }<span class="keywordflow">else</span> <span class="keywordflow">if</span>(<a class="code" href="../../da/da0/a00009.php#a4a822815e57b31479eb6d364e3003fa2">verifMail</a>()){</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        text = <span class="stringliteral">&#39;Veuillez mettre un bon email&#39;</span>;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;    }<span class="keywordflow">else</span> <span class="keywordflow">if</span>(<a class="code" href="../../da/da0/a00009.php#a0db9c30b86d2f4aa120daa6247990007">verifPseudo</a>()){</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;      text = <span class="stringliteral">&#39;Veuillez rentrer un pseudo entre 2 et 25 caractères&#39;</span>;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    }<span class="keywordflow">else</span> <span class="keywordflow">if</span>(<a class="code" href="../../da/da0/a00009.php#a9d0e9578c0fb0424b8b09301ecffffd5">verifImage</a>()){</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;      text = <span class="stringliteral">&#39;Veuillez mettre une image png,jpg,jpeg,ou gif&#39;</span>;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;    }</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;    httpErrors(403,text);</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;  }<span class="keywordflow">else</span>{</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;    alert(<span class="stringliteral">&quot;Votre inscription a été enregistrée, vous allez être redirigé vers la page d&#39;accueil s&#39;il n&#39;y a aucune erreur pour l&#39;avatar.&quot;</span>);</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;  }</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;}</div><div class="ttc" id="a00009_php_a0db9c30b86d2f4aa120daa6247990007"><div class="ttname"><a href="../../da/da0/a00009.php#a0db9c30b86d2f4aa120daa6247990007">verifPseudo</a></div><div class="ttdeci">function verifPseudo()</div><div class="ttdoc">Check if the value of the nickname is correct. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00021">fonctions.js:21</a></div></div>
<div class="ttc" id="a00015_php_ae14c93c8599895dff3c04db5d1d8504c"><div class="ttname"><a href="../../dd/d1b/a00015.php#ae14c93c8599895dff3c04db5d1d8504c">valideInscription</a></div><div class="ttdeci">function valideInscription(event)</div><div class="ttdoc">check the information before the POST in the file register </div><div class="ttdef"><b>Definition:</b> <a href="../../dd/d1b/a00015_source.php#l00037">inscription.js:37</a></div></div>
<div class="ttc" id="a00009_php_a4a822815e57b31479eb6d364e3003fa2"><div class="ttname"><a href="../../da/da0/a00009.php#a4a822815e57b31479eb6d364e3003fa2">verifMail</a></div><div class="ttdeci">function verifMail()</div><div class="ttdoc">Check if the value of the email is correct. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00086">fonctions.js:86</a></div></div>
<div class="ttc" id="a00009_php_a5e7778e2c5dd64ac673d79add217c6cf"><div class="ttname"><a href="../../da/da0/a00009.php#a5e7778e2c5dd64ac673d79add217c6cf">verifMotDePasse</a></div><div class="ttdeci">function verifMotDePasse()</div><div class="ttdoc">Check if the value of the password is correct. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00034">fonctions.js:34</a></div></div>
<div class="ttc" id="a00009_php_ac5538f7db327e4d05dd85cbfb8db94d7"><div class="ttname"><a href="../../da/da0/a00009.php#ac5538f7db327e4d05dd85cbfb8db94d7">verifPseudoBDD</a></div><div class="ttdeci">function verifPseudoBDD(ajaxResponse)</div><div class="ttdoc">check if the nickname is not taken. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00119">fonctions.js:119</a></div></div>
<div class="ttc" id="a00009_php_a1426a760631d33602005a8bb59e49c7a"><div class="ttname"><a href="../../da/da0/a00009.php#a1426a760631d33602005a8bb59e49c7a">recupérationAvatar</a></div><div class="ttdeci">function recupérationAvatar()</div><div class="ttdoc">Displays the avatar chosen by the user on his computer. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00008">fonctions.js:8</a></div></div>
<div class="ttc" id="a00009_php_a24e23b6a325155daad0f098a989d6d41"><div class="ttname"><a href="../../da/da0/a00009.php#a24e23b6a325155daad0f098a989d6d41">verifEmailBDD</a></div><div class="ttdeci">function verifEmailBDD(ajaxResponse)</div><div class="ttdoc">Check if the email is not taken. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00135">fonctions.js:135</a></div></div>
<div class="ttc" id="a00015_php_adda857c7fc0ffa8117463c95f5ba277e"><div class="ttname"><a href="../../dd/d1b/a00015.php#adda857c7fc0ffa8117463c95f5ba277e">verifBDDEmail</a></div><div class="ttdeci">var verifBDDEmail</div><div class="ttdef"><b>Definition:</b> <a href="../../dd/d1b/a00015_source.php#l00031">inscription.js:31</a></div></div>
<div class="ttc" id="a00009_php_a9d0e9578c0fb0424b8b09301ecffffd5"><div class="ttname"><a href="../../da/da0/a00009.php#a9d0e9578c0fb0424b8b09301ecffffd5">verifImage</a></div><div class="ttdeci">function verifImage()</div><div class="ttdoc">Check if the type of the avatar is a jpeg or jpg or gif or png . </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00173">fonctions.js:173</a></div></div>
<div class="ttc" id="a00015_php_a1f0d86ab32405786812d806542ca3280"><div class="ttname"><a href="../../dd/d1b/a00015.php#a1f0d86ab32405786812d806542ca3280">pseudo</a></div><div class="ttdeci">var pseudo</div><div class="ttdef"><b>Definition:</b> <a href="../../dd/d1b/a00015_source.php#l00020">inscription.js:20</a></div></div>
<div class="ttc" id="a00015_php_a558403c3a40c010539026c0e7e8a7b49"><div class="ttname"><a href="../../dd/d1b/a00015.php#a558403c3a40c010539026c0e7e8a7b49">verifBDDPseudo</a></div><div class="ttdeci">var verifBDDPseudo</div><div class="ttdef"><b>Definition:</b> <a href="../../dd/d1b/a00015_source.php#l00030">inscription.js:30</a></div></div>
<div class="ttc" id="a00015_php_afabde1db53e2a42b1568728e0fc155f7"><div class="ttname"><a href="../../dd/d1b/a00015.php#afabde1db53e2a42b1568728e0fc155f7">email</a></div><div class="ttdeci">var email</div><div class="ttdef"><b>Definition:</b> <a href="../../dd/d1b/a00015_source.php#l00026">inscription.js:26</a></div></div>
<div class="ttc" id="a00015_php_af2952b3a0807f32876447a30f44b4a4c"><div class="ttname"><a href="../../dd/d1b/a00015.php#af2952b3a0807f32876447a30f44b4a4c">ajaxRequest</a></div><div class="ttdeci">ajaxRequest(&quot;GET&quot;,'php/request.php/pseudo', verifPseudoBDD,'pseudo='+pseudo)</div></div>
<div class="ttc" id="a00009_php_a76081b25499ce0257c512f37f1ad9988"><div class="ttname"><a href="../../da/da0/a00009.php#a76081b25499ce0257c512f37f1ad9988">surligne</a></div><div class="ttdeci">function surligne(champ, erreur)</div><div class="ttdoc">Change backgound color of the html element if there is an error or not. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/da0/a00009_source.php#l00151">fonctions.js:151</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../dd/d1b/a00015.php">inscription.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
