<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>ProjetFinalCPP: Entities.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">ProjetFinalCPP
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d2/dee/a00049.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Entities.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d5/df9/a00044_source.php">Contraption.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/de8/a00061_source.php">Object.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d5/de0/a00050_source.php">Entity.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../de/d8c/a00036_source.php">Animal.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/dc6/a00037_source.php">Ant.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../db/db6/a00074_source.php">Vegetal.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../df/d03/a00062_source.php">Plant.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d9/d73/a00060_source.php">Mushroom.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Entities.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/dcc/a00102.png" border="0" usemap="#Entities_8hpp" alt=""/></div>
<map name="Entities_8hpp" id="Entities_8hpp">
<area shape="rect" id="node2" href="../../d5/df9/a00044.php" title="Contraption.hpp" alt="" coords="1751,379,1866,405"/>
<area shape="rect" id="node43" href="../../d4/de8/a00061.php" title="Object.hpp" alt="" coords="1766,229,1851,256"/>
<area shape="rect" id="node44" href="../../d5/de0/a00050.php" title="Entity.hpp" alt="" coords="2013,304,2095,331"/>
<area shape="rect" id="node45" href="../../de/d8c/a00036.php" title="Animal.hpp" alt="" coords="2092,155,2179,181"/>
<area shape="rect" id="node47" href="../../d1/dc6/a00037.php" title="Ant.hpp" alt="" coords="2102,80,2169,107"/>
<area shape="rect" id="node48" href="../../db/db6/a00074.php" title="Vegetal.hpp" alt="" coords="1921,155,2011,181"/>
<area shape="rect" id="node49" href="../../df/d03/a00062.php" title="Plant.hpp" alt="" coords="2001,80,2078,107"/>
<area shape="rect" id="node50" href="../../d9/d73/a00060.php" title="Mushroom.hpp" alt="" coords="1817,80,1925,107"/>
<area shape="rect" id="node3" href="../../d6/d2d/a00047.php" title="defines.hpp" alt="" coords="1091,453,1180,480"/>
<area shape="rect" id="node16" href="../../d1/d6e/a00073.php" title="types.hpp" alt="" coords="1555,752,1633,779"/>
<area shape="rect" id="node41" href="../../d5/db6/a00042.php" title="collides.hpp" alt="" coords="1949,453,2039,480"/>
<area shape="rect" id="node42" href="../../d7/df7/a00058.php" title="Map.hpp" alt="" coords="1490,528,1562,555"/>
<area shape="rect" id="node9" href="../../db/d3a/a00040.php" title="bdd.hpp" alt="" coords="965,528,1033,555"/>
<area shape="rect" id="node21" href="../../d6/d97/a00045.php" title="convert.hpp" alt="" coords="825,752,915,779"/>
<area shape="rect" id="node26" href="../../d1/d84/a00052.php" title="files.hpp" alt="" coords="1123,677,1193,704"/>
<area shape="rect" id="node28" href="../../d0/d89/a00071.php" title="time.hpp" alt="" coords="1386,677,1458,704"/>
<area shape="rect" id="node31" href="../../df/d5f/a00064.php" title="pointers.hpp" alt="" coords="1690,603,1783,629"/>
<area shape="rect" id="node32" href="../../d2/db1/a00070.php" title="string.hpp" alt="" coords="632,752,711,779"/>
<area shape="rect" id="node35" href="../../d8/d41/a00038.php" title="Args.hpp" alt="" coords="1186,528,1261,555"/>
<area shape="rect" id="node37" href="../../d9/db3/a00066.php" title="RNG.hpp" alt="" coords="1778,528,1855,555"/>
<area shape="rect" id="node39" href="../../d3/d8b/a00059.php" title="maths.hpp" alt="" coords="1950,528,2033,555"/>
<area shape="rect" id="node19" href="../../d2/d79/a00051.php" title="errors.hpp" alt="" coords="1333,603,1413,629"/>
<area shape="rect" id="node34" href="../../d3/de7/a00039.php" title="array.hpp" alt="" coords="1008,752,1084,779"/>
<area shape="rect" id="node20" href="../../d6/d42/a00043.php" title="console.hpp" alt="" coords="1269,677,1361,704"/>
<area shape="rect" id="node33" href="../../d9/d2e/a00056.php" title="macro.hpp" alt="" coords="482,827,565,853"/>
<area shape="rect" id="node46" href="../../d4/d6d/a00055.php" title="Hostile.hpp" alt="" coords="2010,229,2098,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d1e/a00103.png" border="0" usemap="#Entities_8hppdep" alt=""/></div>
<map name="Entities_8hppdep" id="Entities_8hppdep">
<area shape="rect" id="node2" href="../../dd/d32/a00041.php" title="C++.hpp" alt="" coords="14,155,87,181"/>
<area shape="rect" id="node3" href="../../d1/d6f/a00063.php" title="Player.hpp" alt="" coords="49,80,133,107"/>
</map>
</div>
</div>
<p><a href="../../d2/dee/a00049_source.php">Go to the source code of this file.</a></p>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>29 mai 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d2/dee/a00049_source.php">Entities.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d2/dee/a00049.php">Entities.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
