<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: Vegetal Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/d3c/a00028.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="../../d9/db6/a00146.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Vegetal Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A vegetal.  
 <a href="../../dc/d3c/a00028.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d4/de8/a00061_source.php">Vegetal.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Vegetal:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/d4a/a00147.png" border="0" usemap="#Vegetal_inherit__map" alt="Inheritance graph"/></div>
<map name="Vegetal_inherit__map" id="Vegetal_inherit__map">
<area shape="rect" id="node4" href="../../d1/d2b/a00018.php" title="A mushroom. " alt="" coords="5,229,88,256"/>
<area shape="rect" id="node5" href="../../de/d11/a00021.php" title="A plant. " alt="" coords="113,229,165,256"/>
<area shape="rect" id="node2" href="../../d2/de7/a00014.php" title="An entity. " alt="" coords="64,80,120,107"/>
<area shape="rect" id="node3" href="../../da/d45/a00011.php" title="A contraption. " alt="" coords="47,5,137,32"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for Vegetal:</div>
<div class="dyncontent">
<div class="center"><img src="../../db/d48/a00148.png" border="0" usemap="#Vegetal_coll__map" alt="Collaboration graph"/></div>
<map name="Vegetal_coll__map" id="Vegetal_coll__map">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php" title="An entity. " alt="" coords="22,80,78,107"/>
<area shape="rect" id="node3" href="../../da/d45/a00011.php" title="A contraption. " alt="" coords="5,5,95,32"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ac9d1bee0742cb45180637db1bed06294"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d3c/a00028.php#ac9d1bee0742cb45180637db1bed06294">Vegetal</a> (<a class="el" href="../../d4/d51/a00017.php">Map</a> *map=nullptr, <a class="el" href="../../d3/d52/a00023.php">Point</a> pt={0, 0, 0}, <a class="el" href="../../df/d86/a00012.php">ContraptionAttr</a> attr={0, 0, 0})</td></tr>
<tr class="memdesc:ac9d1bee0742cb45180637db1bed06294"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor of the class.  <a href="#ac9d1bee0742cb45180637db1bed06294">More...</a><br /></td></tr>
<tr class="separator:ac9d1bee0742cb45180637db1bed06294"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae273444c873c7f3be7f38b6f60156a4c"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d3c/a00028.php#ae273444c873c7f3be7f38b6f60156a4c">~Vegetal</a> ()</td></tr>
<tr class="memdesc:ae273444c873c7f3be7f38b6f60156a4c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Virtual destructor.  <a href="#ae273444c873c7f3be7f38b6f60156a4c">More...</a><br /></td></tr>
<tr class="separator:ae273444c873c7f3be7f38b6f60156a4c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac3ac9ca3d977facf17953da4c853f37f"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d3c/a00028.php#ac3ac9ca3d977facf17953da4c853f37f">printInfos</a> (std::ostream &amp;stream) const </td></tr>
<tr class="memdesc:ac3ac9ca3d977facf17953da4c853f37f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the infos in the instance of the class in <em>stream</em>.  <a href="#ac3ac9ca3d977facf17953da4c853f37f">More...</a><br /></td></tr>
<tr class="separator:ac3ac9ca3d977facf17953da4c853f37f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ea0ad75fb2add027996b1653a4751f4"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="../../dc/d3c/a00028.php">Vegetal</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d3c/a00028.php#a4ea0ad75fb2add027996b1653a4751f4">cut</a> (double percent=100)</td></tr>
<tr class="memdesc:a4ea0ad75fb2add027996b1653a4751f4"><td class="mdescLeft">&#160;</td><td class="mdescRight">Cut the plant to have twice.  <a href="#a4ea0ad75fb2add027996b1653a4751f4">More...</a><br /></td></tr>
<tr class="separator:a4ea0ad75fb2add027996b1653a4751f4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00014"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00014')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d2/de7/a00014.php">Entity</a></td></tr>
<tr class="memitem:a8eb01833b85eafedca05d504d7be006b inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a8eb01833b85eafedca05d504d7be006b">Entity</a> (<a class="el" href="../../d4/d51/a00017.php">Map</a> *map=nullptr, <a class="el" href="../../d3/d52/a00023.php">Point</a> pt={0, 0, 0}, <a class="el" href="../../df/d86/a00012.php">ContraptionAttr</a> attr={0, 0, 0})</td></tr>
<tr class="memdesc:a8eb01833b85eafedca05d504d7be006b inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor of the class.  <a href="#a8eb01833b85eafedca05d504d7be006b">More...</a><br /></td></tr>
<tr class="separator:a8eb01833b85eafedca05d504d7be006b inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a588098978eea6a3486b7361605ff3f0f inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a588098978eea6a3486b7361605ff3f0f">~Entity</a> ()</td></tr>
<tr class="memdesc:a588098978eea6a3486b7361605ff3f0f inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Virtual destructor.  <a href="#a588098978eea6a3486b7361605ff3f0f">More...</a><br /></td></tr>
<tr class="separator:a588098978eea6a3486b7361605ff3f0f inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd211ba2273c0fafef236763c80df4e9 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#afd211ba2273c0fafef236763c80df4e9">setLife</a> (double life)</td></tr>
<tr class="memdesc:afd211ba2273c0fafef236763c80df4e9 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the life of the entity.  <a href="#afd211ba2273c0fafef236763c80df4e9">More...</a><br /></td></tr>
<tr class="separator:afd211ba2273c0fafef236763c80df4e9 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abcead1c3d42baabdcfb06b695b163a04 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#abcead1c3d42baabdcfb06b695b163a04">setDamages</a> (double damages)</td></tr>
<tr class="memdesc:abcead1c3d42baabdcfb06b695b163a04 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">The damages of the entity.  <a href="#abcead1c3d42baabdcfb06b695b163a04">More...</a><br /></td></tr>
<tr class="separator:abcead1c3d42baabdcfb06b695b163a04 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a91d83b59b1f3bcae287c7185cc06f561 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a91d83b59b1f3bcae287c7185cc06f561">setResistance</a> (double resistance)</td></tr>
<tr class="memdesc:a91d83b59b1f3bcae287c7185cc06f561 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the resistance of the entity.  <a href="#a91d83b59b1f3bcae287c7185cc06f561">More...</a><br /></td></tr>
<tr class="separator:a91d83b59b1f3bcae287c7185cc06f561 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1dd5e5689f86ac1ddc9a539c498d82ec inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a1dd5e5689f86ac1ddc9a539c498d82ec">setAge</a> (double age)</td></tr>
<tr class="memdesc:a1dd5e5689f86ac1ddc9a539c498d82ec inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the age of the entity.  <a href="#a1dd5e5689f86ac1ddc9a539c498d82ec">More...</a><br /></td></tr>
<tr class="separator:a1dd5e5689f86ac1ddc9a539c498d82ec inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a192bdf0dc40a986f8aed9be2d8607cb5 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a192bdf0dc40a986f8aed9be2d8607cb5">setReborn</a> (const double reborn)</td></tr>
<tr class="memdesc:a192bdf0dc40a986f8aed9be2d8607cb5 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the reborn time.  <a href="#a192bdf0dc40a986f8aed9be2d8607cb5">More...</a><br /></td></tr>
<tr class="separator:a192bdf0dc40a986f8aed9be2d8607cb5 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad52da0415cd4ba8b93f34ceb0c229569 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#ad52da0415cd4ba8b93f34ceb0c229569">setTimeActReborn</a> (const double time)</td></tr>
<tr class="memdesc:ad52da0415cd4ba8b93f34ceb0c229569 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the actual time.  <a href="#ad52da0415cd4ba8b93f34ceb0c229569">More...</a><br /></td></tr>
<tr class="separator:ad52da0415cd4ba8b93f34ceb0c229569 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9150f012d86d1ef0f9c070d41da8e5ba inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a9150f012d86d1ef0f9c070d41da8e5ba">setTimePrecReborn</a> (const double time)</td></tr>
<tr class="memdesc:a9150f012d86d1ef0f9c070d41da8e5ba inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the precedent time.  <a href="#a9150f012d86d1ef0f9c070d41da8e5ba">More...</a><br /></td></tr>
<tr class="separator:a9150f012d86d1ef0f9c070d41da8e5ba inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5741125f8abd83cf979bc9a590712057 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a5741125f8abd83cf979bc9a590712057">setRegen</a> (const double regen)</td></tr>
<tr class="memdesc:a5741125f8abd83cf979bc9a590712057 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the regeneration time.  <a href="#a5741125f8abd83cf979bc9a590712057">More...</a><br /></td></tr>
<tr class="separator:a5741125f8abd83cf979bc9a590712057 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac4980b5bbf4fcba13d28be159c7c8739 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#ac4980b5bbf4fcba13d28be159c7c8739">setTimeActRegen</a> (const double time)</td></tr>
<tr class="memdesc:ac4980b5bbf4fcba13d28be159c7c8739 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the actual time.  <a href="#ac4980b5bbf4fcba13d28be159c7c8739">More...</a><br /></td></tr>
<tr class="separator:ac4980b5bbf4fcba13d28be159c7c8739 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a67c69bfc713e0275c704bd2ad40bf997 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a67c69bfc713e0275c704bd2ad40bf997">setTimePrecRegen</a> (const double time)</td></tr>
<tr class="memdesc:a67c69bfc713e0275c704bd2ad40bf997 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the precedent time.  <a href="#a67c69bfc713e0275c704bd2ad40bf997">More...</a><br /></td></tr>
<tr class="separator:a67c69bfc713e0275c704bd2ad40bf997 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a04d2bf369c65382b8001db51b3f9568b inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a04d2bf369c65382b8001db51b3f9568b">getLifeMax</a> () const </td></tr>
<tr class="separator:a04d2bf369c65382b8001db51b3f9568b inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b51aceb9bb22ddd39ce8c8acb378e2c inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a9b51aceb9bb22ddd39ce8c8acb378e2c">getDamages</a> () const </td></tr>
<tr class="separator:a9b51aceb9bb22ddd39ce8c8acb378e2c inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abbd4dc44c41c2f29d45666e73184a5c7 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#abbd4dc44c41c2f29d45666e73184a5c7">getResistance</a> () const </td></tr>
<tr class="separator:abbd4dc44c41c2f29d45666e73184a5c7 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f9600c31ebb4ee8025204d86b2a0355 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a3f9600c31ebb4ee8025204d86b2a0355">getAge</a> () const </td></tr>
<tr class="separator:a3f9600c31ebb4ee8025204d86b2a0355 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a4ebc5d8f48e62f4ab322d6f7f35c48 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a9a4ebc5d8f48e62f4ab322d6f7f35c48">getReborn</a> () const </td></tr>
<tr class="separator:a9a4ebc5d8f48e62f4ab322d6f7f35c48 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af6020aac4cb48ab6efd0f8985fe58d5a inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#af6020aac4cb48ab6efd0f8985fe58d5a">getTimeActReborn</a> () const </td></tr>
<tr class="separator:af6020aac4cb48ab6efd0f8985fe58d5a inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5b727d71b80ecf08e26df9377b156f69 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a5b727d71b80ecf08e26df9377b156f69">getTimePrecReborn</a> () const </td></tr>
<tr class="separator:a5b727d71b80ecf08e26df9377b156f69 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8fefea906129f4a978559a2f19814255 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a8fefea906129f4a978559a2f19814255">getRegen</a> () const </td></tr>
<tr class="separator:a8fefea906129f4a978559a2f19814255 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a65a785f390af7af0bc58b69bd9aa964f inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a65a785f390af7af0bc58b69bd9aa964f">getTimeActRegen</a> () const </td></tr>
<tr class="separator:a65a785f390af7af0bc58b69bd9aa964f inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ad4de93247ee864f07acfd798d2fd13 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a4ad4de93247ee864f07acfd798d2fd13">getTimePrecRegen</a> () const </td></tr>
<tr class="separator:a4ad4de93247ee864f07acfd798d2fd13 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c839621027ac7ae02197923acd45fbd inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a0c839621027ac7ae02197923acd45fbd">grow</a> ()</td></tr>
<tr class="memdesc:a0c839621027ac7ae02197923acd45fbd inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Grow the entity.  <a href="#a0c839621027ac7ae02197923acd45fbd">More...</a><br /></td></tr>
<tr class="separator:a0c839621027ac7ae02197923acd45fbd inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5256532f85660d2c0b781888f4de7d0c inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a5256532f85660d2c0b781888f4de7d0c">getLife</a> () const </td></tr>
<tr class="separator:a5256532f85660d2c0b781888f4de7d0c inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3f0d200294bf72ae5adb0ae752e93b9 inherit pub_methods_a00014"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#ad3f0d200294bf72ae5adb0ae752e93b9">hit</a> (double damages)</td></tr>
<tr class="memdesc:ad3f0d200294bf72ae5adb0ae752e93b9 inherit pub_methods_a00014"><td class="mdescLeft">&#160;</td><td class="mdescRight">Hit an entity with <em>damages</em>.  <a href="#ad3f0d200294bf72ae5adb0ae752e93b9">More...</a><br /></td></tr>
<tr class="separator:ad3f0d200294bf72ae5adb0ae752e93b9 inherit pub_methods_a00014"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00011"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00011')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../da/d45/a00011.php">Contraption</a></td></tr>
<tr class="memitem:ac80a221d48732cc349d5ccef1e4ad319 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ac80a221d48732cc349d5ccef1e4ad319">Contraption</a> (<a class="el" href="../../d4/d51/a00017.php">Map</a> *map=nullptr, <a class="el" href="../../d3/d52/a00023.php">Point</a> pt={0, 0, 0}, <a class="el" href="../../df/d86/a00012.php">ContraptionAttr</a> attr={0, 0, 0})</td></tr>
<tr class="memdesc:ac80a221d48732cc349d5ccef1e4ad319 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor of the class.  <a href="#ac80a221d48732cc349d5ccef1e4ad319">More...</a><br /></td></tr>
<tr class="separator:ac80a221d48732cc349d5ccef1e4ad319 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acfdea93e7835722a3b211ba2b8dd1463 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#acfdea93e7835722a3b211ba2b8dd1463">~Contraption</a> ()</td></tr>
<tr class="memdesc:acfdea93e7835722a3b211ba2b8dd1463 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Virtual destructor.  <a href="#acfdea93e7835722a3b211ba2b8dd1463">More...</a><br /></td></tr>
<tr class="separator:acfdea93e7835722a3b211ba2b8dd1463 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05facc668dcb27c1bab72118aa5bafe7 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a05facc668dcb27c1bab72118aa5bafe7">setPosition</a> (<a class="el" href="../../d3/d52/a00023.php">Point</a> pt)</td></tr>
<tr class="memdesc:a05facc668dcb27c1bab72118aa5bafe7 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the position.  <a href="#a05facc668dcb27c1bab72118aa5bafe7">More...</a><br /></td></tr>
<tr class="separator:a05facc668dcb27c1bab72118aa5bafe7 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a144577a5b80062834989f99a96b6c89c inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a144577a5b80062834989f99a96b6c89c">setPosition</a> (double x, double y, double z=0)</td></tr>
<tr class="memdesc:a144577a5b80062834989f99a96b6c89c inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the position.  <a href="#a144577a5b80062834989f99a96b6c89c">More...</a><br /></td></tr>
<tr class="separator:a144577a5b80062834989f99a96b6c89c inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab14db8239bfc09ba3c5c6e07a23033b7 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ab14db8239bfc09ba3c5c6e07a23033b7">setX</a> (double x)</td></tr>
<tr class="memdesc:ab14db8239bfc09ba3c5c6e07a23033b7 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the x coordinate.  <a href="#ab14db8239bfc09ba3c5c6e07a23033b7">More...</a><br /></td></tr>
<tr class="separator:ab14db8239bfc09ba3c5c6e07a23033b7 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a260fe681d3f4be9cb08546dff4d3d4 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a9a260fe681d3f4be9cb08546dff4d3d4">setY</a> (double y)</td></tr>
<tr class="memdesc:a9a260fe681d3f4be9cb08546dff4d3d4 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the y coordinate.  <a href="#a9a260fe681d3f4be9cb08546dff4d3d4">More...</a><br /></td></tr>
<tr class="separator:a9a260fe681d3f4be9cb08546dff4d3d4 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61b34301ffd55f3f9b6bc319020e691d inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a61b34301ffd55f3f9b6bc319020e691d">setZ</a> (double z)</td></tr>
<tr class="memdesc:a61b34301ffd55f3f9b6bc319020e691d inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the z coordinate.  <a href="#a61b34301ffd55f3f9b6bc319020e691d">More...</a><br /></td></tr>
<tr class="separator:a61b34301ffd55f3f9b6bc319020e691d inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e221cb1cdd414d2d06492b575ec7120 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a3e221cb1cdd414d2d06492b575ec7120">setAttributes</a> (<a class="el" href="../../df/d86/a00012.php">ContraptionAttr</a> attr)</td></tr>
<tr class="memdesc:a3e221cb1cdd414d2d06492b575ec7120 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the attributes.  <a href="#a3e221cb1cdd414d2d06492b575ec7120">More...</a><br /></td></tr>
<tr class="separator:a3e221cb1cdd414d2d06492b575ec7120 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a96a40d8c6b09bc86be65042fad49592f inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a96a40d8c6b09bc86be65042fad49592f">setAttributes</a> (double w, double h, double angle=0)</td></tr>
<tr class="memdesc:a96a40d8c6b09bc86be65042fad49592f inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the attributes.  <a href="#a96a40d8c6b09bc86be65042fad49592f">More...</a><br /></td></tr>
<tr class="separator:a96a40d8c6b09bc86be65042fad49592f inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83d954f1cb764a7410de01d33cb9e396 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a83d954f1cb764a7410de01d33cb9e396">setW</a> (double w)</td></tr>
<tr class="memdesc:a83d954f1cb764a7410de01d33cb9e396 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the width.  <a href="#a83d954f1cb764a7410de01d33cb9e396">More...</a><br /></td></tr>
<tr class="separator:a83d954f1cb764a7410de01d33cb9e396 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afb8030a7a7df2bef59356c293f845487 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#afb8030a7a7df2bef59356c293f845487">setH</a> (double h)</td></tr>
<tr class="memdesc:afb8030a7a7df2bef59356c293f845487 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the height.  <a href="#afb8030a7a7df2bef59356c293f845487">More...</a><br /></td></tr>
<tr class="separator:afb8030a7a7df2bef59356c293f845487 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad1482208cab08d738341ab2265b37deb inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ad1482208cab08d738341ab2265b37deb">setA</a> (double angle)</td></tr>
<tr class="memdesc:ad1482208cab08d738341ab2265b37deb inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the angle.  <a href="#ad1482208cab08d738341ab2265b37deb">More...</a><br /></td></tr>
<tr class="separator:ad1482208cab08d738341ab2265b37deb inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0d88e87317d6f003471fcf52808a4a25 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a0d88e87317d6f003471fcf52808a4a25">setMap</a> (<a class="el" href="../../d4/d51/a00017.php">Map</a> *map)</td></tr>
<tr class="memdesc:a0d88e87317d6f003471fcf52808a4a25 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the map.  <a href="#a0d88e87317d6f003471fcf52808a4a25">More...</a><br /></td></tr>
<tr class="separator:a0d88e87317d6f003471fcf52808a4a25 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae9131d3133c67c22f8692d4bd806187e inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ae9131d3133c67c22f8692d4bd806187e">setLevel</a> (size_t level)</td></tr>
<tr class="memdesc:ae9131d3133c67c22f8692d4bd806187e inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the level.  <a href="#ae9131d3133c67c22f8692d4bd806187e">More...</a><br /></td></tr>
<tr class="separator:ae9131d3133c67c22f8692d4bd806187e inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abc9cc2cd7e06c45e4c0edf96f405bae2 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d3/d52/a00023.php">Point</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#abc9cc2cd7e06c45e4c0edf96f405bae2">getPosition</a> () const </td></tr>
<tr class="separator:abc9cc2cd7e06c45e4c0edf96f405bae2 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8eddeb512a0133271555e8f1ef888dc3 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a8eddeb512a0133271555e8f1ef888dc3">getX</a> () const </td></tr>
<tr class="separator:a8eddeb512a0133271555e8f1ef888dc3 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1cf1642c874236857eff096f32f3285c inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a1cf1642c874236857eff096f32f3285c">getY</a> () const </td></tr>
<tr class="separator:a1cf1642c874236857eff096f32f3285c inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3365e9eda5d1c8426910522dcbb14d52 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a3365e9eda5d1c8426910522dcbb14d52">getZ</a> () const </td></tr>
<tr class="separator:a3365e9eda5d1c8426910522dcbb14d52 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9993ab6cac0ce33ea91485965572cba9 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../df/d86/a00012.php">ContraptionAttr</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a9993ab6cac0ce33ea91485965572cba9">getAttributes</a> () const </td></tr>
<tr class="separator:a9993ab6cac0ce33ea91485965572cba9 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf50efec2040353189fe1b46152ba8d0 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#acf50efec2040353189fe1b46152ba8d0">getW</a> () const </td></tr>
<tr class="separator:acf50efec2040353189fe1b46152ba8d0 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa468a3b0582bb0e073f2f642611c10f1 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#aa468a3b0582bb0e073f2f642611c10f1">getH</a> () const </td></tr>
<tr class="separator:aa468a3b0582bb0e073f2f642611c10f1 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08d8bb97ba4e9b6238f5a80af9800579 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a08d8bb97ba4e9b6238f5a80af9800579">getA</a> () const </td></tr>
<tr class="separator:a08d8bb97ba4e9b6238f5a80af9800579 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3ca9a1e5aff93640d295576af62b7202 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d4/d51/a00017.php">Map</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a3ca9a1e5aff93640d295576af62b7202">getMap</a> () const </td></tr>
<tr class="separator:a3ca9a1e5aff93640d295576af62b7202 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b6d4a5f2d520dfa5e58afe5b421a126 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a3b6d4a5f2d520dfa5e58afe5b421a126">getLevel</a> () const </td></tr>
<tr class="separator:a3b6d4a5f2d520dfa5e58afe5b421a126 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd10a73d032a10e48c57e7b3252c58c2 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">virtual double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#afd10a73d032a10e48c57e7b3252c58c2">getRelativeZ</a> (<a class="el" href="../../da/d45/a00011.php">Contraption</a> &amp;obj)</td></tr>
<tr class="memdesc:afd10a73d032a10e48c57e7b3252c58c2 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute a z with the obstacles.  <a href="#afd10a73d032a10e48c57e7b3252c58c2">More...</a><br /></td></tr>
<tr class="separator:afd10a73d032a10e48c57e7b3252c58c2 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3af679109317a6740c661fe5164158ff inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a3af679109317a6740c661fe5164158ff">addPosition</a> (double x, double y, double z=0)</td></tr>
<tr class="memdesc:a3af679109317a6740c661fe5164158ff inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add coordinates to the actual position.  <a href="#a3af679109317a6740c661fe5164158ff">More...</a><br /></td></tr>
<tr class="separator:a3af679109317a6740c661fe5164158ff inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab69fdcd66f63e0a038a4006d43ecb9b6 inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ab69fdcd66f63e0a038a4006d43ecb9b6">turnLeft</a> ()</td></tr>
<tr class="memdesc:ab69fdcd66f63e0a038a4006d43ecb9b6 inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Turn the <a class="el" href="../../da/d45/a00011.php" title="A contraption. ">Contraption</a> to the left.  <a href="#ab69fdcd66f63e0a038a4006d43ecb9b6">More...</a><br /></td></tr>
<tr class="separator:ab69fdcd66f63e0a038a4006d43ecb9b6 inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20f271c846ea0c8bc96c618616a260ba inherit pub_methods_a00011"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a20f271c846ea0c8bc96c618616a260ba">turnRight</a> ()</td></tr>
<tr class="memdesc:a20f271c846ea0c8bc96c618616a260ba inherit pub_methods_a00011"><td class="mdescLeft">&#160;</td><td class="mdescRight">Turn the <a class="el" href="../../da/d45/a00011.php" title="A contraption. ">Contraption</a> to the right.  <a href="#a20f271c846ea0c8bc96c618616a260ba">More...</a><br /></td></tr>
<tr class="separator:a20f271c846ea0c8bc96c618616a260ba inherit pub_methods_a00011"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A vegetal. </p>

<p>Definition at line <a class="el" href="../../d4/de8/a00061_source.php#l00017">17</a> of file <a class="el" href="../../d4/de8/a00061_source.php">Vegetal.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ac9d1bee0742cb45180637db1bed06294"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Vegetal::Vegetal </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d4/d51/a00017.php">Map</a> *&#160;</td>
          <td class="paramname"><em>map</em> = <code>nullptr</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../d3/d52/a00023.php">Point</a>&#160;</td>
          <td class="paramname"><em>pt</em> = <code>{0,&#160;0,&#160;0}</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../df/d86/a00012.php">ContraptionAttr</a>&#160;</td>
          <td class="paramname"><em>attr</em> = <code>{0,&#160;0,&#160;0}</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Constructor of the class. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">map</td><td>The map where it is </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">pt</td><td>The position in the map </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">attr</td><td>The attributes of the object(width, height, angle) </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae273444c873c7f3be7f38b6f60156a4c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual Vegetal::~Vegetal </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Virtual destructor. </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a4ea0ad75fb2add027996b1653a4751f4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="../../dc/d3c/a00028.php">Vegetal</a>* Vegetal::cut </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>percent</em> = <code>100</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Cut the plant to have twice. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">percent</td><td>The percent of cut</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return a pointer to the child plant </dd></dl>

</div>
</div>
<a class="anchor" id="ac3ac9ca3d977facf17953da4c853f37f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void Vegetal::printInfos </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>stream</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Print the infos in the instance of the class in <em>stream</em>. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">stream</td><td>The output stream</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Reimplemented from <a class="el" href="../../d2/de7/a00014.php#a20e050d3112f769d9a911e1b52f2ac77">Entity</a>.</p>

<p>Reimplemented in <a class="el" href="../../d1/d2b/a00018.php#a1467b6e6e2b41e3e3790f7e2b8e28b6d">Mushroom</a>, and <a class="el" href="../../de/d11/a00021.php#a2ee3b0d4379f9969d620b7f0bc3a277f">Plant</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d4/de8/a00061_source.php">Vegetal.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dc/d3c/a00028.php">Vegetal</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
