<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: site.php Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d6f/a00063_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">site.php</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d1/d6f/a00063.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;&lt;?php</div><div class="line"><a name="l00014"></a><span class="lineno"><a class="line" href="../../d1/d6f/a00063.php#ad208b57c36b8c1e0d09481b79b261b1c">   14</a></span>&#160;    <span class="keyword">function</span> <a class="code" href="../../d1/d6f/a00063.php#ad208b57c36b8c1e0d09481b79b261b1c">get_site_name</a>(<a class="code" href="../../d0/d33/a00027.php#a94f91e878bce0991e2cd595c5dd79b3f">$bdd</a>){</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;        require_once(<span class="stringliteral">&quot;bdd.php&quot;</span>);</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;        $datas = <a class="code" href="../../d0/d33/a00027.php#a94f91e878bce0991e2cd595c5dd79b3f">$bdd</a>-&gt;select(<span class="stringliteral">&quot;page_admin&quot;</span>, <span class="stringliteral">&quot;*&quot;</span>);</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;        $datas = <a class="code" href="../../d2/de7/a00014.php#ac25e0cea9220cf427db18de77a1cc282">typeValue_array</a>($datas);</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;        $name = <a class="code" href="../../d2/de7/a00014.php#a876add8c54fbea2f702f5365dfbe03be">get_in_array</a>(<span class="stringliteral">&quot;site_name&quot;</span>, $datas);</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <span class="keywordflow">return</span> $name;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    }</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="../../d1/d6f/a00063.php#a7d839f332f102d8050f984a05897f17c">   30</a></span>&#160;    <span class="keyword">function</span> <a class="code" href="../../d1/d6f/a00063.php#a7d839f332f102d8050f984a05897f17c">is_this_active</a>($page, $opt=<span class="stringliteral">&quot;&quot;</span>){</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;        $paths = explode(<span class="stringliteral">&quot;/&quot;</span>, $_SERVER[<span class="stringliteral">&quot;SCRIPT_FILENAME&quot;</span>]);</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;        <span class="keywordflow">for</span>($i = 0; $i &lt; sizeOf($paths); ++$i){</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;            $path = $paths[$i];</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;            <span class="keywordflow">if</span>(strpos($path, <span class="stringliteral">&quot;.&quot;</span>) !== <span class="keyword">false</span>){</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                $paths = $path;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                <span class="keywordflow">break</span>;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;            }</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;        }</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;        <span class="keywordflow">if</span>($paths !== $page){</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;            <span class="keywordflow">return</span> <span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;        }</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        <span class="keywordflow">if</span>($opt != <span class="stringliteral">&quot;&quot;</span>){</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;            <span class="keywordflow">if</span>(strpos($opt, <span class="stringliteral">&quot;&amp;&quot;</span>) !== <span class="keyword">false</span>){</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                $opts = explode(<span class="stringliteral">&quot;&amp;&quot;</span>, $opt);</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;            } <span class="keywordflow">else</span> {</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                $opts[0] = $opt;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;            }</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;            <span class="keywordflow">for</span>($i = 0; $i &lt; sizeOf($opts); ++$i){</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                $opt = $opts[$i];</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                $vals = explode(<span class="stringliteral">&quot;=&quot;</span>, $opt);</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                <span class="keywordflow">if</span>(!<a class="code" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a>($_GET[$vals[0]])){</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                    <span class="keywordflow">return</span> <span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                } <span class="keywordflow">else</span> <span class="keywordflow">if</span>($_GET[$vals[0]] !== $vals[1]) {</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                    <span class="keywordflow">return</span> <span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                }</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;            }</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;            <span class="keywordflow">return</span> <span class="stringliteral">&quot;active&quot;</span>;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        }</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        <span class="keywordflow">return</span> <span class="stringliteral">&quot;active&quot;</span>;</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;    }</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;?&gt;</div><div class="ttc" id="a00014_php_a876add8c54fbea2f702f5365dfbe03be"><div class="ttname"><a href="../../d2/de7/a00014.php#a876add8c54fbea2f702f5365dfbe03be">get_in_array</a></div><div class="ttdeci">get_in_array($index, $array)</div><div class="ttdoc">Return the given value in the array if it exists. </div><div class="ttdef"><b>Definition:</b> <a href="../../d2/de7/a00014_source.php#l00123">arrays.php:123</a></div></div>
<div class="ttc" id="a00010_php_a9e0d51979af70f1e0d06bb7bb7047898"><div class="ttname"><a href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898">isset</a></div><div class="ttdeci">function isset()</div><div class="ttdoc">Function to know if a variable exist. </div><div class="ttdef"><b>Definition:</b> <a href="../../d7/dec/a00010_source.php#l00406">_script.js:406</a></div></div>
<div class="ttc" id="a00063_php_ad208b57c36b8c1e0d09481b79b261b1c"><div class="ttname"><a href="../../d1/d6f/a00063.php#ad208b57c36b8c1e0d09481b79b261b1c">get_site_name</a></div><div class="ttdeci">get_site_name($bdd)</div><div class="ttdoc">Get the name of the website. </div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d6f/a00063_source.php#l00014">site.php:14</a></div></div>
<div class="ttc" id="a00027_php_a94f91e878bce0991e2cd595c5dd79b3f"><div class="ttname"><a href="../../d0/d33/a00027.php#a94f91e878bce0991e2cd595c5dd79b3f">$bdd</a></div><div class="ttdeci">$bdd</div><div class="ttdef"><b>Definition:</b> <a href="../../d0/d33/a00027_source.php#l00007">connexion.php:7</a></div></div>
<div class="ttc" id="a00063_php_a7d839f332f102d8050f984a05897f17c"><div class="ttname"><a href="../../d1/d6f/a00063.php#a7d839f332f102d8050f984a05897f17c">is_this_active</a></div><div class="ttdeci">is_this_active($page, $opt=&quot;&quot;)</div><div class="ttdoc">Function that verify if it&amp;#39;s the asked page. </div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d6f/a00063_source.php#l00030">site.php:30</a></div></div>
<div class="ttc" id="a00014_php_ac25e0cea9220cf427db18de77a1cc282"><div class="ttname"><a href="../../d2/de7/a00014.php#ac25e0cea9220cf427db18de77a1cc282">typeValue_array</a></div><div class="ttdeci">typeValue_array($in)</div><div class="ttdoc">Convert a type/value array in an index/value array. </div><div class="ttdef"><b>Definition:</b> <a href="../../d2/de7/a00014_source.php#l00099">arrays.php:99</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_05194b7bb14e4bdbd759acf3e4294839.php">php</a></li><li class="navelem"><a class="el" href="../../dir_272b8c85f84b9c47a49e8b7a9d6744ed.php">bases</a></li><li class="navelem"><a class="el" href="../../d1/d6f/a00063.php">site.php</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
