<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: files.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d31/a00069.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">files.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;fstream&gt;</code><br />
<code>#include &lt;string&gt;</code><br />
<code>#include &lt;vector&gt;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for files.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/db1/a00140.png" border="0" usemap="#files_8hpp" alt=""/></div>
<map name="files_8hpp" id="files_8hpp">
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d4e/a00141.png" border="0" usemap="#files_8hppdep" alt=""/></div>
<map name="files_8hppdep" id="files_8hppdep">
<area shape="rect" id="node2" href="../../da/d24/a00068.php" title="errors.hpp" alt="" coords="751,80,831,107"/>
<area shape="rect" id="node4" href="../../d1/d6f/a00063.php" title="defines.hpp" alt="" coords="353,229,443,256"/>
<area shape="rect" id="node18" href="../../d9/d2e/a00056.php" title="C++.hpp" alt="" coords="413,827,487,853"/>
<area shape="rect" id="node31" href="../../db/df8/a00076.php" title="Map.hpp" alt="" coords="769,229,841,256"/>
<area shape="rect" id="node3" href="../../d4/d6d/a00055.php" title="bdd.hpp" alt="" coords="667,155,735,181"/>
<area shape="rect" id="node30" href="../../dc/dee/a00053.php" title="Args.hpp" alt="" coords="530,155,605,181"/>
<area shape="rect" id="node5" href="../../da/d2a/a00086.php" title="QtFunctions.hpp" alt="" coords="5,453,124,480"/>
<area shape="rect" id="node16" href="../../d9/d73/a00060.php" title="Contraption.hpp" alt="" coords="341,304,455,331"/>
<area shape="rect" id="node29" href="../../df/d03/a00062.php" title="cryptage.hpp" alt="" coords="103,677,200,704"/>
<area shape="rect" id="node6" href="../../df/d13/a00085.php" title="QtDefines.hpp" alt="" coords="126,901,233,928"/>
<area shape="rect" id="node7" href="../../df/d5d/a00084.php" title="Qt.hpp" alt="" coords="361,1200,422,1227"/>
<area shape="rect" id="node12" href="../../d2/db1/a00070.php" title="Font.hpp" alt="" coords="105,976,179,1003"/>
<area shape="rect" id="node13" href="../../d0/d61/a00100.php" title="WindowButton.hpp" alt="" coords="255,976,387,1003"/>
<area shape="rect" id="node8" href="../../dc/d54/a00094.php" title="TitleLabel.hpp" alt="" coords="204,1275,307,1301"/>
<area shape="rect" id="node10" href="../../d9/da5/a00075.php" title="MainWindow.h" alt="" coords="385,1424,493,1451"/>
<area shape="rect" id="node11" href="../../d1/dc1/a00092.php" title="TableWidget.hpp" alt="" coords="331,1275,451,1301"/>
<area shape="rect" id="node9" href="../../df/d5f/a00064.php" title="Dialog.hpp" alt="" coords="348,1349,432,1376"/>
<area shape="rect" id="node14" href="../../d4/d3a/a00101.php" title="WindowTitleBar.hpp" alt="" coords="299,1051,438,1077"/>
<area shape="rect" id="node15" href="../../da/d74/a00099.php" title="Window.hpp" alt="" coords="344,1125,439,1152"/>
<area shape="rect" id="node17" href="../../d9/db3/a00066.php" title="Entities.hpp" alt="" coords="405,677,495,704"/>
<area shape="rect" id="node21" href="../../d1/d51/a00079.php" title="Object.hpp" alt="" coords="301,379,386,405"/>
<area shape="rect" id="node22" href="../../dc/ddf/a00067.php" title="Entity.hpp" alt="" coords="411,379,492,405"/>
<area shape="rect" id="node20" href="../../d8/d53/a00081.php" title="Player.hpp" alt="" coords="368,752,452,779"/>
<area shape="rect" id="node19" href="../../d0/d89/a00071.php" title="functions.hpp" alt="" coords="513,1051,613,1077"/>
<area shape="rect" id="node23" href="../../d2/d79/a00051.php" title="Animal.hpp" alt="" coords="424,528,511,555"/>
<area shape="rect" id="node25" href="../../d1/d6e/a00073.php" title="Hostile.hpp" alt="" coords="405,453,493,480"/>
<area shape="rect" id="node26" href="../../d1/d84/a00097.php" title="Vegetal.hpp" alt="" coords="562,528,653,555"/>
<area shape="rect" id="node24" href="../../d1/d84/a00052.php" title="Ant.hpp" alt="" coords="453,603,519,629"/>
<area shape="rect" id="node27" href="../../da/dec/a00080.php" title="Plant.hpp" alt="" coords="594,603,671,629"/>
<area shape="rect" id="node28" href="../../d9/da4/a00078.php" title="Mushroom.hpp" alt="" coords="696,603,804,629"/>
</map>
</div>
</div>
<p><a href="../../d4/d31/a00069_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a42e1aa02e585ad4e35d14ef5c133395a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php#a42e1aa02e585ad4e35d14ef5c133395a">fileFormat</a> (std::string &amp;line)</td></tr>
<tr class="memdesc:a42e1aa02e585ad4e35d14ef5c133395a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Format a given <em>line</em> for files.  <a href="#a42e1aa02e585ad4e35d14ef5c133395a">More...</a><br /></td></tr>
<tr class="separator:a42e1aa02e585ad4e35d14ef5c133395a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab148021dd478aa69c83029819b268737"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php#ab148021dd478aa69c83029819b268737">getFileSize</a> (const std::string &amp;path)</td></tr>
<tr class="memdesc:ab148021dd478aa69c83029819b268737"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the file size.  <a href="#ab148021dd478aa69c83029819b268737">More...</a><br /></td></tr>
<tr class="separator:ab148021dd478aa69c83029819b268737"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2917d2eb46f63f2c97b1a30de55ec3c5"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php#a2917d2eb46f63f2c97b1a30de55ec3c5">getlines</a> (std::ifstream &amp;input)</td></tr>
<tr class="memdesc:a2917d2eb46f63f2c97b1a30de55ec3c5"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get all the lines in a given file.  <a href="#a2917d2eb46f63f2c97b1a30de55ec3c5">More...</a><br /></td></tr>
<tr class="separator:a2917d2eb46f63f2c97b1a30de55ec3c5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa9034f20bf3b289424ebda507e52e427"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php#aa9034f20bf3b289424ebda507e52e427">setlines</a> (std::ofstream &amp;output, std::vector&lt; std::string &gt; lines)</td></tr>
<tr class="memdesc:aa9034f20bf3b289424ebda507e52e427"><td class="mdescLeft">&#160;</td><td class="mdescRight">Write all the lines in a given file.  <a href="#aa9034f20bf3b289424ebda507e52e427">More...</a><br /></td></tr>
<tr class="separator:aa9034f20bf3b289424ebda507e52e427"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a76c27f6a40c6f54d0c76ce2498fae8d7"><td class="memItemLeft" align="right" valign="top">std::ifstream&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php#a76c27f6a40c6f54d0c76ce2498fae8d7">reader</a></td></tr>
<tr class="memdesc:a76c27f6a40c6f54d0c76ce2498fae8d7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Define a global file reader.  <a href="#a76c27f6a40c6f54d0c76ce2498fae8d7">More...</a><br /></td></tr>
<tr class="separator:a76c27f6a40c6f54d0c76ce2498fae8d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c037aab5abffa1d77dad2a0f0295b0e"><td class="memItemLeft" align="right" valign="top">std::ofstream&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/a00069.php#a5c037aab5abffa1d77dad2a0f0295b0e">writer</a></td></tr>
<tr class="memdesc:a5c037aab5abffa1d77dad2a0f0295b0e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Define a global file writer.  <a href="#a5c037aab5abffa1d77dad2a0f0295b0e">More...</a><br /></td></tr>
<tr class="separator:a5c037aab5abffa1d77dad2a0f0295b0e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>02 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d4/d31/a00069_source.php">files.hpp</a>.</p>
</div><h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a42e1aa02e585ad4e35d14ef5c133395a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void fileFormat </td>
          <td>(</td>
          <td class="paramtype">std::string &amp;&#160;</td>
          <td class="paramname"><em>line</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Format a given <em>line</em> for files. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in,out]</td><td class="paramname">line</td><td>The line to format</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="ab148021dd478aa69c83029819b268737"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t getFileSize </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>path</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the file size. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">path</td><td>The path to the file</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the size of the file </dd></dl>

</div>
</div>
<a class="anchor" id="a2917d2eb46f63f2c97b1a30de55ec3c5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;std::string&gt; getlines </td>
          <td>(</td>
          <td class="paramtype">std::ifstream &amp;&#160;</td>
          <td class="paramname"><em>input</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get all the lines in a given file. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">input</td><td>The opened ifstream</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return a vector which contains the file's lines </dd></dl>

</div>
</div>
<a class="anchor" id="aa9034f20bf3b289424ebda507e52e427"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool setlines </td>
          <td>(</td>
          <td class="paramtype">std::ofstream &amp;&#160;</td>
          <td class="paramname"><em>output</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::vector&lt; std::string &gt;&#160;</td>
          <td class="paramname"><em>lines</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Write all the lines in a given file. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">input</td><td>The opened ofstream </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">lines</td><td>The lines to write</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd><b>true</b> or <b>false</b> </dd></dl>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="a76c27f6a40c6f54d0c76ce2498fae8d7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::ifstream reader</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Define a global file reader. </p>

</div>
</div>
<a class="anchor" id="a5c037aab5abffa1d77dad2a0f0295b0e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::ofstream writer</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Define a global file writer. </p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_9cc7dab42d10c04902c95d2c14820089.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dir_42c90fb9218922ddd8984da73ce0d59c.php">C++</a></li><li class="navelem"><a class="el" href="../../d4/d31/a00069.php">files.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
