<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Dialog.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('da/d45/a00011_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Dialog.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../da/d45/a00011.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_DIALOG</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_DIALOG</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &lt;QtWidgets&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d2/de7/a00014.php">PushButton.hpp</a>&quot;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../dd/d1b/a00015.php">TitleLabel.hpp</a>&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00020"></a><span class="lineno"><a class="line" href="../../d7/d46/a00002.php">   20</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../d7/d46/a00002.php">Dialog</a> : <span class="keyword">public</span> QDialog {</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;        <a class="code" href="../../d7/d46/a00002.php#aa0b9cd0c1778f065842c9f5d8b1d0ade">Dialog</a>(QWidget* parent = <span class="keyword">nullptr</span>, Qt::WindowFlags flags = Qt::WindowTitleHint | Qt::WindowSystemMenuHint);</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        <a class="code" href="../../d7/d46/a00002.php#a2a1fe6ef28513eed13bfcd3a4da83ccb">~Dialog</a>();</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="../../d7/d46/a00002.php#a71fa68c918f499cf0882f10e163653b7">   30</a></span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d7/d46/a00002.php#a71fa68c918f499cf0882f10e163653b7">setText</a>(std::string text){ this-&gt;text = text; }</div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="../../d7/d46/a00002.php#a4c10c671f4913a51c225eab2a3934f10">   34</a></span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d7/d46/a00002.php#a4c10c671f4913a51c225eab2a3934f10">enableCancel</a>(<span class="keywordtype">bool</span> enable){ cancelEnable = enable; }</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;    <span class="keyword">public</span> slots:</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;        <span class="keyword">virtual</span> <span class="keywordtype">int</span> <a class="code" href="../../d7/d46/a00002.php#a6505fd839711734947bfe2040a74f614">exec</a>();</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    signals:</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;        </div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        <span class="keywordtype">void</span> deletions();</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        QVBoxLayout* container;</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        std::vector&lt;QHBoxLayout*&gt; lines;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        std::vector&lt;H2TitleLabel*&gt; labels;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        QHBoxLayout* buttons;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        <a class="code" href="../../d1/d7c/a00003.php">GreenPushButton</a>* ok;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        <a class="code" href="../../d4/dee/a00008.php">RedPushButton</a>* cancel;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        <span class="keywordtype">bool</span> cancelEnable;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        std::string text;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;};</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="preprocessor">#endif //HEADER_DIALOG</span></div><div class="ttc" id="a00002_php"><div class="ttname"><a href="../../d7/d46/a00002.php">Dialog</a></div><div class="ttdoc">An implementation of QDialog for the software. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00020">Dialog.hpp:20</a></div></div>
<div class="ttc" id="a00002_php_a2a1fe6ef28513eed13bfcd3a4da83ccb"><div class="ttname"><a href="../../d7/d46/a00002.php#a2a1fe6ef28513eed13bfcd3a4da83ccb">Dialog::~Dialog</a></div><div class="ttdeci">~Dialog()</div></div>
<div class="ttc" id="a00002_php_a71fa68c918f499cf0882f10e163653b7"><div class="ttname"><a href="../../d7/d46/a00002.php#a71fa68c918f499cf0882f10e163653b7">Dialog::setText</a></div><div class="ttdeci">void setText(std::string text)</div><div class="ttdoc">Set the text of the Dialog. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00030">Dialog.hpp:30</a></div></div>
<div class="ttc" id="a00003_php"><div class="ttname"><a href="../../d1/d7c/a00003.php">GreenPushButton</a></div><div class="ttdoc">An implementation of PushButton for the software. </div><div class="ttdef"><b>Definition:</b> <a href="../../d2/de7/a00014_source.php#l00077">PushButton.hpp:77</a></div></div>
<div class="ttc" id="a00014_php"><div class="ttname"><a href="../../d2/de7/a00014.php">PushButton.hpp</a></div></div>
<div class="ttc" id="a00008_php"><div class="ttname"><a href="../../d4/dee/a00008.php">RedPushButton</a></div><div class="ttdoc">An implementation of PushButton for the software. </div><div class="ttdef"><b>Definition:</b> <a href="../../d2/de7/a00014_source.php#l00055">PushButton.hpp:55</a></div></div>
<div class="ttc" id="a00002_php_a4c10c671f4913a51c225eab2a3934f10"><div class="ttname"><a href="../../d7/d46/a00002.php#a4c10c671f4913a51c225eab2a3934f10">Dialog::enableCancel</a></div><div class="ttdeci">void enableCancel(bool enable)</div><div class="ttdoc">Set if the cancel button is shown or hidden. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00034">Dialog.hpp:34</a></div></div>
<div class="ttc" id="a00002_php_a6505fd839711734947bfe2040a74f614"><div class="ttname"><a href="../../d7/d46/a00002.php#a6505fd839711734947bfe2040a74f614">Dialog::exec</a></div><div class="ttdeci">virtual int exec()</div><div class="ttdoc">Overload of the exec slot of QDialog. </div></div>
<div class="ttc" id="a00002_php_aa0b9cd0c1778f065842c9f5d8b1d0ade"><div class="ttname"><a href="../../d7/d46/a00002.php#aa0b9cd0c1778f065842c9f5d8b1d0ade">Dialog::Dialog</a></div><div class="ttdeci">Dialog(QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowTitleHint|Qt::WindowSystemMenuHint)</div><div class="ttdoc">Create a QDialog. </div></div>
<div class="ttc" id="a00015_php"><div class="ttname"><a href="../../dd/d1b/a00015.php">TitleLabel.hpp</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../da/d45/a00011.php">Dialog.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
