<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: ajax.js File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/dd4/a00013.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">ajax.js File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../d7/dd4/a00013_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:aa048c2d0291f4b7a55ba31de642c5a9a"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dd4/a00013.php#aa048c2d0291f4b7a55ba31de642c5a9a">httpErrors</a> (errorNumber, errorText)</td></tr>
<tr class="memdesc:aa048c2d0291f4b7a55ba31de642c5a9a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initialize the error div.  <a href="#aa048c2d0291f4b7a55ba31de642c5a9a">More...</a><br /></td></tr>
<tr class="separator:aa048c2d0291f4b7a55ba31de642c5a9a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39a06d6c4a0e9dc2e5b11124e3b2537e"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dd4/a00013.php#a39a06d6c4a0e9dc2e5b11124e3b2537e">httpSuccess</a> ()</td></tr>
<tr class="memdesc:a39a06d6c4a0e9dc2e5b11124e3b2537e"><td class="mdescLeft">&#160;</td><td class="mdescRight">On success, hide the error div.  <a href="#a39a06d6c4a0e9dc2e5b11124e3b2537e">More...</a><br /></td></tr>
<tr class="separator:a39a06d6c4a0e9dc2e5b11124e3b2537e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abef425142325124458ad69a853742275"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dd4/a00013.php#abef425142325124458ad69a853742275">ajaxRequest</a> (type, request, callback, <a class="el" href="../../d5/df9/a00044.php#a20b6cd228a69593c03af5dc445393936">data</a>=null, errorCallback=function(){}, async=true)</td></tr>
<tr class="memdesc:abef425142325124458ad69a853742275"><td class="mdescLeft">&#160;</td><td class="mdescRight">The function that start an ajax request.  <a href="#abef425142325124458ad69a853742275">More...</a><br /></td></tr>
<tr class="separator:abef425142325124458ad69a853742275"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ae2475e10618961c050dcba04e8c42331"><td class="memItemLeft" align="right" valign="top">use&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dd4/a00013.php#ae2475e10618961c050dcba04e8c42331">strict</a></td></tr>
<tr class="separator:ae2475e10618961c050dcba04e8c42331"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acc4c6d9354ac67e1c3259ce578320aa6"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dd4/a00013.php#acc4c6d9354ac67e1c3259ce578320aa6">errorDiv</a> = <a class="el" href="../../d9/d73/a00060.php#aa341c64280e4f907737862137f8ee707">document.getElementById</a>(&quot;errors&quot;)</td></tr>
<tr class="separator:acc4c6d9354ac67e1c3259ce578320aa6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7c35532bc95b97064568a25321d0e16b"><td class="memItemLeft" align="right" valign="top">var&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dd4/a00013.php#a7c35532bc95b97064568a25321d0e16b">divErrorsClass</a> = &quot;container&quot;</td></tr>
<tr class="separator:a7c35532bc95b97064568a25321d0e16b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>09 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>
</div><h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="abef425142325124458ad69a853742275"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function ajaxRequest </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>type</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>request</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>callback</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>data</em> = <code>null</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>errorCallback</em> = <code>function(){}</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>async</em> = <code>true</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The function that start an ajax request. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">type</td><td>The type of the request <b>GET</b>, <b>POST</b>, <b>PUT</b>, <b>DELETE</b>, <b>AUTH</b> </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">request</td><td>The file to request for </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">callback</td><td>The function to call on success </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">data</td><td>The datas to send </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">errorCallback</td><td>The function to call on error </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">async</td><td>Set if the request has to be <b>synchronous(false)</b> or <b>asynchronous(true)</b> </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../d7/dd4/a00013_source.php#l00099">99</a> of file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/dd4/a00013_abef425142325124458ad69a853742275_cgraph.png" border="0" usemap="#d7/dd4/a00013_abef425142325124458ad69a853742275_cgraph" alt=""/></div>
<map name="d7/dd4/a00013_abef425142325124458ad69a853742275_cgraph" id="d7/dd4/a00013_abef425142325124458ad69a853742275_cgraph">
<area shape="rect" id="node2" href="../../d7/dd4/a00013.php#a39a06d6c4a0e9dc2e5b11124e3b2537e" title="On success, hide the error div. " alt="" coords="148,5,243,32"/>
<area shape="rect" id="node3" href="../../d7/dd4/a00013.php#aa048c2d0291f4b7a55ba31de642c5a9a" title="Initialize the error div. " alt="" coords="156,56,235,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aa048c2d0291f4b7a55ba31de642c5a9a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function httpErrors </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>errorNumber</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>errorText</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Initialize the error div. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">errorNumber</td><td>The number of the error </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">errorText</td><td>The text of the error</td></tr>
  </table>
  </dd>
</dl>
<p>The function is called when an error occurs in the request </p>
<p>After 2 seconds, hide the div more and more every 0.05 seconds </p>

<p>Definition at line <a class="el" href="../../d7/dd4/a00013_source.php#l00020">20</a> of file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>

</div>
</div>
<a class="anchor" id="a39a06d6c4a0e9dc2e5b11124e3b2537e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function httpSuccess </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>On success, hide the error div. </p>

<p>Definition at line <a class="el" href="../../d7/dd4/a00013_source.php#l00083">83</a> of file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="a7c35532bc95b97064568a25321d0e16b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var divErrorsClass = &quot;container&quot;</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d7/dd4/a00013_source.php#l00011">11</a> of file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>

</div>
</div>
<a class="anchor" id="acc4c6d9354ac67e1c3259ce578320aa6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">var errorDiv = <a class="el" href="../../d9/d73/a00060.php#aa341c64280e4f907737862137f8ee707">document.getElementById</a>(&quot;errors&quot;)</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d7/dd4/a00013_source.php#l00010">10</a> of file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>

</div>
</div>
<a class="anchor" id="ae2475e10618961c050dcba04e8c42331"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">use strict</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../d7/dd4/a00013_source.php#l00008">8</a> of file <a class="el" href="../../d7/dd4/a00013_source.php">ajax.js</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../dir_50bae84d6b514f2657cf039fb05a19d6.php">bases</a></li><li class="navelem"><a class="el" href="../../d7/dd4/a00013.php">ajax.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
