<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Mail Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="../../classes.php"><span>Data&#160;Structure&#160;Index</span></a></li>
      <li><a href="../../functions.php"><span>Data&#160;Fields</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('de/d21/a00006.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">Mail Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A class to send mails.  
 <a href="../../de/d21/a00006.php#details">More...</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ac186b4fd84ab68c80ce2b0626c2ef6a5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#ac186b4fd84ab68c80ce2b0626c2ef6a5">__construct</a> ($to=&quot;&quot;, $subject=&quot;&quot;, $msg=&quot;&quot;)</td></tr>
<tr class="memdesc:ac186b4fd84ab68c80ce2b0626c2ef6a5"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor.  <a href="#ac186b4fd84ab68c80ce2b0626c2ef6a5">More...</a><br /></td></tr>
<tr class="separator:ac186b4fd84ab68c80ce2b0626c2ef6a5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa5439eb97bf29defd763f78351e6b249"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#aa5439eb97bf29defd763f78351e6b249">setReceiver</a> ($to)</td></tr>
<tr class="memdesc:aa5439eb97bf29defd763f78351e6b249"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the mail receiver.  <a href="#aa5439eb97bf29defd763f78351e6b249">More...</a><br /></td></tr>
<tr class="separator:aa5439eb97bf29defd763f78351e6b249"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a971f2abb85a2e0fc85954322896d6b80"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#a971f2abb85a2e0fc85954322896d6b80">setSubject</a> ($subject)</td></tr>
<tr class="memdesc:a971f2abb85a2e0fc85954322896d6b80"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the mail subject.  <a href="#a971f2abb85a2e0fc85954322896d6b80">More...</a><br /></td></tr>
<tr class="separator:a971f2abb85a2e0fc85954322896d6b80"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afde57541bb65476d5101974f2c5d0d23"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#afde57541bb65476d5101974f2c5d0d23">setMsg</a> ($msg)</td></tr>
<tr class="memdesc:afde57541bb65476d5101974f2c5d0d23"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the mail message.  <a href="#afde57541bb65476d5101974f2c5d0d23">More...</a><br /></td></tr>
<tr class="separator:afde57541bb65476d5101974f2c5d0d23"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac1f59fefc1b33175a734321e13b42253"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#ac1f59fefc1b33175a734321e13b42253">setHeaders</a> ($headers)</td></tr>
<tr class="memdesc:ac1f59fefc1b33175a734321e13b42253"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the mail headers.  <a href="#ac1f59fefc1b33175a734321e13b42253">More...</a><br /></td></tr>
<tr class="separator:ac1f59fefc1b33175a734321e13b42253"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd24d8440fec45b8c891417e2f182a72"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#afd24d8440fec45b8c891417e2f182a72">setSender</a> ($from)</td></tr>
<tr class="memdesc:afd24d8440fec45b8c891417e2f182a72"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the mail sender.  <a href="#afd24d8440fec45b8c891417e2f182a72">More...</a><br /></td></tr>
<tr class="separator:afd24d8440fec45b8c891417e2f182a72"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acfdf4a9744da87ad49295819dfa963db"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#acfdf4a9744da87ad49295819dfa963db">setCC</a> ($cc)</td></tr>
<tr class="memdesc:acfdf4a9744da87ad49295819dfa963db"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set a mail CC.  <a href="#acfdf4a9744da87ad49295819dfa963db">More...</a><br /></td></tr>
<tr class="separator:acfdf4a9744da87ad49295819dfa963db"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac97950a3477eaa50d543e4563793a68f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#ac97950a3477eaa50d543e4563793a68f">setBCC</a> ($bcc)</td></tr>
<tr class="memdesc:ac97950a3477eaa50d543e4563793a68f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set a mail BCC.  <a href="#ac97950a3477eaa50d543e4563793a68f">More...</a><br /></td></tr>
<tr class="separator:ac97950a3477eaa50d543e4563793a68f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a27b347822dc0556d25d6e28eface1160"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#a27b347822dc0556d25d6e28eface1160">addHeader</a> ($header)</td></tr>
<tr class="memdesc:a27b347822dc0556d25d6e28eface1160"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a mail header.  <a href="#a27b347822dc0556d25d6e28eface1160">More...</a><br /></td></tr>
<tr class="separator:a27b347822dc0556d25d6e28eface1160"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c783809a74b71213ef7137d292fd628"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#a1c783809a74b71213ef7137d292fd628">setParameters</a> ($parameters)</td></tr>
<tr class="memdesc:a1c783809a74b71213ef7137d292fd628"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set mail parameters.  <a href="#a1c783809a74b71213ef7137d292fd628">More...</a><br /></td></tr>
<tr class="separator:a1c783809a74b71213ef7137d292fd628"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac9dc9971c6e68a9668867f255e473113"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#ac9dc9971c6e68a9668867f255e473113">addParameter</a> ($parameter)</td></tr>
<tr class="memdesc:ac9dc9971c6e68a9668867f255e473113"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add mail parameters.  <a href="#ac9dc9971c6e68a9668867f255e473113">More...</a><br /></td></tr>
<tr class="separator:ac9dc9971c6e68a9668867f255e473113"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a2397793e2759f67049d39aedbb1ab6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d21/a00006.php#a8a2397793e2759f67049d39aedbb1ab6">send</a> ($to=&quot;&quot;, $subject=&quot;&quot;, $msg=&quot;&quot;)</td></tr>
<tr class="memdesc:a8a2397793e2759f67049d39aedbb1ab6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Send the mail.  <a href="#a8a2397793e2759f67049d39aedbb1ab6">More...</a><br /></td></tr>
<tr class="separator:a8a2397793e2759f67049d39aedbb1ab6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A class to send mails. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00013">13</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ac186b4fd84ab68c80ce2b0626c2ef6a5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">__construct </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$to</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$subject</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$msg</em> = <code>&quot;&quot;</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00022">22</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a27b347822dc0556d25d6e28eface1160"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">addHeader </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$header</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add a mail header. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00069">69</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="ac9dc9971c6e68a9668867f255e473113"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">addParameter </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$parameter</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add mail parameters. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00079">79</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="a8a2397793e2759f67049d39aedbb1ab6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">send </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$to</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$subject</em> = <code>&quot;&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$msg</em> = <code>&quot;&quot;</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Send the mail. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00084">84</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="ac97950a3477eaa50d543e4563793a68f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setBCC </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$bcc</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set a mail BCC. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00064">64</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d21/a00006_ac97950a3477eaa50d543e4563793a68f_cgraph.png" border="0" usemap="#de/d21/a00006_ac97950a3477eaa50d543e4563793a68f_cgraph" alt=""/></div>
<map name="de/d21/a00006_ac97950a3477eaa50d543e4563793a68f_cgraph" id="de/d21/a00006_ac97950a3477eaa50d543e4563793a68f_cgraph">
<area shape="rect" id="node2" href="../../de/d21/a00006.php#a27b347822dc0556d25d6e28eface1160" title="Add a mail header. " alt="" coords="123,5,208,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="acfdf4a9744da87ad49295819dfa963db"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setCC </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$cc</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set a mail CC. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00059">59</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d21/a00006_acfdf4a9744da87ad49295819dfa963db_cgraph.png" border="0" usemap="#de/d21/a00006_acfdf4a9744da87ad49295819dfa963db_cgraph" alt=""/></div>
<map name="de/d21/a00006_acfdf4a9744da87ad49295819dfa963db_cgraph" id="de/d21/a00006_acfdf4a9744da87ad49295819dfa963db_cgraph">
<area shape="rect" id="node2" href="../../de/d21/a00006.php#a27b347822dc0556d25d6e28eface1160" title="Add a mail header. " alt="" coords="113,5,199,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ac1f59fefc1b33175a734321e13b42253"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setHeaders </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$headers</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the mail headers. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00048">48</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="afde57541bb65476d5101974f2c5d0d23"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setMsg </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$msg</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the mail message. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00043">43</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="a1c783809a74b71213ef7137d292fd628"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setParameters </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$parameters</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set mail parameters. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00074">74</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="aa5439eb97bf29defd763f78351e6b249"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setReceiver </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$to</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the mail receiver. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00033">33</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<a class="anchor" id="afd24d8440fec45b8c891417e2f182a72"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setSender </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$from</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the mail sender. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00053">53</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d21/a00006_afd24d8440fec45b8c891417e2f182a72_cgraph.png" border="0" usemap="#de/d21/a00006_afd24d8440fec45b8c891417e2f182a72_cgraph" alt=""/></div>
<map name="de/d21/a00006_afd24d8440fec45b8c891417e2f182a72_cgraph" id="de/d21/a00006_afd24d8440fec45b8c891417e2f182a72_cgraph">
<area shape="rect" id="node2" href="../../de/d21/a00006.php#a27b347822dc0556d25d6e28eface1160" title="Add a mail header. " alt="" coords="135,5,220,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a971f2abb85a2e0fc85954322896d6b80"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">setSubject </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$subject</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the mail subject. </p>

<p>Definition at line <a class="el" href="../../dc/de2/a00024_source.php#l00038">38</a> of file <a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../dc/de2/a00024_source.php">class-Mail.php</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../de/d21/a00006.php">Mail</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
