<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>ProjetFinalCPP: MainWindow Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">ProjetFinalCPP
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/d46/a00002.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../de/d5e/a00007.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">MainWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The window that is shown.  
 <a href="../../d7/d46/a00002.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d0/d0b/a00004_source.php">MainWindow.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for MainWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/dee/a00008.png" border="0" usemap="#MainWindow_inherit__map" alt="Inheritance graph"/></div>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for MainWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/da0/a00009.png" border="0" usemap="#MainWindow_coll__map" alt="Collaboration graph"/></div>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a430b81b3bb84b8561b4e63fe76e28c39"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a430b81b3bb84b8561b4e63fe76e28c39">connections</a> ()</td></tr>
<tr class="memdesc:a430b81b3bb84b8561b4e63fe76e28c39"><td class="mdescLeft">&#160;</td><td class="mdescRight">Try and verify the connection.  <a href="#a430b81b3bb84b8561b4e63fe76e28c39">More...</a><br /></td></tr>
<tr class="separator:a430b81b3bb84b8561b4e63fe76e28c39"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a08a133d21fea8948f84acc105ab5fc33"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a08a133d21fea8948f84acc105ab5fc33">MainWindow</a> (QWidget *parent=NULL)</td></tr>
<tr class="memdesc:a08a133d21fea8948f84acc105ab5fc33"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create the window to connect to the database.  <a href="#a08a133d21fea8948f84acc105ab5fc33">More...</a><br /></td></tr>
<tr class="separator:a08a133d21fea8948f84acc105ab5fc33"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae98d00a93bc118200eeef9f9bba1dba7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#ae98d00a93bc118200eeef9f9bba1dba7">~MainWindow</a> ()</td></tr>
<tr class="separator:ae98d00a93bc118200eeef9f9bba1dba7"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a78ab18fed76eb54bda4508dc9be4b64b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a78ab18fed76eb54bda4508dc9be4b64b">createConnectWidgets</a> ()</td></tr>
<tr class="memdesc:a78ab18fed76eb54bda4508dc9be4b64b"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create all the connection's widgets.  <a href="#a78ab18fed76eb54bda4508dc9be4b64b">More...</a><br /></td></tr>
<tr class="separator:a78ab18fed76eb54bda4508dc9be4b64b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5cfeb89a38b9225a3b3964e6d688ba60"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a5cfeb89a38b9225a3b3964e6d688ba60">initConnectWidgets</a> ()</td></tr>
<tr class="memdesc:a5cfeb89a38b9225a3b3964e6d688ba60"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initialize all the connection's widgets.  <a href="#a5cfeb89a38b9225a3b3964e6d688ba60">More...</a><br /></td></tr>
<tr class="separator:a5cfeb89a38b9225a3b3964e6d688ba60"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9da75111decb2a68a08c06dec6796d8a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a9da75111decb2a68a08c06dec6796d8a">setContentConnectWidgets</a> ()</td></tr>
<tr class="memdesc:a9da75111decb2a68a08c06dec6796d8a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Do all the add for these widgets.  <a href="#a9da75111decb2a68a08c06dec6796d8a">More...</a><br /></td></tr>
<tr class="separator:a9da75111decb2a68a08c06dec6796d8a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aad6ca3020e583fffe727258905c15629"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#aad6ca3020e583fffe727258905c15629">useConnectWidgets</a> ()</td></tr>
<tr class="memdesc:aad6ca3020e583fffe727258905c15629"><td class="mdescLeft">&#160;</td><td class="mdescRight">Show only the connection's widgets.  <a href="#aad6ca3020e583fffe727258905c15629">More...</a><br /></td></tr>
<tr class="separator:aad6ca3020e583fffe727258905c15629"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a70aa06cbac136bf2ce8bee98b9bebd27"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a70aa06cbac136bf2ce8bee98b9bebd27">verifyConnection</a> ()</td></tr>
<tr class="memdesc:a70aa06cbac136bf2ce8bee98b9bebd27"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create the page after a connection.  <a href="#a70aa06cbac136bf2ce8bee98b9bebd27">More...</a><br /></td></tr>
<tr class="separator:a70aa06cbac136bf2ce8bee98b9bebd27"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a63c8b347f526518517340a5f912c5575"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a63c8b347f526518517340a5f912c5575">createConnectDialog</a> ()</td></tr>
<tr class="memdesc:a63c8b347f526518517340a5f912c5575"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create the connection QDialog message on error.  <a href="#a63c8b347f526518517340a5f912c5575">More...</a><br /></td></tr>
<tr class="separator:a63c8b347f526518517340a5f912c5575"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a79d1533b5cbbc9040c5d78c9dfb29d38"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a79d1533b5cbbc9040c5d78c9dfb29d38">initConnectDialog</a> ()</td></tr>
<tr class="memdesc:a79d1533b5cbbc9040c5d78c9dfb29d38"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initialize all the widgets of the QDialog.  <a href="#a79d1533b5cbbc9040c5d78c9dfb29d38">More...</a><br /></td></tr>
<tr class="separator:a79d1533b5cbbc9040c5d78c9dfb29d38"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3338456a91f9f32f2f30b9e702df5ea4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a3338456a91f9f32f2f30b9e702df5ea4">setContentConnectDialog</a> ()</td></tr>
<tr class="memdesc:a3338456a91f9f32f2f30b9e702df5ea4"><td class="mdescLeft">&#160;</td><td class="mdescRight">Do all the add for these widgets.  <a href="#a3338456a91f9f32f2f30b9e702df5ea4">More...</a><br /></td></tr>
<tr class="separator:a3338456a91f9f32f2f30b9e702df5ea4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a79a619ed1dd1d17b8b3624d919fefe4e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a79a619ed1dd1d17b8b3624d919fefe4e">useConnectDialog</a> ()</td></tr>
<tr class="memdesc:a79a619ed1dd1d17b8b3624d919fefe4e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Show the QDialog.  <a href="#a79a619ed1dd1d17b8b3624d919fefe4e">More...</a><br /></td></tr>
<tr class="separator:a79a619ed1dd1d17b8b3624d919fefe4e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2364ae069aba1f220ac4cd2fecaf4d6c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a2364ae069aba1f220ac4cd2fecaf4d6c">createAdminWidgets</a> ()</td></tr>
<tr class="separator:a2364ae069aba1f220ac4cd2fecaf4d6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a601d88aa6fbda83575e07d7dc9e19a15"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#a601d88aa6fbda83575e07d7dc9e19a15">initAdminWidgets</a> ()</td></tr>
<tr class="separator:a601d88aa6fbda83575e07d7dc9e19a15"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af0aca5335b2f075de2cdbf0fe9c33645"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#af0aca5335b2f075de2cdbf0fe9c33645">setContentAdminWidgets</a> ()</td></tr>
<tr class="memdesc:af0aca5335b2f075de2cdbf0fe9c33645"><td class="mdescLeft">&#160;</td><td class="mdescRight">Do all the add for these widgets.  <a href="#af0aca5335b2f075de2cdbf0fe9c33645">More...</a><br /></td></tr>
<tr class="separator:af0aca5335b2f075de2cdbf0fe9c33645"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5cd67fa4d5e5aace91a9c98cc8feec7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#ac5cd67fa4d5e5aace91a9c98cc8feec7">useAdminWidgets</a> ()</td></tr>
<tr class="separator:ac5cd67fa4d5e5aace91a9c98cc8feec7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aceb5bf98f0d68be0d164584da0605624"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d46/a00002.php#aceb5bf98f0d68be0d164584da0605624">adminWidgets</a> ()</td></tr>
<tr class="separator:aceb5bf98f0d68be0d164584da0605624"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The window that is shown. </p>

<p>Definition at line <a class="el" href="../../d0/d0b/a00004_source.php#l00017">17</a> of file <a class="el" href="../../d0/d0b/a00004_source.php">MainWindow.h</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a08a133d21fea8948f84acc105ab5fc33"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">MainWindow::MainWindow </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>NULL</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Create the window to connect to the database. </p>

</div>
</div>
<a class="anchor" id="ae98d00a93bc118200eeef9f9bba1dba7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">MainWindow::~MainWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="aceb5bf98f0d68be0d164584da0605624"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::adminWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a430b81b3bb84b8561b4e63fe76e28c39"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::connections </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Try and verify the connection. </p>

</div>
</div>
<a class="anchor" id="a2364ae069aba1f220ac4cd2fecaf4d6c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::createAdminWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a63c8b347f526518517340a5f912c5575"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::createConnectDialog </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Create the connection QDialog message on error. </p>

</div>
</div>
<a class="anchor" id="a78ab18fed76eb54bda4508dc9be4b64b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::createConnectWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Create all the connection's widgets. </p>

</div>
</div>
<a class="anchor" id="a601d88aa6fbda83575e07d7dc9e19a15"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::initAdminWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a79d1533b5cbbc9040c5d78c9dfb29d38"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::initConnectDialog </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Initialize all the widgets of the QDialog. </p>

</div>
</div>
<a class="anchor" id="a5cfeb89a38b9225a3b3964e6d688ba60"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::initConnectWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Initialize all the connection's widgets. </p>

</div>
</div>
<a class="anchor" id="af0aca5335b2f075de2cdbf0fe9c33645"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::setContentAdminWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Do all the add for these widgets. </p>

</div>
</div>
<a class="anchor" id="a3338456a91f9f32f2f30b9e702df5ea4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::setContentConnectDialog </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Do all the add for these widgets. </p>

</div>
</div>
<a class="anchor" id="a9da75111decb2a68a08c06dec6796d8a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::setContentConnectWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Do all the add for these widgets. </p>

</div>
</div>
<a class="anchor" id="ac5cd67fa4d5e5aace91a9c98cc8feec7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::useAdminWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a79a619ed1dd1d17b8b3624d919fefe4e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::useConnectDialog </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Show the QDialog. </p>

</div>
</div>
<a class="anchor" id="aad6ca3020e583fffe727258905c15629"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::useConnectWidgets </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Show only the connection's widgets. </p>

</div>
</div>
<a class="anchor" id="a70aa06cbac136bf2ce8bee98b9bebd27"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::verifyConnection </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Create the page after a connection. </p>
<dl class="todo"><dt><b><a class="el" href="../../d8/d84/a00001.php#_todo000001">Todo:</a></b></dt><dd></dd></dl>
<p>Verify the connection to the database </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d0/d0b/a00004_source.php">MainWindow.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d7/d46/a00002.php">MainWindow</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
