<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Window.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d44/a00098_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Window.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d1/d44/a00098.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="preprocessor">#ifndef HEADER_WINDOW</span></div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="preprocessor">#define HEADER_WINDOW</span></div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#ifdef Q_WS_X11</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #include &lt;QX11Info&gt;</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#endif</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">#include &lt;QtWidgets&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d0/d61/a00100.php">WindowTitleBar.hpp</a>&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d4/d6d/a00055.php">C++/C++.hpp</a>&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="../../d3/dea/a00046.php">   22</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../d3/dea/a00046.php">Window</a> : <span class="keyword">public</span> <a class="code" href="../../d6/d97/a00045.php">Widget</a>{</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;        <a class="code" href="../../d3/dea/a00046.php#a8c86e48ef3180201cc97cb928abd66ca">Window</a>(QWidget* parent = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;        <a class="code" href="../../d3/dea/a00046.php#a245d821e6016fa1f6970ccbbedd635f6">~Window</a>();</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a008e887882941bcd08b6439dc001ea51">setWindowTitle</a>(<span class="keyword">const</span> QString &amp;title);</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a8c65cb42e811de87be8743af6b9d21ed">setCentralWidget</a>(QWidget* widget);</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a2983759dc6be4f8da44eff6069b2d3c8">setSize</a>(<span class="keywordtype">int</span> w, <span class="keywordtype">int</span> h);</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno"><a class="line" href="../../d3/dea/a00046.php#a4cec8e761a776437c9886d6982c22a54">   58</a></span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(<span class="keywordtype">int</span> m){ this-&gt;<a class="code" href="../../d3/dea/a00046.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(m, m, m, m); }</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(<span class="keywordtype">int</span> t, <span class="keywordtype">int</span> r, <span class="keywordtype">int</span> b, <span class="keywordtype">int</span> l);</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a677a2c1046a84743e709515f5618b1e8">showEvent</a>(QShowEvent* event);</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a1b653d42eb4810a8c0be48dc65d98b3a">paintEvent</a>(QPaintEvent* event);</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a3d72edbec3fed3709ea3d374973c70b4">resizeEvent</a>(QResizeEvent* event);</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a1ce5696d3fac4e90e6c9fbd0477d0f9d">drawBackground</a>(QPixmap* cache);</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#acbed45e30a51c6855e5e6ea88197b161">drawDefaultBackground</a>(QPixmap* cache);</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a3f710c0adafe15f27766f70a1c5b4dee">setBackground</a>(QPixmap* cache = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">enableResize</a>(<span class="keywordtype">bool</span> enable);</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a8ad2a767e19299b153f9bc0457f13114">showTitlebar</a>(<span class="keywordtype">bool</span> enable);</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;    signals:</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a56ced9e90dad8415ce9ba9ccdb8f50c7">WindowTitleChanged</a>(QString title);</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a9b8e592bf73f07ec549125eb6367395c">WindowResizeChanged</a>(<span class="keywordtype">bool</span> state);</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d3/dea/a00046.php#a1f3319d59097b7c9e5bde545e6867c1b">TitleBarShowState</a>(<span class="keywordtype">bool</span> state);</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        <span class="keywordtype">void</span> CenterOnScreen();</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        <span class="keywordtype">void</span> setTransparency();</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;        <span class="keywordtype">void</span> useTransparency();</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00153"></a><span class="lineno"><a class="line" href="../../d3/dea/a00046.php#a065e43061d8abb3717302dc1acf139c3">  153</a></span>&#160;        QPixmap* <a class="code" href="../../d3/dea/a00046.php#a065e43061d8abb3717302dc1acf139c3">m_Cache</a>;</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;        QGridLayout* m_MainLayout;</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        <a class="code" href="../../d4/dca/a00048.php">WindowTitleBar</a>* m_TitleBar;</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;        QSizeGrip* m_SizeGrip;</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        QVBoxLayout* m_CenterLayout;</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;        QWidget* m_CenterWidget;</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;        <span class="keywordtype">bool</span> transparent;</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;        <span class="keywordtype">bool</span> enabledResize;</div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;};</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;<span class="preprocessor">#endif //HEADER_WINDOW</span></div><div class="ttc" id="a00055_php"><div class="ttname"><a href="../../d4/d6d/a00055.php">C++.hpp</a></div></div>
<div class="ttc" id="a00046_php_a1f3319d59097b7c9e5bde545e6867c1b"><div class="ttname"><a href="../../d3/dea/a00046.php#a1f3319d59097b7c9e5bde545e6867c1b">Window::TitleBarShowState</a></div><div class="ttdeci">void TitleBarShowState(bool state)</div><div class="ttdoc">Call when the state of the titlebar is changed show/hide. </div></div>
<div class="ttc" id="a00046_php_a1b653d42eb4810a8c0be48dc65d98b3a"><div class="ttname"><a href="../../d3/dea/a00046.php#a1b653d42eb4810a8c0be48dc65d98b3a">Window::paintEvent</a></div><div class="ttdeci">void paintEvent(QPaintEvent *event)</div><div class="ttdoc">The paint event of the window. </div></div>
<div class="ttc" id="a00046_php_a4cec8e761a776437c9886d6982c22a54"><div class="ttname"><a href="../../d3/dea/a00046.php#a4cec8e761a776437c9886d6982c22a54">Window::setMargin</a></div><div class="ttdeci">void setMargin(int m)</div><div class="ttdoc">Set the window margin. </div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d44/a00098_source.php#l00058">Window.hpp:58</a></div></div>
<div class="ttc" id="a00046_php_a8c65cb42e811de87be8743af6b9d21ed"><div class="ttname"><a href="../../d3/dea/a00046.php#a8c65cb42e811de87be8743af6b9d21ed">Window::setCentralWidget</a></div><div class="ttdeci">void setCentralWidget(QWidget *widget)</div><div class="ttdoc">Set the central widget. </div></div>
<div class="ttc" id="a00045_php"><div class="ttname"><a href="../../d6/d97/a00045.php">Widget</a></div><div class="ttdoc">Create a personnalized Widget. </div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d84/a00097_source.php#l00017">Widget.hpp:17</a></div></div>
<div class="ttc" id="a00046_php_a3f710c0adafe15f27766f70a1c5b4dee"><div class="ttname"><a href="../../d3/dea/a00046.php#a3f710c0adafe15f27766f70a1c5b4dee">Window::setBackground</a></div><div class="ttdeci">void setBackground(QPixmap *cache=nullptr)</div><div class="ttdoc">Set the background window. </div></div>
<div class="ttc" id="a00046_php_a245d821e6016fa1f6970ccbbedd635f6"><div class="ttname"><a href="../../d3/dea/a00046.php#a245d821e6016fa1f6970ccbbedd635f6">Window::~Window</a></div><div class="ttdeci">~Window()</div><div class="ttdoc">The destructor. </div></div>
<div class="ttc" id="a00046_php_a3d72edbec3fed3709ea3d374973c70b4"><div class="ttname"><a href="../../d3/dea/a00046.php#a3d72edbec3fed3709ea3d374973c70b4">Window::resizeEvent</a></div><div class="ttdeci">void resizeEvent(QResizeEvent *event)</div><div class="ttdoc">The resize event of the window. </div></div>
<div class="ttc" id="a00048_php"><div class="ttname"><a href="../../d4/dca/a00048.php">WindowTitleBar</a></div><div class="ttdoc">The titlebar of the Window class. </div><div class="ttdef"><b>Definition:</b> <a href="../../d0/d61/a00100_source.php#l00018">WindowTitleBar.hpp:18</a></div></div>
<div class="ttc" id="a00046_php_a56ced9e90dad8415ce9ba9ccdb8f50c7"><div class="ttname"><a href="../../d3/dea/a00046.php#a56ced9e90dad8415ce9ba9ccdb8f50c7">Window::WindowTitleChanged</a></div><div class="ttdeci">void WindowTitleChanged(QString title)</div><div class="ttdoc">Call when the window title is changed. </div></div>
<div class="ttc" id="a00046_php_a8c86e48ef3180201cc97cb928abd66ca"><div class="ttname"><a href="../../d3/dea/a00046.php#a8c86e48ef3180201cc97cb928abd66ca">Window::Window</a></div><div class="ttdeci">Window(QWidget *parent=nullptr)</div><div class="ttdoc">The constructor. </div></div>
<div class="ttc" id="a00100_php"><div class="ttname"><a href="../../d0/d61/a00100.php">WindowTitleBar.hpp</a></div></div>
<div class="ttc" id="a00046_php_a85b13ae29ce6f9aa9ffb7408b0ddd4b7"><div class="ttname"><a href="../../d3/dea/a00046.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">Window::enableResize</a></div><div class="ttdeci">void enableResize(bool enable)</div><div class="ttdoc">Set if yes or no the window can be resized. </div></div>
<div class="ttc" id="a00046_php"><div class="ttname"><a href="../../d3/dea/a00046.php">Window</a></div><div class="ttdoc">A custom window. </div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d44/a00098_source.php#l00022">Window.hpp:22</a></div></div>
<div class="ttc" id="a00046_php_a677a2c1046a84743e709515f5618b1e8"><div class="ttname"><a href="../../d3/dea/a00046.php#a677a2c1046a84743e709515f5618b1e8">Window::showEvent</a></div><div class="ttdeci">void showEvent(QShowEvent *event)</div><div class="ttdoc">The show event of the window. </div></div>
<div class="ttc" id="a00046_php_a9b8e592bf73f07ec549125eb6367395c"><div class="ttname"><a href="../../d3/dea/a00046.php#a9b8e592bf73f07ec549125eb6367395c">Window::WindowResizeChanged</a></div><div class="ttdeci">void WindowResizeChanged(bool state)</div><div class="ttdoc">Call when the window is resized. </div></div>
<div class="ttc" id="a00046_php_a008e887882941bcd08b6439dc001ea51"><div class="ttname"><a href="../../d3/dea/a00046.php#a008e887882941bcd08b6439dc001ea51">Window::setWindowTitle</a></div><div class="ttdeci">void setWindowTitle(const QString &amp;title)</div><div class="ttdoc">Set the window title. </div></div>
<div class="ttc" id="a00046_php_acbed45e30a51c6855e5e6ea88197b161"><div class="ttname"><a href="../../d3/dea/a00046.php#acbed45e30a51c6855e5e6ea88197b161">Window::drawDefaultBackground</a></div><div class="ttdeci">void drawDefaultBackground(QPixmap *cache)</div><div class="ttdoc">Draw the default background of the window. </div></div>
<div class="ttc" id="a00046_php_a065e43061d8abb3717302dc1acf139c3"><div class="ttname"><a href="../../d3/dea/a00046.php#a065e43061d8abb3717302dc1acf139c3">Window::m_Cache</a></div><div class="ttdeci">QPixmap * m_Cache</div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d44/a00098_source.php#l00153">Window.hpp:153</a></div></div>
<div class="ttc" id="a00046_php_a2983759dc6be4f8da44eff6069b2d3c8"><div class="ttname"><a href="../../d3/dea/a00046.php#a2983759dc6be4f8da44eff6069b2d3c8">Window::setSize</a></div><div class="ttdeci">void setSize(int w, int h)</div><div class="ttdoc">Set the window size. </div></div>
<div class="ttc" id="a00046_php_a8ad2a767e19299b153f9bc0457f13114"><div class="ttname"><a href="../../d3/dea/a00046.php#a8ad2a767e19299b153f9bc0457f13114">Window::showTitlebar</a></div><div class="ttdeci">void showTitlebar(bool enable)</div><div class="ttdoc">Set the titlebar visibility. </div></div>
<div class="ttc" id="a00046_php_a1ce5696d3fac4e90e6c9fbd0477d0f9d"><div class="ttname"><a href="../../d3/dea/a00046.php#a1ce5696d3fac4e90e6c9fbd0477d0f9d">Window::drawBackground</a></div><div class="ttdeci">virtual void drawBackground(QPixmap *cache)</div><div class="ttdoc">Draw the background of the window. </div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../d1/d44/a00098.php">Window.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
