<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: fonctions.php File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d86/a00012.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">fonctions.php File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../df/d86/a00012_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:afcef1294902ca07027096e59292f89c1"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#afcef1294902ca07027096e59292f89c1">sendJsonData</a> ($message, $h)</td></tr>
<tr class="memdesc:afcef1294902ca07027096e59292f89c1"><td class="mdescLeft">&#160;</td><td class="mdescRight">Send datas in JSON format.  <a href="#afcef1294902ca07027096e59292f89c1">More...</a><br /></td></tr>
<tr class="separator:afcef1294902ca07027096e59292f89c1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4c00ed23cbac293dc1b0c38b4ca6e3b6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a4c00ed23cbac293dc1b0c38b4ca6e3b6">authentification</a> ($bdd)</td></tr>
<tr class="memdesc:a4c00ed23cbac293dc1b0c38b4ca6e3b6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Authenticates the user.  <a href="#a4c00ed23cbac293dc1b0c38b4ca6e3b6">More...</a><br /></td></tr>
<tr class="separator:a4c00ed23cbac293dc1b0c38b4ca6e3b6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a392292a494893cd5382dd1c9273ee9c8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a392292a494893cd5382dd1c9273ee9c8">verifieToken</a> ($bdd)</td></tr>
<tr class="memdesc:a392292a494893cd5382dd1c9273ee9c8"><td class="mdescLeft">&#160;</td><td class="mdescRight">check the user's token  <a href="#a392292a494893cd5382dd1c9273ee9c8">More...</a><br /></td></tr>
<tr class="separator:a392292a494893cd5382dd1c9273ee9c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fd7bd7ced184a62771c0a16217068cc"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a9fd7bd7ced184a62771c0a16217068cc">creationPartie</a> ($bdd)</td></tr>
<tr class="memdesc:a9fd7bd7ced184a62771c0a16217068cc"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a Game.  <a href="#a9fd7bd7ced184a62771c0a16217068cc">More...</a><br /></td></tr>
<tr class="separator:a9fd7bd7ced184a62771c0a16217068cc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5fde6a754bc0e9c7872a974abde85a8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#af5fde6a754bc0e9c7872a974abde85a8">score</a> ($bdd)</td></tr>
<tr class="memdesc:af5fde6a754bc0e9c7872a974abde85a8"><td class="mdescLeft">&#160;</td><td class="mdescRight">score calculation  <a href="#af5fde6a754bc0e9c7872a974abde85a8">More...</a><br /></td></tr>
<tr class="separator:af5fde6a754bc0e9c7872a974abde85a8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a082db1f75a28750b9c46d1060cd14d2f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a082db1f75a28750b9c46d1060cd14d2f">verifReponse</a> ($bdd)</td></tr>
<tr class="memdesc:a082db1f75a28750b9c46d1060cd14d2f"><td class="mdescLeft">&#160;</td><td class="mdescRight">check if he has answered correctly  <a href="#a082db1f75a28750b9c46d1060cd14d2f">More...</a><br /></td></tr>
<tr class="separator:a082db1f75a28750b9c46d1060cd14d2f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a4c00ed23cbac293dc1b0c38b4ca6e3b6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">authentification </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$bdd</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Authenticates the user. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">bdd</td><td>The database</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>token</dd></dl>
<p>Authenticates the user if he enters the correct password and username. Moreover,he create and send token or send HTTP error if he enters the bad password and username. </p>

<p>Definition at line <a class="el" href="../../df/d86/a00012_source.php#l00033">33</a> of file <a class="el" href="../../df/d86/a00012_source.php">fonctions.php</a>.</p>

</div>
</div>
<a class="anchor" id="a9fd7bd7ced184a62771c0a16217068cc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">creationPartie </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$bdd</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Create a Game. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">bdd</td><td>The database </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">tabQuestions</td><td>The questions table</td></tr>
  </table>
  </dd>
</dl>
<p>he gets back in a table "tabquestion", via the database the questions randomly with the themes he chose before on the site. Secondly, he recover the date and create a game in the database. Thirdly, he recover from the difficulty chose before on the site, the number of questions in the array "tabquestion" then he send id of the questions and id of the game in the table "contient". </p>

<p>Definition at line <a class="el" href="../../df/d86/a00012_source.php#l00086">86</a> of file <a class="el" href="../../df/d86/a00012_source.php">fonctions.php</a>.</p>

</div>
</div>
<a class="anchor" id="af5fde6a754bc0e9c7872a974abde85a8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">score </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$bdd</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>score calculation </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">bdd</td><td>The database</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>data The array that contains the time and the score of the game</dd></dl>
<p>Thanks to the information of the time and the answers, it put 0 point by bad answer or 10 points if it answered well before 5 sec then he lose 0,5 point every second until 1 point.if he made a better score or plays for the first time the score is save with the time of the game. then the time of the game and the score are send </p>

<p>Definition at line <a class="el" href="../../df/d86/a00012_source.php#l00117">117</a> of file <a class="el" href="../../df/d86/a00012_source.php">fonctions.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_af5fde6a754bc0e9c7872a974abde85a8_cgraph.png" border="0" usemap="#df/d86/a00012_af5fde6a754bc0e9c7872a974abde85a8_cgraph" alt=""/></div>
<map name="df/d86/a00012_af5fde6a754bc0e9c7872a974abde85a8_cgraph" id="df/d86/a00012_af5fde6a754bc0e9c7872a974abde85a8_cgraph">
<area shape="rect" id="node2" href="../../df/d86/a00012.php#afcef1294902ca07027096e59292f89c1" title="Send datas in JSON format. " alt="" coords="108,5,215,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="afcef1294902ca07027096e59292f89c1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">sendJsonData </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$message</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$h</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Send datas in JSON format. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">message</td><td>The data to send </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">h</td><td>The header to add <pre class="fragment">\return  Return the data encoded to send.</pre> </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../df/d86/a00012_source.php#l00016">16</a> of file <a class="el" href="../../df/d86/a00012_source.php">fonctions.php</a>.</p>

</div>
</div>
<a class="anchor" id="a392292a494893cd5382dd1c9273ee9c8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">verifieToken </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$bdd</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>check the user's token </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">bdd</td><td>The database</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>false or true if the token is good</dd></dl>
<p>Check if the user's token is good thanks to the database with the cookie "pseudo". He remove cookie "token" and "pseudo" if the cookie "token" and the database "token" does not match and send false otherwise he send true. </p>

<p>Definition at line <a class="el" href="../../df/d86/a00012_source.php#l00059">59</a> of file <a class="el" href="../../df/d86/a00012_source.php">fonctions.php</a>.</p>

</div>
</div>
<a class="anchor" id="a082db1f75a28750b9c46d1060cd14d2f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">verifReponse </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$bdd</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>check if he has answered correctly </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">bdd</td><td>The database</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>array data (true or false)</dd></dl>
<p>He recover the value that the user has chosen and check if had answered correctly or not. </p>

<p>Definition at line <a class="el" href="../../df/d86/a00012_source.php#l00172">172</a> of file <a class="el" href="../../df/d86/a00012_source.php">fonctions.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_a082db1f75a28750b9c46d1060cd14d2f_cgraph.png" border="0" usemap="#df/d86/a00012_a082db1f75a28750b9c46d1060cd14d2f_cgraph" alt=""/></div>
<map name="df/d86/a00012_a082db1f75a28750b9c46d1060cd14d2f_cgraph" id="df/d86/a00012_a082db1f75a28750b9c46d1060cd14d2f_cgraph">
<area shape="rect" id="node2" href="../../df/d86/a00012.php#afcef1294902ca07027096e59292f89c1" title="Send datas in JSON format. " alt="" coords="152,5,259,32"/>
</map>
</div>
</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_05194b7bb14e4bdbd759acf3e4294839.php">php</a></li><li class="navelem"><a class="el" href="../../df/d86/a00012.php">fonctions.php</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
