<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: C++.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/d2e/a00056_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">C++.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d9/d2e/a00056.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;<span class="preprocessor">#ifndef HEADER_CPP</span></div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;<span class="preprocessor">#define HEADER_CPP</span></div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d9/db3/a00066.php">Entities.hpp</a>&quot;</span></div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d8/d53/a00081.php">Player.hpp</a>&quot;</span></div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../df/d03/a00062.php">cryptage.hpp</a>&quot;</span></div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d3/d8b/a00059.php">console.hpp</a>&quot;</span></div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d1/d6f/a00063.php">defines.hpp</a>&quot;</span></div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../da/d24/a00068.php">errors.hpp</a>&quot;</span></div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d4/de8/a00061.php">convert.hpp</a>&quot;</span></div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d7/df7/a00058.php">collides.hpp</a>&quot;</span></div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../da/d82/a00091.php">string.hpp</a>&quot;</span></div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d1/dea/a00054.php">array.hpp</a>&quot;</span></div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d4/d7d/a00093.php">time.hpp</a>&quot;</span></div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d1/d09/a00077.php">maths.hpp</a>&quot;</span></div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d4/d31/a00069.php">files.hpp</a>&quot;</span></div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../db/dab/a00089.php">sorting.hpp</a>&quot;</span></div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d9/d77/a00095.php">tree.hpp</a>&quot;</span></div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../db/df8/a00076.php">Map.hpp</a>&quot;</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../db/db6/a00074.php">macro.hpp</a>&quot;</span></div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d9/df8/a00096.php">types.hpp</a>&quot;</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;<span class="preprocessor">#endif //HEADER_CPP</span></div><div class="ttc" id="a00076_php"><div class="ttname"><a href="../../db/df8/a00076.php">Map.hpp</a></div></div>
<div class="ttc" id="a00095_php"><div class="ttname"><a href="../../d9/d77/a00095.php">tree.hpp</a></div></div>
<div class="ttc" id="a00089_php"><div class="ttname"><a href="../../db/dab/a00089.php">sorting.hpp</a></div></div>
<div class="ttc" id="a00061_php"><div class="ttname"><a href="../../d4/de8/a00061.php">convert.hpp</a></div></div>
<div class="ttc" id="a00074_php"><div class="ttname"><a href="../../db/db6/a00074.php">macro.hpp</a></div></div>
<div class="ttc" id="a00093_php"><div class="ttname"><a href="../../d4/d7d/a00093.php">time.hpp</a></div></div>
<div class="ttc" id="a00068_php"><div class="ttname"><a href="../../da/d24/a00068.php">errors.hpp</a></div></div>
<div class="ttc" id="a00066_php"><div class="ttname"><a href="../../d9/db3/a00066.php">Entities.hpp</a></div></div>
<div class="ttc" id="a00058_php"><div class="ttname"><a href="../../d7/df7/a00058.php">collides.hpp</a></div></div>
<div class="ttc" id="a00077_php"><div class="ttname"><a href="../../d1/d09/a00077.php">maths.hpp</a></div></div>
<div class="ttc" id="a00091_php"><div class="ttname"><a href="../../da/d82/a00091.php">string.hpp</a></div></div>
<div class="ttc" id="a00069_php"><div class="ttname"><a href="../../d4/d31/a00069.php">files.hpp</a></div></div>
<div class="ttc" id="a00054_php"><div class="ttname"><a href="../../d1/dea/a00054.php">array.hpp</a></div></div>
<div class="ttc" id="a00096_php"><div class="ttname"><a href="../../d9/df8/a00096.php">types.hpp</a></div></div>
<div class="ttc" id="a00062_php"><div class="ttname"><a href="../../df/d03/a00062.php">cryptage.hpp</a></div></div>
<div class="ttc" id="a00081_php"><div class="ttname"><a href="../../d8/d53/a00081.php">Player.hpp</a></div></div>
<div class="ttc" id="a00059_php"><div class="ttname"><a href="../../d3/d8b/a00059.php">console.hpp</a></div></div>
<div class="ttc" id="a00063_php"><div class="ttname"><a href="../../d1/d6f/a00063.php">defines.hpp</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_9cc7dab42d10c04902c95d2c14820089.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dir_42c90fb9218922ddd8984da73ce0d59c.php">C++</a></li><li class="navelem"><a class="el" href="../../d9/d2e/a00056.php">C++.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
