<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: C++.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/d2e/a00056.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">C++.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d9/db3/a00066_source.php">Entities.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d8/d53/a00081_source.php">Player.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../df/d03/a00062_source.php">cryptage.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d3/d8b/a00059_source.php">console.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/d6f/a00063_source.php">defines.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../da/d24/a00068_source.php">errors.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/de8/a00061_source.php">convert.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d7/df7/a00058_source.php">collides.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../da/d82/a00091_source.php">string.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/dea/a00054_source.php">array.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d7d/a00093_source.php">time.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/d09/a00077_source.php">maths.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d31/a00069_source.php">files.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../db/dab/a00089_source.php">sorting.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d9/d77/a00095_source.php">tree.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../db/df8/a00076_source.php">Map.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../db/db6/a00074_source.php">macro.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d9/df8/a00096_source.php">types.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for C++.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d8/d17/a00114.png" border="0" usemap="#C_09_09_8hpp" alt=""/></div>
<map name="C_09_09_8hpp" id="C_09_09_8hpp">
<area shape="rect" id="node2" href="../../d9/db3/a00066.php" title="Entities.hpp" alt="" coords="1377,155,1468,181"/>
<area shape="rect" id="node4" href="../../d1/d6f/a00063.php" title="defines.hpp" alt="" coords="641,528,730,555"/>
<area shape="rect" id="node14" href="../../d9/df8/a00096.php" title="types.hpp" alt="" coords="1365,827,1443,853"/>
<area shape="rect" id="node16" href="../../da/d24/a00068.php" title="errors.hpp" alt="" coords="1027,677,1107,704"/>
<area shape="rect" id="node17" href="../../d3/d8b/a00059.php" title="console.hpp" alt="" coords="1134,752,1226,779"/>
<area shape="rect" id="node18" href="../../d4/de8/a00061.php" title="convert.hpp" alt="" coords="529,827,620,853"/>
<area shape="rect" id="node23" href="../../d4/d31/a00069.php" title="files.hpp" alt="" coords="1250,752,1321,779"/>
<area shape="rect" id="node26" href="../../d4/d7d/a00093.php" title="time.hpp" alt="" coords="57,752,129,779"/>
<area shape="rect" id="node30" href="../../da/d82/a00091.php" title="string.hpp" alt="" coords="570,677,649,704"/>
<area shape="rect" id="node32" href="../../db/db6/a00074.php" title="macro.hpp" alt="" coords="1027,752,1109,779"/>
<area shape="rect" id="node33" href="../../d1/dea/a00054.php" title="array.hpp" alt="" coords="850,752,926,779"/>
<area shape="rect" id="node36" href="../../d1/d09/a00077.php" title="maths.hpp" alt="" coords="1893,603,1976,629"/>
<area shape="rect" id="node38" href="../../d7/df7/a00058.php" title="collides.hpp" alt="" coords="1872,528,1963,555"/>
<area shape="rect" id="node39" href="../../db/df8/a00076.php" title="Map.hpp" alt="" coords="1267,603,1339,629"/>
<area shape="rect" id="node47" href="../../d8/d53/a00081.php" title="Player.hpp" alt="" coords="1259,80,1343,107"/>
<area shape="rect" id="node48" href="../../df/d03/a00062.php" title="cryptage.hpp" alt="" coords="755,379,853,405"/>
<area shape="rect" id="node49" href="../../db/dab/a00089.php" title="sorting.hpp" alt="" coords="1519,827,1606,853"/>
<area shape="rect" id="node50" href="../../d9/d77/a00095.php" title="tree.hpp" alt="" coords="2037,155,2107,181"/>
<area shape="rect" id="node3" href="../../d9/d73/a00060.php" title="Contraption.hpp" alt="" coords="1559,453,1673,480"/>
<area shape="rect" id="node40" href="../../d1/d51/a00079.php" title="Object.hpp" alt="" coords="1712,304,1797,331"/>
<area shape="rect" id="node41" href="../../dc/ddf/a00067.php" title="Entity.hpp" alt="" coords="1417,379,1498,405"/>
<area shape="rect" id="node42" href="../../d2/d79/a00051.php" title="Animal.hpp" alt="" coords="1354,304,1441,331"/>
<area shape="rect" id="node43" href="../../d1/d84/a00052.php" title="Ant.hpp" alt="" coords="1293,229,1360,256"/>
<area shape="rect" id="node44" href="../../d1/d84/a00097.php" title="Vegetal.hpp" alt="" coords="1472,304,1563,331"/>
<area shape="rect" id="node45" href="../../da/dec/a00080.php" title="Plant.hpp" alt="" coords="1485,229,1563,256"/>
<area shape="rect" id="node46" href="../../d9/da4/a00078.php" title="Mushroom.hpp" alt="" coords="1587,229,1695,256"/>
<area shape="rect" id="node11" href="../../d4/d6d/a00055.php" title="bdd.hpp" alt="" coords="971,603,1039,629"/>
<area shape="rect" id="node29" href="../../d4/d63/a00082.php" title="pointers.hpp" alt="" coords="1435,677,1528,704"/>
<area shape="rect" id="node34" href="../../d1/d1e/a00087.php" title="RNG.hpp" alt="" coords="207,752,284,779"/>
<area shape="rect" id="node35" href="../../dc/dee/a00053.php" title="Args.hpp" alt="" coords="821,603,896,629"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/da3/a00115.png" border="0" usemap="#C_09_09_8hppdep" alt=""/></div>
<map name="C_09_09_8hppdep" id="C_09_09_8hppdep">
<area shape="rect" id="node2" href="../../df/d13/a00085.php" title="QtDefines.hpp" alt="" coords="5,80,112,107"/>
<area shape="rect" id="node9" href="../../d0/d61/a00100.php" title="WindowButton.hpp" alt="" coords="119,155,251,181"/>
<area shape="rect" id="node10" href="../../d4/d3a/a00101.php" title="WindowTitleBar.hpp" alt="" coords="164,229,303,256"/>
<area shape="rect" id="node11" href="../../da/d74/a00099.php" title="Window.hpp" alt="" coords="186,304,281,331"/>
<area shape="rect" id="node12" href="../../d0/d89/a00071.php" title="functions.hpp" alt="" coords="378,229,478,256"/>
<area shape="rect" id="node3" href="../../df/d5d/a00084.php" title="Qt.hpp" alt="" coords="203,379,264,405"/>
<area shape="rect" id="node8" href="../../d2/db1/a00070.php" title="Font.hpp" alt="" coords="22,155,95,181"/>
<area shape="rect" id="node4" href="../../dc/d54/a00094.php" title="TitleLabel.hpp" alt="" coords="93,453,195,480"/>
<area shape="rect" id="node6" href="../../d9/da5/a00075.php" title="MainWindow.h" alt="" coords="154,603,262,629"/>
<area shape="rect" id="node7" href="../../d1/dc1/a00092.php" title="TableWidget.hpp" alt="" coords="271,453,391,480"/>
<area shape="rect" id="node5" href="../../df/d5f/a00064.php" title="Dialog.hpp" alt="" coords="61,528,145,555"/>
</map>
</div>
</div>
<p><a href="../../d9/d2e/a00056_source.php">Go to the source code of this file.</a></p>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>07 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d9/d2e/a00056_source.php">C++.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_9cc7dab42d10c04902c95d2c14820089.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dir_42c90fb9218922ddd8984da73ce0d59c.php">C++</a></li><li class="navelem"><a class="el" href="../../d9/d2e/a00056.php">C++.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
