<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Member List</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/d5b/a00026.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">MainWindow Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d6/d5b/a00026.php">MainWindow</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a4c5997d915dc5101e208682364723048">addEntry</a>(std::string table, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a9b236786067bb4d825a3c6717bf96b47">addingWidgets</a>(std::string table, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#afd48a422f88143ea6c66b0c71c55eb08">adminWidgets</a>(std::string table=&quot;&quot;)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#acfdbadec2420e7862c53e511332992cc">changeActive</a>(int state, std::string table, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a430b81b3bb84b8561b4e63fe76e28c39">connections</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a74ed49cc57a01562288f4be1e665f450">createAddingWidgets</a>(std::string table, std::map&lt; std::string, std::string &gt; col, size_t index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a2364ae069aba1f220ac4cd2fecaf4d6c">createAdminWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a78ab18fed76eb54bda4508dc9be4b64b">createConnectWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a9eb2d8d3bff2599bef550d68a4d11925">createValues</a>(std::string table, std::vector&lt; std::string &gt; &amp;values)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#abf97603f986be8d9d79252512949fb30">createWidgetsLabel</a>(std::map&lt; std::string, std::string &gt; col, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a400129c80a43e87a9777a06f919060f7">createWidgetsLabels</a>(std::string table, std::map&lt; std::string, std::string &gt; col, size_t index, std::vector&lt; std::string &gt; &amp;out)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#aae5abc1edc939a854d3da3bec4e95c9a">deleteAll</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#ac44a72386cf26dcc86f108aed760ddf0">deleteEntry</a>(std::string table, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#abc9f5971cf1748fae12a5acf641ecd1d">drawBackground</a>(QPixmap *cache)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#acbed45e30a51c6855e5e6ea88197b161">drawDefaultBackground</a>(QPixmap *cache)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">enableResize</a>(bool enable)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a6db4ef4db3e407746616115fce25c199">fillWidgets</a>(std::string table, std::map&lt; std::string, std::string &gt; col, size_t index, std::string lineId)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#ae9685223f3a3fecce767e877bbc344ca">getCheckedChoices</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a5cfeb89a38b9225a3b3964e6d688ba60">initConnectWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a065e43061d8abb3717302dc1acf139c3">m_Cache</a></td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a996c5a2b6f77944776856f08ec30858d">MainWindow</a>(QWidget *parent=nullptr)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a1b653d42eb4810a8c0be48dc65d98b3a">paintEvent</a>(QPaintEvent *event)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#ab09110d257b762db4f2be34235d8465f">putAccents</a>(std::string &amp;text)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a542a7527ced73b2c9bc14f8dc9661a66">quit</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a3d72edbec3fed3709ea3d374973c70b4">resizeEvent</a>(QResizeEvent *event)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a3f710c0adafe15f27766f70a1c5b4dee">setBackground</a>(QPixmap *cache=nullptr)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a8c65cb42e811de87be8743af6b9d21ed">setCentralWidget</a>(QWidget *widget)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#af0aca5335b2f075de2cdbf0fe9c33645">setContentAdminWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a9da75111decb2a68a08c06dec6796d8a">setContentConnectWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(int m)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#aad09788fdd6171092b43f31a91a384a2">setMargin</a>(int t, int r, int b, int l)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a2983759dc6be4f8da44eff6069b2d3c8">setSize</a>(int w, int h)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a008e887882941bcd08b6439dc001ea51">setWindowTitle</a>(const QString &amp;title)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a677a2c1046a84743e709515f5618b1e8">showEvent</a>(QShowEvent *event)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a8ad2a767e19299b153f9bc0457f13114">showTitlebar</a>(bool enable)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a1f3319d59097b7c9e5bde545e6867c1b">TitleBarShowState</a>(bool state)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a4cd7e847432365bae79f88a3acf278c7">toAdmin</a>(std::string table=&quot;&quot;, std::string index=&quot;&quot;)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a675227b9f43a0a590d2446b074053943">updateEntry</a>(std::string table, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a9e7ab1ecbd6fbece432bb5cd2c7f35f7">updEntry</a>(std::string table, std::string index)</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#ac5cd67fa4d5e5aace91a9c98cc8feec7">useAdminWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#aad6ca3020e583fffe727258905c15629">useConnectWidgets</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#a70aa06cbac136bf2ce8bee98b9bebd27">verifyConnection</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/dea/a00046.php#ace1aa23652eb4425355a81760b39fd37">Widget</a>(QWidget *parent=nullptr)</td><td class="entry"><a class="el" href="../../d3/dea/a00046.php">Widget</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a8c86e48ef3180201cc97cb928abd66ca">Window</a>(QWidget *parent=nullptr)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a9b8e592bf73f07ec549125eb6367395c">WindowResizeChanged</a>(bool state)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a56ced9e90dad8415ce9ba9ccdb8f50c7">WindowTitleChanged</a>(QString title)</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d5b/a00026.php#ae98d00a93bc118200eeef9f9bba1dba7">~MainWindow</a>()</td><td class="entry"><a class="el" href="../../d6/d5b/a00026.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/dea/a00046.php#a714cf798aadb4d615f6f60a355382c02">~Widget</a>()</td><td class="entry"><a class="el" href="../../d3/dea/a00046.php">Widget</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d2d/a00047.php#a245d821e6016fa1f6970ccbbedd635f6">~Window</a>()</td><td class="entry"><a class="el" href="../../d6/d2d/a00047.php">Window</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
