<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: tchat.php Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/df7/a00058_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">tchat.php</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d7/df7/a00058.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;&lt;?php</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;    require_once(<span class="stringliteral">&quot;getter.php&quot;</span>);</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;    require_once(<span class="stringliteral">&quot;bdd.php&quot;</span>);</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno"><a class="line" href="../../d7/df7/a00058.php#a94f91e878bce0991e2cd595c5dd79b3f">   14</a></span>&#160;    <a class="code" href="../../d7/df7/a00058.php#a94f91e878bce0991e2cd595c5dd79b3f">$bdd</a> = <span class="keyword">new</span> <a class="code" href="../../d1/d7c/a00003.php">Bdd</a>(<span class="stringliteral">&quot;mysql&quot;</span>, <span class="stringliteral">&quot;127.0.0.1:3306&quot;</span>, <span class="stringliteral">&quot;chatbottest&quot;</span>, <span class="stringliteral">&quot;mathias&quot;</span>, <span class="stringliteral">&quot;chipie&quot;</span>);</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno"><a class="line" href="../../d7/df7/a00058.php#a49a8a4009b02e49717caa88b128affc5">   16</a></span>&#160;    <a class="code" href="../../d7/df7/a00058.php#a49a8a4009b02e49717caa88b128affc5">$res</a> = <a class="code" href="../../d4/d8c/a00035.php#a443ea3a863c29aed90f572de52c0b04d">nextRes</a>();</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keywordflow">if</span>(<a class="code" href="../../d7/df7/a00058.php#a49a8a4009b02e49717caa88b128affc5">$res</a> == <span class="stringliteral">&quot;start&quot;</span>){</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;        echo <span class="stringliteral">&quot;Bonjour, je suis ici pour vous conseiller. Quelle est votre question ?&quot;</span>;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    } <span class="keywordflow">else</span> <span class="keywordflow">if</span>(<a class="code" href="../../d7/df7/a00058.php#a49a8a4009b02e49717caa88b128affc5">$res</a> == <span class="stringliteral">&quot;talk&quot;</span>){</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        $text = $_POST[<span class="stringliteral">&quot;text&quot;</span>];</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        $reps = <a class="code" href="../../d7/df7/a00058.php#a94f91e878bce0991e2cd595c5dd79b3f">$bdd</a>-&gt;select(<span class="stringliteral">&quot;keywords&quot;</span>, <span class="stringliteral">&quot;*&quot;</span>);</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        $percent = 0;</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        $prec = -1;</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        $answer = <span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;        $out = <span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;        $id = 0;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        $idC = 0;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;        <span class="keywordflow">foreach</span>($reps as $key =&gt; $rep){</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;            $keywords = explode(<span class="stringliteral">&quot;|&quot;</span>, $rep[<span class="stringliteral">&quot;keywords&quot;</span>]);</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;            $i = 0;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;            <span class="keywordflow">foreach</span>($keywords as $keyword){</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                $i += mb_substr_count(strtolower($text), strtolower($keyword));</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;            }</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;            $percent = $i / sizeOf($keywords);</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;            <span class="keywordflow">if</span>($precent &gt;= 1){</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                <span class="keywordflow">if</span>($answer == <span class="stringliteral">&quot;&quot;</span>){</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    $answer .= $rep[<span class="stringliteral">&quot;answers&quot;</span>];</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                } <span class="keywordflow">else</span> {</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    $answer .= <span class="stringliteral">&quot; &quot;</span> . $rep[<span class="stringliteral">&quot;answers&quot;</span>];</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                }</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;            }</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;            <span class="keywordflow">if</span>($prec &lt; $percent){</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                $prec = $percent;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;                $out = $rep[<span class="stringliteral">&quot;answers&quot;</span>];</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                $idC = $id;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;            }</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;            $id++;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        }</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;        $percent = $prec;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;        <span class="keywordflow">if</span>($percent &lt; 0.5 &amp;&amp; $answer == <span class="stringliteral">&quot;&quot;</span>){</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;            echo <span class="stringliteral">&quot;Je n&#39;ai pas compris votre question. Pourriez-vous la reformuler ?&quot;</span>;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        } <span class="keywordflow">else</span> {</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;            echo $answer . <span class="stringliteral">&quot; &quot;</span> . $out;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        }</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;        <span class="comment">//echo &quot;Votre question est : \&quot;&quot; . $text . &quot;\&quot; et $rep&quot;;</span></div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;    }</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;?&gt;</div><div class="ttc" id="a00003_php"><div class="ttname"><a href="../../d1/d7c/a00003.php">Bdd</a></div><div class="ttdoc">A class to connect to a database. </div><div class="ttdef"><b>Definition:</b> <a href="../../d7/d7a/a00016_source.php#l00017">bdd.php:17</a></div></div>
<div class="ttc" id="a00058_php_a94f91e878bce0991e2cd595c5dd79b3f"><div class="ttname"><a href="../../d7/df7/a00058.php#a94f91e878bce0991e2cd595c5dd79b3f">$bdd</a></div><div class="ttdeci">$bdd</div><div class="ttdef"><b>Definition:</b> <a href="../../d7/df7/a00058_source.php#l00014">tchat.php:14</a></div></div>
<div class="ttc" id="a00058_php_a49a8a4009b02e49717caa88b128affc5"><div class="ttname"><a href="../../d7/df7/a00058.php#a49a8a4009b02e49717caa88b128affc5">$res</a></div><div class="ttdeci">$res</div><div class="ttdef"><b>Definition:</b> <a href="../../d7/df7/a00058_source.php#l00016">tchat.php:16</a></div></div>
<div class="ttc" id="a00035_php_a443ea3a863c29aed90f572de52c0b04d"><div class="ttname"><a href="../../d4/d8c/a00035.php#a443ea3a863c29aed90f572de52c0b04d">nextRes</a></div><div class="ttdeci">nextRes()</div><div class="ttdoc">Return the next ressource in the array or false. </div><div class="ttdef"><b>Definition:</b> <a href="../../d4/d8c/a00035_source.php#l00038">getter.php:38</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_05194b7bb14e4bdbd759acf3e4294839.php">php</a></li><li class="navelem"><a class="el" href="../../dir_272b8c85f84b9c47a49e8b7a9d6744ed.php">bases</a></li><li class="navelem"><a class="el" href="../../d7/df7/a00058.php">tchat.php</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
