<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Entities.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/db3/a00066.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Entities.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d9/d73/a00060_source.php">Contraption.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/d51/a00079_source.php">Object.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../dc/ddf/a00067_source.php">Entity.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d2/d79/a00051_source.php">Animal.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/d84/a00052_source.php">Ant.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/d84/a00097_source.php">Vegetal.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../da/dec/a00080_source.php">Plant.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d9/da4/a00078_source.php">Mushroom.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Entities.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d76/a00134.png" border="0" usemap="#Entities_8hpp" alt=""/></div>
<map name="Entities_8hpp" id="Entities_8hpp">
<area shape="rect" id="node2" href="../../d9/d73/a00060.php" title="Contraption.hpp" alt="" coords="1293,379,1408,405"/>
<area shape="rect" id="node43" href="../../d1/d51/a00079.php" title="Object.hpp" alt="" coords="1308,229,1393,256"/>
<area shape="rect" id="node44" href="../../dc/ddf/a00067.php" title="Entity.hpp" alt="" coords="1441,304,1522,331"/>
<area shape="rect" id="node45" href="../../d2/d79/a00051.php" title="Animal.hpp" alt="" coords="1494,155,1581,181"/>
<area shape="rect" id="node47" href="../../d1/d84/a00052.php" title="Ant.hpp" alt="" coords="1519,80,1585,107"/>
<area shape="rect" id="node48" href="../../d1/d84/a00097.php" title="Vegetal.hpp" alt="" coords="1616,155,1707,181"/>
<area shape="rect" id="node49" href="../../da/dec/a00080.php" title="Plant.hpp" alt="" coords="1609,80,1687,107"/>
<area shape="rect" id="node50" href="../../d9/da4/a00078.php" title="Mushroom.hpp" alt="" coords="1711,80,1819,107"/>
<area shape="rect" id="node3" href="../../d1/d6f/a00063.php" title="defines.hpp" alt="" coords="1395,453,1485,480"/>
<area shape="rect" id="node18" href="../../d9/df8/a00096.php" title="types.hpp" alt="" coords="675,752,754,779"/>
<area shape="rect" id="node41" href="../../d7/df7/a00058.php" title="collides.hpp" alt="" coords="1740,453,1831,480"/>
<area shape="rect" id="node42" href="../../db/df8/a00076.php" title="Map.hpp" alt="" coords="1129,528,1201,555"/>
<area shape="rect" id="node10" href="../../d4/d6d/a00055.php" title="bdd.hpp" alt="" coords="753,528,821,555"/>
<area shape="rect" id="node23" href="../../d4/de8/a00061.php" title="convert.hpp" alt="" coords="1753,752,1844,779"/>
<area shape="rect" id="node28" href="../../d4/d31/a00069.php" title="files.hpp" alt="" coords="1210,677,1281,704"/>
<area shape="rect" id="node30" href="../../d4/d7d/a00093.php" title="time.hpp" alt="" coords="960,677,1032,704"/>
<area shape="rect" id="node31" href="../../d4/d63/a00082.php" title="pointers.hpp" alt="" coords="987,603,1080,629"/>
<area shape="rect" id="node32" href="../../da/d82/a00091.php" title="string.hpp" alt="" coords="1619,677,1698,704"/>
<area shape="rect" id="node36" href="../../d1/d1e/a00087.php" title="RNG.hpp" alt="" coords="1919,752,1996,779"/>
<area shape="rect" id="node38" href="../../dc/dee/a00053.php" title="Args.hpp" alt="" coords="1276,528,1351,555"/>
<area shape="rect" id="node40" href="../../d1/d09/a00077.php" title="maths.hpp" alt="" coords="1937,528,2020,555"/>
<area shape="rect" id="node21" href="../../da/d24/a00068.php" title="errors.hpp" alt="" coords="1205,603,1285,629"/>
<area shape="rect" id="node35" href="../../d1/dea/a00054.php" title="array.hpp" alt="" coords="1213,752,1289,779"/>
<area shape="rect" id="node22" href="../../d3/d8b/a00059.php" title="console.hpp" alt="" coords="1317,677,1409,704"/>
<area shape="rect" id="node34" href="../../db/db6/a00074.php" title="macro.hpp" alt="" coords="1495,752,1577,779"/>
<area shape="rect" id="node46" href="../../d1/d6e/a00073.php" title="Hostile.hpp" alt="" coords="1519,229,1607,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d5b/a00135.png" border="0" usemap="#Entities_8hppdep" alt=""/></div>
<map name="Entities_8hppdep" id="Entities_8hppdep">
<area shape="rect" id="node2" href="../../d9/d2e/a00056.php" title="C++.hpp" alt="" coords="253,155,326,181"/>
<area shape="rect" id="node14" href="../../d8/d53/a00081.php" title="Player.hpp" alt="" coords="287,80,371,107"/>
<area shape="rect" id="node3" href="../../df/d13/a00085.php" title="QtDefines.hpp" alt="" coords="5,229,112,256"/>
<area shape="rect" id="node10" href="../../d0/d61/a00100.php" title="WindowButton.hpp" alt="" coords="119,304,251,331"/>
<area shape="rect" id="node11" href="../../d4/d3a/a00101.php" title="WindowTitleBar.hpp" alt="" coords="164,379,303,405"/>
<area shape="rect" id="node12" href="../../da/d74/a00099.php" title="Window.hpp" alt="" coords="186,453,281,480"/>
<area shape="rect" id="node13" href="../../d0/d89/a00071.php" title="functions.hpp" alt="" coords="378,379,478,405"/>
<area shape="rect" id="node4" href="../../df/d5d/a00084.php" title="Qt.hpp" alt="" coords="203,528,264,555"/>
<area shape="rect" id="node9" href="../../d2/db1/a00070.php" title="Font.hpp" alt="" coords="22,304,95,331"/>
<area shape="rect" id="node5" href="../../dc/d54/a00094.php" title="TitleLabel.hpp" alt="" coords="93,603,195,629"/>
<area shape="rect" id="node7" href="../../d9/da5/a00075.php" title="MainWindow.h" alt="" coords="154,752,262,779"/>
<area shape="rect" id="node8" href="../../d1/dc1/a00092.php" title="TableWidget.hpp" alt="" coords="271,603,391,629"/>
<area shape="rect" id="node6" href="../../df/d5f/a00064.php" title="Dialog.hpp" alt="" coords="61,677,145,704"/>
</map>
</div>
</div>
<p><a href="../../d9/db3/a00066_source.php">Go to the source code of this file.</a></p>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>29 mai 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d9/db3/a00066_source.php">Entities.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_9cc7dab42d10c04902c95d2c14820089.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dir_42c90fb9218922ddd8984da73ce0d59c.php">C++</a></li><li class="navelem"><a class="el" href="../../d9/db3/a00066.php">Entities.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
