<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: fonctions.js File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('da/d45/a00011.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">fonctions.js File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../da/d45/a00011_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a1426a760631d33602005a8bb59e49c7a"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a1426a760631d33602005a8bb59e49c7a">recupérationAvatar</a> ()</td></tr>
<tr class="memdesc:a1426a760631d33602005a8bb59e49c7a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Displays the avatar chosen by the user on his computer.  <a href="#a1426a760631d33602005a8bb59e49c7a">More...</a><br /></td></tr>
<tr class="separator:a1426a760631d33602005a8bb59e49c7a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0db9c30b86d2f4aa120daa6247990007"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a0db9c30b86d2f4aa120daa6247990007">verifPseudo</a> ()</td></tr>
<tr class="memdesc:a0db9c30b86d2f4aa120daa6247990007"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the value of the nickname is correct.  <a href="#a0db9c30b86d2f4aa120daa6247990007">More...</a><br /></td></tr>
<tr class="separator:a0db9c30b86d2f4aa120daa6247990007"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5e7778e2c5dd64ac673d79add217c6cf"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a5e7778e2c5dd64ac673d79add217c6cf">verifMotDePasse</a> ()</td></tr>
<tr class="memdesc:a5e7778e2c5dd64ac673d79add217c6cf"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the value of the password is correct.  <a href="#a5e7778e2c5dd64ac673d79add217c6cf">More...</a><br /></td></tr>
<tr class="separator:a5e7778e2c5dd64ac673d79add217c6cf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad853bfd925b71db5ce9624d60548b1b7"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ad853bfd925b71db5ce9624d60548b1b7">verifMotDePasse2</a> ()</td></tr>
<tr class="memdesc:ad853bfd925b71db5ce9624d60548b1b7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the value of the nickname is correct.  <a href="#ad853bfd925b71db5ce9624d60548b1b7">More...</a><br /></td></tr>
<tr class="separator:ad853bfd925b71db5ce9624d60548b1b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4a822815e57b31479eb6d364e3003fa2"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a4a822815e57b31479eb6d364e3003fa2">verifMail</a> ()</td></tr>
<tr class="memdesc:a4a822815e57b31479eb6d364e3003fa2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the value of the email is correct.  <a href="#a4a822815e57b31479eb6d364e3003fa2">More...</a><br /></td></tr>
<tr class="separator:a4a822815e57b31479eb6d364e3003fa2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a47d34320afdb9ab37a4214a0c33d4791"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a47d34320afdb9ab37a4214a0c33d4791">mdpActuelVerif</a> ()</td></tr>
<tr class="memdesc:a47d34320afdb9ab37a4214a0c33d4791"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the value of the password is correct compared to the database password.  <a href="#a47d34320afdb9ab37a4214a0c33d4791">More...</a><br /></td></tr>
<tr class="separator:a47d34320afdb9ab37a4214a0c33d4791"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5538f7db327e4d05dd85cbfb8db94d7"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ac5538f7db327e4d05dd85cbfb8db94d7">verifPseudoBDD</a> (ajaxResponse)</td></tr>
<tr class="memdesc:ac5538f7db327e4d05dd85cbfb8db94d7"><td class="mdescLeft">&#160;</td><td class="mdescRight">check if the nickname is not taken.  <a href="#ac5538f7db327e4d05dd85cbfb8db94d7">More...</a><br /></td></tr>
<tr class="separator:ac5538f7db327e4d05dd85cbfb8db94d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a24e23b6a325155daad0f098a989d6d41"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a24e23b6a325155daad0f098a989d6d41">verifEmailBDD</a> (ajaxResponse)</td></tr>
<tr class="memdesc:a24e23b6a325155daad0f098a989d6d41"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the email is not taken.  <a href="#a24e23b6a325155daad0f098a989d6d41">More...</a><br /></td></tr>
<tr class="separator:a24e23b6a325155daad0f098a989d6d41"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a76081b25499ce0257c512f37f1ad9988"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988">surligne</a> (champ, erreur)</td></tr>
<tr class="memdesc:a76081b25499ce0257c512f37f1ad9988"><td class="mdescLeft">&#160;</td><td class="mdescRight">Change backgound color of the html element if there is an error or not.  <a href="#a76081b25499ce0257c512f37f1ad9988">More...</a><br /></td></tr>
<tr class="separator:a76081b25499ce0257c512f37f1ad9988"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a34b3788c0664245d1de030f262f040ef"><td class="memItemLeft" align="right" valign="top">function&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#a34b3788c0664245d1de030f262f040ef">affichageDifficulte</a> (ajaxResponse)</td></tr>
<tr class="memdesc:a34b3788c0664245d1de030f262f040ef"><td class="mdescLeft">&#160;</td><td class="mdescRight">display difficulty with the html element "option" in a select.  <a href="#a34b3788c0664245d1de030f262f040ef">More...</a><br /></td></tr>
<tr class="separator:a34b3788c0664245d1de030f262f040ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ae2475e10618961c050dcba04e8c42331"><td class="memItemLeft" align="right" valign="top">use&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d45/a00011.php#ae2475e10618961c050dcba04e8c42331">strict</a></td></tr>
<tr class="separator:ae2475e10618961c050dcba04e8c42331"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a34b3788c0664245d1de030f262f040ef"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function affichageDifficulte </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>display difficulty with the html element "option" in a select. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The Array of "nom_difficulte" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00179">179</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

</div>
</div>
<a class="anchor" id="a47d34320afdb9ab37a4214a0c33d4791"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function mdpActuelVerif </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Check if the value of the password is correct compared to the database password. </p>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00121">121</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_a47d34320afdb9ab37a4214a0c33d4791_cgraph.png" border="0" usemap="#da/d45/a00011_a47d34320afdb9ab37a4214a0c33d4791_cgraph" alt=""/></div>
<map name="da/d45/a00011_a47d34320afdb9ab37a4214a0c33d4791_cgraph" id="da/d45/a00011_a47d34320afdb9ab37a4214a0c33d4791_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="164,5,231,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a1426a760631d33602005a8bb59e49c7a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function recupérationAvatar </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Displays the avatar chosen by the user on his computer. </p>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00013">13</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

</div>
</div>
<a class="anchor" id="a76081b25499ce0257c512f37f1ad9988"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function surligne </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>champ</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>erreur</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Change backgound color of the html element if there is an error or not. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">champ</td><td>The html element </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">erreur</td><td>Boolean if there is an error or not </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00168">168</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

</div>
</div>
<a class="anchor" id="a24e23b6a325155daad0f098a989d6d41"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function verifEmailBDD </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Check if the email is not taken. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The array of "email" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00152">152</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_a24e23b6a325155daad0f098a989d6d41_cgraph.png" border="0" usemap="#da/d45/a00011_a24e23b6a325155daad0f098a989d6d41_cgraph" alt=""/></div>
<map name="da/d45/a00011_a24e23b6a325155daad0f098a989d6d41_cgraph" id="da/d45/a00011_a24e23b6a325155daad0f098a989d6d41_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="163,5,229,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a4a822815e57b31479eb6d364e3003fa2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function verifMail </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Check if the value of the email is correct. </p>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00104">104</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_a4a822815e57b31479eb6d364e3003fa2_cgraph.png" border="0" usemap="#da/d45/a00011_a4a822815e57b31479eb6d364e3003fa2_cgraph" alt=""/></div>
<map name="da/d45/a00011_a4a822815e57b31479eb6d364e3003fa2_cgraph" id="da/d45/a00011_a4a822815e57b31479eb6d364e3003fa2_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="124,5,191,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a5e7778e2c5dd64ac673d79add217c6cf"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function verifMotDePasse </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Check if the value of the password is correct. </p>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00046">46</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_a5e7778e2c5dd64ac673d79add217c6cf_cgraph.png" border="0" usemap="#da/d45/a00011_a5e7778e2c5dd64ac673d79add217c6cf_cgraph" alt=""/></div>
<map name="da/d45/a00011_a5e7778e2c5dd64ac673d79add217c6cf_cgraph" id="da/d45/a00011_a5e7778e2c5dd64ac673d79add217c6cf_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="176,5,243,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ad853bfd925b71db5ce9624d60548b1b7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function verifMotDePasse2 </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Check if the value of the nickname is correct. </p>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00078">78</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_ad853bfd925b71db5ce9624d60548b1b7_cgraph.png" border="0" usemap="#da/d45/a00011_ad853bfd925b71db5ce9624d60548b1b7_cgraph" alt=""/></div>
<map name="da/d45/a00011_ad853bfd925b71db5ce9624d60548b1b7_cgraph" id="da/d45/a00011_ad853bfd925b71db5ce9624d60548b1b7_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="184,5,251,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a0db9c30b86d2f4aa120daa6247990007"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function verifPseudo </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Check if the value of the nickname is correct. </p>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00029">29</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_a0db9c30b86d2f4aa120daa6247990007_cgraph.png" border="0" usemap="#da/d45/a00011_a0db9c30b86d2f4aa120daa6247990007_cgraph" alt=""/></div>
<map name="da/d45/a00011_a0db9c30b86d2f4aa120daa6247990007_cgraph" id="da/d45/a00011_a0db9c30b86d2f4aa120daa6247990007_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="144,5,211,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ac5538f7db327e4d05dd85cbfb8db94d7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">function verifPseudoBDD </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>ajaxResponse</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>check if the nickname is not taken. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ajaxResponse</td><td>The array of "pseudo" </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00136">136</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d45/a00011_ac5538f7db327e4d05dd85cbfb8db94d7_cgraph.png" border="0" usemap="#da/d45/a00011_ac5538f7db327e4d05dd85cbfb8db94d7_cgraph" alt=""/></div>
<map name="da/d45/a00011_ac5538f7db327e4d05dd85cbfb8db94d7_cgraph" id="da/d45/a00011_ac5538f7db327e4d05dd85cbfb8db94d7_cgraph">
<area shape="rect" id="node2" href="../../da/d45/a00011.php#a76081b25499ce0257c512f37f1ad9988" title="Change backgound color of the html element if there is an error or not. " alt="" coords="173,5,240,32"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="ae2475e10618961c050dcba04e8c42331"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">use strict</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00007">7</a> of file <a class="el" href="../../da/d45/a00011_source.php">fonctions.js</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../da/d45/a00011.php">fonctions.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
