<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Map.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/df8/a00076.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#enum-members">Enumerations</a>  </div>
  <div class="headertitle">
<div class="title">Map.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d3/d8b/a00059_source.php">console.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../da/d24/a00068_source.php">errors.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d31/a00069_source.php">files.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Map.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/d9a/a00152.png" border="0" usemap="#Map_8hpp" alt=""/></div>
<map name="Map_8hpp" id="Map_8hpp">
<area shape="rect" id="node2" href="../../d3/d8b/a00059.php" title="console.hpp" alt="" coords="327,155,419,181"/>
<area shape="rect" id="node12" href="../../da/d24/a00068.php" title="errors.hpp" alt="" coords="476,80,556,107"/>
<area shape="rect" id="node13" href="../../d4/d31/a00069.php" title="files.hpp" alt="" coords="645,155,715,181"/>
<area shape="rect" id="node3" href="../../d4/de8/a00061.php" title="convert.hpp" alt="" coords="291,229,381,256"/>
<area shape="rect" id="node9" href="../../d9/df8/a00096.php" title="types.hpp" alt="" coords="97,229,175,256"/>
<area shape="rect" id="node16" href="../../d4/d7d/a00093.php" title="time.hpp" alt="" coords="480,155,552,181"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d01/a00153.png" border="0" usemap="#Map_8hppdep" alt=""/></div>
<map name="Map_8hppdep" id="Map_8hppdep">
<area shape="rect" id="node2" href="../../d9/d73/a00060.php" title="Contraption.hpp" alt="" coords="107,80,221,107"/>
<area shape="rect" id="node4" href="../../d9/d2e/a00056.php" title="C++.hpp" alt="" coords="310,603,383,629"/>
<area shape="rect" id="node3" href="../../d9/db3/a00066.php" title="Entities.hpp" alt="" coords="221,453,312,480"/>
<area shape="rect" id="node17" href="../../d1/d51/a00079.php" title="Object.hpp" alt="" coords="43,229,128,256"/>
<area shape="rect" id="node18" href="../../dc/ddf/a00067.php" title="Entity.hpp" alt="" coords="175,155,257,181"/>
<area shape="rect" id="node16" href="../../d8/d53/a00081.php" title="Player.hpp" alt="" coords="305,528,389,555"/>
<area shape="rect" id="node5" href="../../df/d13/a00085.php" title="QtDefines.hpp" alt="" coords="63,677,169,704"/>
<area shape="rect" id="node12" href="../../d0/d61/a00100.php" title="WindowButton.hpp" alt="" coords="177,752,309,779"/>
<area shape="rect" id="node13" href="../../d4/d3a/a00101.php" title="WindowTitleBar.hpp" alt="" coords="221,827,360,853"/>
<area shape="rect" id="node14" href="../../da/d74/a00099.php" title="Window.hpp" alt="" coords="243,901,338,928"/>
<area shape="rect" id="node15" href="../../d0/d89/a00071.php" title="functions.hpp" alt="" coords="435,827,535,853"/>
<area shape="rect" id="node6" href="../../df/d5d/a00084.php" title="Qt.hpp" alt="" coords="260,976,321,1003"/>
<area shape="rect" id="node11" href="../../d2/db1/a00070.php" title="Font.hpp" alt="" coords="79,752,153,779"/>
<area shape="rect" id="node7" href="../../dc/d54/a00094.php" title="TitleLabel.hpp" alt="" coords="150,1051,253,1077"/>
<area shape="rect" id="node9" href="../../d9/da5/a00075.php" title="MainWindow.h" alt="" coords="211,1200,319,1227"/>
<area shape="rect" id="node10" href="../../d1/dc1/a00092.php" title="TableWidget.hpp" alt="" coords="328,1051,448,1077"/>
<area shape="rect" id="node8" href="../../df/d5f/a00064.php" title="Dialog.hpp" alt="" coords="118,1125,202,1152"/>
<area shape="rect" id="node19" href="../../d2/d79/a00051.php" title="Animal.hpp" alt="" coords="213,304,299,331"/>
<area shape="rect" id="node21" href="../../d1/d6e/a00073.php" title="Hostile.hpp" alt="" coords="253,229,341,256"/>
<area shape="rect" id="node22" href="../../d1/d84/a00097.php" title="Vegetal.hpp" alt="" coords="361,304,452,331"/>
<area shape="rect" id="node20" href="../../d1/d84/a00052.php" title="Ant.hpp" alt="" coords="233,379,300,405"/>
<area shape="rect" id="node23" href="../../da/dec/a00080.php" title="Plant.hpp" alt="" coords="375,379,452,405"/>
<area shape="rect" id="node24" href="../../d9/da4/a00078.php" title="Mushroom.hpp" alt="" coords="477,379,585,405"/>
</map>
</div>
</div>
<p><a href="../../db/df8/a00076_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/de0/a00050.php">WorldDimensions</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An object to group the dimensions of the world.  <a href="../../d5/de0/a00050.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d33/a00027.php">Map</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A map class to have something common.  <a href="../../d0/d33/a00027.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:aac0c2192b0b28c4353d6250244b70287"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df8/a00076.php#aac0c2192b0b28c4353d6250244b70287">MapLine</a> = std::vector&lt; <a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7">Tile</a> &gt;</td></tr>
<tr class="separator:aac0c2192b0b28c4353d6250244b70287"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1ee2140d47f9982ff0aa65b71256bc80"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df8/a00076.php#a1ee2140d47f9982ff0aa65b71256bc80">MapArray</a> = std::vector&lt; <a class="el" href="../../db/df8/a00076.php#aac0c2192b0b28c4353d6250244b70287">MapLine</a> &gt;</td></tr>
<tr class="separator:a1ee2140d47f9982ff0aa65b71256bc80"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="enum-members"></a>
Enumerations</h2></td></tr>
<tr class="memitem:acd2017d946fd818c3b8ca377bc4006c7"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7">Tile</a> { <br />
&#160;&#160;<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7ab50339a10e1de285ac99d4c3990b8693">Tile::NONE</a> = 0, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7a2add2964642f39099cb51edf4a4f5a70">Tile::WATER</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7aa620a361e9c7602698b91e34b416c08b">Tile::LAVA</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7aa3030e42cd8f04255711905a9182399f">Tile::GRASS</a>, 
<br />
&#160;&#160;<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7a3ef5656907af69ff36347e8dc2416744">Tile::DIRT</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7a48d536b2de1195d0c9f6ea8ab884085e">Tile::WALL</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7aa63e2adb56a8019132fbe12acda3b7d6">Tile::STONE</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7aadec9358cd14fbdcdb29c5b2f040d712">Tile::HOLE</a>, 
<br />
&#160;&#160;<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7a6d0c9fc747131795e6e5d0c5119f12cb">Tile::VOID</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7abb1ca97ec761fc37101737ba0aa2e7c5">Tile::ERROR</a>, 
<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7a2582dd863c1c50525a267e1cbe656929">Tile::AIR</a>
<br />
 }<tr class="memdesc:acd2017d946fd818c3b8ca377bc4006c7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Tiles of the map.  <a href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7">More...</a><br /></td></tr>
</td></tr>
<tr class="separator:acd2017d946fd818c3b8ca377bc4006c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>30 mai 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../db/df8/a00076_source.php">Map.hpp</a>.</p>
</div><h2 class="groupheader">Typedef Documentation</h2>
<a class="anchor" id="a1ee2140d47f9982ff0aa65b71256bc80"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="../../db/df8/a00076.php#a1ee2140d47f9982ff0aa65b71256bc80">MapArray</a> =  std::vector&lt;<a class="el" href="../../db/df8/a00076.php#aac0c2192b0b28c4353d6250244b70287">MapLine</a>&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../db/df8/a00076_source.php#l00042">42</a> of file <a class="el" href="../../db/df8/a00076_source.php">Map.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="aac0c2192b0b28c4353d6250244b70287"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="../../db/df8/a00076.php#aac0c2192b0b28c4353d6250244b70287">MapLine</a> =  std::vector&lt;<a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7">Tile</a>&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="../../db/df8/a00076_source.php#l00041">41</a> of file <a class="el" href="../../db/df8/a00076_source.php">Map.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Enumeration Type Documentation</h2>
<a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="../../db/df8/a00076.php#acd2017d946fd818c3b8ca377bc4006c7">Tile</a></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">strong</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Tiles of the map. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7ab50339a10e1de285ac99d4c3990b8693"></a>NONE&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7a2add2964642f39099cb51edf4a4f5a70"></a>WATER&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7aa620a361e9c7602698b91e34b416c08b"></a>LAVA&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7aa3030e42cd8f04255711905a9182399f"></a>GRASS&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7a3ef5656907af69ff36347e8dc2416744"></a>DIRT&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7a48d536b2de1195d0c9f6ea8ab884085e"></a>WALL&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7aa63e2adb56a8019132fbe12acda3b7d6"></a>STONE&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7aadec9358cd14fbdcdb29c5b2f040d712"></a>HOLE&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7a6d0c9fc747131795e6e5d0c5119f12cb"></a>VOID&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7abb1ca97ec761fc37101737ba0aa2e7c5"></a>ERROR&#160;</td><td class="fielddoc">
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="acd2017d946fd818c3b8ca377bc4006c7a2582dd863c1c50525a267e1cbe656929"></a>AIR&#160;</td><td class="fielddoc">
</td></tr>
</table>

<p>Definition at line <a class="el" href="../../db/df8/a00076_source.php#l00018">18</a> of file <a class="el" href="../../db/df8/a00076_source.php">Map.hpp</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_9cc7dab42d10c04902c95d2c14820089.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dir_42c90fb9218922ddd8984da73ce0d59c.php">C++</a></li><li class="navelem"><a class="el" href="../../db/df8/a00076.php">Map.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
