<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: Ant.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d8c/a00035.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a>  </div>
  <div class="headertitle">
<div class="title">Ant.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../db/df3/a00034_source.php">Animal.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Ant.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/d89/a00071.png" border="0" usemap="#Ant_8hpp" alt=""/></div>
<map name="Ant_8hpp" id="Ant_8hpp">
<area shape="rect" id="node2" href="../../db/df3/a00034.php" title="Animal.hpp" alt="" coords="909,80,996,107"/>
<area shape="rect" id="node3" href="../../d4/dca/a00048.php" title="Entity.hpp" alt="" coords="912,229,993,256"/>
<area shape="rect" id="node50" href="../../d2/d79/a00051.php" title="Hostile.hpp" alt="" coords="950,155,1038,181"/>
<area shape="rect" id="node4" href="../../d6/d42/a00043.php" title="Contraption.hpp" alt="" coords="895,304,1010,331"/>
<area shape="rect" id="node5" href="../../d3/dea/a00046.php" title="defines.hpp" alt="" coords="559,379,648,405"/>
<area shape="rect" id="node46" href="../../dd/d32/a00041.php" title="collides.hpp" alt="" coords="1107,379,1198,405"/>
<area shape="rect" id="node49" href="../../dc/dee/a00053.php" title="Map.hpp" alt="" coords="917,379,989,405"/>
<area shape="rect" id="node12" href="../../d8/d41/a00038.php" title="bdd.hpp" alt="" coords="569,453,637,480"/>
<area shape="rect" id="node45" href="../../de/d8c/a00036.php" title="Args.hpp" alt="" coords="790,528,865,555"/>
<area shape="rect" id="node17" href="../../d2/dee/a00049.php" title="errors.hpp" alt="" coords="787,603,867,629"/>
<area shape="rect" id="node36" href="../../df/d03/a00062.php" title="string.hpp" alt="" coords="51,528,129,555"/>
<area shape="rect" id="node18" href="../../d5/db6/a00042.php" title="console.hpp" alt="" coords="633,677,725,704"/>
<area shape="rect" id="node28" href="../../d5/de0/a00050.php" title="files.hpp" alt="" coords="749,677,820,704"/>
<area shape="rect" id="node31" href="../../df/d5f/a00064.php" title="time.hpp" alt="" coords="934,677,1006,704"/>
<area shape="rect" id="node19" href="../../d5/df9/a00044.php" title="convert.hpp" alt="" coords="217,752,307,779"/>
<area shape="rect" id="node25" href="../../d9/db3/a00066.php" title="types.hpp" alt="" coords="644,752,723,779"/>
<area shape="rect" id="node34" href="../../d1/d6f/a00063.php" title="Threadable.hpp" alt="" coords="1060,752,1171,779"/>
<area shape="rect" id="node39" href="../../d1/d84/a00052.php" title="macro.hpp" alt="" coords="182,603,265,629"/>
<area shape="rect" id="node40" href="../../d1/dc6/a00037.php" title="array.hpp" alt="" coords="487,603,563,629"/>
<area shape="rect" id="node43" href="../../d9/d73/a00060.php" title="RNG.hpp" alt="" coords="289,603,366,629"/>
<area shape="rect" id="node47" href="../../d1/dea/a00054.php" title="maths.hpp" alt="" coords="1167,453,1250,480"/>
</map>
</div>
</div>
<p><a href="../../d4/d8c/a00035_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d0b/a00004.php">Ant</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An ant.  <a href="../../d0/d0b/a00004.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>07 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d4/d8c/a00035_source.php">Ant.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d4/d8c/a00035.php">Ant.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
