<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Qt: GraphScene.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/d7a/a00016.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#typedef-members">Typedefs</a>  </div>
  <div class="headertitle">
<div class="title">GraphScene.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;map&gt;</code><br />
<code>#include &lt;vector&gt;</code><br />
<code>#include &lt;utility&gt;</code><br />
<code>#include &lt;cmath&gt;</code><br />
<code>#include &quot;<a class="el" href="../../db/db2/a00020_source.php">Scene.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for GraphScene.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d87/a00032.png" border="0" usemap="#GraphScene_8hpp" alt=""/></div>
<map name="GraphScene_8hpp" id="GraphScene_8hpp">
<area shape="rect" id="node6" href="../../db/db2/a00020.php" title="Scene.hpp" alt="" coords="320,80,404,107"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/dc0/a00033.png" border="0" usemap="#GraphScene_8hppdep" alt=""/></div>
<map name="GraphScene_8hppdep" id="GraphScene_8hppdep">
<area shape="rect" id="node2" href="../../d1/d2b/a00018.php" title="QtDefines.hpp" alt="" coords="16,80,123,107"/>
<area shape="rect" id="node3" href="../../d4/d51/a00017.php" title="Qt.hpp" alt="" coords="35,379,96,405"/>
<area shape="rect" id="node5" href="../../d3/dfe/a00025.php" title="WindowButton.hpp" alt="" coords="57,155,189,181"/>
<area shape="rect" id="node4" href="../../d7/de0/a00022.php" title="TableWidget.hpp" alt="" coords="5,453,125,480"/>
<area shape="rect" id="node6" href="../../d6/d5b/a00026.php" title="WindowTitleBar.hpp" alt="" coords="55,229,193,256"/>
<area shape="rect" id="node7" href="../../dc/de2/a00024.php" title="Window.hpp" alt="" coords="66,304,161,331"/>
</map>
</div>
</div>
<p><a href="../../d7/d7a/a00016_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/dad/a00005.php">GraphScene</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A <a class="el" href="../../d4/dee/a00008.php" title="An implementation of QGraphcsScene with an updator. ">Scene</a> implementation to draw graphs.  <a href="../../dd/dad/a00005.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:a8dcc9a1fe4837db39cd87e259f0ed6ed"><td class="memItemLeft" align="right" valign="top">typedef long double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a></td></tr>
<tr class="memdesc:a8dcc9a1fe4837db39cd87e259f0ed6ed"><td class="mdescLeft">&#160;</td><td class="mdescRight">An alias to simplify the use of the type for the graph.  <a href="#a8dcc9a1fe4837db39cd87e259f0ed6ed">More...</a><br /></td></tr>
<tr class="separator:a8dcc9a1fe4837db39cd87e259f0ed6ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad5373de30ddd6b6c0f911f63ed642739"><td class="memItemLeft" align="right" valign="top">typedef std::map&lt; <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>, <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d7a/a00016.php#ad5373de30ddd6b6c0f911f63ed642739">GraphMap</a></td></tr>
<tr class="memdesc:ad5373de30ddd6b6c0f911f63ed642739"><td class="mdescLeft">&#160;</td><td class="mdescRight">The array where the graphs' points are stored.  <a href="#ad5373de30ddd6b6c0f911f63ed642739">More...</a><br /></td></tr>
<tr class="separator:ad5373de30ddd6b6c0f911f63ed642739"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a464fcd96dfa56d6feac32bfcd2e0403f"><td class="memItemLeft" align="right" valign="top">typedef std::pair&lt; std::pair&lt; <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>, <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a> &gt;, std::pair&lt; <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>, <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a> &gt; &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d7a/a00016.php#a464fcd96dfa56d6feac32bfcd2e0403f">utmost</a></td></tr>
<tr class="memdesc:a464fcd96dfa56d6feac32bfcd2e0403f"><td class="mdescLeft">&#160;</td><td class="mdescRight">A data type to simplify the draw of the differents graphs.  <a href="#a464fcd96dfa56d6feac32bfcd2e0403f">More...</a><br /></td></tr>
<tr class="separator:a464fcd96dfa56d6feac32bfcd2e0403f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>10 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d7/d7a/a00016_source.php">GraphScene.hpp</a>.</p>
</div><h2 class="groupheader">Typedef Documentation</h2>
<a class="anchor" id="ad5373de30ddd6b6c0f911f63ed642739"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef std::map&lt;<a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>, <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>&gt; <a class="el" href="../../d7/d7a/a00016.php#ad5373de30ddd6b6c0f911f63ed642739">GraphMap</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The array where the graphs' points are stored. </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00021">21</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">GraphScene.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a8dcc9a1fe4837db39cd87e259f0ed6ed"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef long double <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>An alias to simplify the use of the type for the graph. </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00019">19</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">GraphScene.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a464fcd96dfa56d6feac32bfcd2e0403f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef std::pair&lt;std::pair&lt;<a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>, <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>&gt;, std::pair&lt;<a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>, <a class="el" href="../../d7/d7a/a00016.php#a8dcc9a1fe4837db39cd87e259f0ed6ed">GraphMapType</a>&gt; &gt; <a class="el" href="../../d7/d7a/a00016.php#a464fcd96dfa56d6feac32bfcd2e0403f">utmost</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>A data type to simplify the draw of the differents graphs. </p>

<p>Definition at line <a class="el" href="../../d7/d7a/a00016_source.php#l00023">23</a> of file <a class="el" href="../../d7/d7a/a00016_source.php">GraphScene.hpp</a>.</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../d7/d7a/a00016.php">GraphScene.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
