<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: Contraption Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d86/a00012.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../d8/d87/a00118.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Contraption Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A contraption.  
 <a href="../../df/d86/a00012.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Contraption:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d6a/a00119.png" border="0" usemap="#Contraption_inherit__map" alt="Inheritance graph"/></div>
<map name="Contraption_inherit__map" id="Contraption_inherit__map">
<area shape="rect" id="node2" href="../../dd/d1b/a00015.php" title="An entity. " alt="" coords="53,80,109,107"/>
<area shape="rect" id="node8" href="../../de/d11/a00021.php" title="An object. " alt="" coords="133,80,193,107"/>
<area shape="rect" id="node3" href="../../d1/d7c/a00003.php" title="An animal. " alt="" coords="5,155,68,181"/>
<area shape="rect" id="node5" href="../../df/d61/a00031.php" title="A vegetal. " alt="" coords="93,155,159,181"/>
<area shape="rect" id="node4" href="../../d0/d0b/a00004.php" title="An ant. " alt="" coords="15,229,58,256"/>
<area shape="rect" id="node6" href="../../dd/da2/a00019.php" title="A mushroom. " alt="" coords="83,229,166,256"/>
<area shape="rect" id="node7" href="../../d7/de0/a00022.php" title="A plant. " alt="" coords="191,229,243,256"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ac80a221d48732cc349d5ccef1e4ad319"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#ac80a221d48732cc349d5ccef1e4ad319">Contraption</a> (<a class="el" href="../../d1/d2b/a00018.php">Map</a> *map=nullptr, <a class="el" href="../../dc/de2/a00024.php">Point</a> pt={0, 0, 0}, <a class="el" href="../../d7/dd4/a00013.php">ContraptionAttr</a> attr={0, 0, 0})</td></tr>
<tr class="memdesc:ac80a221d48732cc349d5ccef1e4ad319"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor of the class.  <a href="#ac80a221d48732cc349d5ccef1e4ad319">More...</a><br /></td></tr>
<tr class="separator:ac80a221d48732cc349d5ccef1e4ad319"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acfdea93e7835722a3b211ba2b8dd1463"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#acfdea93e7835722a3b211ba2b8dd1463">~Contraption</a> ()</td></tr>
<tr class="memdesc:acfdea93e7835722a3b211ba2b8dd1463"><td class="mdescLeft">&#160;</td><td class="mdescRight">Virtual destructor.  <a href="#acfdea93e7835722a3b211ba2b8dd1463">More...</a><br /></td></tr>
<tr class="separator:acfdea93e7835722a3b211ba2b8dd1463"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05facc668dcb27c1bab72118aa5bafe7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a05facc668dcb27c1bab72118aa5bafe7">setPosition</a> (<a class="el" href="../../dc/de2/a00024.php">Point</a> pt)</td></tr>
<tr class="memdesc:a05facc668dcb27c1bab72118aa5bafe7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the position.  <a href="#a05facc668dcb27c1bab72118aa5bafe7">More...</a><br /></td></tr>
<tr class="separator:a05facc668dcb27c1bab72118aa5bafe7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a144577a5b80062834989f99a96b6c89c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a144577a5b80062834989f99a96b6c89c">setPosition</a> (double x, double y, double z=0)</td></tr>
<tr class="memdesc:a144577a5b80062834989f99a96b6c89c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the position.  <a href="#a144577a5b80062834989f99a96b6c89c">More...</a><br /></td></tr>
<tr class="separator:a144577a5b80062834989f99a96b6c89c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab14db8239bfc09ba3c5c6e07a23033b7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#ab14db8239bfc09ba3c5c6e07a23033b7">setX</a> (double x)</td></tr>
<tr class="memdesc:ab14db8239bfc09ba3c5c6e07a23033b7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the x coordinate.  <a href="#ab14db8239bfc09ba3c5c6e07a23033b7">More...</a><br /></td></tr>
<tr class="separator:ab14db8239bfc09ba3c5c6e07a23033b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a260fe681d3f4be9cb08546dff4d3d4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a9a260fe681d3f4be9cb08546dff4d3d4">setY</a> (double y)</td></tr>
<tr class="memdesc:a9a260fe681d3f4be9cb08546dff4d3d4"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the y coordinate.  <a href="#a9a260fe681d3f4be9cb08546dff4d3d4">More...</a><br /></td></tr>
<tr class="separator:a9a260fe681d3f4be9cb08546dff4d3d4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61b34301ffd55f3f9b6bc319020e691d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a61b34301ffd55f3f9b6bc319020e691d">setZ</a> (double z)</td></tr>
<tr class="memdesc:a61b34301ffd55f3f9b6bc319020e691d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the z coordinate.  <a href="#a61b34301ffd55f3f9b6bc319020e691d">More...</a><br /></td></tr>
<tr class="separator:a61b34301ffd55f3f9b6bc319020e691d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e221cb1cdd414d2d06492b575ec7120"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a3e221cb1cdd414d2d06492b575ec7120">setAttributes</a> (<a class="el" href="../../d7/dd4/a00013.php">ContraptionAttr</a> attr)</td></tr>
<tr class="memdesc:a3e221cb1cdd414d2d06492b575ec7120"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the attributes.  <a href="#a3e221cb1cdd414d2d06492b575ec7120">More...</a><br /></td></tr>
<tr class="separator:a3e221cb1cdd414d2d06492b575ec7120"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a96a40d8c6b09bc86be65042fad49592f"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a96a40d8c6b09bc86be65042fad49592f">setAttributes</a> (double w, double h, double angle=0)</td></tr>
<tr class="memdesc:a96a40d8c6b09bc86be65042fad49592f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the attributes.  <a href="#a96a40d8c6b09bc86be65042fad49592f">More...</a><br /></td></tr>
<tr class="separator:a96a40d8c6b09bc86be65042fad49592f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83d954f1cb764a7410de01d33cb9e396"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a83d954f1cb764a7410de01d33cb9e396">setW</a> (double w)</td></tr>
<tr class="memdesc:a83d954f1cb764a7410de01d33cb9e396"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the width.  <a href="#a83d954f1cb764a7410de01d33cb9e396">More...</a><br /></td></tr>
<tr class="separator:a83d954f1cb764a7410de01d33cb9e396"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afb8030a7a7df2bef59356c293f845487"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#afb8030a7a7df2bef59356c293f845487">setH</a> (double h)</td></tr>
<tr class="memdesc:afb8030a7a7df2bef59356c293f845487"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the height.  <a href="#afb8030a7a7df2bef59356c293f845487">More...</a><br /></td></tr>
<tr class="separator:afb8030a7a7df2bef59356c293f845487"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad1482208cab08d738341ab2265b37deb"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#ad1482208cab08d738341ab2265b37deb">setA</a> (double angle)</td></tr>
<tr class="memdesc:ad1482208cab08d738341ab2265b37deb"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the angle.  <a href="#ad1482208cab08d738341ab2265b37deb">More...</a><br /></td></tr>
<tr class="separator:ad1482208cab08d738341ab2265b37deb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0d88e87317d6f003471fcf52808a4a25"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a0d88e87317d6f003471fcf52808a4a25">setMap</a> (<a class="el" href="../../d1/d2b/a00018.php">Map</a> *map)</td></tr>
<tr class="memdesc:a0d88e87317d6f003471fcf52808a4a25"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the map.  <a href="#a0d88e87317d6f003471fcf52808a4a25">More...</a><br /></td></tr>
<tr class="separator:a0d88e87317d6f003471fcf52808a4a25"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae9131d3133c67c22f8692d4bd806187e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#ae9131d3133c67c22f8692d4bd806187e">setLevel</a> (size_t level)</td></tr>
<tr class="memdesc:ae9131d3133c67c22f8692d4bd806187e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the level.  <a href="#ae9131d3133c67c22f8692d4bd806187e">More...</a><br /></td></tr>
<tr class="separator:ae9131d3133c67c22f8692d4bd806187e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abc9cc2cd7e06c45e4c0edf96f405bae2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dc/de2/a00024.php">Point</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#abc9cc2cd7e06c45e4c0edf96f405bae2">getPosition</a> () const </td></tr>
<tr class="separator:abc9cc2cd7e06c45e4c0edf96f405bae2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8eddeb512a0133271555e8f1ef888dc3"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a8eddeb512a0133271555e8f1ef888dc3">getX</a> () const </td></tr>
<tr class="separator:a8eddeb512a0133271555e8f1ef888dc3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1cf1642c874236857eff096f32f3285c"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a1cf1642c874236857eff096f32f3285c">getY</a> () const </td></tr>
<tr class="separator:a1cf1642c874236857eff096f32f3285c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3365e9eda5d1c8426910522dcbb14d52"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a3365e9eda5d1c8426910522dcbb14d52">getZ</a> () const </td></tr>
<tr class="separator:a3365e9eda5d1c8426910522dcbb14d52"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9993ab6cac0ce33ea91485965572cba9"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d7/dd4/a00013.php">ContraptionAttr</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a9993ab6cac0ce33ea91485965572cba9">getAttributes</a> () const </td></tr>
<tr class="separator:a9993ab6cac0ce33ea91485965572cba9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf50efec2040353189fe1b46152ba8d0"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#acf50efec2040353189fe1b46152ba8d0">getW</a> () const </td></tr>
<tr class="separator:acf50efec2040353189fe1b46152ba8d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa468a3b0582bb0e073f2f642611c10f1"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#aa468a3b0582bb0e073f2f642611c10f1">getH</a> () const </td></tr>
<tr class="separator:aa468a3b0582bb0e073f2f642611c10f1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08d8bb97ba4e9b6238f5a80af9800579"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a08d8bb97ba4e9b6238f5a80af9800579">getA</a> () const </td></tr>
<tr class="separator:a08d8bb97ba4e9b6238f5a80af9800579"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3ca9a1e5aff93640d295576af62b7202"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d1/d2b/a00018.php">Map</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a3ca9a1e5aff93640d295576af62b7202">getMap</a> () const </td></tr>
<tr class="separator:a3ca9a1e5aff93640d295576af62b7202"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b6d4a5f2d520dfa5e58afe5b421a126"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a3b6d4a5f2d520dfa5e58afe5b421a126">getLevel</a> () const </td></tr>
<tr class="separator:a3b6d4a5f2d520dfa5e58afe5b421a126"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6dedcd33d891a22ae7d6ce4d7e1d6a37"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a6dedcd33d891a22ae7d6ce4d7e1d6a37">printInfos</a> (std::ostream &amp;stream) const </td></tr>
<tr class="memdesc:a6dedcd33d891a22ae7d6ce4d7e1d6a37"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the infos in the instance of the class in <em>stream</em>.  <a href="#a6dedcd33d891a22ae7d6ce4d7e1d6a37">More...</a><br /></td></tr>
<tr class="separator:a6dedcd33d891a22ae7d6ce4d7e1d6a37"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd10a73d032a10e48c57e7b3252c58c2"><td class="memItemLeft" align="right" valign="top">virtual double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#afd10a73d032a10e48c57e7b3252c58c2">getRelativeZ</a> (<a class="el" href="../../df/d86/a00012.php">Contraption</a> &amp;obj)</td></tr>
<tr class="memdesc:afd10a73d032a10e48c57e7b3252c58c2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute a z with the obstacles.  <a href="#afd10a73d032a10e48c57e7b3252c58c2">More...</a><br /></td></tr>
<tr class="separator:afd10a73d032a10e48c57e7b3252c58c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3af679109317a6740c661fe5164158ff"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a3af679109317a6740c661fe5164158ff">addPosition</a> (double x, double y, double z=0)</td></tr>
<tr class="memdesc:a3af679109317a6740c661fe5164158ff"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add coordinates to the actual position.  <a href="#a3af679109317a6740c661fe5164158ff">More...</a><br /></td></tr>
<tr class="separator:a3af679109317a6740c661fe5164158ff"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab69fdcd66f63e0a038a4006d43ecb9b6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#ab69fdcd66f63e0a038a4006d43ecb9b6">turnLeft</a> ()</td></tr>
<tr class="memdesc:ab69fdcd66f63e0a038a4006d43ecb9b6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Turn the <a class="el" href="../../df/d86/a00012.php" title="A contraption. ">Contraption</a> to the left.  <a href="#ab69fdcd66f63e0a038a4006d43ecb9b6">More...</a><br /></td></tr>
<tr class="separator:ab69fdcd66f63e0a038a4006d43ecb9b6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20f271c846ea0c8bc96c618616a260ba"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a20f271c846ea0c8bc96c618616a260ba">turnRight</a> ()</td></tr>
<tr class="memdesc:a20f271c846ea0c8bc96c618616a260ba"><td class="mdescLeft">&#160;</td><td class="mdescRight">Turn the <a class="el" href="../../df/d86/a00012.php" title="A contraption. ">Contraption</a> to the right.  <a href="#a20f271c846ea0c8bc96c618616a260ba">More...</a><br /></td></tr>
<tr class="separator:a20f271c846ea0c8bc96c618616a260ba"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a763a20bdd6cf99e565f2516d1c4bb161"><td class="memItemLeft" align="right" valign="top">std::ostream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d86/a00012.php#a763a20bdd6cf99e565f2516d1c4bb161">operator&lt;&lt;</a> (std::ostream &amp;stream, <a class="el" href="../../df/d86/a00012.php">Contraption</a> const &amp;in)</td></tr>
<tr class="memdesc:a763a20bdd6cf99e565f2516d1c4bb161"><td class="mdescLeft">&#160;</td><td class="mdescRight">Overload of the &lt;&lt; operator.  <a href="#a763a20bdd6cf99e565f2516d1c4bb161">More...</a><br /></td></tr>
<tr class="separator:a763a20bdd6cf99e565f2516d1c4bb161"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A contraption. </p>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00020">20</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ac80a221d48732cc349d5ccef1e4ad319"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Contraption::Contraption </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d1/d2b/a00018.php">Map</a> *&#160;</td>
          <td class="paramname"><em>map</em> = <code>nullptr</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../dc/de2/a00024.php">Point</a>&#160;</td>
          <td class="paramname"><em>pt</em> = <code>{0,&#160;0,&#160;0}</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../d7/dd4/a00013.php">ContraptionAttr</a>&#160;</td>
          <td class="paramname"><em>attr</em> = <code>{0,&#160;0,&#160;0}</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Constructor of the class. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">map</td><td>The map where it is </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">pt</td><td>The position in the map </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">attr</td><td>The attributes of the object(width, height, angle) </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="acfdea93e7835722a3b211ba2b8dd1463"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual Contraption::~Contraption </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Virtual destructor. </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a3af679109317a6740c661fe5164158ff"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::addPosition </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>y</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>z</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Add coordinates to the actual position. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>X coordinate </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">y</td><td>Y coordinate </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">z</td><td>Z coordinate</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="a08d8bb97ba4e9b6238f5a80af9800579"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double Contraption::getA </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the angle </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00147">147</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a9993ab6cac0ce33ea91485965572cba9"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d7/dd4/a00013.php">ContraptionAttr</a> Contraption::getAttributes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the attributes </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00140">140</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="aa468a3b0582bb0e073f2f642611c10f1"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double Contraption::getH </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the height </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00145">145</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a3b6d4a5f2d520dfa5e58afe5b421a126"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">size_t Contraption::getLevel </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the level </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00153">153</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_a3b6d4a5f2d520dfa5e58afe5b421a126_cgraph.png" border="0" usemap="#df/d86/a00012_a3b6d4a5f2d520dfa5e58afe5b421a126_cgraph" alt=""/></div>
<map name="df/d86/a00012_a3b6d4a5f2d520dfa5e58afe5b421a126_cgraph" id="df/d86/a00012_a3b6d4a5f2d520dfa5e58afe5b421a126_cgraph">
<area shape="rect" id="node2" href="../../df/d86/a00012.php#a6dedcd33d891a22ae7d6ce4d7e1d6a37" title="Print the infos in the instance of the class in stream. " alt="" coords="210,5,361,32"/>
<area shape="rect" id="node3" href="../../df/d86/a00012.php#afd10a73d032a10e48c57e7b3252c58c2" title="Compute a z with the obstacles. " alt="" coords="200,56,371,83"/>
<area shape="rect" id="node4" href="../../df/d86/a00012.php#a3af679109317a6740c661fe5164158ff" title="Add coordinates to the actual position. " alt="" coords="203,107,368,133"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a3ca9a1e5aff93640d295576af62b7202"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d1/d2b/a00018.php">Map</a>* Contraption::getMap </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the map </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00150">150</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="abc9cc2cd7e06c45e4c0edf96f405bae2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../dc/de2/a00024.php">Point</a> Contraption::getPosition </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the position </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00130">130</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="afd10a73d032a10e48c57e7b3252c58c2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual double Contraption::getRelativeZ </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../df/d86/a00012.php">Contraption</a> &amp;&#160;</td>
          <td class="paramname"><em>obj</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Compute a z with the obstacles. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">obj</td><td>The obstacle to compute z with</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the computed z </dd></dl>

<p>Reimplemented in <a class="el" href="../../d1/d7c/a00003.php#a24b488a8597fd44c0e4654598736bd4a">Animal</a>.</p>

</div>
</div>
<a class="anchor" id="acf50efec2040353189fe1b46152ba8d0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double Contraption::getW </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the width </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00143">143</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a8eddeb512a0133271555e8f1ef888dc3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double Contraption::getX </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the X position </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00133">133</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a1cf1642c874236857eff096f32f3285c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double Contraption::getY </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the Y position </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00135">135</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a3365e9eda5d1c8426910522dcbb14d52"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double Contraption::getZ </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>Return the Z position </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00137">137</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a6dedcd33d891a22ae7d6ce4d7e1d6a37"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void Contraption::printInfos </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>stream</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Print the infos in the instance of the class in <em>stream</em>. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">stream</td><td>The output stream</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Reimplemented in <a class="el" href="../../d1/d7c/a00003.php#aadcff88a99d15e3420b1a06401879bf7">Animal</a>, <a class="el" href="../../dd/d1b/a00015.php#a20e050d3112f769d9a911e1b52f2ac77">Entity</a>, <a class="el" href="../../d0/d0b/a00004.php#a199ef1722ee48997bc56b183f3c2e417">Ant</a>, <a class="el" href="../../dd/da2/a00019.php#a1467b6e6e2b41e3e3790f7e2b8e28b6d">Mushroom</a>, <a class="el" href="../../de/d11/a00021.php#a4afb4bd99645b9bfd1c95fcb93f3077b">Object</a>, <a class="el" href="../../d7/de0/a00022.php#a2ee3b0d4379f9969d620b7f0bc3a277f">Plant</a>, and <a class="el" href="../../df/d61/a00031.php#ac3ac9ca3d977facf17953da4c853f37f">Vegetal</a>.</p>

</div>
</div>
<a class="anchor" id="ad1482208cab08d738341ab2265b37deb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setA </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>angle</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the angle. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">angle</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00110">110</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a3e221cb1cdd414d2d06492b575ec7120"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setAttributes </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d7/dd4/a00013.php">ContraptionAttr</a>&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the attributes. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">attr</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00079">79</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_a3e221cb1cdd414d2d06492b575ec7120_cgraph.png" border="0" usemap="#df/d86/a00012_a3e221cb1cdd414d2d06492b575ec7120_cgraph" alt=""/></div>
</div>
</p>

</div>
</div>
<a class="anchor" id="a96a40d8c6b09bc86be65042fad49592f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setAttributes </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>w</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>angle</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the attributes. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">w</td><td>The width to set </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">h</td><td>The height to set </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">angle</td><td>The angle to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="afb8030a7a7df2bef59356c293f845487"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setH </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the height. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">h</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00103">103</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="ae9131d3133c67c22f8692d4bd806187e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setLevel </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>level</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the level. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">level</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00126">126</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a0d88e87317d6f003471fcf52808a4a25"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setMap </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d1/d2b/a00018.php">Map</a> *&#160;</td>
          <td class="paramname"><em>map</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the map. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">map</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00118">118</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="a05facc668dcb27c1bab72118aa5bafe7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setPosition </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../dc/de2/a00024.php">Point</a>&#160;</td>
          <td class="paramname"><em>pt</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the position. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">pt</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00040">40</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_a05facc668dcb27c1bab72118aa5bafe7_cgraph.png" border="0" usemap="#df/d86/a00012_a05facc668dcb27c1bab72118aa5bafe7_cgraph" alt=""/></div>
<map name="df/d86/a00012_a05facc668dcb27c1bab72118aa5bafe7_cgraph" id="df/d86/a00012_a05facc668dcb27c1bab72118aa5bafe7_cgraph">
<area shape="rect" id="node2" href="../../df/d86/a00012.php#ab14db8239bfc09ba3c5c6e07a23033b7" title="Set the x coordinate. " alt="" coords="216,5,340,32"/>
<area shape="rect" id="node3" href="../../df/d86/a00012.php#a9a260fe681d3f4be9cb08546dff4d3d4" title="Set the y coordinate. " alt="" coords="216,56,340,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a144577a5b80062834989f99a96b6c89c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setPosition </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>y</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>z</em> = <code>0</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the position. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The x to set </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">y</td><td>The y to set </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">z</td><td>The z to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="a83d954f1cb764a7410de01d33cb9e396"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setW </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the width. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">w</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00096">96</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="ab14db8239bfc09ba3c5c6e07a23033b7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setX </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>x</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the x coordinate. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">x</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="a9a260fe681d3f4be9cb08546dff4d3d4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setY </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>y</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the y coordinate. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">y</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a class="anchor" id="a61b34301ffd55f3f9b6bc319020e691d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::setZ </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>z</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the z coordinate. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">z</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00071">71</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="ab69fdcd66f63e0a038a4006d43ecb9b6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::turnLeft </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Turn the <a class="el" href="../../df/d86/a00012.php" title="A contraption. ">Contraption</a> to the left. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00191">191</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_ab69fdcd66f63e0a038a4006d43ecb9b6_cgraph.png" border="0" usemap="#df/d86/a00012_ab69fdcd66f63e0a038a4006d43ecb9b6_cgraph" alt=""/></div>
<map name="df/d86/a00012_ab69fdcd66f63e0a038a4006d43ecb9b6_cgraph" id="df/d86/a00012_ab69fdcd66f63e0a038a4006d43ecb9b6_cgraph">
<area shape="rect" id="node2" href="../../df/d86/a00012.php#ad1482208cab08d738341ab2265b37deb" title="Set the angle. " alt="" coords="195,5,319,32"/>
<area shape="rect" id="node3" href="../../df/d86/a00012.php#a08d8bb97ba4e9b6238f5a80af9800579" title="Contraption::getA" alt="" coords="195,56,319,83"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a20f271c846ea0c8bc96c618616a260ba"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Contraption::turnRight </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Turn the <a class="el" href="../../df/d86/a00012.php" title="A contraption. ">Contraption</a> to the right. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../d5/db6/a00042_source.php#l00196">196</a> of file <a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d86/a00012_a20f271c846ea0c8bc96c618616a260ba_cgraph.png" border="0" usemap="#df/d86/a00012_a20f271c846ea0c8bc96c618616a260ba_cgraph" alt=""/></div>
<map name="df/d86/a00012_a20f271c846ea0c8bc96c618616a260ba_cgraph" id="df/d86/a00012_a20f271c846ea0c8bc96c618616a260ba_cgraph">
<area shape="rect" id="node2" href="../../df/d86/a00012.php#ad1482208cab08d738341ab2265b37deb" title="Set the angle. " alt="" coords="204,5,328,32"/>
<area shape="rect" id="node3" href="../../df/d86/a00012.php#a08d8bb97ba4e9b6238f5a80af9800579" title="Contraption::getA" alt="" coords="204,56,328,83"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Friends And Related Function Documentation</h2>
<a class="anchor" id="a763a20bdd6cf99e565f2516d1c4bb161"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ostream&amp; operator&lt;&lt; </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>stream</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../df/d86/a00012.php">Contraption</a> const &amp;&#160;</td>
          <td class="paramname"><em>in</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Overload of the &lt;&lt; operator. </p>
<p>Allow you to put a <a class="el" href="../../df/d86/a00012.php" title="A contraption. ">Contraption</a> object in an output stream </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d5/db6/a00042_source.php">Contraption.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../df/d86/a00012.php">Contraption</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
