<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: Color Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/dec/a00010.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../d3/d00/a00113.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Color Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Change the text color in the console.  
 <a href="../../d7/dec/a00010.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Color:</div>
<div class="dyncontent">
<div class="center"><img src="../../d8/d17/a00114.png" border="0" usemap="#Color_inherit__map" alt="Inheritance graph"/></div>
<map name="Color_inherit__map" id="Color_inherit__map">
<area shape="rect" id="node2" href="../../d3/dfe/a00025.php" title="Reinit the color in the console. " alt="" coords="5,80,61,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:af13248c98bcd8bf432f3c9dab0a27135"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#af13248c98bcd8bf432f3c9dab0a27135">Color</a> (std::string color)</td></tr>
<tr class="memdesc:af13248c98bcd8bf432f3c9dab0a27135"><td class="mdescLeft">&#160;</td><td class="mdescRight">Construct a <a class="el" href="../../d7/dec/a00010.php" title="Change the text color in the console. ">Color</a> object with a first color.  <a href="#af13248c98bcd8bf432f3c9dab0a27135">More...</a><br /></td></tr>
<tr class="separator:af13248c98bcd8bf432f3c9dab0a27135"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20b97d6cf5e50f86b517f543142ac1e2"><td class="memTemplParams" colspan="2">template&lt;class... Args&gt; </td></tr>
<tr class="memitem:a20b97d6cf5e50f86b517f543142ac1e2"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#a20b97d6cf5e50f86b517f543142ac1e2">Color</a> (Args...args)</td></tr>
<tr class="memdesc:a20b97d6cf5e50f86b517f543142ac1e2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Construct a <a class="el" href="../../d7/dec/a00010.php" title="Change the text color in the console. ">Color</a> object with colors.  <a href="#a20b97d6cf5e50f86b517f543142ac1e2">More...</a><br /></td></tr>
<tr class="separator:a20b97d6cf5e50f86b517f543142ac1e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f77bc1b8cfcd1382cd55e4ef6856bac"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#a4f77bc1b8cfcd1382cd55e4ef6856bac">addColors</a> (int color)</td></tr>
<tr class="memdesc:a4f77bc1b8cfcd1382cd55e4ef6856bac"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a color to the object.  <a href="#a4f77bc1b8cfcd1382cd55e4ef6856bac">More...</a><br /></td></tr>
<tr class="separator:a4f77bc1b8cfcd1382cd55e4ef6856bac"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad810a3eea73cc7b62c80885692488738"><td class="memTemplParams" colspan="2">template&lt;class... Args&gt; </td></tr>
<tr class="memitem:ad810a3eea73cc7b62c80885692488738"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#ad810a3eea73cc7b62c80885692488738">addColors</a> (int color, Args...args)</td></tr>
<tr class="memdesc:ad810a3eea73cc7b62c80885692488738"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add colors to the object.  <a href="#ad810a3eea73cc7b62c80885692488738">More...</a><br /></td></tr>
<tr class="separator:ad810a3eea73cc7b62c80885692488738"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9ef0be1de42c7a08b30d5715ae943a26"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#a9ef0be1de42c7a08b30d5715ae943a26">addColors</a> (<a class="el" href="../../db/d3a/a00040.php#a55ecd4f2ec2ebfe8d5b0163e4ac2a967">Colors</a> color)</td></tr>
<tr class="memdesc:a9ef0be1de42c7a08b30d5715ae943a26"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add a color to the object.  <a href="#a9ef0be1de42c7a08b30d5715ae943a26">More...</a><br /></td></tr>
<tr class="separator:a9ef0be1de42c7a08b30d5715ae943a26"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1d83143ba7476b3f1d60c85b61713790"><td class="memTemplParams" colspan="2">template&lt;class... Args&gt; </td></tr>
<tr class="memitem:a1d83143ba7476b3f1d60c85b61713790"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#a1d83143ba7476b3f1d60c85b61713790">addColors</a> (<a class="el" href="../../db/d3a/a00040.php#a55ecd4f2ec2ebfe8d5b0163e4ac2a967">Colors</a> color, Args...args)</td></tr>
<tr class="memdesc:a1d83143ba7476b3f1d60c85b61713790"><td class="mdescLeft">&#160;</td><td class="mdescRight">Add colors to the object.  <a href="#a1d83143ba7476b3f1d60c85b61713790">More...</a><br /></td></tr>
<tr class="separator:a1d83143ba7476b3f1d60c85b61713790"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a84513fec989f2f817d2b1c5e6989450e"><td class="memItemLeft" align="right" valign="top">std::ostream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dec/a00010.php#a84513fec989f2f817d2b1c5e6989450e">operator&lt;&lt;</a> (std::ostream &amp;stream, <a class="el" href="../../d7/dec/a00010.php">Color</a> const &amp;c)</td></tr>
<tr class="memdesc:a84513fec989f2f817d2b1c5e6989450e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Overloading of the &lt;&lt; operator.  <a href="#a84513fec989f2f817d2b1c5e6989450e">More...</a><br /></td></tr>
<tr class="separator:a84513fec989f2f817d2b1c5e6989450e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Change the text color in the console. </p>

<p>Definition at line <a class="el" href="../../db/d3a/a00040_source.php#l00062">62</a> of file <a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="af13248c98bcd8bf432f3c9dab0a27135"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Color::Color </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Construct a <a class="el" href="../../d7/dec/a00010.php" title="Change the text color in the console. ">Color</a> object with a first color. </p>

</div>
</div>
<a class="anchor" id="a20b97d6cf5e50f86b517f543142ac1e2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Args&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">Color::Color </td>
          <td>(</td>
          <td class="paramtype">Args...&#160;</td>
          <td class="paramname"><em>args</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Construct a <a class="el" href="../../d7/dec/a00010.php" title="Change the text color in the console. ">Color</a> object with colors. </p>

<p>Definition at line <a class="el" href="../../db/d3a/a00040_source.php#l00074">74</a> of file <a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a4f77bc1b8cfcd1382cd55e4ef6856bac"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Color::addColors </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Add a color to the object. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">color</td><td>The integer of the color</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../db/d3a/a00040_source.php#l00094">94</a> of file <a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/dec/a00010_a4f77bc1b8cfcd1382cd55e4ef6856bac_cgraph.png" border="0" usemap="#d7/dec/a00010_a4f77bc1b8cfcd1382cd55e4ef6856bac_cgraph" alt=""/></div>
<map name="d7/dec/a00010_a4f77bc1b8cfcd1382cd55e4ef6856bac_cgraph" id="d7/dec/a00010_a4f77bc1b8cfcd1382cd55e4ef6856bac_cgraph">
<area shape="rect" id="node2" href="../../d5/db6/a00042.php#a09a70dbff0164874fba7fda6d3afd8c7" title="Convert an enum in string. " alt="" coords="173,5,213,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ad810a3eea73cc7b62c80885692488738"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Args&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Color::addColors </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>color</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Args...&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Add colors to the object. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">color</td><td>One of the colors to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">args</td><td>the other colors to add</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../db/d3a/a00040_source.php#l00105">105</a> of file <a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/dec/a00010_ad810a3eea73cc7b62c80885692488738_cgraph.png" border="0" usemap="#d7/dec/a00010_ad810a3eea73cc7b62c80885692488738_cgraph" alt=""/></div>
<map name="d7/dec/a00010_ad810a3eea73cc7b62c80885692488738_cgraph" id="d7/dec/a00010_ad810a3eea73cc7b62c80885692488738_cgraph">
<area shape="rect" id="node2" href="../../d5/db6/a00042.php#a09a70dbff0164874fba7fda6d3afd8c7" title="Convert an enum in string. " alt="" coords="173,5,213,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a9ef0be1de42c7a08b30d5715ae943a26"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Color::addColors </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../db/d3a/a00040.php#a55ecd4f2ec2ebfe8d5b0163e4ac2a967">Colors</a>&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Add a color to the object. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">color</td><td>The integer of the color</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../db/d3a/a00040_source.php#l00117">117</a> of file <a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/dec/a00010_a9ef0be1de42c7a08b30d5715ae943a26_cgraph.png" border="0" usemap="#d7/dec/a00010_a9ef0be1de42c7a08b30d5715ae943a26_cgraph" alt=""/></div>
<map name="d7/dec/a00010_a9ef0be1de42c7a08b30d5715ae943a26_cgraph" id="d7/dec/a00010_a9ef0be1de42c7a08b30d5715ae943a26_cgraph">
<area shape="rect" id="node2" href="../../d5/db6/a00042.php#a09a70dbff0164874fba7fda6d3afd8c7" title="Convert an enum in string. " alt="" coords="173,5,213,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a1d83143ba7476b3f1d60c85b61713790"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Args&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Color::addColors </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../db/d3a/a00040.php#a55ecd4f2ec2ebfe8d5b0163e4ac2a967">Colors</a>&#160;</td>
          <td class="paramname"><em>color</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Args...&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Add colors to the object. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">color</td><td>One of the colors to add </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">args</td><td>the other colors to add</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Definition at line <a class="el" href="../../db/d3a/a00040_source.php#l00128">128</a> of file <a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/dec/a00010_a1d83143ba7476b3f1d60c85b61713790_cgraph.png" border="0" usemap="#d7/dec/a00010_a1d83143ba7476b3f1d60c85b61713790_cgraph" alt=""/></div>
<map name="d7/dec/a00010_a1d83143ba7476b3f1d60c85b61713790_cgraph" id="d7/dec/a00010_a1d83143ba7476b3f1d60c85b61713790_cgraph">
<area shape="rect" id="node2" href="../../d5/db6/a00042.php#a09a70dbff0164874fba7fda6d3afd8c7" title="Convert an enum in string. " alt="" coords="173,5,213,32"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Friends And Related Function Documentation</h2>
<a class="anchor" id="a84513fec989f2f817d2b1c5e6989450e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ostream&amp; operator&lt;&lt; </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>stream</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../d7/dec/a00010.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Overloading of the &lt;&lt; operator. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../db/d3a/a00040_source.php">console.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d7/dec/a00010.php">Color</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
