<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: arrays.php File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d2/de7/a00014.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">arrays.php File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="../../d2/de7/a00014_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:aa49347b7e235619c160a816bd41898cf"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#aa49347b7e235619c160a816bd41898cf">replace_all</a> ($from, $to, $in)</td></tr>
<tr class="memdesc:aa49347b7e235619c160a816bd41898cf"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that replace something by something else in a string or an array.  <a href="#aa49347b7e235619c160a816bd41898cf">More...</a><br /></td></tr>
<tr class="separator:aa49347b7e235619c160a816bd41898cf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aea7ad19f6d28a81c980beb024ec73922"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#aea7ad19f6d28a81c980beb024ec73922">deleteMapIndex</a> ($in, $index)</td></tr>
<tr class="memdesc:aea7ad19f6d28a81c980beb024ec73922"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that delete the specified index of the map array.  <a href="#aea7ad19f6d28a81c980beb024ec73922">More...</a><br /></td></tr>
<tr class="separator:aea7ad19f6d28a81c980beb024ec73922"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab46b061f71601ad13967e3faa737e7e5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#ab46b061f71601ad13967e3faa737e7e5">deleteIndex</a> ($in, $index)</td></tr>
<tr class="memdesc:ab46b061f71601ad13967e3faa737e7e5"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that delete the specified index of the array.  <a href="#ab46b061f71601ad13967e3faa737e7e5">More...</a><br /></td></tr>
<tr class="separator:ab46b061f71601ad13967e3faa737e7e5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af4f4a899c74553180042d2bea3412a74"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#af4f4a899c74553180042d2bea3412a74">deleteFirst</a> ($in)</td></tr>
<tr class="memdesc:af4f4a899c74553180042d2bea3412a74"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that delete the first index of an array.  <a href="#af4f4a899c74553180042d2bea3412a74">More...</a><br /></td></tr>
<tr class="separator:af4f4a899c74553180042d2bea3412a74"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa260c051ba00921f461dd4d2092ed270"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#aa260c051ba00921f461dd4d2092ed270">deleteLast</a> ($in)</td></tr>
<tr class="memdesc:aa260c051ba00921f461dd4d2092ed270"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that delete the last index of an array.  <a href="#aa260c051ba00921f461dd4d2092ed270">More...</a><br /></td></tr>
<tr class="separator:aa260c051ba00921f461dd4d2092ed270"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac25e0cea9220cf427db18de77a1cc282"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#ac25e0cea9220cf427db18de77a1cc282">typeValue_array</a> ($in)</td></tr>
<tr class="memdesc:ac25e0cea9220cf427db18de77a1cc282"><td class="mdescLeft">&#160;</td><td class="mdescRight">Convert a type/value array in an index/value array.  <a href="#ac25e0cea9220cf427db18de77a1cc282">More...</a><br /></td></tr>
<tr class="separator:ac25e0cea9220cf427db18de77a1cc282"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a876add8c54fbea2f702f5365dfbe03be"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a876add8c54fbea2f702f5365dfbe03be">get_in_array</a> ($index, $array)</td></tr>
<tr class="memdesc:a876add8c54fbea2f702f5365dfbe03be"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the given value in the array if it exists.  <a href="#a876add8c54fbea2f702f5365dfbe03be">More...</a><br /></td></tr>
<tr class="separator:a876add8c54fbea2f702f5365dfbe03be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a036c7414be684df67cb85655b9999528"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#a036c7414be684df67cb85655b9999528">it_exists</a> ($index, $array)</td></tr>
<tr class="memdesc:a036c7414be684df67cb85655b9999528"><td class="mdescLeft">&#160;</td><td class="mdescRight">Verify if an index exists in an array with a * possible.  <a href="#a036c7414be684df67cb85655b9999528">More...</a><br /></td></tr>
<tr class="separator:a036c7414be684df67cb85655b9999528"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae5bb45152f585894d61fed14c6e743d1"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/de7/a00014.php#ae5bb45152f585894d61fed14c6e743d1">error_log_array</a> ($array)</td></tr>
<tr class="memdesc:ae5bb45152f585894d61fed14c6e743d1"><td class="mdescLeft">&#160;</td><td class="mdescRight">Put an array to the error_log as a string.  <a href="#ae5bb45152f585894d61fed14c6e743d1">More...</a><br /></td></tr>
<tr class="separator:ae5bb45152f585894d61fed14c6e743d1"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>08 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>
</div><h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="af4f4a899c74553180042d2bea3412a74"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">deleteFirst </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that delete the first index of an array. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$in</td><td>The array </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the array without the first index </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00081">81</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/de7/a00014_af4f4a899c74553180042d2bea3412a74_cgraph.png" border="0" usemap="#d2/de7/a00014_af4f4a899c74553180042d2bea3412a74_cgraph" alt=""/></div>
<map name="d2/de7/a00014_af4f4a899c74553180042d2bea3412a74_cgraph" id="d2/de7/a00014_af4f4a899c74553180042d2bea3412a74_cgraph">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php#ab46b061f71601ad13967e3faa737e7e5" title="Function that delete the specified index of the array. " alt="" coords="136,5,225,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ab46b061f71601ad13967e3faa737e7e5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">deleteIndex </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$in</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$index</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that delete the specified index of the array. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$in</td><td>The array </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$index</td><td>The index to delete </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the array without the given index </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00056">56</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

</div>
</div>
<a class="anchor" id="aa260c051ba00921f461dd4d2092ed270"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">deleteLast </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that delete the last index of an array. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$in</td><td>The array </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the array without the last index </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00090">90</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/de7/a00014_aa260c051ba00921f461dd4d2092ed270_cgraph.png" border="0" usemap="#d2/de7/a00014_aa260c051ba00921f461dd4d2092ed270_cgraph" alt=""/></div>
<map name="d2/de7/a00014_aa260c051ba00921f461dd4d2092ed270_cgraph" id="d2/de7/a00014_aa260c051ba00921f461dd4d2092ed270_cgraph">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php#ab46b061f71601ad13967e3faa737e7e5" title="Function that delete the specified index of the array. " alt="" coords="136,5,225,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aea7ad19f6d28a81c980beb024ec73922"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">deleteMapIndex </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$in</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$index</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that delete the specified index of the map array. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$in</td><td>The map array </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$index</td><td>The index to delete </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the map array without the given index </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00034">34</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

</div>
</div>
<a class="anchor" id="ae5bb45152f585894d61fed14c6e743d1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">error_log_array </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$array</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Put an array to the error_log as a string. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$array</td><td>The array to print </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Print all the array as a string in error_log </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00190">190</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

</div>
</div>
<a class="anchor" id="a876add8c54fbea2f702f5365dfbe03be"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">get_in_array </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$index</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$array</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the given value in the array if it exists. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$index</td><td>The index to get </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$array</td><td>The array to search the index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return <b>false</b> or the value </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00123">123</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/de7/a00014_a876add8c54fbea2f702f5365dfbe03be_cgraph.png" border="0" usemap="#d2/de7/a00014_a876add8c54fbea2f702f5365dfbe03be_cgraph" alt=""/></div>
<map name="d2/de7/a00014_a876add8c54fbea2f702f5365dfbe03be_cgraph" id="d2/de7/a00014_a876add8c54fbea2f702f5365dfbe03be_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="147,5,197,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a036c7414be684df67cb85655b9999528"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">it_exists </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$index</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$array</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Verify if an index exists in an array with a * possible. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$index</td><td>The index to verify, it allow the * to search as regex </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$array</td><td>The array in which to search </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return <b>false</b> or the key </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00155">155</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/de7/a00014_a036c7414be684df67cb85655b9999528_cgraph.png" border="0" usemap="#d2/de7/a00014_a036c7414be684df67cb85655b9999528_cgraph" alt=""/></div>
<map name="d2/de7/a00014_a036c7414be684df67cb85655b9999528_cgraph" id="d2/de7/a00014_a036c7414be684df67cb85655b9999528_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="124,5,175,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aa49347b7e235619c160a816bd41898cf"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">replace_all </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$from</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$to</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$in</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that replace something by something else in a string or an array. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$from</td><td>The string to replace </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$to</td><td>The string for replacement </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">$in</td><td>The string in which to do the replacement </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the replaced string or array </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00016">16</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

</div>
</div>
<a class="anchor" id="ac25e0cea9220cf427db18de77a1cc282"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typeValue_array </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$in</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Convert a type/value array in an index/value array. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">$in</td><td>The type/value array </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return an index/value array </dd></dl>

<p>Definition at line <a class="el" href="../../d2/de7/a00014_source.php#l00099">99</a> of file <a class="el" href="../../d2/de7/a00014_source.php">arrays.php</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/de7/a00014_ac25e0cea9220cf427db18de77a1cc282_cgraph.png" border="0" usemap="#d2/de7/a00014_ac25e0cea9220cf427db18de77a1cc282_cgraph" alt=""/></div>
<map name="d2/de7/a00014_ac25e0cea9220cf427db18de77a1cc282_cgraph" id="d2/de7/a00014_ac25e0cea9220cf427db18de77a1cc282_cgraph">
<area shape="rect" id="node2" href="../../d7/dec/a00010.php#a9e0d51979af70f1e0d06bb7bb7047898" title="Function to know if a variable exist. " alt="" coords="169,5,220,32"/>
</map>
</div>
</p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_05194b7bb14e4bdbd759acf3e4294839.php">php</a></li><li class="navelem"><a class="el" href="../../dir_272b8c85f84b9c47a49e8b7a9d6744ed.php">bases</a></li><li class="navelem"><a class="el" href="../../d2/de7/a00014.php">arrays.php</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
