<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: string.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d03/a00062_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">string.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../df/d03/a00062.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_STRING</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_STRING</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &lt;locale&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">#include &lt;regex&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d1/d84/a00052.php">macro.hpp</a>&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d5/df9/a00044.php">convert.hpp</a>&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d1/dc6/a00037.php">array.hpp</a>&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d9/d73/a00060.php">RNG.hpp</a>&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d2/dee/a00049.php">errors.hpp</a>&quot;</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;std::vector&lt;std::string&gt; <a class="code" href="../../df/d03/a00062.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>(std::string in, <span class="keywordtype">char</span> separator = <span class="charliteral">&#39; &#39;</span>);</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;std::vector&lt;std::string&gt; <a class="code" href="../../df/d03/a00062.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>(std::string in, std::string c);</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;std::vector&lt;std::string&gt; <a class="code" href="../../df/d03/a00062.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>(std::string in, std::vector&lt;std::string&gt; cars);</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00047"></a><span class="lineno"><a class="line" href="../../df/d03/a00062.php#ad81b7e411acc02d29749ab23e6e615ee">   47</a></span>&#160;    <a class="code" href="../../d1/d84/a00052.php#a4a9a280c3a601b98a7d1694f622a269c">ALIAS_TEMPLATE_FUNCTION</a>(<a class="code" href="../../df/d03/a00062.php#ad81b7e411acc02d29749ab23e6e615ee">explode</a>, <a class="code" href="../../df/d03/a00062.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>);</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;<span class="comment">/***********/</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;<span class="keywordtype">void</span> <a class="code" href="../../df/d03/a00062.php#aabfbfab3c3f6562da02d78a54d1ca0e0">trim</a>(std::string&amp; in);</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;std::string <a class="code" href="../../df/d03/a00062.php#aad282b8ce93b90e54cbd1e337446f15a">uppercase</a>(std::string str, std::string::iterator begin, std::string::iterator end);</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;std::string <a class="code" href="../../df/d03/a00062.php#ab6e8937516645f1cb8f4f9c6981feed5">lowercase</a>(std::string str, std::string::iterator begin, std::string::iterator end);</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;std::string <a class="code" href="../../df/d03/a00062.php#ac246cdbda2d19cb1011203aa94cb0c4f">replace</a>(std::string str, std::string from, std::string to, <span class="keywordtype">bool</span> regex = <span class="keyword">false</span>);</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;std::string <a class="code" href="../../df/d03/a00062.php#abfbfe8f3754081903836460cd2f72cb8">randStr</a>(<span class="keywordtype">size_t</span> nb);</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;<span class="keywordtype">size_t</span> <a class="code" href="../../df/d03/a00062.php#acd2025e6c626d84af37996f3adc4d313">count</a>(std::string text, <span class="keywordtype">char</span> c);</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;std::vector&lt;std::vector&lt;std::string&gt;&gt; <a class="code" href="../../df/d03/a00062.php#ac30abc9c5804b9f6719a9798fc8eba90">getall</a>(std::string str_regex, std::string str);</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;std::string <a class="code" href="../../df/d03/a00062.php#a14e02f8805cfac4b82495e998a4f47e9">removeAccents</a>(std::string str);</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;<span class="preprocessor">#endif //HEADER_STRING</span></div><div class="ttc" id="a00049_php"><div class="ttname"><a href="../../d2/dee/a00049.php">errors.hpp</a></div></div>
<div class="ttc" id="a00062_php_abfbfe8f3754081903836460cd2f72cb8"><div class="ttname"><a href="../../df/d03/a00062.php#abfbfe8f3754081903836460cd2f72cb8">randStr</a></div><div class="ttdeci">std::string randStr(size_t nb)</div><div class="ttdoc">Create a random string. </div></div>
<div class="ttc" id="a00037_php"><div class="ttname"><a href="../../d1/dc6/a00037.php">array.hpp</a></div></div>
<div class="ttc" id="a00062_php_ad81b7e411acc02d29749ab23e6e615ee"><div class="ttname"><a href="../../df/d03/a00062.php#ad81b7e411acc02d29749ab23e6e615ee">explode</a></div><div class="ttdeci">auto explode(Args &amp;&amp;...args) -&gt; decltype(split(std::forward&lt; Args &gt;(args)...))</div><div class="ttdoc">Alias for split. </div><div class="ttdef"><b>Definition:</b> <a href="../../df/d03/a00062_source.php#l00047">string.hpp:47</a></div></div>
<div class="ttc" id="a00062_php_aad282b8ce93b90e54cbd1e337446f15a"><div class="ttname"><a href="../../df/d03/a00062.php#aad282b8ce93b90e54cbd1e337446f15a">uppercase</a></div><div class="ttdeci">std::string uppercase(std::string str, std::string::iterator begin, std::string::iterator end)</div><div class="ttdoc">Set the given interval to uppercase. </div></div>
<div class="ttc" id="a00062_php_a14e02f8805cfac4b82495e998a4f47e9"><div class="ttname"><a href="../../df/d03/a00062.php#a14e02f8805cfac4b82495e998a4f47e9">removeAccents</a></div><div class="ttdeci">std::string removeAccents(std::string str)</div><div class="ttdoc">Replace all the accents of a string. </div></div>
<div class="ttc" id="a00062_php_acd2025e6c626d84af37996f3adc4d313"><div class="ttname"><a href="../../df/d03/a00062.php#acd2025e6c626d84af37996f3adc4d313">count</a></div><div class="ttdeci">size_t count(std::string text, char c)</div><div class="ttdoc">Count the number of appearances. </div></div>
<div class="ttc" id="a00062_php_ab6e8937516645f1cb8f4f9c6981feed5"><div class="ttname"><a href="../../df/d03/a00062.php#ab6e8937516645f1cb8f4f9c6981feed5">lowercase</a></div><div class="ttdeci">std::string lowercase(std::string str, std::string::iterator begin, std::string::iterator end)</div><div class="ttdoc">Set the given interval to lowercase. </div></div>
<div class="ttc" id="a00062_php_ad0f62921e752f26b9ebd77ec32e8824e"><div class="ttname"><a href="../../df/d03/a00062.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a></div><div class="ttdeci">std::vector&lt; std::string &gt; split(std::string in, char separator= ' ')</div><div class="ttdoc">Explode a string in an array with the given caracter. </div></div>
<div class="ttc" id="a00060_php"><div class="ttname"><a href="../../d9/d73/a00060.php">RNG.hpp</a></div></div>
<div class="ttc" id="a00052_php_a4a9a280c3a601b98a7d1694f622a269c"><div class="ttname"><a href="../../d1/d84/a00052.php#a4a9a280c3a601b98a7d1694f622a269c">ALIAS_TEMPLATE_FUNCTION</a></div><div class="ttdeci">#define ALIAS_TEMPLATE_FUNCTION(highLevelF, lowLevelF)</div><div class="ttdoc">A macro to create aliases. </div><div class="ttdef"><b>Definition:</b> <a href="../../d1/d84/a00052_source.php#l00016">macro.hpp:16</a></div></div>
<div class="ttc" id="a00044_php"><div class="ttname"><a href="../../d5/df9/a00044.php">convert.hpp</a></div></div>
<div class="ttc" id="a00062_php_ac246cdbda2d19cb1011203aa94cb0c4f"><div class="ttname"><a href="../../df/d03/a00062.php#ac246cdbda2d19cb1011203aa94cb0c4f">replace</a></div><div class="ttdeci">std::string replace(std::string str, std::string from, std::string to, bool regex=false)</div><div class="ttdoc">Replace something by something else in a string using regex_replace. </div></div>
<div class="ttc" id="a00062_php_ac30abc9c5804b9f6719a9798fc8eba90"><div class="ttname"><a href="../../df/d03/a00062.php#ac30abc9c5804b9f6719a9798fc8eba90">getall</a></div><div class="ttdeci">std::vector&lt; std::vector&lt; std::string &gt; &gt; getall(std::string str_regex, std::string str)</div><div class="ttdoc">Return all occurences of a regex in a string. </div></div>
<div class="ttc" id="a00052_php"><div class="ttname"><a href="../../d1/d84/a00052.php">macro.hpp</a></div></div>
<div class="ttc" id="a00062_php_aabfbfab3c3f6562da02d78a54d1ca0e0"><div class="ttname"><a href="../../df/d03/a00062.php#aabfbfab3c3f6562da02d78a54d1ca0e0">trim</a></div><div class="ttdeci">void trim(std::string &amp;in)</div><div class="ttdoc">Delete all the too-much spaces in the given string. </div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../df/d03/a00062.php">string.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
