<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: navBar.js Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/de0/a00022_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">navBar.js</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d7/de0/a00022.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<a class="code" href="../../d7/de0/a00022.php#aadf9f96b23f60c2c7f3dfd2e485fae36">affichageNav</a>();</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="comment">/*!*    \brief  Manage the display of the navBar if a pseudo cookie exists or not.*/</span></div><div class="line"><a name="l00010"></a><span class="lineno"><a class="line" href="../../d7/de0/a00022.php#aadf9f96b23f60c2c7f3dfd2e485fae36">   10</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../d7/de0/a00022.php#aadf9f96b23f60c2c7f3dfd2e485fae36">affichageNav</a>(){</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;  var <a class="code" href="../../dd/d1b/a00015.php#a1f0d86ab32405786812d806542ca3280">pseudo</a>;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;  <span class="keywordflow">if</span>(Cookies.get(<span class="stringliteral">&#39;pseudo&#39;</span>)){</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;    pseudo = Cookies.get(<span class="stringliteral">&#39;pseudo&#39;</span>);</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;    <a class="code" href="../../d1/d7c/a00003.php#a2e3f7b2aca271c0d87c61a33b0030941">ajaxRequest</a>(<span class="stringliteral">&#39;GET&#39;</span>, <span class="stringliteral">&#39;php/request.php/navInfo&#39;</span>, <a class="code" href="../../d7/de0/a00022.php#a373c65ea2fc1b38e81387398e287ac8d">affichageConnecter</a>,<span class="stringliteral">&#39;pseudo=&#39;</span>+pseudo);</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;  }<span class="keywordflow">else</span>{</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;    <a class="code" href="../../d7/de0/a00022.php#a57c667ec3d857e12e4d334e3f2453313">affichageDeconnecter</a>();</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;  }</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;}</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="comment">/*!*    \brief  Displays the navbar when you are disconnected*/</span></div><div class="line"><a name="l00021"></a><span class="lineno"><a class="line" href="../../d7/de0/a00022.php#a57c667ec3d857e12e4d334e3f2453313">   21</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../d7/de0/a00022.php#a57c667ec3d857e12e4d334e3f2453313">affichageDeconnecter</a>(){</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;  var text =<span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;  text+=<span class="stringliteral">&#39;&lt;li&gt;&lt;a href=&quot;./connexion.php&quot; target=&quot;_self&quot;&gt;CONNEXION&lt;/a&gt;&lt;/li&gt;&#39;</span>;</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;    text+=<span class="stringliteral">&#39;&lt;li&gt;&lt;a href=&quot;./inscription.php&quot; target=&quot;_self&quot;&gt;INSCRIPTION&lt;/a&gt;&lt;/li&gt;&#39;</span>;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;  $(<span class="stringliteral">&#39;#connexion&#39;</span>).innerHTML= text;</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;}</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;<span class="comment">/*!*    \brief  Displays the navbar when you are connected*/</span></div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="../../d7/de0/a00022.php#a373c65ea2fc1b38e81387398e287ac8d">   29</a></span>&#160;<span class="keyword">function</span> <a class="code" href="../../d7/de0/a00022.php#a373c65ea2fc1b38e81387398e287ac8d">affichageConnecter</a>(ajaxResponse){</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;  var json= JSON.parse(ajaxResponse);</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;  var text =<span class="stringliteral">&quot;&quot;</span>;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;  text+=<span class="stringliteral">&#39;&lt;li&gt;&lt;span&gt;&lt;img src=&quot;&#39;</span>+json[0][<span class="stringliteral">&#39;avatar&#39;</span>]+<span class="stringliteral">&#39;&quot; alt=&quot;Avatar&quot;&gt;&#39;</span>+json[0][<span class="stringliteral">&#39;pseudo&#39;</span>]+<span class="stringliteral">&#39;&lt;/span&gt;&lt;/li&gt;&#39;</span>;</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;  text+=<span class="stringliteral">&#39;&lt;li class=&quot;deconnexion&quot; id=&quot;boutonDeconnexion&quot;&gt;&lt;img src=&quot;design/img/deconnexion.png&quot; alt=&quot;icon deconnexion&quot;&gt;&lt;span &quot;&gt;Deconnexion&lt;/span&gt;&lt;/li&gt;&#39;</span>;</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;  $(<span class="stringliteral">&#39;#connexion&#39;</span>).innerHTML= text;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;  $(<span class="stringliteral">&#39;#boutonDeconnexion&#39;</span>).addEventListener(<span class="stringliteral">&#39;click&#39;</span>,deconnexion);</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;}</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;<span class="comment">/*!*    \brief  Delete cookies and the current session with an ajaxRequest and reload the page*/</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;<span class="keyword">function</span> deconnexion(){</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;  <a class="code" href="../../d1/d7c/a00003.php#a2e3f7b2aca271c0d87c61a33b0030941">ajaxRequest</a>(<span class="stringliteral">&#39;DELETE&#39;</span>,<span class="stringliteral">&#39;php/request.php/sessionDestroy&#39;</span>,<span class="keyword">function</span>(){},null,<span class="keyword">function</span>(){},<span class="keyword">false</span>);</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;  $(<span class="stringliteral">&#39;#boutonDeconnexion&#39;</span>).removeEventListener(<span class="stringliteral">&#39;click&#39;</span>,deconnexion);</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;  document.location.reload(<span class="keyword">true</span>);</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;}</div><div class="ttc" id="a00022_php_a373c65ea2fc1b38e81387398e287ac8d"><div class="ttname"><a href="../../d7/de0/a00022.php#a373c65ea2fc1b38e81387398e287ac8d">affichageConnecter</a></div><div class="ttdeci">function affichageConnecter(ajaxResponse)</div><div class="ttdoc">Displays the navbar when you are connected. </div><div class="ttdef"><b>Definition:</b> <a href="../../d7/de0/a00022_source.php#l00029">navBar.js:29</a></div></div>
<div class="ttc" id="a00022_php_aadf9f96b23f60c2c7f3dfd2e485fae36"><div class="ttname"><a href="../../d7/de0/a00022.php#aadf9f96b23f60c2c7f3dfd2e485fae36">affichageNav</a></div><div class="ttdeci">affichageNav()</div><div class="ttdoc">Manage the display of the navBar if a pseudo cookie exists or not. </div><div class="ttdef"><b>Definition:</b> <a href="../../d7/de0/a00022_source.php#l00010">navBar.js:10</a></div></div>
<div class="ttc" id="a00015_php_a1f0d86ab32405786812d806542ca3280"><div class="ttname"><a href="../../dd/d1b/a00015.php#a1f0d86ab32405786812d806542ca3280">pseudo</a></div><div class="ttdeci">var pseudo</div><div class="ttdef"><b>Definition:</b> <a href="../../dd/d1b/a00015_source.php#l00020">inscription.js:20</a></div></div>
<div class="ttc" id="a00003_php_a2e3f7b2aca271c0d87c61a33b0030941"><div class="ttname"><a href="../../d1/d7c/a00003.php#a2e3f7b2aca271c0d87c61a33b0030941">ajaxRequest</a></div><div class="ttdeci">ajaxRequest('GET','php/request.php/tableauDifficulte', affichageDifficulte)</div></div>
<div class="ttc" id="a00022_php_a57c667ec3d857e12e4d334e3f2453313"><div class="ttname"><a href="../../d7/de0/a00022.php#a57c667ec3d857e12e4d334e3f2453313">affichageDeconnecter</a></div><div class="ttdeci">function affichageDeconnecter()</div><div class="ttdoc">Displays the navbar when you are disconnected. </div><div class="ttdef"><b>Definition:</b> <a href="../../d7/de0/a00022_source.php#l00021">navBar.js:21</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_2867b8401105090ba43035c8b1fd9c0c.php">js</a></li><li class="navelem"><a class="el" href="../../d7/de0/a00022.php">navBar.js</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
