<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: string.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/de8/a00061_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">string.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d4/de8/a00061.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_STRING</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_STRING</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &lt;locale&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d2/d79/a00051.php">macro.hpp</a>&quot;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d6/d42/a00043.php">convert.hpp</a>&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../de/d8c/a00036.php">array.hpp</a>&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d3/d8b/a00059.php">RNG.hpp</a>&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;std::vector&lt;std::string&gt; <a class="code" href="../../d4/de8/a00061.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>(std::string in, <span class="keywordtype">char</span> separator = <span class="charliteral">&#39; &#39;</span>);</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;std::vector&lt;std::string&gt; <a class="code" href="../../d4/de8/a00061.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>(std::string in, std::string c);</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;std::vector&lt;std::string&gt; <a class="code" href="../../d4/de8/a00061.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>(std::string in, std::vector&lt;std::string&gt; cars);</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno"><a class="line" href="../../d4/de8/a00061.php#ad81b7e411acc02d29749ab23e6e615ee">   45</a></span>&#160;    <a class="code" href="../../d2/d79/a00051.php#a4a9a280c3a601b98a7d1694f622a269c">ALIAS_TEMPLATE_FUNCTION</a>(<a class="code" href="../../d4/de8/a00061.php#ad81b7e411acc02d29749ab23e6e615ee">explode</a>, <a class="code" href="../../d4/de8/a00061.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a>);</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment">/***********/</span></div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;<span class="keywordtype">void</span> <a class="code" href="../../d4/de8/a00061.php#aabfbfab3c3f6562da02d78a54d1ca0e0">trim</a>(std::string&amp; in);</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;std::string <a class="code" href="../../d4/de8/a00061.php#aad282b8ce93b90e54cbd1e337446f15a">uppercase</a>(std::string str, std::string::iterator begin, std::string::iterator end);</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;std::string <a class="code" href="../../d4/de8/a00061.php#ab6e8937516645f1cb8f4f9c6981feed5">lowercase</a>(std::string str, std::string::iterator begin, std::string::iterator end);</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;std::string <a class="code" href="../../d4/de8/a00061.php#a925387acbdabec822115ff7e71e440a4">replace</a>(std::string str, std::string from, std::string to);</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;std::string <a class="code" href="../../d4/de8/a00061.php#abfbfe8f3754081903836460cd2f72cb8">randStr</a>(<span class="keywordtype">size_t</span> nb);</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;<span class="keywordtype">size_t</span> <a class="code" href="../../d4/de8/a00061.php#acd2025e6c626d84af37996f3adc4d313">count</a>(std::string text, <span class="keywordtype">char</span> c);</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;<span class="preprocessor">#endif //HEADER_STRING</span></div><div class="ttc" id="a00036_php"><div class="ttname"><a href="../../de/d8c/a00036.php">array.hpp</a></div></div>
<div class="ttc" id="a00061_php_abfbfe8f3754081903836460cd2f72cb8"><div class="ttname"><a href="../../d4/de8/a00061.php#abfbfe8f3754081903836460cd2f72cb8">randStr</a></div><div class="ttdeci">std::string randStr(size_t nb)</div><div class="ttdoc">Create a random string. </div></div>
<div class="ttc" id="a00061_php_ad81b7e411acc02d29749ab23e6e615ee"><div class="ttname"><a href="../../d4/de8/a00061.php#ad81b7e411acc02d29749ab23e6e615ee">explode</a></div><div class="ttdeci">auto explode(Args &amp;&amp;...args) -&gt; decltype(split(std::forward&lt; Args &gt;(args)...))</div><div class="ttdoc">Alias for split. </div><div class="ttdef"><b>Definition:</b> <a href="../../d4/de8/a00061_source.php#l00045">string.hpp:45</a></div></div>
<div class="ttc" id="a00043_php"><div class="ttname"><a href="../../d6/d42/a00043.php">convert.hpp</a></div></div>
<div class="ttc" id="a00061_php_aad282b8ce93b90e54cbd1e337446f15a"><div class="ttname"><a href="../../d4/de8/a00061.php#aad282b8ce93b90e54cbd1e337446f15a">uppercase</a></div><div class="ttdeci">std::string uppercase(std::string str, std::string::iterator begin, std::string::iterator end)</div><div class="ttdoc">Set the given interval to uppercase. </div></div>
<div class="ttc" id="a00061_php_a925387acbdabec822115ff7e71e440a4"><div class="ttname"><a href="../../d4/de8/a00061.php#a925387acbdabec822115ff7e71e440a4">replace</a></div><div class="ttdeci">std::string replace(std::string str, std::string from, std::string to)</div><div class="ttdoc">Replace something by something else in a string. </div></div>
<div class="ttc" id="a00051_php"><div class="ttname"><a href="../../d2/d79/a00051.php">macro.hpp</a></div></div>
<div class="ttc" id="a00061_php_acd2025e6c626d84af37996f3adc4d313"><div class="ttname"><a href="../../d4/de8/a00061.php#acd2025e6c626d84af37996f3adc4d313">count</a></div><div class="ttdeci">size_t count(std::string text, char c)</div><div class="ttdoc">Count the number of appearances. </div></div>
<div class="ttc" id="a00051_php_a4a9a280c3a601b98a7d1694f622a269c"><div class="ttname"><a href="../../d2/d79/a00051.php#a4a9a280c3a601b98a7d1694f622a269c">ALIAS_TEMPLATE_FUNCTION</a></div><div class="ttdeci">#define ALIAS_TEMPLATE_FUNCTION(highLevelF, lowLevelF)</div><div class="ttdoc">A macro to create aliases. </div><div class="ttdef"><b>Definition:</b> <a href="../../d2/d79/a00051_source.php#l00016">macro.hpp:16</a></div></div>
<div class="ttc" id="a00059_php"><div class="ttname"><a href="../../d3/d8b/a00059.php">RNG.hpp</a></div></div>
<div class="ttc" id="a00061_php_ad0f62921e752f26b9ebd77ec32e8824e"><div class="ttname"><a href="../../d4/de8/a00061.php#ad0f62921e752f26b9ebd77ec32e8824e">split</a></div><div class="ttdeci">std::vector&lt; std::string &gt; split(std::string in, char separator= ' ')</div><div class="ttdoc">Explode a string in an array with the given caracter. </div></div>
<div class="ttc" id="a00061_php_ab6e8937516645f1cb8f4f9c6981feed5"><div class="ttname"><a href="../../d4/de8/a00061.php#ab6e8937516645f1cb8f4f9c6981feed5">lowercase</a></div><div class="ttdeci">std::string lowercase(std::string str, std::string::iterator begin, std::string::iterator end)</div><div class="ttdoc">Set the given interval to lowercase. </div></div>
<div class="ttc" id="a00061_php_aabfbfab3c3f6562da02d78a54d1ca0e0"><div class="ttname"><a href="../../d4/de8/a00061.php#aabfbfab3c3f6562da02d78a54d1ca0e0">trim</a></div><div class="ttdeci">void trim(std::string &amp;in)</div><div class="ttdoc">Delete all the too-much spaces in the given string. </div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d4/de8/a00061.php">string.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
