<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: My own C++ Features</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li class="current"><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('index.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">My own C++ Features </div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><dl class="section user"><dt>Objects</dt><dd><ul>
<li><a class="el" href="df/d86/a00012.php" title="A contraption. ">Contraption</a><ul>
<li><a class="el" href="de/d11/a00021.php" title="An object. ">Object</a></li>
<li><a class="el" href="dd/d1b/a00015.php" title="An entity. ">Entity</a><ul>
<li><a class="el" href="d5/d16/a00029.php" title="A vegetal. ">Vegetal</a><ul>
<li><a class="el" href="d7/de0/a00022.php" title="A plant. ">Plant</a></li>
<li><a class="el" href="dd/da2/a00019.php" title="A mushroom. ">Mushroom</a></li>
</ul>
</li>
<li><a class="el" href="d1/d7c/a00003.php" title="An animal. ">Animal</a><ul>
<li><a class="el" href="d0/d0b/a00004.php" title="An ant. ">Ant</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="d3/d52/a00023.php" title="A player that can be a child from any class. ">Player</a></li>
<li><a class="el" href="dd/dad/a00005.php" title="A class to manage the arguments. ">Arguments</a></li>
<li><a class="el" href="de/d21/a00006.php" title="A class to connect to a BDD. ">BDD</a></li>
<li>jumble</li>
<li><a class="el" href="d7/dec/a00010.php" title="Change the text color in the console. ">Color</a></li>
<li><a class="el" href="d3/dfe/a00025.php" title="Reinit the color in the console. ">Reinit</a></li>
<li><a class="el" href="da/da0/a00009.php" title="Clear the console. ">Cls</a></li>
<li><a class="el" href="da/d45/a00011.php" title="A class to play with the cursor in the console. ">ConsoleCursor</a></li>
<li>abstract <a class="el" href="d2/de7/a00014.php" title="A class to be the parent for every crypt class. ">Crypto</a><ul>
<li><a class="el" href="de/d5e/a00007.php" title="A class to use the cesar algorithm for encryption. ">Cesar</a></li>
<li><a class="el" href="d0/d33/a00027.php" title="A class to use the RSA algorithm for encryption. ">RSA</a></li>
</ul>
</li>
<li><a class="el" href="d1/d2b/a00018.php" title="A map class to have something common. ">Map</a></li>
<li><a class="el" href="d6/d5b/a00026.php" title="A class to simplify the use of random. ">RNG</a></li>
<li>Rng</li>
<li><a class="el" href="d4/dee/a00008.php" title="A clock to measure the elapsed time. ">Clock</a></li>
<li><a class="el" href="dc/d3c/a00028.php" title="A timer to do something at the end. ">Timer</a> </li>
</ul>
</dd></dl>
<dl class="section user"><dt>Some structures &amp; defines</dt><dd><ul>
<li>arguments</li>
<li>bdd</li>
<li>cesar</li>
<li>reader</li>
<li>writer</li>
<li>rng</li>
<li>Colors</li>
<li><a class="el" href="dc/de2/a00024.php" title="A struct to define a point in space. ">Point</a></li>
<li><a class="el" href="d7/dd4/a00013.php" title="A struct to define Contraption attributes. ">ContraptionAttr</a></li>
<li>Direction</li>
<li>Tile</li>
<li><a class="el" href="d5/d79/a00030.php" title="An object to group the dimensions of the world. ">WorldDimensions</a></li>
<li><a class="el" href="db/db2/a00020.php" title="A struct to define a node for the tree. ">Node</a></li>
<li>line_number = <b>LINE</b></li>
<li>RIGHT_NODE = 1</li>
<li>LEFT_NODE = -1</li>
<li>NO_NODE = 0 </li>
</ul>
</dd></dl>
<dl class="section user"><dt>Functions</dt><dd><ul>
<li>ALIAS_TEMPLATE_FUNCTION</li>
<li><a class="el" href="d4/d6d/a00055.php#a55f9782a77b1459ff662dd21a69edab3" title="Delete a pointer. ">deletePtr(T&amp;)</a></li>
<li><a class="el" href="d9/d2e/a00056.php#a9f2903f65500ce246447f08fea1d734a" title="Compute a random number in a computed range. ">rngRange(T, U)</a></li>
<li><a class="el" href="d3/d8b/a00059.php#a5834b1cc3c766f7520e829ca23284546" title="Get the number of seconds since the Epoch. ">getSec()</a></li>
<li><a class="el" href="d3/d8b/a00059.php#a61c3fca982e77f1f6899239b22b9ad79">getMilli()</a></li>
<li><a class="el" href="d7/df7/a00058.php#ad0f62921e752f26b9ebd77ec32e8824e" title="Explode a string in an array with the given caracter. ">split(std::string, char)</a></li>
<li><a class="el" href="d7/df7/a00058.php#a3f9b8ef62eba953dd328969e206b3f11" title="Explode a string in an array with the given string. ">split(std::string, std::string)</a></li>
<li>explode(std::string, char)</li>
<li>explode(std::string, std::string)</li>
<li><a class="el" href="d7/df7/a00058.php#aabfbfab3c3f6562da02d78a54d1ca0e0" title="Delete all the too-much spaces in the given string. ">trim(std::string&amp;)</a></li>
<li><a class="el" href="d7/df7/a00058.php#aad282b8ce93b90e54cbd1e337446f15a" title="Set the given interval to uppercase. ">uppercase(std::string, std::string::iterator, std::string::iterator)</a></li>
<li><a class="el" href="d7/df7/a00058.php#ab6e8937516645f1cb8f4f9c6981feed5" title="Set the given interval to lowercase. ">lowercase(std::string, std::string::iterator, std::string::iterator)</a></li>
<li><a class="el" href="d7/df7/a00058.php#a925387acbdabec822115ff7e71e440a4" title="Replace something by something else in a string. ">replace(std::string, std::string, std::string)</a></li>
<li><a class="el" href="d7/df7/a00058.php#abfbfe8f3754081903836460cd2f72cb8" title="Create a random string. ">randStr(size_t)</a></li>
<li><a class="el" href="d1/d22/a00057.php#a26ed92f1897ceffb429cd8f436460a3e" title="sort a map ascendently ">sortAsc(std::map&lt;Key, Value&gt;)</a></li>
<li><a class="el" href="d1/d22/a00057.php#a3d14862e28ea7d3bb92662b4068f5763" title="Sort a map descendently. ">sortDesc(std::map&lt;Key, Value&gt;)</a></li>
<li><a class="el" href="d5/de0/a00050.php#ab5254a19797bf686467bc0f475bf6fdd" title="Return the whole part of the given number. ">wholePart(V)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a6a8af65111300da455bef67651f83c73" title="Return the decimal part of the given number. ">decimalPart(V)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a9f362f22a77587bb719f13bc7fb185a2" title="Return the modulo of two numbers. ">mod(V, U)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a6e9b223b45f9c0ef8d93fa65db1a8f98" title="Return the result of the pgcd. ">pgcd(V, V)</a></li>
<li><a class="el" href="d5/de0/a00050.php#ab60083feca94427f7b2c4dfaeb249f07" title="Return the result of the euclidian function. ">eucl(V, V)</a></li>
<li><a class="el" href="d5/de0/a00050.php#aa7446c664998ff110eeaf6c2bab19772" title="Return the distance of the given coordinates. ">dist(T, T, T, T, T, T)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a54a702d8a0a5aa317cc65f5b01ed4ee6" title="Return the square of the given number. ">sq(T)</a></li>
<li><a class="el" href="d5/de0/a00050.php#ad44dc8b9cd6eaa619880db19cf171751" title="Return the absolute value of the given number. ">abs(T)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a193486f414e3b93b2284a85977a4a02c" title="Return the minimum of the arguments. ">min(T, V)</a></li>
<li><a class="el" href="d5/de0/a00050.php#ac5673d3f9fc79ba39127c4a339dea626" title="Return the maximum of the arguments. ">max(T, V)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a709c7dabaae9dea50d277980278081e0" title="Return the round of the given number. ">round(T, int)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a94305b67cb0435c3395b548ec8283154" title="Return true if the given number is prime, false either. ">isPrime(float)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a65b1640156c68ea7687a41428022c1d8" title="Return true if the caracter is a number. ">isNumber(char)</a></li>
<li><a class="el" href="d5/de0/a00050.php#af667d8a0d7e420b313a26791c49359fb" title="Return the result of the sigmoide function. ">sigmoide(double)</a></li>
<li><a class="el" href="d5/de0/a00050.php#aaa55b9d8528b25fa5167908db82dff21" title="Compute with the derivated sigmoide. ">dsigmoide(double)</a></li>
<li><a class="el" href="d5/de0/a00050.php#a75105ac3cb9ee25de080d973f0bfe112" title="Do the log of x in base 2. ">log2p(int)</a></li>
<li><a class="el" href="d1/dc6/a00037.php#a9e71f7b4b2dc9351d81534c753d02b2f" title="Compute if there is a collision between two circles. ">collidesC(double, double, double, double, double, double)</a></li>
<li><a class="el" href="d1/dc6/a00037.php#a2c41f8567fc8effdd8ee6a163fbe9440" title="Compute if there is a collision between two rectangles. ">collidesR(double, double, double, double, double, double, double, double)</a></li>
<li><a class="el" href="d1/dc6/a00037.php#a8e7babfd2bd0dd7b2f392372848edc80" title="Compute if there is a collision between a rectangle and a circle. ">collidesRC(double, double, double, double, double, double, double)</a></li>
<li><a class="el" href="d1/dc6/a00037.php#a3ce463b4b6c6477444bad3dcb1499f85" title="Compute if there is a collision between a point and a circle. ">collidesPC(double, double, double, double, double)</a></li>
<li><a class="el" href="d1/dc6/a00037.php#a2d9df4f37d280cec5c3e91ba7b83ed11" title="Compute if there is a collision between a point and a rectangle. ">collidesPR(double, double, double, double, double, double)</a></li>
<li><a class="el" href="d1/dc6/a00037.php#a1213c000f201a2e1991e60a0e2973d91" title="Compute if there is a collision on a segment. ">ProjectionSurSegment(double, double, double, double, double, double)</a></li>
<li><a class="el" href="db/d3a/a00040.php#a78b4ad7bc552ad244dec369856aa8d91" title="Convert in variable in string. ">tos(V)</a></li>
<li><a class="el" href="db/d3a/a00040.php#a0de9d90c31d0a16f1d173f84be9e091a" title="Convert in variable in int. ">toi(V)</a></li>
<li><a class="el" href="db/d3a/a00040.php#a2432d9eaa9d57e487a6813a01993e8ef" title="Convert in variable in double. ">tod(V)</a></li>
<li><a class="el" href="db/d3a/a00040.php#a28ef26e9e217e572497d67676081f08e" title="Convert in variable in float. ">tof(V)</a></li>
<li><a class="el" href="db/d3a/a00040.php#a046732bd284eb239dc2eda5a92a17681" title="Convert in variable in unsigned int. ">tou(V)</a></li>
<li><a class="el" href="db/d3a/a00040.php#aa70ef73b7fa30f68e3f14a6b60de10eb" title="Convert in variable in unsigned long long int. ">tov(V)</a></li>
<li><a class="el" href="db/d3a/a00040.php#a013b8a84340b1ab68401095a566cc0ea" title="Convert in variable in size_t. ">tost(V)</a></li>
<li>error_log(size_t, T, Args...)</li>
<li>warning_log(size_t, T, Args...)</li>
<li>info_log(size_t, T, Args...)</li>
<li><a class="el" href="d3/dea/a00046.php#a42e1aa02e585ad4e35d14ef5c133395a" title="Format a given line for files. ">fileFormat(std::string&amp;)</a></li>
<li><a class="el" href="d3/dea/a00046.php#ab148021dd478aa69c83029819b268737" title="Get the file size. ">getFileSize(const std::string&amp;)</a></li>
<li><a class="el" href="d3/dea/a00046.php#a2917d2eb46f63f2c97b1a30de55ec3c5" title="Get all the lines in a given file. ">getlines(std::ifstream&amp;)</a></li>
<li><a class="el" href="d3/dea/a00046.php#aa9034f20bf3b289424ebda507e52e427" title="Write all the lines in a given file. ">setlines(std::ofstream&amp;, std::vector&lt;std::string&gt;)</a></li>
<li><a class="el" href="d4/de8/a00061.php#aecf59a2b719b8c7121eee69d1bb737e8" title="Print the type of \â obj. ">printType(C&amp;)</a></li>
<li><a class="el" href="d4/de8/a00061.php#a6d01957e99131ce0c8d0902a9a8cdf38" title="Get the type of obj in a string. ">getType(C&amp;)</a></li>
<li><a class="el" href="d4/de8/a00061.php#ae549f98d8a0469bd0533f807c2b51b84" title="Get the type of a pointer obj in a string. ">getType(C)</a></li>
<li><a class="el" href="db/df3/a00034.php#a5090547d046a342ba3ac573e8248f628" title="Stick the a vector with the glue given. ">implode(std::vector&lt;T&gt;, std::string)</a></li>
<li><a class="el" href="db/df3/a00034.php#ad2b1019448d0599264d51172242e1be4" title="Print the content of a vector. ">print_r(std::vector&lt;T&gt;)</a></li>
<li><a class="el" href="db/df3/a00034.php#aeda2dbc3a1ec9d5f58f2991fb7d0ad13" title="Print the content of an array. ">print_r(T)</a></li>
<li><a class="el" href="db/df3/a00034.php#addfa691004e6d94461994bb7eccadf19" title="Rewrite a vector array without the value at the given index. ">rewrite(std::vector&lt;V&gt;, unsigned)</a></li>
<li><a class="el" href="db/df3/a00034.php#a54f668e0211381d2d15ca45dcf3c55d0" title="Verify if a vector contains or not something. ">contains(std::vector&lt;T&gt;, T)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a150358d1355a1feec0dd9c239e528ba5" title="A function to print the node value in cout stream. ">printNode(Node&lt;T&gt;*, long int)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a6ba86e01e66ef0911ee1fd3e3a1db1ca" title="Function to sort a tree depending on weights. ">sorter(std::pair&lt;T, NodeWeight&gt;, std::pair&lt;T, NodeWeight&gt;)</a></li>
<li><a class="el" href="d9/d73/a00060.php#ac2acdabec1b9860acb985d49992db032" title="Create a binary tree with default sorter function. ">createBinaryTree(std::vector&lt;std::pair&lt;T, NodeWeight&gt;&gt;)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a0d56f2cd35d9fdf524dc21c2fd243233" title="Return an array format for the tree. ">convertInTreeValues(std::vector&lt;std::pair&lt;T, U&gt;&gt;)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a8bcdc1113d4578db82209cd9c38d8cb1" title="Create a child for the tree. ">createChild(T, NodeWeight)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a1186e4caac5cd7b49c6ebb5dfac23e53" title="Return the height of the tree. ">treeHeight(Node&lt;T&gt;*)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a822f289cec240962d857d201aaea89b5" title="Print the tree. ">printTree(Node&lt;T&gt;*)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a62d38298b4f4a9c44baa90aa8e9f29b0" title="Get the depth on right. ">getRightNodeCount(Node&lt;T&gt;*)</a></li>
<li><a class="el" href="d9/d73/a00060.php#ac5c778ab71fa0fc25e9fc3d1d32e2c6a" title="Get the depth on left. ">getLeftNodeCount(Node&lt;T&gt;*)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a10b614bb30047d2274d091e553426e85" title="Find a value in the tree and return the right node. ">finder(T, Node&lt;T&gt;*, std::string&amp;)</a></li>
<li><a class="el" href="d9/d73/a00060.php#a653f604d83b424493ac7d0d3d586a3c2" title="Find a value in the tree and return the node and the path to the node. ">find(T, Node&lt;T&gt;*)</a></li>
<li><a class="el" href="d9/d73/a00060.php#aa7f015a27dd3c807d38c0e9762706a31" title="Free the tree and the differents nodes. ">freeTree(Node&lt;T&gt;*)</a> </li>
</ul>
</dd></dl>
<dl class="section user"><dt>Other things</dt><dd><ul>
<li>ColsArray</li>
<li>ListArray</li>
<li>VI</li>
<li>VS</li>
<li>MapLine</li>
<li>MapArray</li>
</ul>
</dd></dl>
<dl class="section date"><dt>Date</dt><dd>10 juin 2018 </dd></dl>
<dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
