<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>C++: C++.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">C++
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">My own functions in C++</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/dc6/a00037.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">C++.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d5/df9/a00044_source.php">Entities.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d6d/a00055_source.php">Player.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d5/db6/a00042_source.php">cryptage.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d3/de7/a00039_source.php">console.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d6/d42/a00043_source.php">defines.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d3/dea/a00046_source.php">errors.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../dd/d32/a00041_source.php">convert.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d8/d41/a00038_source.php">collides.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d3/d8b/a00059_source.php">string.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d8c/a00035_source.php">array.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d9/d73/a00060_source.php">time.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d2/d79/a00051_source.php">maths.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d6/d2d/a00047_source.php">files.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d7/df7/a00058_source.php">sorting.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/de8/a00061_source.php">Tree.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d5/de0/a00050_source.php">Map.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d2/dee/a00049_source.php">macro.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../df/d03/a00062_source.php">types.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for C++.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/d89/a00071.png" border="0" usemap="#C_09_09_8hpp" alt=""/></div>
<map name="C_09_09_8hpp" id="C_09_09_8hpp">
<area shape="rect" id="node2" href="../../d5/df9/a00044.php" title="Entities.hpp" alt="" coords="1529,155,1620,181"/>
<area shape="rect" id="node4" href="../../d6/d42/a00043.php" title="defines.hpp" alt="" coords="714,528,803,555"/>
<area shape="rect" id="node12" href="../../d3/dea/a00046.php" title="errors.hpp" alt="" coords="1236,677,1316,704"/>
<area shape="rect" id="node13" href="../../d3/de7/a00039.php" title="console.hpp" alt="" coords="1143,752,1235,779"/>
<area shape="rect" id="node14" href="../../dd/d32/a00041.php" title="convert.hpp" alt="" coords="132,827,223,853"/>
<area shape="rect" id="node20" href="../../df/d03/a00062.php" title="types.hpp" alt="" coords="1749,827,1827,853"/>
<area shape="rect" id="node22" href="../../d6/d2d/a00047.php" title="files.hpp" alt="" coords="1259,752,1330,779"/>
<area shape="rect" id="node25" href="../../d9/d73/a00060.php" title="time.hpp" alt="" coords="1492,752,1564,779"/>
<area shape="rect" id="node30" href="../../d3/d8b/a00059.php" title="string.hpp" alt="" coords="630,677,709,704"/>
<area shape="rect" id="node32" href="../../d2/dee/a00049.php" title="macro.hpp" alt="" coords="821,752,904,779"/>
<area shape="rect" id="node33" href="../../d4/d8c/a00035.php" title="array.hpp" alt="" coords="1023,752,1099,779"/>
<area shape="rect" id="node36" href="../../d2/d79/a00051.php" title="maths.hpp" alt="" coords="1964,603,2047,629"/>
<area shape="rect" id="node38" href="../../d8/d41/a00038.php" title="collides.hpp" alt="" coords="1960,528,2051,555"/>
<area shape="rect" id="node39" href="../../d5/de0/a00050.php" title="Map.hpp" alt="" coords="1192,528,1264,555"/>
<area shape="rect" id="node47" href="../../d4/d6d/a00055.php" title="Player.hpp" alt="" coords="1518,80,1602,107"/>
<area shape="rect" id="node48" href="../../d5/db6/a00042.php" title="cryptage.hpp" alt="" coords="725,155,822,181"/>
<area shape="rect" id="node49" href="../../d7/df7/a00058.php" title="sorting.hpp" alt="" coords="293,827,379,853"/>
<area shape="rect" id="node50" href="../../d4/de8/a00061.php" title="Tree.hpp" alt="" coords="1418,528,1491,555"/>
<area shape="rect" id="node3" href="../../db/d3a/a00040.php" title="Contraption.hpp" alt="" coords="1619,453,1733,480"/>
<area shape="rect" id="node40" href="../../dc/dee/a00053.php" title="Object.hpp" alt="" coords="1460,379,1545,405"/>
<area shape="rect" id="node41" href="../../d6/d97/a00045.php" title="Entity.hpp" alt="" coords="1635,379,1717,405"/>
<area shape="rect" id="node42" href="../../dc/d87/a00032.php" title="Animal.hpp" alt="" coords="1506,304,1593,331"/>
<area shape="rect" id="node43" href="../../d0/dc0/a00033.php" title="Ant.hpp" alt="" coords="1445,229,1512,256"/>
<area shape="rect" id="node44" href="../../d1/d6f/a00063.php" title="Vegetal.hpp" alt="" coords="1631,304,1721,331"/>
<area shape="rect" id="node45" href="../../d1/dea/a00054.php" title="Plant.hpp" alt="" coords="1637,229,1715,256"/>
<area shape="rect" id="node46" href="../../d1/d84/a00052.php" title="Mushroom.hpp" alt="" coords="1739,229,1847,256"/>
<area shape="rect" id="node11" href="../../de/d8c/a00036.php" title="bdd.hpp" alt="" coords="791,603,859,629"/>
<area shape="rect" id="node29" href="../../d9/d2e/a00056.php" title="pointers.hpp" alt="" coords="817,677,911,704"/>
<area shape="rect" id="node34" href="../../d1/d22/a00057.php" title="RNG.hpp" alt="" coords="715,752,792,779"/>
<area shape="rect" id="node35" href="../../db/df3/a00034.php" title="Args.hpp" alt="" coords="985,603,1060,629"/>
</map>
</div>
</div>
<p><a href="../../d1/dc6/a00037_source.php">Go to the source code of this file.</a></p>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>11 juin 2018 </dd></dl>

<p>Definition in file <a class="el" href="../../d1/dc6/a00037_source.php">C++.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../d1/dc6/a00037.php">C++.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
