<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Globals</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li class="current"><a href="globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="globals.php"><span>All</span></a></li>
      <li><a href="globals_func.php"><span>Functions</span></a></li>
      <li class="current"><a href="globals_vars.php"><span>Variables</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_0x24"><span>$</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_d"><span>d</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_l"><span>l</span></a></li>
      <li><a href="#index_n"><span>n</span></a></li>
      <li><a href="#index_p"><span>p</span></a></li>
      <li><a href="#index_q"><span>q</span></a></li>
      <li class="current"><a href="#index_s"><span>s</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('globals_vars.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_0x24"></a>- $ -</h3><ul>
<li>$avatar
: <a class="el" href="d3/d52/a00023.php#ac62167326fcdc762297fe76407218b55">register.php</a>
</li>
<li>$bdd
: <a class="el" href="d1/d7c/a00003.php#a94f91e878bce0991e2cd595c5dd79b3f">connexion.php</a>
, <a class="el" href="de/d21/a00006.php#a94f91e878bce0991e2cd595c5dd79b3f">cree-une-partie.php</a>
, <a class="el" href="de/d5e/a00007.php#a94f91e878bce0991e2cd595c5dd79b3f">creer-une-partie.php</a>
, <a class="el" href="df/d86/a00012.php#a94f91e878bce0991e2cd595c5dd79b3f">index.php</a>
, <a class="el" href="d2/de7/a00014.php#a94f91e878bce0991e2cd595c5dd79b3f">inscription.php</a>
, <a class="el" href="d7/d7a/a00016.php#a94f91e878bce0991e2cd595c5dd79b3f">jeu.php</a>
, <a class="el" href="d4/d51/a00017.php#a94f91e878bce0991e2cd595c5dd79b3f">modifier.php</a>
, <a class="el" href="db/db2/a00020.php#a94f91e878bce0991e2cd595c5dd79b3f">palmares.php</a>
, <a class="el" href="d3/d52/a00023.php#a94f91e878bce0991e2cd595c5dd79b3f">register.php</a>
, <a class="el" href="dc/de2/a00024.php#a94f91e878bce0991e2cd595c5dd79b3f">request.php</a>
</li>
<li>$data
: <a class="el" href="dc/de2/a00024.php#a6efc15b5a2314dd4b5aaa556a375c6d6">request.php</a>
</li>
<li>$email
: <a class="el" href="d3/d52/a00023.php#ad634f418b20382e2802f80532d76d3cd">register.php</a>
</li>
<li>$head
: <a class="el" href="de/d21/a00006.php#a687ea7fcd78263867b5bd34ed56b6379">cree-une-partie.php</a>
, <a class="el" href="d1/d7c/a00003.php#a687ea7fcd78263867b5bd34ed56b6379">connexion.php</a>
, <a class="el" href="d4/d51/a00017.php#a687ea7fcd78263867b5bd34ed56b6379">modifier.php</a>
, <a class="el" href="df/d86/a00012.php#a687ea7fcd78263867b5bd34ed56b6379">index.php</a>
, <a class="el" href="d2/de7/a00014.php#a687ea7fcd78263867b5bd34ed56b6379">inscription.php</a>
, <a class="el" href="db/db2/a00020.php#a687ea7fcd78263867b5bd34ed56b6379">palmares.php</a>
, <a class="el" href="de/d5e/a00007.php#a687ea7fcd78263867b5bd34ed56b6379">creer-une-partie.php</a>
, <a class="el" href="d7/d7a/a00016.php#a687ea7fcd78263867b5bd34ed56b6379">jeu.php</a>
</li>
<li>$mdp
: <a class="el" href="d3/d52/a00023.php#a8a65334de2f0d486a42b02ecf82fe8fb">register.php</a>
</li>
<li>$pseudo
: <a class="el" href="d3/d52/a00023.php#a5aaec5de32a8e7a31b5104f80d58dec0">register.php</a>
</li>
<li>$requestRessource
: <a class="el" href="dc/de2/a00024.php#a7fd0384e6fc79c4dac5e25ab16d186ba">request.php</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>compteurProposition
: <a class="el" href="dd/d1b/a00015.php#a8acc3305bb0c57accb21b6c3dfb9a6fd">jeu.js</a>
</li>
<li>compteurQuestion
: <a class="el" href="dd/d1b/a00015.php#a991c67d3335f20552b86efe85cc5d875">jeu.js</a>
</li>
</ul>


<h3><a class="anchor" id="index_d"></a>- d -</h3><ul>
<li>data
: <a class="el" href="dd/d1b/a00015.php#a20b6cd228a69593c03af5dc445393936">jeu.js</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>exit
: <a class="el" href="dc/de2/a00024.php#afb00944b44575a6b06d388e807358cd5">request.php</a>
</li>
</ul>


<h3><a class="anchor" id="index_l"></a>- l -</h3><ul>
<li>location
: <a class="el" href="d8/d84/a00001.php#a9e7735e216b2770753e10ca177623f0f">accueilPerso.js</a>
</li>
</ul>


<h3><a class="anchor" id="index_n"></a>- n -</h3><ul>
<li>nbThemes
: <a class="el" href="d0/d0b/a00004.php#abaac36f85ddb9ededb3d06ba67dca72e">Creation.js</a>
</li>
</ul>


<h3><a class="anchor" id="index_p"></a>- p -</h3><ul>
<li>proposition
: <a class="el" href="dd/d1b/a00015.php#ab516b26a4218f0f59b789a0d446bf79f">jeu.js</a>
</li>
<li>pseudo
: <a class="el" href="d1/d2b/a00018.php#a1f0d86ab32405786812d806542ca3280">navBar.js</a>
</li>
</ul>


<h3><a class="anchor" id="index_q"></a>- q -</h3><ul>
<li>questions
: <a class="el" href="dd/d1b/a00015.php#ac11b64f88548d479a2d12c6d6cdf9c6b">jeu.js</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>solutionProposition
: <a class="el" href="dd/d1b/a00015.php#a160fd6ecbda71c65cdea78feb687bec1">jeu.js</a>
</li>
<li>strict
: <a class="el" href="d3/dfe/a00025.php#ae2475e10618961c050dcba04e8c42331">script.js</a>
, <a class="el" href="dd/da2/a00019.php#ae2475e10618961c050dcba04e8c42331">palmares.js</a>
, <a class="el" href="d1/d2b/a00018.php#ae2475e10618961c050dcba04e8c42331">navBar.js</a>
, <a class="el" href="d7/dd4/a00013.php#ae2475e10618961c050dcba04e8c42331">inscription.js</a>
, <a class="el" href="d7/d46/a00002.php#ae2475e10618961c050dcba04e8c42331">authentification.js</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
