<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Globals</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li class="current"><a href="globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="globals.php"><span>All</span></a></li>
      <li class="current"><a href="globals_func.php"><span>Functions</span></a></li>
      <li><a href="globals_vars.php"><span>Variables</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="globals_func.php#index_0x21"><span>!</span></a></li>
      <li><a href="globals_func__.php#index__"><span>_</span></a></li>
      <li><a href="globals_func_a.php#index_a"><span>a</span></a></li>
      <li><a href="globals_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="globals_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="globals_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="globals_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="globals_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="globals_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="globals_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="globals_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="globals_func_j.php#index_j"><span>j</span></a></li>
      <li><a href="globals_func_k.php#index_k"><span>k</span></a></li>
      <li><a href="globals_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="globals_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="globals_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="globals_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="globals_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="globals_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="globals_func_r.php#index_r"><span>r</span></a></li>
      <li class="current"><a href="globals_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="globals_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="globals_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="globals_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="globals_func_w.php#index_w"><span>w</span></a></li>
      <li><a href="globals_func_x.php#index_x"><span>x</span></a></li>
      <li><a href="globals_func_y.php#index_y"><span>y</span></a></li>
      <li><a href="globals_func_z.php#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('globals_func_s.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>s()
: <a class="el" href="de/d11/a00021.php#ae1f57cfe393e1e182cf26e0346a0ba28">bootstrap/bootstrap.min.js</a>
</li>
<li>saveFileTo()
: <a class="el" href="db/df3/a00034.php#a7fc3f2f4db9af0955fcc004c4bf83a24">files.php</a>
</li>
<li>score()
: <a class="el" href="d4/d8c/a00035.php#af5fde6a754bc0e9c7872a974abde85a8">fonctions.php</a>
</li>
<li>scrollTo()
: <a class="el" href="d7/dec/a00010.php#a09e57842c5e01d9ec59cdcefca4ced17">_script.js</a>
</li>
<li>scrollToC()
: <a class="el" href="d7/dec/a00010.php#ac5d6071e0a5be58c23869e8a6df856af">_script.js</a>
</li>
<li>scrollToEnd()
: <a class="el" href="d7/dec/a00010.php#aa3ec1a835eed518a0155433ff96b827d">_script.js</a>
</li>
<li>scrollToX()
: <a class="el" href="d7/dec/a00010.php#a9c830694d7ae43ca4fe8f502fec440ed">_script.js</a>
</li>
<li>sendJsonData()
: <a class="el" href="d4/d8c/a00035.php#afcef1294902ca07027096e59292f89c1">fonctions.php</a>
</li>
<li>serverError()
: <a class="el" href="d0/dc0/a00033.php#acbd041cd9910f5f824af42ec0d252b5c">errors.php</a>
</li>
<li>setActive()
: <a class="el" href="d7/dec/a00010.php#a971392259eca595d520db8a8bf280b3f">_script.js</a>
</li>
<li>setAll()
: <a class="el" href="d7/dec/a00010.php#a0d1d68cf89a4925c39cf1bab98e5d250">_script.js</a>
</li>
<li>setError()
: <a class="el" href="d0/dc0/a00033.php#a4c6673203933d2acfbb6719aead6a500">errors.php</a>
</li>
<li>setId()
: <a class="el" href="d7/dec/a00010.php#a8ae089c8a5330c10b1e89134abbf6e91">_script.js</a>
</li>
<li>showArrows()
: <a class="el" href="d3/de7/a00039.php#ab634298de9bead214fc2452731540058">gallery.js</a>
</li>
<li>showPass()
: <a class="el" href="df/d03/a00062.php#ac916a879e99dde7caf00f59284870538">show_pass.js</a>
</li>
<li>sqlDate()
: <a class="el" href="dc/d87/a00032.php#a9163d2fe688993dee3abd2ca8f183067">dates.php</a>
</li>
<li>st()
: <a class="el" href="d1/d2b/a00018.php#ac529e2a8872864d6e8757b609ca5edf5">bootstrap.bundle.min.js</a>
</li>
<li>surligne()
: <a class="el" href="d5/db6/a00042.php#a76081b25499ce0257c512f37f1ad9988">inscription.js</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
