<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: Globals</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li class="current"><a href="globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="globals.php"><span>All</span></a></li>
      <li><a href="globals_func.php"><span>Functions</span></a></li>
      <li class="current"><a href="globals_vars.php"><span>Variables</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="globals_vars.php#index_0x24"><span>$</span></a></li>
      <li><a href="globals_vars__.php#index__"><span>_</span></a></li>
      <li><a href="globals_vars_a.php#index_a"><span>a</span></a></li>
      <li><a href="globals_vars_b.php#index_b"><span>b</span></a></li>
      <li class="current"><a href="globals_vars_c.php#index_c"><span>c</span></a></li>
      <li><a href="globals_vars_d.php#index_d"><span>d</span></a></li>
      <li><a href="globals_vars_e.php#index_e"><span>e</span></a></li>
      <li><a href="globals_vars_f.php#index_f"><span>f</span></a></li>
      <li><a href="globals_vars_g.php#index_g"><span>g</span></a></li>
      <li><a href="globals_vars_h.php#index_h"><span>h</span></a></li>
      <li><a href="globals_vars_i.php#index_i"><span>i</span></a></li>
      <li><a href="globals_vars_j.php#index_j"><span>j</span></a></li>
      <li><a href="globals_vars_k.php#index_k"><span>k</span></a></li>
      <li><a href="globals_vars_l.php#index_l"><span>l</span></a></li>
      <li><a href="globals_vars_m.php#index_m"><span>m</span></a></li>
      <li><a href="globals_vars_n.php#index_n"><span>n</span></a></li>
      <li><a href="globals_vars_o.php#index_o"><span>o</span></a></li>
      <li><a href="globals_vars_p.php#index_p"><span>p</span></a></li>
      <li><a href="globals_vars_q.php#index_q"><span>q</span></a></li>
      <li><a href="globals_vars_r.php#index_r"><span>r</span></a></li>
      <li><a href="globals_vars_s.php#index_s"><span>s</span></a></li>
      <li><a href="globals_vars_t.php#index_t"><span>t</span></a></li>
      <li><a href="globals_vars_u.php#index_u"><span>u</span></a></li>
      <li><a href="globals_vars_v.php#index_v"><span>v</span></a></li>
      <li><a href="globals_vars_w.php#index_w"><span>w</span></a></li>
      <li><a href="globals_vars_x.php#index_x"><span>x</span></a></li>
      <li><a href="globals_vars_y.php#index_y"><span>y</span></a></li>
      <li><a href="globals_vars_z.php#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('globals_vars_c.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>c
: <a class="el" href="db/db2/a00020.php#ad9d1ac02e33c4aed62ad517a7cb8b3fb">autres/bootstrap.min.js</a>
, <a class="el" href="de/d11/a00021.php#abce695e0af988ece0826d9ad59b8160d">bootstrap/bootstrap.min.js</a>
</li>
<li>C
: <a class="el" href="de/d11/a00021.php#ae59e0ac8d0c43c81f50236f719763efc">bootstrap/bootstrap.min.js</a>
</li>
<li>c
: <a class="el" href="d3/dea/a00046.php#abce695e0af988ece0826d9ad59b8160d">jquery.min.js</a>
</li>
<li>Carousel
: <a class="el" href="de/d11/a00021.php#a9621ceb4a44f5fdda96598c55f5ae3a9">bootstrap/bootstrap.min.js</a>
, <a class="el" href="d4/d51/a00017.php#a973fed123161d28ea502af96c99576a6">bootstrap.bundle.js</a>
, <a class="el" href="d1/d2b/a00018.php#a9621ceb4a44f5fdda96598c55f5ae3a9">bootstrap.bundle.min.js</a>
, <a class="el" href="dd/da2/a00019.php#a973fed123161d28ea502af96c99576a6">bootstrap.js</a>
</li>
<li>change
: <a class="el" href="df/d5f/a00064.php#a386c3ec694dd3e8e178623e2d1cb302a">stars.js</a>
</li>
<li>classCallCheck
: <a class="el" href="d4/d51/a00017.php#aa5a2e5bf0a535a30a11262d9df06151b">bootstrap.bundle.js</a>
</li>
<li>close
: <a class="el" href="db/db2/a00020.php#a72fbb3628c3cc943ced8aad64247888c">autres/bootstrap.min.js</a>
</li>
<li>Collapse
: <a class="el" href="d1/d2b/a00018.php#a9cc1096330cc4b7cbbb959246d6968fb">bootstrap.bundle.min.js</a>
, <a class="el" href="dd/da2/a00019.php#a4df4f2a75d24a2e6a7e8a33a097c355a">bootstrap.js</a>
, <a class="el" href="d4/d51/a00017.php#a4df4f2a75d24a2e6a7e8a33a097c355a">bootstrap.bundle.js</a>
, <a class="el" href="de/d11/a00021.php#a9cc1096330cc4b7cbbb959246d6968fb">bootstrap/bootstrap.min.js</a>
</li>
<li>compteurProposition
: <a class="el" href="d5/df9/a00044.php#a8acc3305bb0c57accb21b6c3dfb9a6fd">jeu.js</a>
</li>
<li>compteurQuestion
: <a class="el" href="d5/df9/a00044.php#a991c67d3335f20552b86efe85cc5d875">jeu.js</a>
</li>
<li>Constructor
: <a class="el" href="db/db2/a00020.php#a0545907c609a48549a0cf5d4c692f851">autres/bootstrap.min.js</a>
</li>
<li>createClass
: <a class="el" href="d4/d51/a00017.php#aaf3dfd019b0e65fefde9702c4b377344">bootstrap.bundle.js</a>
</li>
<li>Ct
: <a class="el" href="d1/d2b/a00018.php#a0e7692658f580850a55a03a84745dac3">bootstrap.bundle.min.js</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
