<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Hot Dog QUIZ: My own JS Features</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Hot Dog QUIZ
   &#160;<span id="projectnumber">1.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li class="current"><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('index.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">My own JS Features </div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><dl class="section user"><dt>Some classes &amp; ids</dt><dd><ul>
<li>score (<b>class</b>)<ul>
<li>width (<b>attributes</b>)</li>
<li>height (<b>attributes</b>)</li>
<li>min (<b>attributes</b>)</li>
<li>max (<b>attributes</b>)</li>
<li>note (<b>attributes</b>)</li>
<li>degre (<b>attributes</b>)</li>
</ul>
</li>
<li>map (<b>id</b>)<ul>
<li>path (<b>attributes</b>)</li>
<li>plain-color (<b>attributes</b>)</li>
<li>line-color (<b>attributes</b>)</li>
<li>hover-plain-color (<b>attributes</b>)</li>
<li>hover-line-color (<b>attributes</b>)</li>
<li>scale (<b>attributes</b>)</li>
</ul>
</li>
<li>gallery (<b>class</b>)</li>
<li>tchat (<b>id</b>)<ul>
<li>human (<b>class</b>)</li>
<li>bot (<b>class</b>)</li>
</ul>
</li>
<li>stars (<b>id</b>)</li>
<li>shower (<b>class</b>) </li>
</ul>
</dd></dl>
<dl class="section user"><dt>Functions</dt><dd><ul>
<li><a class="el" href="d7/dec/a00010.php#abc28be0063ceea3a2dbac6e5d8f42bd4" title="Add a function to the onloadFunction array and save the arguments. ">addOnload()</a></li>
<li><a class="el" href="d7/dec/a00010.php#af25c5b56dd6e0a4c8e76e1d6ec197417" title="Add a function to the onresizeFunction array and save the arguments. ">addOnresize()</a></li>
<li><a class="el" href="d7/dd4/a00013.php#abef425142325124458ad69a853742275" title="The function that start an ajax request. ">ajaxRequest()</a></li>
<li><a class="el" href="de/d11/a00021.php#a9feccf800829cefff3a1214b7aaf1e51" title="Encode html caracters in string. ">html_encode()</a></li>
<li><a class="el" href="de/d11/a00021.php#a45e51b85c4813b1c858c8c4ed7fed67f" title="Decode html caracters in string. ">html_decode()</a></li>
</ul>
</dd></dl>
<dl class="section date"><dt>Date</dt><dd>10 juin 2018 </dd></dl>
<dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.11 </li>
  </ul>
</div>
</body>
</html>
